var searchData = [
  [
    'updateaccountsignaturebyidoptions',
    [
      'UpdateAccountSignatureByIdOptions',
      [
        '../class_docu_sign_1_1e_sign_1_1_api_1_1_accounts_api_1_1_update_account_signature_by_id_options.html',
        1,
        'DocuSign::eSign::Api::AccountsApi',
      ],
    ],
  ],
  [
    'updateaccountsignatureimageoptions',
    [
      'UpdateAccountSignatureImageOptions',
      [
        '../class_docu_sign_1_1e_sign_1_1_api_1_1_accounts_api_1_1_update_account_signature_image_options.html',
        1,
        'DocuSign::eSign::Api::AccountsApi',
      ],
    ],
  ],
  [
    'updatechunkeduploadoptions',
    [
      'UpdateChunkedUploadOptions',
      [
        '../class_docu_sign_1_1e_sign_1_1_api_1_1_envelopes_api_1_1_update_chunked_upload_options.html',
        1,
        'DocuSign::eSign::Api::EnvelopesApi',
      ],
    ],
  ],
  [
    'updateconsumerdisclosureoptions',
    [
      'UpdateConsumerDisclosureOptions',
      [
        '../class_docu_sign_1_1e_sign_1_1_api_1_1_accounts_api_1_1_update_consumer_disclosure_options.html',
        1,
        'DocuSign::eSign::Api::AccountsApi',
      ],
    ],
  ],
  [
    'updatecustomfieldoptions',
    [
      'UpdateCustomFieldOptions',
      [
        '../class_docu_sign_1_1e_sign_1_1_api_1_1_accounts_api_1_1_update_custom_field_options.html',
        1,
        'DocuSign::eSign::Api::AccountsApi',
      ],
    ],
  ],
  [
    'updatedocumentoptions',
    [
      'UpdateDocumentOptions',
      [
        '../class_docu_sign_1_1e_sign_1_1_api_1_1_templates_api_1_1_update_document_options.html',
        1,
        'DocuSign::eSign::Api::TemplatesApi',
      ],
    ],
  ],
  [
    'updateoptions',
    [
      'UpdateOptions',
      [
        '../class_docu_sign_1_1e_sign_1_1_api_1_1_envelopes_api_1_1_update_options.html',
        1,
        'DocuSign::eSign::Api::EnvelopesApi',
      ],
    ],
  ],
  [
    'updatepermissionprofileoptions',
    [
      'UpdatePermissionProfileOptions',
      [
        '../class_docu_sign_1_1e_sign_1_1_api_1_1_accounts_api_1_1_update_permission_profile_options.html',
        1,
        'DocuSign::eSign::Api::AccountsApi',
      ],
    ],
  ],
  [
    'updateplanoptions',
    [
      'UpdatePlanOptions',
      [
        '../class_docu_sign_1_1e_sign_1_1_api_1_1_billing_api_1_1_update_plan_options.html',
        1,
        'DocuSign::eSign::Api::BillingApi',
      ],
    ],
  ],
  [
    'updaterecipientsoptions',
    [
      'UpdateRecipientsOptions',
      [
        '../class_docu_sign_1_1e_sign_1_1_api_1_1_envelopes_api_1_1_update_recipients_options.html',
        1,
        'DocuSign::eSign::Api::EnvelopesApi',
      ],
    ],
  ],
  [
    'updaterecipientsoptions',
    [
      'UpdateRecipientsOptions',
      [
        '../class_docu_sign_1_1e_sign_1_1_api_1_1_templates_api_1_1_update_recipients_options.html',
        1,
        'DocuSign::eSign::Api::TemplatesApi',
      ],
    ],
  ],
  [
    'updatesharedaccessoptions',
    [
      'UpdateSharedAccessOptions',
      [
        '../class_docu_sign_1_1e_sign_1_1_api_1_1_accounts_api_1_1_update_shared_access_options.html',
        1,
        'DocuSign::eSign::Api::AccountsApi',
      ],
    ],
  ],
  [
    'updatesignatureimageoptions',
    [
      'UpdateSignatureImageOptions',
      [
        '../class_docu_sign_1_1e_sign_1_1_api_1_1_users_api_1_1_update_signature_image_options.html',
        1,
        'DocuSign::eSign::Api::UsersApi',
      ],
    ],
  ],
  [
    'updatesignatureoptions',
    [
      'UpdateSignatureOptions',
      [
        '../class_docu_sign_1_1e_sign_1_1_api_1_1_users_api_1_1_update_signature_options.html',
        1,
        'DocuSign::eSign::Api::UsersApi',
      ],
    ],
  ],
  [
    'updatetransactionrequest',
    [
      'UpdateTransactionRequest',
      [
        '../class_docu_sign_1_1e_sign_1_1_model_1_1_update_transaction_request.html',
        1,
        'DocuSign::eSign::Model',
      ],
    ],
  ],
  [
    'updatetransactionresponse',
    [
      'UpdateTransactionResponse',
      [
        '../class_docu_sign_1_1e_sign_1_1_model_1_1_update_transaction_response.html',
        1,
        'DocuSign::eSign::Model',
      ],
    ],
  ],
  [
    'usagehistory',
    [
      'UsageHistory',
      [
        '../class_docu_sign_1_1e_sign_1_1_model_1_1_usage_history.html',
        1,
        'DocuSign::eSign::Model',
      ],
    ],
  ],
  [
    'user',
    [
      'User',
      [
        '../class_docu_sign_1_1e_sign_1_1_model_1_1_user.html',
        1,
        'DocuSign::eSign::Model',
      ],
    ],
  ],
  [
    'useraccountmanagementgranularinformation',
    [
      'UserAccountManagementGranularInformation',
      [
        '../class_docu_sign_1_1e_sign_1_1_model_1_1_user_account_management_granular_information.html',
        1,
        'DocuSign::eSign::Model',
      ],
    ],
  ],
  [
    'userinfo',
    [
      'UserInfo',
      [
        '../class_docu_sign_1_1e_sign_1_1_model_1_1_user_info.html',
        1,
        'DocuSign::eSign::Model',
      ],
    ],
  ],
  [
    'userinfo',
    [
      'UserInfo',
      [
        '../class_docu_sign_1_1e_sign_1_1_client_1_1_auth_1_1_o_auth_1_1_user_info.html',
        1,
        'DocuSign::eSign::Client::Auth::OAuth',
      ],
    ],
  ],
  [
    'userinfolist',
    [
      'UserInfoList',
      [
        '../class_docu_sign_1_1e_sign_1_1_model_1_1_user_info_list.html',
        1,
        'DocuSign::eSign::Model',
      ],
    ],
  ],
  [
    'userinforesponse',
    [
      'UserInfoResponse',
      [
        '../class_docu_sign_1_1e_sign_1_1_model_1_1_user_info_response.html',
        1,
        'DocuSign::eSign::Model',
      ],
    ],
  ],
  [
    'userinformation',
    [
      'UserInformation',
      [
        '../class_docu_sign_1_1e_sign_1_1_model_1_1_user_information.html',
        1,
        'DocuSign::eSign::Model',
      ],
    ],
  ],
  [
    'userinformationlist',
    [
      'UserInformationList',
      [
        '../class_docu_sign_1_1e_sign_1_1_model_1_1_user_information_list.html',
        1,
        'DocuSign::eSign::Model',
      ],
    ],
  ],
  [
    'userpasswordinformation',
    [
      'UserPasswordInformation',
      [
        '../class_docu_sign_1_1e_sign_1_1_model_1_1_user_password_information.html',
        1,
        'DocuSign::eSign::Model',
      ],
    ],
  ],
  [
    'userpasswordrules',
    [
      'UserPasswordRules',
      [
        '../class_docu_sign_1_1e_sign_1_1_model_1_1_user_password_rules.html',
        1,
        'DocuSign::eSign::Model',
      ],
    ],
  ],
  [
    'userprofile',
    [
      'UserProfile',
      [
        '../class_docu_sign_1_1e_sign_1_1_model_1_1_user_profile.html',
        1,
        'DocuSign::eSign::Model',
      ],
    ],
  ],
  [
    'usersapi',
    [
      'UsersApi',
      [
        '../class_docu_sign_1_1e_sign_1_1_api_1_1_users_api.html',
        1,
        'DocuSign::eSign::Api',
      ],
    ],
  ],
  [
    'usersettingsinformation',
    [
      'UserSettingsInformation',
      [
        '../class_docu_sign_1_1e_sign_1_1_model_1_1_user_settings_information.html',
        1,
        'DocuSign::eSign::Model',
      ],
    ],
  ],
  [
    'usershareditem',
    [
      'UserSharedItem',
      [
        '../class_docu_sign_1_1e_sign_1_1_model_1_1_user_shared_item.html',
        1,
        'DocuSign::eSign::Model',
      ],
    ],
  ],
  [
    'usersignature',
    [
      'UserSignature',
      [
        '../class_docu_sign_1_1e_sign_1_1_model_1_1_user_signature.html',
        1,
        'DocuSign::eSign::Model',
      ],
    ],
  ],
  [
    'usersignaturedefinition',
    [
      'UserSignatureDefinition',
      [
        '../class_docu_sign_1_1e_sign_1_1_model_1_1_user_signature_definition.html',
        1,
        'DocuSign::eSign::Model',
      ],
    ],
  ],
  [
    'usersignaturesinformation',
    [
      'UserSignaturesInformation',
      [
        '../class_docu_sign_1_1e_sign_1_1_model_1_1_user_signatures_information.html',
        1,
        'DocuSign::eSign::Model',
      ],
    ],
  ],
  [
    'usersocialidresult',
    [
      'UserSocialIdResult',
      [
        '../class_docu_sign_1_1e_sign_1_1_model_1_1_user_social_id_result.html',
        1,
        'DocuSign::eSign::Model',
      ],
    ],
  ],
  [
    'usersresponse',
    [
      'UsersResponse',
      [
        '../class_docu_sign_1_1e_sign_1_1_model_1_1_users_response.html',
        1,
        'DocuSign::eSign::Model',
      ],
    ],
  ],
];
