var searchData = [
  [
    'makepayment',
    [
      'MakePayment',
      [
        '../interface_docu_sign_1_1e_sign_1_1_api_1_1_i_billing_api.html#ab07afae5b2938c3976d99c99547f3405',
        1,
        'DocuSign.eSign.Api.IBillingApi.MakePayment()',
      ],
      [
        '../class_docu_sign_1_1e_sign_1_1_api_1_1_billing_api.html#a1119c70ee7f7b65477def5876ae92b43',
        1,
        'DocuSign.eSign.Api.BillingApi.MakePayment()',
      ],
    ],
  ],
  [
    'makepaymentasync',
    [
      'MakePaymentAsync',
      [
        '../interface_docu_sign_1_1e_sign_1_1_api_1_1_i_billing_api.html#a39e308ecfe651fea9823ccc4ba6951e9',
        1,
        'DocuSign.eSign.Api.IBillingApi.MakePaymentAsync()',
      ],
      [
        '../class_docu_sign_1_1e_sign_1_1_api_1_1_billing_api.html#ab781a7f07f34850aa7aa70d90c87ebb9',
        1,
        'DocuSign.eSign.Api.BillingApi.MakePaymentAsync()',
      ],
    ],
  ],
  [
    'makepaymentasyncwithhttpinfo',
    [
      'MakePaymentAsyncWithHttpInfo',
      [
        '../interface_docu_sign_1_1e_sign_1_1_api_1_1_i_billing_api.html#adce7108f903022d30eee769299918480',
        1,
        'DocuSign.eSign.Api.IBillingApi.MakePaymentAsyncWithHttpInfo()',
      ],
      [
        '../class_docu_sign_1_1e_sign_1_1_api_1_1_billing_api.html#aafd88365e1c8d1e08c3bd7a0d3fcb714',
        1,
        'DocuSign.eSign.Api.BillingApi.MakePaymentAsyncWithHttpInfo()',
      ],
    ],
  ],
  [
    'makepaymentwithhttpinfo',
    [
      'MakePaymentWithHttpInfo',
      [
        '../interface_docu_sign_1_1e_sign_1_1_api_1_1_i_billing_api.html#adb40337d51a0d23bf2bdc8794b87ddd0',
        1,
        'DocuSign.eSign.Api.IBillingApi.MakePaymentWithHttpInfo()',
      ],
      [
        '../class_docu_sign_1_1e_sign_1_1_api_1_1_billing_api.html#a5f65852ca7dc671054de24eb402a9bd1',
        1,
        'DocuSign.eSign.Api.BillingApi.MakePaymentWithHttpInfo()',
      ],
    ],
  ],
  [
    'matchbox',
    [
      'MatchBox',
      [
        '../class_docu_sign_1_1e_sign_1_1_model_1_1_match_box.html#a158bffe2213c0408548a3fc0690f6f36',
        1,
        'DocuSign.eSign.Model.MatchBox.MatchBox()',
      ],
      [
        '../class_docu_sign_1_1e_sign_1_1_model_1_1_match_box.html#a474362cd63cb9caaaa5a76d837541c1e',
        1,
        'DocuSign.eSign.Model.MatchBox.MatchBox(string Height=default(string), string PageNumber=default(string), string Width=default(string), string XPosition=default(string), string YPosition=default(string))',
      ],
    ],
  ],
  [
    'membergroupshareditem',
    [
      'MemberGroupSharedItem',
      [
        '../class_docu_sign_1_1e_sign_1_1_model_1_1_member_group_shared_item.html#af237dd1af65347c36b9c6dea6c556d19',
        1,
        'DocuSign.eSign.Model.MemberGroupSharedItem.MemberGroupSharedItem()',
      ],
      [
        '../class_docu_sign_1_1e_sign_1_1_model_1_1_member_group_shared_item.html#a63c3292f37dfb43ecf69c8ffadd5ae16',
        1,
        'DocuSign.eSign.Model.MemberGroupSharedItem.MemberGroupSharedItem(ErrorDetails ErrorDetails=default(ErrorDetails), Group Group=default(Group), string Shared=default(string))',
      ],
    ],
  ],
  [
    'membershareditems',
    [
      'MemberSharedItems',
      [
        '../class_docu_sign_1_1e_sign_1_1_model_1_1_member_shared_items.html#a61faa9d8f72a148bf57359522d673ef8',
        1,
        'DocuSign.eSign.Model.MemberSharedItems.MemberSharedItems()',
      ],
      [
        '../class_docu_sign_1_1e_sign_1_1_model_1_1_member_shared_items.html#a218566a66162044f994900f6fc30730c',
        1,
        'DocuSign.eSign.Model.MemberSharedItems.MemberSharedItems(List&lt; SharedItem &gt; Envelopes=default(List&lt; SharedItem &gt;), ErrorDetails ErrorDetails=default(ErrorDetails), List&lt; FolderSharedItem &gt; Folders=default(List&lt; FolderSharedItem &gt;), List&lt; TemplateSharedItem &gt; Templates=default(List&lt; TemplateSharedItem &gt;), UserInfo User=default(UserInfo))',
      ],
    ],
  ],
  [
    'mergefield',
    [
      'MergeField',
      [
        '../class_docu_sign_1_1e_sign_1_1_model_1_1_merge_field.html#a4dc41bd3c9b3c1dd6ede1de40d23d2ec',
        1,
        'DocuSign.eSign.Model.MergeField.MergeField()',
      ],
      [
        '../class_docu_sign_1_1e_sign_1_1_model_1_1_merge_field.html#a1401a30e751cdfecc53477241f10ccbe',
        1,
        'DocuSign.eSign.Model.MergeField.MergeField(string AllowSenderToEdit=default(string), PropertyMetadata AllowSenderToEditMetadata=default(PropertyMetadata), string ConfigurationType=default(string), PropertyMetadata ConfigurationTypeMetadata=default(PropertyMetadata), string Path=default(string), List&lt; PathExtendedElement &gt; PathExtended=default(List&lt; PathExtendedElement &gt;), PropertyMetadata PathExtendedMetadata=default(PropertyMetadata), PropertyMetadata PathMetadata=default(PropertyMetadata), string Row=default(string), PropertyMetadata RowMetadata=default(PropertyMetadata), string WriteBack=default(string), PropertyMetadata WriteBackMetadata=default(PropertyMetadata))',
      ],
    ],
  ],
  [
    'mobilenotifierconfiguration',
    [
      'MobileNotifierConfiguration',
      [
        '../class_docu_sign_1_1e_sign_1_1_model_1_1_mobile_notifier_configuration.html#aa099aaf47bb9115387db0dbb927fc33d',
        1,
        'DocuSign.eSign.Model.MobileNotifierConfiguration.MobileNotifierConfiguration()',
      ],
      [
        '../class_docu_sign_1_1e_sign_1_1_model_1_1_mobile_notifier_configuration.html#ab2030427d9a93ed04b8f03e9e93a2d86',
        1,
        'DocuSign.eSign.Model.MobileNotifierConfiguration.MobileNotifierConfiguration(string DeviceId=default(string), ErrorDetails ErrorDetails=default(ErrorDetails), string Platform=default(string))',
      ],
    ],
  ],
  [
    'mobilenotifierconfigurationinformation',
    [
      'MobileNotifierConfigurationInformation',
      [
        '../class_docu_sign_1_1e_sign_1_1_model_1_1_mobile_notifier_configuration_information.html#a146be06f606984daae03ca489292108a',
        1,
        'DocuSign.eSign.Model.MobileNotifierConfigurationInformation.MobileNotifierConfigurationInformation()',
      ],
      [
        '../class_docu_sign_1_1e_sign_1_1_model_1_1_mobile_notifier_configuration_information.html#a57b9bb58dffcc77330133775e0016c1d',
        1,
        'DocuSign.eSign.Model.MobileNotifierConfigurationInformation.MobileNotifierConfigurationInformation(List&lt; MobileNotifierConfiguration &gt; MobileNotifierConfigurations=default(List&lt; MobileNotifierConfiguration &gt;))',
      ],
    ],
  ],
  [
    'money',
    [
      'Money',
      [
        '../class_docu_sign_1_1e_sign_1_1_model_1_1_money.html#ab0861290d3d6d56957be6fd589472909',
        1,
        'DocuSign.eSign.Model.Money.Money()',
      ],
      [
        '../class_docu_sign_1_1e_sign_1_1_model_1_1_money.html#a096209c833754e9b9d9629bfcc883885',
        1,
        'DocuSign.eSign.Model.Money.Money(string AmountInBaseUnit=default(string), string Currency=default(string), string DisplayAmount=default(string))',
      ],
    ],
  ],
  [
    'moveenvelopes',
    [
      'MoveEnvelopes',
      [
        '../interface_docu_sign_1_1e_sign_1_1_api_1_1_i_folders_api.html#a5c9c5f74797d56d3d0af6370126eb0dc',
        1,
        'DocuSign.eSign.Api.IFoldersApi.MoveEnvelopes()',
      ],
      [
        '../class_docu_sign_1_1e_sign_1_1_api_1_1_folders_api.html#afbc7fb0c4bbca715f5eed4a59837148e',
        1,
        'DocuSign.eSign.Api.FoldersApi.MoveEnvelopes()',
      ],
    ],
  ],
  [
    'moveenvelopesasync',
    [
      'MoveEnvelopesAsync',
      [
        '../interface_docu_sign_1_1e_sign_1_1_api_1_1_i_folders_api.html#a6c84dd9bc1047a0a7811230ac80fe85c',
        1,
        'DocuSign.eSign.Api.IFoldersApi.MoveEnvelopesAsync()',
      ],
      [
        '../class_docu_sign_1_1e_sign_1_1_api_1_1_folders_api.html#a7f65aaf38ab090d4c09a2766b0a8c215',
        1,
        'DocuSign.eSign.Api.FoldersApi.MoveEnvelopesAsync()',
      ],
    ],
  ],
  [
    'moveenvelopesasyncwithhttpinfo',
    [
      'MoveEnvelopesAsyncWithHttpInfo',
      [
        '../interface_docu_sign_1_1e_sign_1_1_api_1_1_i_folders_api.html#a3f13d0b6ecf863412640dcef3c0eb81e',
        1,
        'DocuSign.eSign.Api.IFoldersApi.MoveEnvelopesAsyncWithHttpInfo()',
      ],
      [
        '../class_docu_sign_1_1e_sign_1_1_api_1_1_folders_api.html#a0e0fbe15aad08569e94c84c87eee9465',
        1,
        'DocuSign.eSign.Api.FoldersApi.MoveEnvelopesAsyncWithHttpInfo()',
      ],
    ],
  ],
  [
    'moveenvelopeswithhttpinfo',
    [
      'MoveEnvelopesWithHttpInfo',
      [
        '../interface_docu_sign_1_1e_sign_1_1_api_1_1_i_folders_api.html#ab92f59536df3e9dbdba30a84800f2ca8',
        1,
        'DocuSign.eSign.Api.IFoldersApi.MoveEnvelopesWithHttpInfo()',
      ],
      [
        '../class_docu_sign_1_1e_sign_1_1_api_1_1_folders_api.html#ac09517015f6d34a0f6545eb7d25afb22',
        1,
        'DocuSign.eSign.Api.FoldersApi.MoveEnvelopesWithHttpInfo()',
      ],
    ],
  ],
];
