var searchData = [
  [
    'radio',
    [
      'Radio',
      [
        '../class_docu_sign_1_1e_sign_1_1_model_1_1_radio.html#a35221c1705a32de6dd4b732b3b845f78',
        1,
        'DocuSign.eSign.Model.Radio.Radio()',
      ],
      [
        '../class_docu_sign_1_1e_sign_1_1_model_1_1_radio.html#af5b52d7ffdcbe4cae0061921416dbd16',
        1,
        'DocuSign.eSign.Model.Radio.Radio(string AnchorAllowWhiteSpaceInCharacters=default(string), PropertyMetadata AnchorAllowWhiteSpaceInCharactersMetadata=default(PropertyMetadata), string AnchorCaseSensitive=default(string), PropertyMetadata AnchorCaseSensitiveMetadata=default(PropertyMetadata), string AnchorHorizontalAlignment=default(string), PropertyMetadata AnchorHorizontalAlignmentMetadata=default(PropertyMetadata), string AnchorIgnoreIfNotPresent=default(string), PropertyMetadata AnchorIgnoreIfNotPresentMetadata=default(PropertyMetadata), string AnchorMatchWholeWord=default(string), PropertyMetadata AnchorMatchWholeWordMetadata=default(PropertyMetadata), string AnchorString=default(string), PropertyMetadata AnchorStringMetadata=default(PropertyMetadata), string AnchorTabProcessorVersion=default(string), PropertyMetadata AnchorTabProcessorVersionMetadata=default(PropertyMetadata), string AnchorUnits=default(string), PropertyMetadata AnchorUnitsMetadata=default(PropertyMetadata), string AnchorXOffset=default(string), PropertyMetadata AnchorXOffsetMetadata=default(PropertyMetadata), string AnchorYOffset=default(string), PropertyMetadata AnchorYOffsetMetadata=default(PropertyMetadata), string Bold=default(string), PropertyMetadata BoldMetadata=default(PropertyMetadata), ErrorDetails ErrorDetails=default(ErrorDetails), string Font=default(string), string FontColor=default(string), PropertyMetadata FontColorMetadata=default(PropertyMetadata), PropertyMetadata FontMetadata=default(PropertyMetadata), string FontSize=default(string), PropertyMetadata FontSizeMetadata=default(PropertyMetadata), string Italic=default(string), PropertyMetadata ItalicMetadata=default(PropertyMetadata), string Locked=default(string), PropertyMetadata LockedMetadata=default(PropertyMetadata), string PageNumber=default(string), PropertyMetadata PageNumberMetadata=default(PropertyMetadata), string Required=default(string), PropertyMetadata RequiredMetadata=default(PropertyMetadata), string Selected=default(string), PropertyMetadata SelectedMetadata=default(PropertyMetadata), string Status=default(string), PropertyMetadata StatusMetadata=default(PropertyMetadata), string TabId=default(string), PropertyMetadata TabIdMetadata=default(PropertyMetadata), string TabOrder=default(string), PropertyMetadata TabOrderMetadata=default(PropertyMetadata), string Underline=default(string), PropertyMetadata UnderlineMetadata=default(PropertyMetadata), string Value=default(string), PropertyMetadata ValueMetadata=default(PropertyMetadata), string XPosition=default(string), PropertyMetadata XPositionMetadata=default(PropertyMetadata), string YPosition=default(string), PropertyMetadata YPositionMetadata=default(PropertyMetadata))',
      ],
    ],
  ],
  [
    'radiogroup',
    [
      'RadioGroup',
      [
        '../class_docu_sign_1_1e_sign_1_1_model_1_1_radio_group.html#a65c7258f167317e7d6acd574339f8cdb',
        1,
        'DocuSign.eSign.Model.RadioGroup.RadioGroup()',
      ],
      [
        '../class_docu_sign_1_1e_sign_1_1_model_1_1_radio_group.html#a8abcf2939e5e6d4e68dafc6bf1b8b9b9',
        1,
        'DocuSign.eSign.Model.RadioGroup.RadioGroup(string ConditionalParentLabel=default(string), PropertyMetadata ConditionalParentLabelMetadata=default(PropertyMetadata), string ConditionalParentValue=default(string), PropertyMetadata ConditionalParentValueMetadata=default(PropertyMetadata), string DocumentId=default(string), PropertyMetadata DocumentIdMetadata=default(PropertyMetadata), string GroupName=default(string), PropertyMetadata GroupNameMetadata=default(PropertyMetadata), List&lt; Radio &gt; Radios=default(List&lt; Radio &gt;), string RecipientId=default(string), string RecipientIdGuid=default(string), PropertyMetadata RecipientIdGuidMetadata=default(PropertyMetadata), PropertyMetadata RecipientIdMetadata=default(PropertyMetadata), string RequireAll=default(string), PropertyMetadata RequireAllMetadata=default(PropertyMetadata), string RequireInitialOnSharedChange=default(string), PropertyMetadata RequireInitialOnSharedChangeMetadata=default(PropertyMetadata), string Shared=default(string), PropertyMetadata SharedMetadata=default(PropertyMetadata), string TabType=default(string), PropertyMetadata TabTypeMetadata=default(PropertyMetadata), string TemplateLocked=default(string), PropertyMetadata TemplateLockedMetadata=default(PropertyMetadata), string TemplateRequired=default(string), PropertyMetadata TemplateRequiredMetadata=default(PropertyMetadata), string Tooltip=default(string), PropertyMetadata TooltipMetadata=default(PropertyMetadata))',
      ],
    ],
  ],
  [
    'readasbytes',
    [
      'ReadAsBytes',
      [
        '../class_docu_sign_1_1e_sign_1_1_client_1_1_api_client.html#a1ecf8ec9bfafdf4fefce15d398bebb96',
        1,
        'DocuSign::eSign::Client::ApiClient',
      ],
    ],
  ],
  [
    'recipientadditionalnotification',
    [
      'RecipientAdditionalNotification',
      [
        '../class_docu_sign_1_1e_sign_1_1_model_1_1_recipient_additional_notification.html#ad1593547f84b860f8b6c82145dded3f5',
        1,
        'DocuSign.eSign.Model.RecipientAdditionalNotification.RecipientAdditionalNotification()',
      ],
      [
        '../class_docu_sign_1_1e_sign_1_1_model_1_1_recipient_additional_notification.html#ad9f896ceb959a3afb63ac4e4bcbe2e9e',
        1,
        'DocuSign.eSign.Model.RecipientAdditionalNotification.RecipientAdditionalNotification(RecipientPhoneNumber PhoneNumber=default(RecipientPhoneNumber), string SecondaryDeliveryMethod=default(string), PropertyMetadata SecondaryDeliveryMethodMetadata=default(PropertyMetadata), string SecondaryDeliveryStatus=default(string))',
      ],
    ],
  ],
  [
    'recipientattachment',
    [
      'RecipientAttachment',
      [
        '../class_docu_sign_1_1e_sign_1_1_model_1_1_recipient_attachment.html#a791174eab26c0f47f8bd9d50d83d6bad',
        1,
        'DocuSign.eSign.Model.RecipientAttachment.RecipientAttachment()',
      ],
      [
        '../class_docu_sign_1_1e_sign_1_1_model_1_1_recipient_attachment.html#aceb8a9f97af3b4e8dee44292bd713eae',
        1,
        'DocuSign.eSign.Model.RecipientAttachment.RecipientAttachment(string AttachmentId=default(string), string AttachmentType=default(string), string Data=default(string), string Label=default(string), string Name=default(string), string RemoteUrl=default(string))',
      ],
    ],
  ],
  [
    'recipientdomain',
    [
      'RecipientDomain',
      [
        '../class_docu_sign_1_1e_sign_1_1_model_1_1_recipient_domain.html#a836bb90b7e1805412f18733f0300ee8e',
        1,
        'DocuSign.eSign.Model.RecipientDomain.RecipientDomain()',
      ],
      [
        '../class_docu_sign_1_1e_sign_1_1_model_1_1_recipient_domain.html#a21d6634d1cd8c9a76b0404f48ef104bd',
        1,
        'DocuSign.eSign.Model.RecipientDomain.RecipientDomain(string Active=default(string), string DomainCode=default(string), string DomainName=default(string), string RecipientDomainId=default(string))',
      ],
    ],
  ],
  [
    'recipientemail',
    [
      'RecipientEmail',
      [
        '../class_docu_sign_1_1e_sign_1_1_model_1_1_recipient_email.html#a53f65f4f999708f13e9d619d4bd62780',
        1,
        'DocuSign.eSign.Model.RecipientEmail.RecipientEmail()',
      ],
      [
        '../class_docu_sign_1_1e_sign_1_1_model_1_1_recipient_email.html#a2ff939226b23159dc03097c613ded22f',
        1,
        'DocuSign.eSign.Model.RecipientEmail.RecipientEmail(string AccountId=default(string), string AccountName=default(string), string Email=default(string), string EnvelopeId=default(string), string Name=default(string), string RecipientId=default(string), bool?Supported=default(bool?), string UserId=default(string))',
      ],
    ],
  ],
  [
    'recipientemailnotification',
    [
      'RecipientEmailNotification',
      [
        '../class_docu_sign_1_1e_sign_1_1_model_1_1_recipient_email_notification.html#ae3a3d67e2c046554eb4948d074dc1678',
        1,
        'DocuSign.eSign.Model.RecipientEmailNotification.RecipientEmailNotification()',
      ],
      [
        '../class_docu_sign_1_1e_sign_1_1_model_1_1_recipient_email_notification.html#a7dae220557546515054654c8ee7dd545',
        1,
        'DocuSign.eSign.Model.RecipientEmailNotification.RecipientEmailNotification(string EmailBody=default(string), PropertyMetadata EmailBodyMetadata=default(PropertyMetadata), string EmailSubject=default(string), PropertyMetadata EmailSubjectMetadata=default(PropertyMetadata), string SupportedLanguage=default(string), PropertyMetadata SupportedLanguageMetadata=default(PropertyMetadata))',
      ],
    ],
  ],
  [
    'recipientevent',
    [
      'RecipientEvent',
      [
        '../class_docu_sign_1_1e_sign_1_1_model_1_1_recipient_event.html#a0ed9a33f0bae7fd09dffa06147b8f851',
        1,
        'DocuSign.eSign.Model.RecipientEvent.RecipientEvent()',
      ],
      [
        '../class_docu_sign_1_1e_sign_1_1_model_1_1_recipient_event.html#ab69cdf3f3ccc0b700a3f7f933295c394',
        1,
        'DocuSign.eSign.Model.RecipientEvent.RecipientEvent(string IncludeDocuments=default(string), string RecipientEventStatusCode=default(string))',
      ],
    ],
  ],
  [
    'recipientformdata',
    [
      'RecipientFormData',
      [
        '../class_docu_sign_1_1e_sign_1_1_model_1_1_recipient_form_data.html#a8ef7e25888c9e592b693882c3d30809b',
        1,
        'DocuSign.eSign.Model.RecipientFormData.RecipientFormData()',
      ],
      [
        '../class_docu_sign_1_1e_sign_1_1_model_1_1_recipient_form_data.html#ae80e9946c776c28105d5180da57c14d1',
        1,
        'DocuSign.eSign.Model.RecipientFormData.RecipientFormData(string DeclinedTime=default(string), string DeliveredTime=default(string), string Email=default(string), List&lt; FormDataItem &gt; FormData=default(List&lt; FormDataItem &gt;), string Name=default(string), string RecipientId=default(string), string SentTime=default(string), string SignedTime=default(string))',
      ],
    ],
  ],
  [
    'recipientgroup',
    [
      'RecipientGroup',
      [
        '../class_docu_sign_1_1e_sign_1_1_model_1_1_recipient_group.html#ae4efa22eb404a6519043688d147749b0',
        1,
        'DocuSign.eSign.Model.RecipientGroup.RecipientGroup()',
      ],
      [
        '../class_docu_sign_1_1e_sign_1_1_model_1_1_recipient_group.html#a01cc356c299ae600e510ab2bb3423cd2',
        1,
        'DocuSign.eSign.Model.RecipientGroup.RecipientGroup(string GroupMessage=default(string), string GroupName=default(string), List&lt; RecipientOption &gt; Recipients=default(List&lt; RecipientOption &gt;))',
      ],
    ],
  ],
  [
    'recipientidentityinputoption',
    [
      'RecipientIdentityInputOption',
      [
        '../class_docu_sign_1_1e_sign_1_1_model_1_1_recipient_identity_input_option.html#a3ed90633a26c9654a34c890fa26ec6de',
        1,
        'DocuSign.eSign.Model.RecipientIdentityInputOption.RecipientIdentityInputOption()',
      ],
      [
        '../class_docu_sign_1_1e_sign_1_1_model_1_1_recipient_identity_input_option.html#a9fecff482589ff426036ebeb23d80f8d',
        1,
        'DocuSign.eSign.Model.RecipientIdentityInputOption.RecipientIdentityInputOption(string Name=default(string), List&lt; RecipientIdentityPhoneNumber &gt; PhoneNumberList=default(List&lt; RecipientIdentityPhoneNumber &gt;), string ValueType=default(string))',
      ],
    ],
  ],
  [
    'recipientidentityphonenumber',
    [
      'RecipientIdentityPhoneNumber',
      [
        '../class_docu_sign_1_1e_sign_1_1_model_1_1_recipient_identity_phone_number.html#a9782b284d1168bc78d1405f2a4c71c99',
        1,
        'DocuSign.eSign.Model.RecipientIdentityPhoneNumber.RecipientIdentityPhoneNumber()',
      ],
      [
        '../class_docu_sign_1_1e_sign_1_1_model_1_1_recipient_identity_phone_number.html#a427241adc43ac18a0f5d008a4358b0b2',
        1,
        'DocuSign.eSign.Model.RecipientIdentityPhoneNumber.RecipientIdentityPhoneNumber(string CountryCode=default(string), string Extension=default(string), string Number=default(string))',
      ],
    ],
  ],
  [
    'recipientidentityverification',
    [
      'RecipientIdentityVerification',
      [
        '../class_docu_sign_1_1e_sign_1_1_model_1_1_recipient_identity_verification.html#a59293547410a44e885ae1e0c733280d0',
        1,
        'DocuSign.eSign.Model.RecipientIdentityVerification.RecipientIdentityVerification()',
      ],
      [
        '../class_docu_sign_1_1e_sign_1_1_model_1_1_recipient_identity_verification.html#a861c4018d5863f279b22c493672d4280',
        1,
        'DocuSign.eSign.Model.RecipientIdentityVerification.RecipientIdentityVerification(List&lt; RecipientIdentityInputOption &gt; InputOptions=default(List&lt; RecipientIdentityInputOption &gt;), string WorkflowId=default(string))',
      ],
    ],
  ],
  [
    'recipientnamesresponse',
    [
      'RecipientNamesResponse',
      [
        '../class_docu_sign_1_1e_sign_1_1_model_1_1_recipient_names_response.html#a15851a683c1d19ce5c953c39ae3476dd',
        1,
        'DocuSign.eSign.Model.RecipientNamesResponse.RecipientNamesResponse()',
      ],
      [
        '../class_docu_sign_1_1e_sign_1_1_model_1_1_recipient_names_response.html#a7ea6882c4dbe6804012a29861c919517',
        1,
        'DocuSign.eSign.Model.RecipientNamesResponse.RecipientNamesResponse(string MultipleUsers=default(string), List&lt; string &gt; RecipientNames=default(List&lt; string &gt;), string ReservedRecipientEmail=default(string))',
      ],
    ],
  ],
  [
    'recipientoption',
    [
      'RecipientOption',
      [
        '../class_docu_sign_1_1e_sign_1_1_model_1_1_recipient_option.html#a831f659925b650004321155362a36257',
        1,
        'DocuSign.eSign.Model.RecipientOption.RecipientOption()',
      ],
      [
        '../class_docu_sign_1_1e_sign_1_1_model_1_1_recipient_option.html#a2445a8cb674ac1a8647d934ab103e7ac',
        1,
        'DocuSign.eSign.Model.RecipientOption.RecipientOption(string Email=default(string), string Name=default(string), string RecipientLabel=default(string), string RoleName=default(string), string SigningGroupId=default(string))',
      ],
    ],
  ],
  [
    'recipientphoneauthentication',
    [
      'RecipientPhoneAuthentication',
      [
        '../class_docu_sign_1_1e_sign_1_1_model_1_1_recipient_phone_authentication.html#a2ede134254f17c6330970fe44f6f7dab',
        1,
        'DocuSign.eSign.Model.RecipientPhoneAuthentication.RecipientPhoneAuthentication()',
      ],
      [
        '../class_docu_sign_1_1e_sign_1_1_model_1_1_recipient_phone_authentication.html#a8e964294e3cadab74d675bfac4a5c87e',
        1,
        'DocuSign.eSign.Model.RecipientPhoneAuthentication.RecipientPhoneAuthentication(string RecipMayProvideNumber=default(string), PropertyMetadata RecipMayProvideNumberMetadata=default(PropertyMetadata), string RecordVoicePrint=default(string), PropertyMetadata RecordVoicePrintMetadata=default(PropertyMetadata), List&lt; string &gt; SenderProvidedNumbers=default(List&lt; string &gt;), PropertyMetadata SenderProvidedNumbersMetadata=default(PropertyMetadata), string ValidateRecipProvidedNumber=default(string), PropertyMetadata ValidateRecipProvidedNumberMetadata=default(PropertyMetadata))',
      ],
    ],
  ],
  [
    'recipientphonenumber',
    [
      'RecipientPhoneNumber',
      [
        '../class_docu_sign_1_1e_sign_1_1_model_1_1_recipient_phone_number.html#ad89f5afeeab6691483e109b8368b0099',
        1,
        'DocuSign.eSign.Model.RecipientPhoneNumber.RecipientPhoneNumber()',
      ],
      [
        '../class_docu_sign_1_1e_sign_1_1_model_1_1_recipient_phone_number.html#ac0737fe8c2cd816b7dffa4b0fe6ea5f9',
        1,
        'DocuSign.eSign.Model.RecipientPhoneNumber.RecipientPhoneNumber(string CountryCode=default(string), PropertyMetadata CountryCodeMetadata=default(PropertyMetadata), string Number=default(string), PropertyMetadata NumberMetadata=default(PropertyMetadata))',
      ],
    ],
  ],
  [
    'recipientpreviewrequest',
    [
      'RecipientPreviewRequest',
      [
        '../class_docu_sign_1_1e_sign_1_1_model_1_1_recipient_preview_request.html#abca7aafd652ddceefd193598c5ee6eb1',
        1,
        'DocuSign.eSign.Model.RecipientPreviewRequest.RecipientPreviewRequest()',
      ],
      [
        '../class_docu_sign_1_1e_sign_1_1_model_1_1_recipient_preview_request.html#a40d36c780354a7095f9d6c6227676b4f',
        1,
        'DocuSign.eSign.Model.RecipientPreviewRequest.RecipientPreviewRequest(string AssertionId=default(string), string AuthenticationInstant=default(string), string AuthenticationMethod=default(string), string PingFrequency=default(string), string PingUrl=default(string), string RecipientId=default(string), string ReturnUrl=default(string), string SecurityDomain=default(string), string XFrameOptions=default(string), string XFrameOptionsAllowFromUrl=default(string))',
      ],
    ],
  ],
  [
    'recipientprooffile',
    [
      'RecipientProofFile',
      [
        '../class_docu_sign_1_1e_sign_1_1_model_1_1_recipient_proof_file.html#a62e55ea01e3e009a067f668c66fe175a',
        1,
        'DocuSign.eSign.Model.RecipientProofFile.RecipientProofFile()',
      ],
      [
        '../class_docu_sign_1_1e_sign_1_1_model_1_1_recipient_proof_file.html#adb0304a0bfe53dbea22105d51ebb60a2',
        1,
        'DocuSign.eSign.Model.RecipientProofFile.RecipientProofFile(string IsInProofFile=default(string))',
      ],
    ],
  ],
  [
    'recipientrouting',
    [
      'RecipientRouting',
      [
        '../class_docu_sign_1_1e_sign_1_1_model_1_1_recipient_routing.html#a52694d9abf86a9c0e6f406c2b6c4d616',
        1,
        'DocuSign.eSign.Model.RecipientRouting.RecipientRouting()',
      ],
      [
        '../class_docu_sign_1_1e_sign_1_1_model_1_1_recipient_routing.html#aeaa9aeb47d8acc87675584279cbaa271',
        1,
        'DocuSign.eSign.Model.RecipientRouting.RecipientRouting(RecipientRules Rules=default(RecipientRules))',
      ],
    ],
  ],
  [
    'recipientrules',
    [
      'RecipientRules',
      [
        '../class_docu_sign_1_1e_sign_1_1_model_1_1_recipient_rules.html#ac33c87cf3870ceab051ff94b62017ac6',
        1,
        'DocuSign.eSign.Model.RecipientRules.RecipientRules()',
      ],
      [
        '../class_docu_sign_1_1e_sign_1_1_model_1_1_recipient_rules.html#ad780bb0acf8473cce02498bcb65febb8',
        1,
        'DocuSign.eSign.Model.RecipientRules.RecipientRules(List&lt; ConditionalRecipientRule &gt; ConditionalRecipients=default(List&lt; ConditionalRecipientRule &gt;))',
      ],
    ],
  ],
  [
    'recipients',
    [
      'Recipients',
      [
        '../class_docu_sign_1_1e_sign_1_1_model_1_1_recipients.html#a4c24edbcd7047981c082d766c093635d',
        1,
        'DocuSign.eSign.Model.Recipients.Recipients()',
      ],
      [
        '../class_docu_sign_1_1e_sign_1_1_model_1_1_recipients.html#ae789825534702c567c3979ad4e421334',
        1,
        'DocuSign.eSign.Model.Recipients.Recipients(List&lt; Agent &gt; Agents=default(List&lt; Agent &gt;), List&lt; CarbonCopy &gt; CarbonCopies=default(List&lt; CarbonCopy &gt;), List&lt; CertifiedDelivery &gt; CertifiedDeliveries=default(List&lt; CertifiedDelivery &gt;), string CurrentRoutingOrder=default(string), List&lt; Editor &gt; Editors=default(List&lt; Editor &gt;), ErrorDetails ErrorDetails=default(ErrorDetails), List&lt; InPersonSigner &gt; InPersonSigners=default(List&lt; InPersonSigner &gt;), List&lt; Intermediary &gt; Intermediaries=default(List&lt; Intermediary &gt;), List&lt; NotaryRecipient &gt; Notaries=default(List&lt; NotaryRecipient &gt;), string RecipientCount=default(string), List&lt; SealSign &gt; Seals=default(List&lt; SealSign &gt;), List&lt; Signer &gt; Signers=default(List&lt; Signer &gt;), List&lt; Witness &gt; Witnesses=default(List&lt; Witness &gt;))',
      ],
    ],
  ],
  [
    'recipientsamlauthentication',
    [
      'RecipientSAMLAuthentication',
      [
        '../class_docu_sign_1_1e_sign_1_1_model_1_1_recipient_s_a_m_l_authentication.html#ae3719d7e6de468aa47f66d1e337fbac3',
        1,
        'DocuSign.eSign.Model.RecipientSAMLAuthentication.RecipientSAMLAuthentication()',
      ],
      [
        '../class_docu_sign_1_1e_sign_1_1_model_1_1_recipient_s_a_m_l_authentication.html#aa332543812febd6f05e28a42b12f24d0',
        1,
        'DocuSign.eSign.Model.RecipientSAMLAuthentication.RecipientSAMLAuthentication(List&lt; SamlAssertionAttribute &gt; SamlAssertionAttributes=default(List&lt; SamlAssertionAttribute &gt;))',
      ],
    ],
  ],
  [
    'recipientsignatureinformation',
    [
      'RecipientSignatureInformation',
      [
        '../class_docu_sign_1_1e_sign_1_1_model_1_1_recipient_signature_information.html#a582db1f376dfd72eb59e9973fdc20b85',
        1,
        'DocuSign.eSign.Model.RecipientSignatureInformation.RecipientSignatureInformation()',
      ],
      [
        '../class_docu_sign_1_1e_sign_1_1_model_1_1_recipient_signature_information.html#ab96f33b48496b6c9e7de8e69b8b1c8d7',
        1,
        'DocuSign.eSign.Model.RecipientSignatureInformation.RecipientSignatureInformation(string FontStyle=default(string), string SignatureInitials=default(string), string SignatureName=default(string))',
      ],
    ],
  ],
  [
    'recipientsignatureprovider',
    [
      'RecipientSignatureProvider',
      [
        '../class_docu_sign_1_1e_sign_1_1_model_1_1_recipient_signature_provider.html#a4f6e065637302611302b7947da61ce62',
        1,
        'DocuSign.eSign.Model.RecipientSignatureProvider.RecipientSignatureProvider()',
      ],
      [
        '../class_docu_sign_1_1e_sign_1_1_model_1_1_recipient_signature_provider.html#ae6931aaa4cb5c92eec7434564ab42da0',
        1,
        'DocuSign.eSign.Model.RecipientSignatureProvider.RecipientSignatureProvider(string SealDocumentsWithTabsOnly=default(string), string SealName=default(string), string SignatureProviderName=default(string), PropertyMetadata SignatureProviderNameMetadata=default(PropertyMetadata), RecipientSignatureProviderOptions SignatureProviderOptions=default(RecipientSignatureProviderOptions))',
      ],
    ],
  ],
  [
    'recipientsignatureprovideroptions',
    [
      'RecipientSignatureProviderOptions',
      [
        '../class_docu_sign_1_1e_sign_1_1_model_1_1_recipient_signature_provider_options.html#ab2a50bd49563360ee40d8bc193d701da',
        1,
        'DocuSign.eSign.Model.RecipientSignatureProviderOptions.RecipientSignatureProviderOptions()',
      ],
      [
        '../class_docu_sign_1_1e_sign_1_1_model_1_1_recipient_signature_provider_options.html#a730831893d9501d66e98806a29f9ffa4',
        1,
        'DocuSign.eSign.Model.RecipientSignatureProviderOptions.RecipientSignatureProviderOptions(string CpfNumber=default(string), PropertyMetadata CpfNumberMetadata=default(PropertyMetadata), string OneTimePassword=default(string), PropertyMetadata OneTimePasswordMetadata=default(PropertyMetadata), string SignerRole=default(string), PropertyMetadata SignerRoleMetadata=default(PropertyMetadata), string Sms=default(string), PropertyMetadata SmsMetadata=default(PropertyMetadata))',
      ],
    ],
  ],
  [
    'recipientsmsauthentication',
    [
      'RecipientSMSAuthentication',
      [
        '../class_docu_sign_1_1e_sign_1_1_model_1_1_recipient_s_m_s_authentication.html#ae944410d1be0e68e14eca709f2d96f80',
        1,
        'DocuSign.eSign.Model.RecipientSMSAuthentication.RecipientSMSAuthentication()',
      ],
      [
        '../class_docu_sign_1_1e_sign_1_1_model_1_1_recipient_s_m_s_authentication.html#aaf3545705745bdb5ee8c4acb743d81f4',
        1,
        'DocuSign.eSign.Model.RecipientSMSAuthentication.RecipientSMSAuthentication(List&lt; string &gt; SenderProvidedNumbers=default(List&lt; string &gt;), PropertyMetadata SenderProvidedNumbersMetadata=default(PropertyMetadata))',
      ],
    ],
  ],
  [
    'recipientsupdatesummary',
    [
      'RecipientsUpdateSummary',
      [
        '../class_docu_sign_1_1e_sign_1_1_model_1_1_recipients_update_summary.html#ad54f303ae8542860acafb3e7bda3db5e',
        1,
        'DocuSign.eSign.Model.RecipientsUpdateSummary.RecipientsUpdateSummary()',
      ],
      [
        '../class_docu_sign_1_1e_sign_1_1_model_1_1_recipients_update_summary.html#a7144647146ebbfb982fa0ccb774d91b4',
        1,
        'DocuSign.eSign.Model.RecipientsUpdateSummary.RecipientsUpdateSummary(List&lt; RecipientUpdateResponse &gt; RecipientUpdateResults=default(List&lt; RecipientUpdateResponse &gt;))',
      ],
    ],
  ],
  [
    'recipientupdateresponse',
    [
      'RecipientUpdateResponse',
      [
        '../class_docu_sign_1_1e_sign_1_1_model_1_1_recipient_update_response.html#a4322f29fa54f876d577724fbe606eff6',
        1,
        'DocuSign.eSign.Model.RecipientUpdateResponse.RecipientUpdateResponse()',
      ],
      [
        '../class_docu_sign_1_1e_sign_1_1_model_1_1_recipient_update_response.html#a961f590a5318398351500c0048ad46cb',
        1,
        'DocuSign.eSign.Model.RecipientUpdateResponse.RecipientUpdateResponse(string Combined=default(string), ErrorDetails ErrorDetails=default(ErrorDetails), string RecipientId=default(string), string RecipientIdGuid=default(string), Tabs Tabs=default(Tabs))',
      ],
    ],
  ],
  [
    'recipientviewrequest',
    [
      'RecipientViewRequest',
      [
        '../class_docu_sign_1_1e_sign_1_1_model_1_1_recipient_view_request.html#a3d55221d5e6b25c15691435ec48e0fbf',
        1,
        'DocuSign.eSign.Model.RecipientViewRequest.RecipientViewRequest()',
      ],
      [
        '../class_docu_sign_1_1e_sign_1_1_model_1_1_recipient_view_request.html#a7a250cceba631665a0f380dac9f354e9',
        1,
        'DocuSign.eSign.Model.RecipientViewRequest.RecipientViewRequest(string AssertionId=default(string), string AuthenticationInstant=default(string), string AuthenticationMethod=default(string), string ClientUserId=default(string), string Email=default(string), List&lt; string &gt; FrameAncestors=default(List&lt; string &gt;), List&lt; string &gt; MessageOrigins=default(List&lt; string &gt;), string PingFrequency=default(string), string PingUrl=default(string), string RecipientId=default(string), string ReturnUrl=default(string), string SecurityDomain=default(string), string UserId=default(string), string UserName=default(string), string XFrameOptions=default(string), string XFrameOptionsAllowFromUrl=default(string))',
      ],
    ],
  ],
  [
    'referralinformation',
    [
      'ReferralInformation',
      [
        '../class_docu_sign_1_1e_sign_1_1_model_1_1_referral_information.html#a69306568911820bea0006d3aa04f83bf',
        1,
        'DocuSign.eSign.Model.ReferralInformation.ReferralInformation()',
      ],
      [
        '../class_docu_sign_1_1e_sign_1_1_model_1_1_referral_information.html#ad1eb935f26f0065fc57fc64fe088cd79',
        1,
        'DocuSign.eSign.Model.ReferralInformation.ReferralInformation(string AdvertisementId=default(string), string EnableSupport=default(string), string ExternalOrgId=default(string), string GroupMemberId=default(string), string IdType=default(string), string IncludedSeats=default(string), string Industry=default(string), string PlanStartMonth=default(string), string PromoCode=default(string), string PublisherId=default(string), string ReferralCode=default(string), string ReferrerName=default(string), string SaleDiscountAmount=default(string), string SaleDiscountFixedAmount=default(string), string SaleDiscountPercent=default(string), string SaleDiscountPeriods=default(string), string SaleDiscountSeatPriceOverride=default(string), string ShopperId=default(string))',
      ],
    ],
  ],
  [
    'reminders',
    [
      'Reminders',
      [
        '../class_docu_sign_1_1e_sign_1_1_model_1_1_reminders.html#a0af109b70a3463276c1e4461a10d49aa',
        1,
        'DocuSign.eSign.Model.Reminders.Reminders()',
      ],
      [
        '../class_docu_sign_1_1e_sign_1_1_model_1_1_reminders.html#a894f51f2ebaa6d92a1d82ddfb9aabbdc',
        1,
        'DocuSign.eSign.Model.Reminders.Reminders(string ReminderDelay=default(string), string ReminderEnabled=default(string), string ReminderFrequency=default(string))',
      ],
    ],
  ],
  [
    'reportinproductcsvrunrequest',
    [
      'ReportInProductCsvRunRequest',
      [
        '../class_docu_sign_1_1e_sign_1_1_model_1_1_report_in_product_csv_run_request.html#ab97e2ce6425b73f9c3b2dbc3c7d8114f',
        1,
        'DocuSign.eSign.Model.ReportInProductCsvRunRequest.ReportInProductCsvRunRequest()',
      ],
      [
        '../class_docu_sign_1_1e_sign_1_1_model_1_1_report_in_product_csv_run_request.html#abe3175a74f55c8e02dc1af7cbf078903',
        1,
        'DocuSign.eSign.Model.ReportInProductCsvRunRequest.ReportInProductCsvRunRequest(string CustomFieldFilter=default(string), string DateRangeCustomFromDate=default(string), string DateRangeCustomToDate=default(string), string DateRangeFilter=default(string), string EnvelopeDateTypeFilter=default(string), string EnvelopeRecipientNameContainsFilter=default(string), string EnvelopeStatusFilter=default(string), string EnvelopeSubjectContainsFilter=default(string), List&lt; ReportInProductField &gt; Fields=default(List&lt; ReportInProductField &gt;), string ForDownload=default(string), string IsDashboard=default(string), string NewLine=default(string), string OverrideTimezoneKey=default(string), string PeriodLengthFilter=default(string), string Quote=default(string), string ReportCustomizedId=default(string), string ReportDescription=default(string), string ReportId=default(string), string ReportInvocationType=default(string), string ReportName=default(string), string SentByFilter=default(string), string SentByIds=default(string), string Separator=default(string), string SortDirection=default(string), string SortField=default(string), string StartPosition=default(string))',
      ],
    ],
  ],
  [
    'reportinproductfield',
    [
      'ReportInProductField',
      [
        '../class_docu_sign_1_1e_sign_1_1_model_1_1_report_in_product_field.html#af4c0f28a01b3bed9db60b343cd059a11',
        1,
        'DocuSign.eSign.Model.ReportInProductField.ReportInProductField()',
      ],
      [
        '../class_docu_sign_1_1e_sign_1_1_model_1_1_report_in_product_field.html#a31c007bbf55a4b5daa40e33dbfc43ef5',
        1,
        'DocuSign.eSign.Model.ReportInProductField.ReportInProductField(string DisplayOrder=default(string), string FieldVersion=default(string), string Name=default(string), string Selected=default(string))',
      ],
    ],
  ],
  [
    'reportinproductget',
    [
      'ReportInProductGet',
      [
        '../class_docu_sign_1_1e_sign_1_1_model_1_1_report_in_product_get.html#a0bfac2f381d887da517a833c79912e22',
        1,
        'DocuSign.eSign.Model.ReportInProductGet.ReportInProductGet()',
      ],
      [
        '../class_docu_sign_1_1e_sign_1_1_model_1_1_report_in_product_get.html#a36523372cbcad916d32e6e18297191bc',
        1,
        'DocuSign.eSign.Model.ReportInProductGet.ReportInProductGet(string CustomFieldFilter=default(string), string DateRangeCustomFromDate=default(string), string DateRangeCustomToDate=default(string), string DateRangeFilter=default(string), string DisplayOrder=default(string), string EnvelopeDateTypeFilter=default(string), string EnvelopeRecipientNameContainsFilter=default(string), string EnvelopeStatusFilter=default(string), string EnvelopeSubjectContainsFilter=default(string), List&lt; ReportInProductField &gt; Fields=default(List&lt; ReportInProductField &gt;), string LastScheduledExecutionDate=default(string), string LastScheduledExecutionSuccessDate=default(string), string MaxDownloadRows=default(string), string MaxGridRows=default(string), string MaxScheduledRows=default(string), string PeriodLengthFilter=default(string), string ReportCustomizedId=default(string), string ReportDescription=default(string), string ReportId=default(string), string ReportName=default(string), string ReportType=default(string), string RunUri=default(string), string SaveUri=default(string), string ScheduleId=default(string), ReportInProductSentByDetails SentByDetails=default(ReportInProductSentByDetails), string SentByFilter=default(string), string SentByIds=default(string), string SortFieldDirection=default(string), string SortFieldName=default(string))',
      ],
    ],
  ],
  [
    'reportinproductlist',
    [
      'ReportInProductList',
      [
        '../class_docu_sign_1_1e_sign_1_1_model_1_1_report_in_product_list.html#aa312de1a852e6cfc85e09c83b2b3b6d3',
        1,
        'DocuSign.eSign.Model.ReportInProductList.ReportInProductList()',
      ],
      [
        '../class_docu_sign_1_1e_sign_1_1_model_1_1_report_in_product_list.html#a358f3771356adf05e9efb92fd684617b',
        1,
        'DocuSign.eSign.Model.ReportInProductList.ReportInProductList(List&lt; ReportInProductListItem &gt; Reports=default(List&lt; ReportInProductListItem &gt;))',
      ],
    ],
  ],
  [
    'reportinproductlistitem',
    [
      'ReportInProductListItem',
      [
        '../class_docu_sign_1_1e_sign_1_1_model_1_1_report_in_product_list_item.html#ab2f4788f36f79099e0f0f72e2beff912',
        1,
        'DocuSign.eSign.Model.ReportInProductListItem.ReportInProductListItem()',
      ],
      [
        '../class_docu_sign_1_1e_sign_1_1_model_1_1_report_in_product_list_item.html#ad49a33475b77d1553028bb03ac80307e',
        1,
        'DocuSign.eSign.Model.ReportInProductListItem.ReportInProductListItem(string GetUri=default(string), string LastScheduledExecutionDate=default(string), string LastScheduledExecutionSuccessDate=default(string), string ReportCustomizedId=default(string), string ReportDescription=default(string), string ReportId=default(string), string ReportName=default(string), string ReportType=default(string), string RunUri=default(string), string SaveUri=default(string), string ScheduleCreateDate=default(string), string ScheduleEndDate=default(string), string ScheduleId=default(string), string ScheduleRenewDurationDays=default(string))',
      ],
    ],
  ],
  [
    'reportinproductrunrequest',
    [
      'ReportInProductRunRequest',
      [
        '../class_docu_sign_1_1e_sign_1_1_model_1_1_report_in_product_run_request.html#a3de2bb08090e8d1490de58e753e6578f',
        1,
        'DocuSign.eSign.Model.ReportInProductRunRequest.ReportInProductRunRequest()',
      ],
      [
        '../class_docu_sign_1_1e_sign_1_1_model_1_1_report_in_product_run_request.html#ae4f35aa9737f08996ea97d1b30c672aa',
        1,
        'DocuSign.eSign.Model.ReportInProductRunRequest.ReportInProductRunRequest(string CustomFieldFilter=default(string), string DateRangeCustomFromDate=default(string), string DateRangeCustomToDate=default(string), string DateRangeFilter=default(string), string EnvelopeDateTypeFilter=default(string), string EnvelopeRecipientNameContainsFilter=default(string), string EnvelopeStatusFilter=default(string), string EnvelopeSubjectContainsFilter=default(string), List&lt; ReportInProductField &gt; Fields=default(List&lt; ReportInProductField &gt;), string ForDownload=default(string), string IsDashboard=default(string), string PeriodLengthFilter=default(string), string ReportCustomizedId=default(string), string ReportDescription=default(string), string ReportId=default(string), string ReportInvocationType=default(string), string ReportName=default(string), string SentByFilter=default(string), string SentByIds=default(string), string SortDirection=default(string), string SortField=default(string), string StartPosition=default(string))',
      ],
    ],
  ],
  [
    'reportinproductrunresponse',
    [
      'ReportInProductRunResponse',
      [
        '../class_docu_sign_1_1e_sign_1_1_model_1_1_report_in_product_run_response.html#a68ce3eec54454a7ab113f3bc6bdfa0d4',
        1,
        'DocuSign.eSign.Model.ReportInProductRunResponse.ReportInProductRunResponse()',
      ],
      [
        '../class_docu_sign_1_1e_sign_1_1_model_1_1_report_in_product_run_response.html#ad759ffecf1229180c63b39ed844cc76a',
        1,
        'DocuSign.eSign.Model.ReportInProductRunResponse.ReportInProductRunResponse(string EndPosition=default(string), string ExceededMaxResults=default(string), string LastWarehouseRefreshDateTime=default(string), string ResultSetSize=default(string), List&lt; ReportInProductRunResponseRow &gt; Rows=default(List&lt; ReportInProductRunResponseRow &gt;), string StartPosition=default(string), string TotalSetSize=default(string))',
      ],
    ],
  ],
  [
    'reportinproductrunresponserow',
    [
      'ReportInProductRunResponseRow',
      [
        '../class_docu_sign_1_1e_sign_1_1_model_1_1_report_in_product_run_response_row.html#a50b40a8e0d6c47583b769c54de8f7021',
        1,
        'DocuSign.eSign.Model.ReportInProductRunResponseRow.ReportInProductRunResponseRow()',
      ],
      [
        '../class_docu_sign_1_1e_sign_1_1_model_1_1_report_in_product_run_response_row.html#a1817c29c1e878933f1059fcc2900df2d',
        1,
        'DocuSign.eSign.Model.ReportInProductRunResponseRow.ReportInProductRunResponseRow(string EnvelopeId=default(string), ReportInProductRunResponseRowFields Fields=default(ReportInProductRunResponseRowFields))',
      ],
    ],
  ],
  [
    'reportinproductrunresponserowfields',
    [
      'ReportInProductRunResponseRowFields',
      [
        '../class_docu_sign_1_1e_sign_1_1_model_1_1_report_in_product_run_response_row_fields.html#a6982e5fab79c8b9ad150175e918d387d',
        1,
        'DocuSign.eSign.Model.ReportInProductRunResponseRowFields.ReportInProductRunResponseRowFields()',
      ],
      [
        '../class_docu_sign_1_1e_sign_1_1_model_1_1_report_in_product_run_response_row_fields.html#a8a0c6751a318f03014c1b4c53011b861',
        1,
        'DocuSign.eSign.Model.ReportInProductRunResponseRowFields.ReportInProductRunResponseRowFields(string AccessCodeRequired=default(string), string AccessCodesAttempted=default(string), string AccessCodesFailed=default(string), string AccountId=default(string), string AuthenticationCategory=default(string), string AuthenticationSuccess=default(string), string AuthenticationType=default(string), string AverageTimeToCompleteSeconds=default(string), string AvgCompleteSeconds=default(string), string Completed=default(string), string CompletedTs=default(string), string CreatedDate=default(string), string CustomField=default(string), string DeclinedDate=default(string), string DeclinedReason=default(string), string DeliveredDate=default(string), string EnvelopeCount=default(string), string EnvelopeCreator=default(string), string EnvelopeId=default(string), string EnvelopeInitialSendTs=default(string), string EnvelopesBilled=default(string), string EnvelopesCompleted=default(string), string EnvelopesCompletedCount=default(string), string EnvelopesDeclined=default(string), string EnvelopesSent=default(string), string EnvelopesSentCount=default(string), string EnvelopesVoided=default(string), string EnvelopeVoidedReason=default(string), string EodDocumentDescription=default(string), string EodDocumentName=default(string), string EodDocumentProfileId=default(string), string EodTransactionId=default(string), string EodTransactionName=default(string), string EventDate=default(string), string ExpirationDate=default(string), string ExpiredTs=default(string), string FailureReason=default(string), string Failures=default(string), string FailureVendorCode=default(string), string FailureVendorReason=default(string), string FirstSendTs=default(string), string GroupId=default(string), string GroupName=default(string), string HoursToCompleteEnd=default(string), string HoursToCompleteStart=default(string), string IdChecksAttempted=default(string), string IdChecksFailed=default(string), string InitialSendTs=default(string), string IpAddress=default(string), string LastActivity=default(string), string LastActivityDate=default(string), string LastSentDate=default(string), string NotSigned=default(string), string NumberOfAuthenticatedRecipients=default(string), string NumberOfCompletedSignatures=default(string), string NumberOfDocuments=default(string), string NumberOfPages=default(string), string NumberOfRecipients=default(string), string NumberOfSends=default(string), string NumberOfSigners=default(string), string NumberOfTotalDocuments=default(string), string NumberOfTotalPages=default(string), string NumberOfTotalSigners=default(string), string NumberOfUniqueSenders=default(string), string NumberTotalRecipients=default(string), string PeriodEnd=default(string), string PeriodStart=default(string), string PhoneCallsAttempted=default(string), string PhoneCallsFailed=default(string), string ReasonForDeclining=default(string), string ReasonForVoiding=default(string), string ReassignReason=default(string), string Received=default(string), string Recipient=default(string), string RecipientAction=default(string), string RecipientCompanyName=default(string), string RecipientCountry=default(string), string RecipientEmail=default(string), string RecipientId=default(string), string RecipientName=default(string), string RecipientTemplateRoleName=default(string), string RecipientTitle=default(string), string RecipientType=default(string), string RecipientUserId=default(string), string RemainingSignatures=default(string), string RoutingOrder=default(string), string SenderAccountId=default(string), string SenderCompanyName=default(string), string SenderCountry=default(string), string SenderEmail=default(string), string SenderIPAddress=default(string), string SenderJobTitle=default(string), string SenderName=default(string), string SenderUserId=default(string), string SignDate=default(string), string Signed=default(string), string SignedDate=default(string), string SignedOnMobile=default(string), string SignedOnPaper=default(string), string SignerList=default(string), string Status=default(string), string StatusChangedDate=default(string), string StatusChangedTs=default(string), string Subject=default(string), string Successes=default(string), string TemplatesCreated=default(string), string TemplatesCreatedCount=default(string), string TerminalStatusDate=default(string), string TimeToCompleteSeconds=default(string), string TimeToDeliver=default(string), string TotalDocuments=default(string), string TotalEnvelopes=default(string), string TotalPages=default(string), string TotalRecipients=default(string), string TotalSigners=default(string), string UniqueSenders=default(string), string UserAccountEmail=default(string), string UserAccountName=default(string), string UserAccountStatus=default(string), string UserCount=default(string), string UserId=default(string), string VerificationStatus=default(string), string VerificationType=default(string), string ViewDate=default(string), string VoidedTs=default(string))',
      ],
    ],
  ],
  [
    'reportinproductsaveresponse',
    [
      'ReportInProductSaveResponse',
      [
        '../class_docu_sign_1_1e_sign_1_1_model_1_1_report_in_product_save_response.html#a6030dce6e03ed9c6fe1f09fd2e494f23',
        1,
        'DocuSign.eSign.Model.ReportInProductSaveResponse.ReportInProductSaveResponse()',
      ],
      [
        '../class_docu_sign_1_1e_sign_1_1_model_1_1_report_in_product_save_response.html#a64ef02ca01507a24aa8b2e820af0f34f',
        1,
        'DocuSign.eSign.Model.ReportInProductSaveResponse.ReportInProductSaveResponse(string ReportCustomizedId=default(string))',
      ],
    ],
  ],
  [
    'reportinproductsentbydetails',
    [
      'ReportInProductSentByDetails',
      [
        '../class_docu_sign_1_1e_sign_1_1_model_1_1_report_in_product_sent_by_details.html#a58120a37118b1d04decb37a6fb396e09',
        1,
        'DocuSign.eSign.Model.ReportInProductSentByDetails.ReportInProductSentByDetails()',
      ],
      [
        '../class_docu_sign_1_1e_sign_1_1_model_1_1_report_in_product_sent_by_details.html#a488b1e9f82f6fcf1b303d2e0d7d9ccd1',
        1,
        'DocuSign.eSign.Model.ReportInProductSentByDetails.ReportInProductSentByDetails(List&lt; Group &gt; Groups=default(List&lt; Group &gt;), List&lt; UserInfo &gt; Users=default(List&lt; UserInfo &gt;))',
      ],
    ],
  ],
  [
    'requestjwtapplicationtoken',
    [
      'RequestJWTApplicationToken',
      [
        '../class_docu_sign_1_1e_sign_1_1_client_1_1_api_client.html#afbe0bb23232fb3833eef9f0dc5fcd5c9',
        1,
        'DocuSign::eSign::Client::ApiClient',
      ],
    ],
  ],
  [
    'requestjwtusertoken',
    [
      'RequestJWTUserToken',
      [
        '../class_docu_sign_1_1e_sign_1_1_client_1_1_api_client.html#a8d7d22be09c34ce35b103639bf8539f0',
        1,
        'DocuSign.eSign.Client.ApiClient.RequestJWTUserToken(string clientId, string userId, string oauthBasePath, Stream privateKeyStream, int expiresInHours, List&lt; string &gt; scopes=null)',
      ],
      [
        '../class_docu_sign_1_1e_sign_1_1_client_1_1_api_client.html#a08b19c15fe51eabc36b1d222566fb770',
        1,
        'DocuSign.eSign.Client.ApiClient.RequestJWTUserToken(string clientId, string userId, string oauthBasePath, byte[] privateKeyBytes, int expiresInHours, List&lt; string &gt; scopes=null)',
      ],
    ],
  ],
  [
    'resourceinformation',
    [
      'ResourceInformation',
      [
        '../class_docu_sign_1_1e_sign_1_1_model_1_1_resource_information.html#a249732ca40c81d566239b829a0552355',
        1,
        'DocuSign.eSign.Model.ResourceInformation.ResourceInformation()',
      ],
      [
        '../class_docu_sign_1_1e_sign_1_1_model_1_1_resource_information.html#a856500ced91f7619c5c3f1d3bc9722b8',
        1,
        'DocuSign.eSign.Model.ResourceInformation.ResourceInformation(List&lt; NameValue &gt; Resources=default(List&lt; NameValue &gt;))',
      ],
    ],
  ],
  [
    'retryeventforenvelope',
    [
      'RetryEventForEnvelope',
      [
        '../interface_docu_sign_1_1e_sign_1_1_api_1_1_i_connect_api.html#aa0ebb2a8426f91fedf5077777c98dbbe',
        1,
        'DocuSign.eSign.Api.IConnectApi.RetryEventForEnvelope()',
      ],
      [
        '../class_docu_sign_1_1e_sign_1_1_api_1_1_connect_api.html#ad3198cb2b25b8d4ed17bdd46a933e080',
        1,
        'DocuSign.eSign.Api.ConnectApi.RetryEventForEnvelope()',
      ],
    ],
  ],
  [
    'retryeventforenvelopeasync',
    [
      'RetryEventForEnvelopeAsync',
      [
        '../interface_docu_sign_1_1e_sign_1_1_api_1_1_i_connect_api.html#a43c586bcc643f3079a696cec7c1ea072',
        1,
        'DocuSign.eSign.Api.IConnectApi.RetryEventForEnvelopeAsync()',
      ],
      [
        '../class_docu_sign_1_1e_sign_1_1_api_1_1_connect_api.html#a5d3504ec32c54639d24c48acb713d812',
        1,
        'DocuSign.eSign.Api.ConnectApi.RetryEventForEnvelopeAsync()',
      ],
    ],
  ],
  [
    'retryeventforenvelopeasyncwithhttpinfo',
    [
      'RetryEventForEnvelopeAsyncWithHttpInfo',
      [
        '../interface_docu_sign_1_1e_sign_1_1_api_1_1_i_connect_api.html#af9767cb7b2fffabd337c1cfd57755d67',
        1,
        'DocuSign.eSign.Api.IConnectApi.RetryEventForEnvelopeAsyncWithHttpInfo()',
      ],
      [
        '../class_docu_sign_1_1e_sign_1_1_api_1_1_connect_api.html#a2d7fa6421a1e611cdc301e7a2d72921f',
        1,
        'DocuSign.eSign.Api.ConnectApi.RetryEventForEnvelopeAsyncWithHttpInfo()',
      ],
    ],
  ],
  [
    'retryeventforenvelopes',
    [
      'RetryEventForEnvelopes',
      [
        '../interface_docu_sign_1_1e_sign_1_1_api_1_1_i_connect_api.html#a067475c4c1fefc63f8834e375fecd9a6',
        1,
        'DocuSign.eSign.Api.IConnectApi.RetryEventForEnvelopes()',
      ],
      [
        '../class_docu_sign_1_1e_sign_1_1_api_1_1_connect_api.html#a2e57f6d983f7c64785695d25bc0df506',
        1,
        'DocuSign.eSign.Api.ConnectApi.RetryEventForEnvelopes()',
      ],
    ],
  ],
  [
    'retryeventforenvelopesasync',
    [
      'RetryEventForEnvelopesAsync',
      [
        '../interface_docu_sign_1_1e_sign_1_1_api_1_1_i_connect_api.html#ab25371246e70d8d6cb195fa3d072b8ec',
        1,
        'DocuSign.eSign.Api.IConnectApi.RetryEventForEnvelopesAsync()',
      ],
      [
        '../class_docu_sign_1_1e_sign_1_1_api_1_1_connect_api.html#a8a183e80276486d0d574938b4b4f357c',
        1,
        'DocuSign.eSign.Api.ConnectApi.RetryEventForEnvelopesAsync()',
      ],
    ],
  ],
  [
    'retryeventforenvelopesasyncwithhttpinfo',
    [
      'RetryEventForEnvelopesAsyncWithHttpInfo',
      [
        '../interface_docu_sign_1_1e_sign_1_1_api_1_1_i_connect_api.html#ac886b164c45ac30297c322ecb895b0c9',
        1,
        'DocuSign.eSign.Api.IConnectApi.RetryEventForEnvelopesAsyncWithHttpInfo()',
      ],
      [
        '../class_docu_sign_1_1e_sign_1_1_api_1_1_connect_api.html#af6eafddb1ec9689d399df8c60cbcd300',
        1,
        'DocuSign.eSign.Api.ConnectApi.RetryEventForEnvelopesAsyncWithHttpInfo()',
      ],
    ],
  ],
  [
    'retryeventforenvelopeswithhttpinfo',
    [
      'RetryEventForEnvelopesWithHttpInfo',
      [
        '../interface_docu_sign_1_1e_sign_1_1_api_1_1_i_connect_api.html#a66eca6c45ef9ecc4f4787ad08fbb24e0',
        1,
        'DocuSign.eSign.Api.IConnectApi.RetryEventForEnvelopesWithHttpInfo()',
      ],
      [
        '../class_docu_sign_1_1e_sign_1_1_api_1_1_connect_api.html#a3eb8c28d47503e5d5f75a6b3a9dc6cb6',
        1,
        'DocuSign.eSign.Api.ConnectApi.RetryEventForEnvelopesWithHttpInfo()',
      ],
    ],
  ],
  [
    'retryeventforenvelopewithhttpinfo',
    [
      'RetryEventForEnvelopeWithHttpInfo',
      [
        '../interface_docu_sign_1_1e_sign_1_1_api_1_1_i_connect_api.html#a71d373caae49f0396241185e2bdab99c',
        1,
        'DocuSign.eSign.Api.IConnectApi.RetryEventForEnvelopeWithHttpInfo()',
      ],
      [
        '../class_docu_sign_1_1e_sign_1_1_api_1_1_connect_api.html#ae9c40dfe367dae78b903ec8acb1a06c9',
        1,
        'DocuSign.eSign.Api.ConnectApi.RetryEventForEnvelopeWithHttpInfo()',
      ],
    ],
  ],
  [
    'returnurlrequest',
    [
      'ReturnUrlRequest',
      [
        '../class_docu_sign_1_1e_sign_1_1_model_1_1_return_url_request.html#aae2c30b942f59872ea77692d3b9b112f',
        1,
        'DocuSign.eSign.Model.ReturnUrlRequest.ReturnUrlRequest()',
      ],
      [
        '../class_docu_sign_1_1e_sign_1_1_model_1_1_return_url_request.html#ab1946c5624704e8d73240e87fd1a55db',
        1,
        'DocuSign.eSign.Model.ReturnUrlRequest.ReturnUrlRequest(string ReturnUrl=default(string))',
      ],
    ],
  ],
  [
    'revision',
    [
      'Revision',
      [
        '../class_docu_sign_1_1e_sign_1_1_model_1_1_revision.html#a50d98c95df3fb0d18e5dd0dc8370fa32',
        1,
        'DocuSign.eSign.Model.Revision.Revision()',
      ],
      [
        '../class_docu_sign_1_1e_sign_1_1_model_1_1_revision.html#a65e789217f8ef1150601ea72f9f4879d',
        1,
        'DocuSign.eSign.Model.Revision.Revision(string EndData=default(string), string FieldName=default(string), string MaxSignatureLength=default(string), SignatureProperties SignatureProperties=default(SignatureProperties), string SignatureType=default(string), string StartData=default(string))',
      ],
    ],
  ],
  [
    'revokeoauthtoken',
    [
      'RevokeOAuthToken',
      [
        '../interface_docu_sign_1_1e_sign_1_1_api_1_1_i_authentication_api.html#a232a565459e2c4e73c6da2d66d525434',
        1,
        'DocuSign.eSign.Api.IAuthenticationApi.RevokeOAuthToken()',
      ],
      [
        '../class_docu_sign_1_1e_sign_1_1_api_1_1_authentication_api.html#a5d328623d28e154d7b8aa91e23ff58ba',
        1,
        'DocuSign.eSign.Api.AuthenticationApi.RevokeOAuthToken()',
      ],
    ],
  ],
  [
    'revokeoauthtokenasync',
    [
      'RevokeOAuthTokenAsync',
      [
        '../interface_docu_sign_1_1e_sign_1_1_api_1_1_i_authentication_api.html#af16cee0ffd02e213e3d5108618c7a00b',
        1,
        'DocuSign.eSign.Api.IAuthenticationApi.RevokeOAuthTokenAsync()',
      ],
      [
        '../class_docu_sign_1_1e_sign_1_1_api_1_1_authentication_api.html#adec5320e5ddcdbcb84c4d289ba2a4343',
        1,
        'DocuSign.eSign.Api.AuthenticationApi.RevokeOAuthTokenAsync()',
      ],
    ],
  ],
  [
    'revokeoauthtokenasyncwithhttpinfo',
    [
      'RevokeOAuthTokenAsyncWithHttpInfo',
      [
        '../interface_docu_sign_1_1e_sign_1_1_api_1_1_i_authentication_api.html#a0195141d63695ff880e3299803d15881',
        1,
        'DocuSign.eSign.Api.IAuthenticationApi.RevokeOAuthTokenAsyncWithHttpInfo()',
      ],
      [
        '../class_docu_sign_1_1e_sign_1_1_api_1_1_authentication_api.html#a598a6e001c50cec094c49ccf3d827d35',
        1,
        'DocuSign.eSign.Api.AuthenticationApi.RevokeOAuthTokenAsyncWithHttpInfo()',
      ],
    ],
  ],
  [
    'revokeoauthtokenwithhttpinfo',
    [
      'RevokeOAuthTokenWithHttpInfo',
      [
        '../interface_docu_sign_1_1e_sign_1_1_api_1_1_i_authentication_api.html#acc3de194a9be22b5c29248ec6d981610',
        1,
        'DocuSign.eSign.Api.IAuthenticationApi.RevokeOAuthTokenWithHttpInfo()',
      ],
      [
        '../class_docu_sign_1_1e_sign_1_1_api_1_1_authentication_api.html#a02a96d39afd026a90355aa0aa6b09ab9',
        1,
        'DocuSign.eSign.Api.AuthenticationApi.RevokeOAuthTokenWithHttpInfo()',
      ],
    ],
  ],
  [
    'rotatedocumentpage',
    [
      'RotateDocumentPage',
      [
        '../interface_docu_sign_1_1e_sign_1_1_api_1_1_i_envelopes_api.html#a2e756100a73629cb8afce19020976286',
        1,
        'DocuSign.eSign.Api.IEnvelopesApi.RotateDocumentPage()',
      ],
      [
        '../class_docu_sign_1_1e_sign_1_1_api_1_1_envelopes_api.html#afbef2cac8064150eaa4b1bf79f0e1d26',
        1,
        'DocuSign.eSign.Api.EnvelopesApi.RotateDocumentPage()',
      ],
      [
        '../interface_docu_sign_1_1e_sign_1_1_api_1_1_i_templates_api.html#ac1cadb0f5d09ce61edef73dd4b31a6a0',
        1,
        'DocuSign.eSign.Api.ITemplatesApi.RotateDocumentPage()',
      ],
      [
        '../class_docu_sign_1_1e_sign_1_1_api_1_1_templates_api.html#a2efacf00823fed9d041881aaebbe5e24',
        1,
        'DocuSign.eSign.Api.TemplatesApi.RotateDocumentPage()',
      ],
    ],
  ],
  [
    'rotatedocumentpageasync',
    [
      'RotateDocumentPageAsync',
      [
        '../interface_docu_sign_1_1e_sign_1_1_api_1_1_i_envelopes_api.html#ade988c77864d3ccfdb607b5667a57772',
        1,
        'DocuSign.eSign.Api.IEnvelopesApi.RotateDocumentPageAsync()',
      ],
      [
        '../class_docu_sign_1_1e_sign_1_1_api_1_1_envelopes_api.html#a01151e709c3b398079444f48215688e4',
        1,
        'DocuSign.eSign.Api.EnvelopesApi.RotateDocumentPageAsync()',
      ],
      [
        '../interface_docu_sign_1_1e_sign_1_1_api_1_1_i_templates_api.html#a622a1c2ef2a353fe0e9b7e009b9a60fd',
        1,
        'DocuSign.eSign.Api.ITemplatesApi.RotateDocumentPageAsync()',
      ],
      [
        '../class_docu_sign_1_1e_sign_1_1_api_1_1_templates_api.html#a6ccd7148b5e4a15638dd15a75cc8245c',
        1,
        'DocuSign.eSign.Api.TemplatesApi.RotateDocumentPageAsync()',
      ],
    ],
  ],
  [
    'rotatedocumentpageasyncwithhttpinfo',
    [
      'RotateDocumentPageAsyncWithHttpInfo',
      [
        '../interface_docu_sign_1_1e_sign_1_1_api_1_1_i_envelopes_api.html#a0225315e5fdb198b2c78692d7ac908cd',
        1,
        'DocuSign.eSign.Api.IEnvelopesApi.RotateDocumentPageAsyncWithHttpInfo()',
      ],
      [
        '../class_docu_sign_1_1e_sign_1_1_api_1_1_envelopes_api.html#ae45fcadbd3632f09cbbc3a9fb977edc6',
        1,
        'DocuSign.eSign.Api.EnvelopesApi.RotateDocumentPageAsyncWithHttpInfo()',
      ],
      [
        '../interface_docu_sign_1_1e_sign_1_1_api_1_1_i_templates_api.html#ab5f6cccb24035b9f754cea1ef9b19d66',
        1,
        'DocuSign.eSign.Api.ITemplatesApi.RotateDocumentPageAsyncWithHttpInfo()',
      ],
      [
        '../class_docu_sign_1_1e_sign_1_1_api_1_1_templates_api.html#abd829c4ddb67ddaa3199e1392717b76f',
        1,
        'DocuSign.eSign.Api.TemplatesApi.RotateDocumentPageAsyncWithHttpInfo()',
      ],
    ],
  ],
  [
    'rotatedocumentpagewithhttpinfo',
    [
      'RotateDocumentPageWithHttpInfo',
      [
        '../interface_docu_sign_1_1e_sign_1_1_api_1_1_i_envelopes_api.html#a96996477345ca596ceb28b5bac1d4cf2',
        1,
        'DocuSign.eSign.Api.IEnvelopesApi.RotateDocumentPageWithHttpInfo()',
      ],
      [
        '../class_docu_sign_1_1e_sign_1_1_api_1_1_envelopes_api.html#aec215410487390368d027560ee86b06f',
        1,
        'DocuSign.eSign.Api.EnvelopesApi.RotateDocumentPageWithHttpInfo()',
      ],
      [
        '../interface_docu_sign_1_1e_sign_1_1_api_1_1_i_templates_api.html#a8d5206c87a72731469f7f787d8046bc5',
        1,
        'DocuSign.eSign.Api.ITemplatesApi.RotateDocumentPageWithHttpInfo()',
      ],
      [
        '../class_docu_sign_1_1e_sign_1_1_api_1_1_templates_api.html#ade1660d53139a77a124f3440a3506018',
        1,
        'DocuSign.eSign.Api.TemplatesApi.RotateDocumentPageWithHttpInfo()',
      ],
    ],
  ],
];
