var searchData = [
  [
    'accesscodeformat',
    [
      'AccessCodeFormat',
      [
        '../class_docu_sign_1_1e_sign_1_1_model_1_1_access_code_format.html#ae6e9bcff512cb67ef97b5d4fe05a97a9',
        1,
        'DocuSign.eSign.Model.AccessCodeFormat.AccessCodeFormat()',
      ],
      [
        '../class_docu_sign_1_1e_sign_1_1_model_1_1_access_code_format.html#a034bf1b5bdcfdfc950d80ca2dc3987d0',
        1,
        'DocuSign.eSign.Model.AccessCodeFormat.AccessCodeFormat(string FormatRequired=default(string), SettingsMetadata FormatRequiredMetadata=default(SettingsMetadata), string LetterRequired=default(string), SettingsMetadata LetterRequiredMetadata=default(SettingsMetadata), string MinimumLength=default(string), SettingsMetadata MinimumLengthMetadata=default(SettingsMetadata), string NumberRequired=default(string), SettingsMetadata NumberRequiredMetadata=default(SettingsMetadata), string SpecialCharacterRequired=default(string), SettingsMetadata SpecialCharacterRequiredMetadata=default(SettingsMetadata))',
      ],
    ],
  ],
  [
    'accountaddress',
    [
      'AccountAddress',
      [
        '../class_docu_sign_1_1e_sign_1_1_model_1_1_account_address.html#a49653d30b31414c50ce13fd69217185c',
        1,
        'DocuSign.eSign.Model.AccountAddress.AccountAddress()',
      ],
      [
        '../class_docu_sign_1_1e_sign_1_1_model_1_1_account_address.html#abeb62abe9e308d7545ac66d733936216',
        1,
        'DocuSign.eSign.Model.AccountAddress.AccountAddress(string Address1=default(string), string Address2=default(string), string City=default(string), string Country=default(string), string Email=default(string), string Fax=default(string), string FirstName=default(string), string LastName=default(string), string Phone=default(string), string PostalCode=default(string), string State=default(string), List&lt; Country &gt; SupportedCountries=default(List&lt; Country &gt;))',
      ],
    ],
  ],
  [
    'accountbillingplan',
    [
      'AccountBillingPlan',
      [
        '../class_docu_sign_1_1e_sign_1_1_model_1_1_account_billing_plan.html#ab87b8926a09657f7ffafbe18a14ef6f9',
        1,
        'DocuSign.eSign.Model.AccountBillingPlan.AccountBillingPlan()',
      ],
      [
        '../class_docu_sign_1_1e_sign_1_1_model_1_1_account_billing_plan.html#a9c89535132a932b9093ef0fd294f69e3',
        1,
        'DocuSign.eSign.Model.AccountBillingPlan.AccountBillingPlan(List&lt; AddOn &gt; AddOns=default(List&lt; AddOn &gt;), string AppStoreReceiptExpirationDate=default(string), string AppStoreReceiptPurchaseDate=default(string), string CanCancelRenewal=default(string), string CanUpgrade=default(string), string CurrencyCode=default(string), DowngradePlanUpdateResponse DowngradePlanInformation=default(DowngradePlanUpdateResponse), string EnableSupport=default(string), string IncludedSeats=default(string), string IncrementalSeats=default(string), string IsDowngrade=default(string), string NotificationType=default(string), string OtherDiscountPercent=default(string), string PaymentCycle=default(string), string PaymentMethod=default(string), string PerSeatPrice=default(string), string PlanClassification=default(string), List&lt; FeatureSet &gt; PlanFeatureSets=default(List&lt; FeatureSet &gt;), string PlanId=default(string), string PlanName=default(string), string RenewalStatus=default(string), List&lt; SeatDiscount &gt; SeatDiscounts=default(List&lt; SeatDiscount &gt;), string SupportIncidentFee=default(string), string SupportPlanFee=default(string))',
      ],
    ],
  ],
  [
    'accountbillingplanresponse',
    [
      'AccountBillingPlanResponse',
      [
        '../class_docu_sign_1_1e_sign_1_1_model_1_1_account_billing_plan_response.html#a646e1f07e0685ab10615bebc18610600',
        1,
        'DocuSign.eSign.Model.AccountBillingPlanResponse.AccountBillingPlanResponse()',
      ],
      [
        '../class_docu_sign_1_1e_sign_1_1_model_1_1_account_billing_plan_response.html#ab31cf9b0baf0800adb16335b16f23d24',
        1,
        'DocuSign.eSign.Model.AccountBillingPlanResponse.AccountBillingPlanResponse(AccountAddress BillingAddress=default(AccountAddress), string BillingAddressIsCreditCardAddress=default(string), AccountBillingPlan BillingPlan=default(AccountBillingPlan), CreditCardInformation CreditCardInformation=default(CreditCardInformation), DirectDebitProcessorInformation DirectDebitProcessorInformation=default(DirectDebitProcessorInformation), DowngradePlanUpdateResponse DowngradePlanInformation=default(DowngradePlanUpdateResponse), string PaymentMethod=default(string), PaymentProcessorInformation PaymentProcessorInformation=default(PaymentProcessorInformation), ReferralInformation ReferralInformation=default(ReferralInformation), List&lt; BillingPlan &gt; SuccessorPlans=default(List&lt; BillingPlan &gt;))',
      ],
    ],
  ],
  [
    'accountidentityinputoption',
    [
      'AccountIdentityInputOption',
      [
        '../class_docu_sign_1_1e_sign_1_1_model_1_1_account_identity_input_option.html#ac7d58473fc44b3e35bf5fbba70d1025c',
        1,
        'DocuSign.eSign.Model.AccountIdentityInputOption.AccountIdentityInputOption()',
      ],
      [
        '../class_docu_sign_1_1e_sign_1_1_model_1_1_account_identity_input_option.html#a2f6aed94a97451ea510b65194a1739ef',
        1,
        'DocuSign.eSign.Model.AccountIdentityInputOption.AccountIdentityInputOption(bool?IsRequired=default(bool?), string OptionName=default(string), string ValueType=default(string))',
      ],
    ],
  ],
  [
    'accountidentityverificationresponse',
    [
      'AccountIdentityVerificationResponse',
      [
        '../class_docu_sign_1_1e_sign_1_1_model_1_1_account_identity_verification_response.html#ac70b632c3647720539c06921ab858169',
        1,
        'DocuSign.eSign.Model.AccountIdentityVerificationResponse.AccountIdentityVerificationResponse()',
      ],
      [
        '../class_docu_sign_1_1e_sign_1_1_model_1_1_account_identity_verification_response.html#a549cccf0f66c08056fe156ee6aff2bf7',
        1,
        'DocuSign.eSign.Model.AccountIdentityVerificationResponse.AccountIdentityVerificationResponse(List&lt; AccountIdentityVerificationWorkflow &gt; IdentityVerification=default(List&lt; AccountIdentityVerificationWorkflow &gt;))',
      ],
    ],
  ],
  [
    'accountidentityverificationstep',
    [
      'AccountIdentityVerificationStep',
      [
        '../class_docu_sign_1_1e_sign_1_1_model_1_1_account_identity_verification_step.html#ac5bd90da9c748e7f1980309002712298',
        1,
        'DocuSign.eSign.Model.AccountIdentityVerificationStep.AccountIdentityVerificationStep()',
      ],
      [
        '../class_docu_sign_1_1e_sign_1_1_model_1_1_account_identity_verification_step.html#a3db8c0099066ff0aa0b857e16bd728a3',
        1,
        'DocuSign.eSign.Model.AccountIdentityVerificationStep.AccountIdentityVerificationStep(string Name=default(string), string Type=default(string))',
      ],
    ],
  ],
  [
    'accountidentityverificationworkflow',
    [
      'AccountIdentityVerificationWorkflow',
      [
        '../class_docu_sign_1_1e_sign_1_1_model_1_1_account_identity_verification_workflow.html#adb19455b91c410ef65f3696a6b2e3fe7',
        1,
        'DocuSign.eSign.Model.AccountIdentityVerificationWorkflow.AccountIdentityVerificationWorkflow()',
      ],
      [
        '../class_docu_sign_1_1e_sign_1_1_model_1_1_account_identity_verification_workflow.html#af82dd152019879a840e2fa80df533a96',
        1,
        'DocuSign.eSign.Model.AccountIdentityVerificationWorkflow.AccountIdentityVerificationWorkflow(string DefaultDescription=default(string), string DefaultName=default(string), List&lt; AccountIdentityInputOption &gt; InputOptions=default(List&lt; AccountIdentityInputOption &gt;), AccountSignatureProvider SignatureProvider=default(AccountSignatureProvider), List&lt; AccountIdentityVerificationStep &gt; Steps=default(List&lt; AccountIdentityVerificationStep &gt;), string WorkflowId=default(string), string WorkflowResourceKey=default(string))',
      ],
    ],
  ],
  [
    'accountinformation',
    [
      'AccountInformation',
      [
        '../class_docu_sign_1_1e_sign_1_1_model_1_1_account_information.html#a1ad3763133b8985f10170a11ed473fbb',
        1,
        'DocuSign.eSign.Model.AccountInformation.AccountInformation()',
      ],
      [
        '../class_docu_sign_1_1e_sign_1_1_model_1_1_account_information.html#af1e5fff15cda2ffbd340a392c04cdc96',
        1,
        'DocuSign.eSign.Model.AccountInformation.AccountInformation(string AccountIdGuid=default(string), string AccountName=default(string), AccountSettingsInformation AccountSettings=default(AccountSettingsInformation), string AllowTransactionRooms=default(string), string BillingPeriodDaysRemaining=default(string), string BillingPeriodEndDate=default(string), string BillingPeriodEnvelopesAllowed=default(string), string BillingPeriodEnvelopesSent=default(string), string BillingPeriodStartDate=default(string), string BillingProfile=default(string), string CanUpgrade=default(string), string ConnectPermission=default(string), string CreatedDate=default(string), string CurrencyCode=default(string), string CurrentPlanId=default(string), string DisplayApplianceStartUrl=default(string), string DisplayApplianceUrl=default(string), string DistributorCode=default(string), string DocuSignLandingUrl=default(string), Dictionary&lt; string, string &gt; DssValues=default(Dictionary&lt; string, string &gt;), string EnvelopeSendingBlocked=default(string), string EnvelopeUnitPrice=default(string), string ExternalAccountId=default(string), string ForgottenPasswordQuestionsCount=default(string), string IsDowngrade=default(string), string PaymentMethod=default(string), string PlanClassification=default(string), string PlanEndDate=default(string), string PlanName=default(string), string PlanStartDate=default(string), List&lt; RecipientDomain &gt; RecipientDomains=default(List&lt; RecipientDomain &gt;), string SeatsAllowed=default(string), string SeatsInUse=default(string), string Status21CFRPart11=default(string), string SuspensionDate=default(string), string SuspensionStatus=default(string), bool?UseDisplayAppliance=default(bool?))',
      ],
    ],
  ],
  [
    'accountminimumpasswordlength',
    [
      'AccountMinimumPasswordLength',
      [
        '../class_docu_sign_1_1e_sign_1_1_model_1_1_account_minimum_password_length.html#af48c3568f1e5080988f021f6c6103d67',
        1,
        'DocuSign.eSign.Model.AccountMinimumPasswordLength.AccountMinimumPasswordLength()',
      ],
      [
        '../class_docu_sign_1_1e_sign_1_1_model_1_1_account_minimum_password_length.html#a052dbf5666dedb2096b457b4dd3e95e2',
        1,
        'DocuSign.eSign.Model.AccountMinimumPasswordLength.AccountMinimumPasswordLength(string MaximumLength=default(string), string MinimumLength=default(string))',
      ],
    ],
  ],
  [
    'accountnotification',
    [
      'AccountNotification',
      [
        '../class_docu_sign_1_1e_sign_1_1_model_1_1_account_notification.html#a1de53e3c6466e127eb333a7f9c82402a',
        1,
        'DocuSign.eSign.Model.AccountNotification.AccountNotification()',
      ],
      [
        '../class_docu_sign_1_1e_sign_1_1_model_1_1_account_notification.html#aad720dad10926b133b23dc22b4a7d0c9',
        1,
        'DocuSign.eSign.Model.AccountNotification.AccountNotification(Expirations Expirations=default(Expirations), Reminders Reminders=default(Reminders), string UserOverrideEnabled=default(string))',
      ],
    ],
  ],
  [
    'accountpasswordexpirepassworddays',
    [
      'AccountPasswordExpirePasswordDays',
      [
        '../class_docu_sign_1_1e_sign_1_1_model_1_1_account_password_expire_password_days.html#a9a62d3882cdba88e8e14513818ed9d58',
        1,
        'DocuSign.eSign.Model.AccountPasswordExpirePasswordDays.AccountPasswordExpirePasswordDays()',
      ],
      [
        '../class_docu_sign_1_1e_sign_1_1_model_1_1_account_password_expire_password_days.html#a18288ee1da653b6f885eaa1b9043c934',
        1,
        'DocuSign.eSign.Model.AccountPasswordExpirePasswordDays.AccountPasswordExpirePasswordDays(string MaximumDays=default(string), string MinimumDays=default(string))',
      ],
    ],
  ],
  [
    'accountpasswordlockoutdurationminutes',
    [
      'AccountPasswordLockoutDurationMinutes',
      [
        '../class_docu_sign_1_1e_sign_1_1_model_1_1_account_password_lockout_duration_minutes.html#a200a80bd8d659722156bb0430c9b8476',
        1,
        'DocuSign.eSign.Model.AccountPasswordLockoutDurationMinutes.AccountPasswordLockoutDurationMinutes()',
      ],
      [
        '../class_docu_sign_1_1e_sign_1_1_model_1_1_account_password_lockout_duration_minutes.html#af984b63b54f753b104aebae340faae35',
        1,
        'DocuSign.eSign.Model.AccountPasswordLockoutDurationMinutes.AccountPasswordLockoutDurationMinutes(string MaximumMinutes=default(string), string MinimumMinutes=default(string))',
      ],
    ],
  ],
  [
    'accountpasswordlockoutdurationtype',
    [
      'AccountPasswordLockoutDurationType',
      [
        '../class_docu_sign_1_1e_sign_1_1_model_1_1_account_password_lockout_duration_type.html#a54b33fde4fcaaab9137e00bda6c780c0',
        1,
        'DocuSign.eSign.Model.AccountPasswordLockoutDurationType.AccountPasswordLockoutDurationType()',
      ],
      [
        '../class_docu_sign_1_1e_sign_1_1_model_1_1_account_password_lockout_duration_type.html#a3c27c9195da7d20a9e1b6642bbf7d5ed',
        1,
        'DocuSign.eSign.Model.AccountPasswordLockoutDurationType.AccountPasswordLockoutDurationType(List&lt; string &gt; Options=default(List&lt; string &gt;))',
      ],
    ],
  ],
  [
    'accountpasswordminimumpasswordagedays',
    [
      'AccountPasswordMinimumPasswordAgeDays',
      [
        '../class_docu_sign_1_1e_sign_1_1_model_1_1_account_password_minimum_password_age_days.html#a805493c87042a6686ea13313c3144b60',
        1,
        'DocuSign.eSign.Model.AccountPasswordMinimumPasswordAgeDays.AccountPasswordMinimumPasswordAgeDays()',
      ],
      [
        '../class_docu_sign_1_1e_sign_1_1_model_1_1_account_password_minimum_password_age_days.html#a768842ba130c1c7ba1a708b6a07d320d',
        1,
        'DocuSign.eSign.Model.AccountPasswordMinimumPasswordAgeDays.AccountPasswordMinimumPasswordAgeDays(string MaximumAge=default(string), string MinimumAge=default(string))',
      ],
    ],
  ],
  [
    'accountpasswordquestionsrequired',
    [
      'AccountPasswordQuestionsRequired',
      [
        '../class_docu_sign_1_1e_sign_1_1_model_1_1_account_password_questions_required.html#a290db9655838286b39c15f71f658df5c',
        1,
        'DocuSign.eSign.Model.AccountPasswordQuestionsRequired.AccountPasswordQuestionsRequired()',
      ],
      [
        '../class_docu_sign_1_1e_sign_1_1_model_1_1_account_password_questions_required.html#abed136c63e57118ae1669cae9abe1fff',
        1,
        'DocuSign.eSign.Model.AccountPasswordQuestionsRequired.AccountPasswordQuestionsRequired(string MaximumQuestions=default(string), string MinimumQuestions=default(string))',
      ],
    ],
  ],
  [
    'accountpasswordrules',
    [
      'AccountPasswordRules',
      [
        '../class_docu_sign_1_1e_sign_1_1_model_1_1_account_password_rules.html#a6b22441630e0db8d4455aa6a6d33185d',
        1,
        'DocuSign.eSign.Model.AccountPasswordRules.AccountPasswordRules()',
      ],
      [
        '../class_docu_sign_1_1e_sign_1_1_model_1_1_account_password_rules.html#a78e559aa4e56d7dd97673cb35807f8f9',
        1,
        'DocuSign.eSign.Model.AccountPasswordRules.AccountPasswordRules(string ExpirePassword=default(string), string ExpirePasswordDays=default(string), AccountPasswordExpirePasswordDays ExpirePasswordDaysMetadata=default(AccountPasswordExpirePasswordDays), string LockoutDurationMinutes=default(string), AccountPasswordLockoutDurationMinutes LockoutDurationMinutesMetadata=default(AccountPasswordLockoutDurationMinutes), string LockoutDurationType=default(string), AccountPasswordLockoutDurationType LockoutDurationTypeMetadata=default(AccountPasswordLockoutDurationType), string MinimumPasswordAgeDays=default(string), AccountPasswordMinimumPasswordAgeDays MinimumPasswordAgeDaysMetadata=default(AccountPasswordMinimumPasswordAgeDays), string MinimumPasswordLength=default(string), AccountMinimumPasswordLength MinimumPasswordLengthMetadata=default(AccountMinimumPasswordLength), string PasswordIncludeDigit=default(string), string PasswordIncludeDigitOrSpecialCharacter=default(string), string PasswordIncludeLowerCase=default(string), string PasswordIncludeSpecialCharacter=default(string), string PasswordIncludeUpperCase=default(string), string PasswordStrengthType=default(string), AccountPasswordStrengthType PasswordStrengthTypeMetadata=default(AccountPasswordStrengthType), string QuestionsRequired=default(string), AccountPasswordQuestionsRequired QuestionsRequiredMetadata=default(AccountPasswordQuestionsRequired))',
      ],
    ],
  ],
  [
    'accountpasswordstrengthtype',
    [
      'AccountPasswordStrengthType',
      [
        '../class_docu_sign_1_1e_sign_1_1_model_1_1_account_password_strength_type.html#aca56e43178218569357b51798d49dcf1',
        1,
        'DocuSign.eSign.Model.AccountPasswordStrengthType.AccountPasswordStrengthType()',
      ],
      [
        '../class_docu_sign_1_1e_sign_1_1_model_1_1_account_password_strength_type.html#aa3e04064bccdc92bddd9c21ca6bbffe7',
        1,
        'DocuSign.eSign.Model.AccountPasswordStrengthType.AccountPasswordStrengthType(List&lt; AccountPasswordStrengthTypeOption &gt; Options=default(List&lt; AccountPasswordStrengthTypeOption &gt;))',
      ],
    ],
  ],
  [
    'accountpasswordstrengthtypeoption',
    [
      'AccountPasswordStrengthTypeOption',
      [
        '../class_docu_sign_1_1e_sign_1_1_model_1_1_account_password_strength_type_option.html#a8acb95375206c7bcc9c5363afe3490b1',
        1,
        'DocuSign.eSign.Model.AccountPasswordStrengthTypeOption.AccountPasswordStrengthTypeOption()',
      ],
      [
        '../class_docu_sign_1_1e_sign_1_1_model_1_1_account_password_strength_type_option.html#ad4f25086083d2a6d788ad310a60bf0c6',
        1,
        'DocuSign.eSign.Model.AccountPasswordStrengthTypeOption.AccountPasswordStrengthTypeOption(string MinimumLength=default(string), string Name=default(string), string PasswordIncludeDigit=default(string), string PasswordIncludeDigitOrSpecialCharacter=default(string), string PasswordIncludeLowerCase=default(string), string PasswordIncludeSpecialCharacter=default(string), string PasswordIncludeUpperCase=default(string))',
      ],
    ],
  ],
  [
    'accountrolesettings',
    [
      'AccountRoleSettings',
      [
        '../class_docu_sign_1_1e_sign_1_1_model_1_1_account_role_settings.html#a88bda96c73f04e2dbe77a104ac2b5719',
        1,
        'DocuSign.eSign.Model.AccountRoleSettings.AccountRoleSettings()',
      ],
      [
        '../class_docu_sign_1_1e_sign_1_1_model_1_1_account_role_settings.html#abb97d6158f5aed512695bc6c31b345ca',
        1,
        'DocuSign.eSign.Model.AccountRoleSettings.AccountRoleSettings(string AllowAccountManagement=default(string), SettingsMetadata AllowAccountManagementMetadata=default(SettingsMetadata), string AllowApiAccess=default(string), SettingsMetadata AllowApiAccessMetadata=default(SettingsMetadata), string AllowApiAccessToAccount=default(string), SettingsMetadata AllowApiAccessToAccountMetadata=default(SettingsMetadata), string AllowApiSendingOnBehalfOfOthers=default(string), SettingsMetadata AllowApiSendingOnBehalfOfOthersMetadata=default(SettingsMetadata), string AllowApiSequentialSigning=default(string), SettingsMetadata AllowApiSequentialSigningMetadata=default(SettingsMetadata), string AllowAutoTagging=default(string), SettingsMetadata AllowAutoTaggingMetadata=default(SettingsMetadata), string AllowBulkSending=default(string), SettingsMetadata AllowBulkSendingMetadata=default(SettingsMetadata), string AllowDocuSignDesktopClient=default(string), SettingsMetadata AllowDocuSignDesktopClientMetadata=default(SettingsMetadata), string AllowedAddressBookAccess=default(string), SettingsMetadata AllowedAddressBookAccessMetadata=default(SettingsMetadata), string AllowedClickwrapsAccess=default(string), SettingsMetadata AllowedClickwrapsAccessMetadata=default(SettingsMetadata), string AllowedTemplateAccess=default(string), SettingsMetadata AllowedTemplateAccessMetadata=default(SettingsMetadata), string AllowedToBeEnvelopeTransferRecipient=default(string), SettingsMetadata AllowedToBeEnvelopeTransferRecipientMetadata=default(SettingsMetadata), string AllowEnvelopeSending=default(string), SettingsMetadata AllowEnvelopeSendingMetadata=default(SettingsMetadata), string AllowESealRecipients=default(string), SettingsMetadata AllowESealRecipientsMetadata=default(SettingsMetadata), string AllowPowerFormsAdminToAccessAllPowerFormEnvelopes=default(string), SettingsMetadata AllowPowerFormsAdminToAccessAllPowerFormEnvelopesMetadata=default(SettingsMetadata), string AllowSendersToSetRecipientEmailLanguage=default(string), SettingsMetadata AllowSendersToSetRecipientEmailLanguageMetadata=default(SettingsMetadata), string AllowSignerAttachments=default(string), SettingsMetadata AllowSignerAttachmentsMetadata=default(SettingsMetadata), string AllowSupplementalDocuments=default(string), SettingsMetadata AllowSupplementalDocumentsMetadata=default(SettingsMetadata), string AllowTaggingInSendAndCorrect=default(string), SettingsMetadata AllowTaggingInSendAndCorrectMetadata=default(SettingsMetadata), string AllowVaulting=default(string), SettingsMetadata AllowVaultingMetadata=default(SettingsMetadata), string AllowWetSigningOverride=default(string), SettingsMetadata AllowWetSigningOverrideMetadata=default(SettingsMetadata), string CanCreateWorkspaces=default(string), SettingsMetadata CanCreateWorkspacesMetadata=default(SettingsMetadata), string CanSendEnvelopesViaSMS=default(string), SettingsMetadata CanSendEnvelopesViaSMSMetadata=default(SettingsMetadata), string DisableDocumentUpload=default(string), SettingsMetadata DisableDocumentUploadMetadata=default(SettingsMetadata), string DisableOtherActions=default(string), SettingsMetadata DisableOtherActionsMetadata=default(SettingsMetadata), string EnableApiRequestLogging=default(string), SettingsMetadata EnableApiRequestLoggingMetadata=default(SettingsMetadata), string EnableRecipientViewingNotifications=default(string), SettingsMetadata EnableRecipientViewingNotificationsMetadata=default(SettingsMetadata), string EnableSequentialSigningInterface=default(string), SettingsMetadata EnableSequentialSigningInterfaceMetadata=default(SettingsMetadata), string EnableTransactionPointIntegration=default(string), SettingsMetadata EnableTransactionPointIntegrationMetadata=default(SettingsMetadata), string PowerFormRole=default(string), SettingsMetadata PowerFormRoleMetadata=default(SettingsMetadata), string ReceiveCompletedSelfSignedDocumentsAsEmailLinks=default(string), SettingsMetadata ReceiveCompletedSelfSignedDocumentsAsEmailLinksMetadata=default(SettingsMetadata), SettingsMetadata SigningUiVersionMetadata=default(SettingsMetadata), string SupplementalDocumentsMustAccept=default(string), SettingsMetadata SupplementalDocumentsMustAcceptMetadata=default(SettingsMetadata), string SupplementalDocumentsMustRead=default(string), SettingsMetadata SupplementalDocumentsMustReadMetadata=default(SettingsMetadata), string SupplementalDocumentsMustView=default(string), SettingsMetadata SupplementalDocumentsMustViewMetadata=default(SettingsMetadata), string UseNewDocuSignExperienceInterface=default(string), SettingsMetadata UseNewDocuSignExperienceInterfaceMetadata=default(SettingsMetadata), string UseNewSendingInterface=default(string), SettingsMetadata UseNewSendingInterfaceMetadata=default(SettingsMetadata), string VaultingMode=default(string), SettingsMetadata VaultingModeMetadata=default(SettingsMetadata))',
      ],
    ],
  ],
  [
    'accountsapi',
    [
      'AccountsApi',
      [
        '../class_docu_sign_1_1e_sign_1_1_api_1_1_accounts_api.html#a641d3d8eeef9f2ab0d1cb544825b97b2',
        1,
        'DocuSign::eSign::Api::AccountsApi',
      ],
    ],
  ],
  [
    'accountseals',
    [
      'AccountSeals',
      [
        '../class_docu_sign_1_1e_sign_1_1_model_1_1_account_seals.html#ac321cfe5f37fc89631e6a7f45b986b12',
        1,
        'DocuSign.eSign.Model.AccountSeals.AccountSeals()',
      ],
      [
        '../class_docu_sign_1_1e_sign_1_1_model_1_1_account_seals.html#a5bfeefa777567a63e2e5e0485362f561',
        1,
        'DocuSign.eSign.Model.AccountSeals.AccountSeals(List&lt; SealIdentifier &gt; Seals=default(List&lt; SealIdentifier &gt;))',
      ],
    ],
  ],
  [
    'accountsettingsinformation',
    [
      'AccountSettingsInformation',
      [
        '../class_docu_sign_1_1e_sign_1_1_model_1_1_account_settings_information.html#ad839d89ea3c1ca12f6b5f5d8bfa172b8',
        1,
        'DocuSign.eSign.Model.AccountSettingsInformation.AccountSettingsInformation()',
      ],
      [
        '../class_docu_sign_1_1e_sign_1_1_model_1_1_account_settings_information.html#a3726ab411c7891bd451ff4028dc01f9f',
        1,
        'DocuSign.eSign.Model.AccountSettingsInformation.AccountSettingsInformation(AccessCodeFormat AccessCodeFormat=default(AccessCodeFormat), string AccountDateTimeFormat=default(string), SettingsMetadata AccountDateTimeFormatMetadata=default(SettingsMetadata), string AccountDefaultLanguage=default(string), SettingsMetadata AccountDefaultLanguageMetadata=default(SettingsMetadata), string AccountName=default(string), SettingsMetadata AccountNameMetadata=default(SettingsMetadata), AccountNotification AccountNotification=default(AccountNotification), AccountUISettings AccountUISettings=default(AccountUISettings), string AdoptSigConfig=default(string), SettingsMetadata AdoptSigConfigMetadata=default(SettingsMetadata), string AdvancedCorrect=default(string), SettingsMetadata AdvancedCorrectMetadata=default(SettingsMetadata), string AllowAccessCodeFormat=default(string), SettingsMetadata AllowAccessCodeFormatMetadata=default(SettingsMetadata), string AllowAccountManagementGranular=default(string), SettingsMetadata AllowAccountManagementGranularMetadata=default(SettingsMetadata), string AllowAccountMemberNameChange=default(string), SettingsMetadata AllowAccountMemberNameChangeMetadata=default(SettingsMetadata), string AllowAdvancedRecipientRoutingConditional=default(string), SettingsMetadata AllowAdvancedRecipientRoutingConditionalMetadata=default(SettingsMetadata), string AllowAgentNameEmailEdit=default(string), SettingsMetadata AllowAgentNameEmailEditMetadata=default(SettingsMetadata), string AllowAgreementActions=default(string), SettingsMetadata AllowAgreementActionsMetadata=default(SettingsMetadata), string AllowAutoNavSettings=default(string), SettingsMetadata AllowAutoNavSettingsMetadata=default(SettingsMetadata), string AllowAutoTagging=default(string), SettingsMetadata AllowAutoTaggingMetadata=default(SettingsMetadata), string AllowBulkSend=default(string), SettingsMetadata AllowBulkSendMetadata=default(SettingsMetadata), string AllowCDWithdraw=default(string), SettingsMetadata AllowCDWithdrawMetadata=default(SettingsMetadata), string AllowConnectHttpListenerConfigs=default(string), string AllowConnectSendFinishLater=default(string), SettingsMetadata AllowConnectSendFinishLaterMetadata=default(SettingsMetadata), string AllowConnectUnifiedPayloadUI=default(string), string AllowConsumerDisclosureOverride=default(string), SettingsMetadata AllowConsumerDisclosureOverrideMetadata=default(SettingsMetadata), string AllowDataDownload=default(string), SettingsMetadata AllowDataDownloadMetadata=default(SettingsMetadata), string AllowDocumentDisclosures=default(string), SettingsMetadata AllowDocumentDisclosuresMetadata=default(SettingsMetadata), string AllowDocumentsOnSignedEnvelopes=default(string), SettingsMetadata AllowDocumentsOnSignedEnvelopesMetadata=default(SettingsMetadata), string AllowDocumentVisibility=default(string), SettingsMetadata AllowDocumentVisibilityMetadata=default(SettingsMetadata), string AllowEHankoStamps=default(string), SettingsMetadata AllowEHankoStampsMetadata=default(SettingsMetadata), string AllowENoteEOriginal=default(string), SettingsMetadata AllowENoteEOriginalMetadata=default(SettingsMetadata), string AllowEnvelopeCorrect=default(string), SettingsMetadata AllowEnvelopeCorrectMetadata=default(SettingsMetadata), string AllowEnvelopeCustodyTransfer=default(string), SettingsMetadata AllowEnvelopeCustodyTransferMetadata=default(SettingsMetadata), string AllowEnvelopeCustomFields=default(string), SettingsMetadata AllowEnvelopeCustomFieldsMetadata=default(SettingsMetadata), string AllowEnvelopePublishReporting=default(string), SettingsMetadata AllowEnvelopePublishReportingMetadata=default(SettingsMetadata), string AllowEnvelopeReporting=default(string), SettingsMetadata AllowEnvelopeReportingMetadata=default(SettingsMetadata), string AllowExpression=default(string), SettingsMetadata AllowExpressionMetadata=default(SettingsMetadata), string AllowExpressSignerCertificate=default(string), SettingsMetadata AllowExpressSignerCertificateMetadata=default(SettingsMetadata), string AllowExtendedSendingResourceFile=default(string), SettingsMetadata AllowExtendedSendingResourceFileMetadata=default(SettingsMetadata), string AllowExternalLinkedAccounts=default(string), SettingsMetadata AllowExternalLinkedAccountsMetadata=default(SettingsMetadata), string AllowExternalSignaturePad=default(string), SettingsMetadata AllowExternalSignaturePadMetadata=default(SettingsMetadata), string AllowIDVLevel1=default(string), SettingsMetadata AllowIDVLevel1Metadata=default(SettingsMetadata), string AllowIDVLevel2=default(string), SettingsMetadata AllowIDVLevel2Metadata=default(SettingsMetadata), string AllowIDVLevel3=default(string), SettingsMetadata AllowIDVLevel3Metadata=default(SettingsMetadata), string AllowIDVPlatform=default(string), SettingsMetadata AllowIDVPlatformMetadata=default(SettingsMetadata), string AllowInPerson=default(string), SettingsMetadata AllowInPersonMetadata=default(SettingsMetadata), string AllowManagedStamps=default(string), SettingsMetadata AllowManagedStampsMetadata=default(SettingsMetadata), string AllowMarkup=default(string), SettingsMetadata AllowMarkupMetadata=default(SettingsMetadata), string AllowMemberTimeZone=default(string), SettingsMetadata AllowMemberTimeZoneMetadata=default(SettingsMetadata), string AllowMergeFields=default(string), SettingsMetadata AllowMergeFieldsMetadata=default(SettingsMetadata), string AllowMultipleBrandProfiles=default(string), SettingsMetadata AllowMultipleBrandProfilesMetadata=default(SettingsMetadata), string AllowMultipleSignerAttachments=default(string), SettingsMetadata AllowMultipleSignerAttachmentsMetadata=default(SettingsMetadata), string AllowNonUSPhoneAuth=default(string), SettingsMetadata AllowNonUSPhoneAuthMetadata=default(SettingsMetadata), string AllowOcrOfEnvelopeDocuments=default(string), SettingsMetadata AllowOcrOfEnvelopeDocumentsMetadata=default(SettingsMetadata), string AllowOfflineSigning=default(string), SettingsMetadata AllowOfflineSigningMetadata=default(SettingsMetadata), string AllowOpenTrustSignerCertificate=default(string), SettingsMetadata AllowOpenTrustSignerCertificateMetadata=default(SettingsMetadata), string AllowOrganizations=default(string), SettingsMetadata AllowOrganizationsMetadata=default(SettingsMetadata), string AllowPaymentProcessing=default(string), SettingsMetadata AllowPaymentProcessingMetadata=default(SettingsMetadata), string AllowPersonalSignerCertificate=default(string), SettingsMetadata AllowPersonalSignerCertificateMetadata=default(SettingsMetadata), string AllowPhoneAuthentication=default(string), SettingsMetadata AllowPhoneAuthenticationMetadata=default(SettingsMetadata), string AllowPhoneAuthOverride=default(string), SettingsMetadata AllowPhoneAuthOverrideMetadata=default(SettingsMetadata), string AllowPrivateSigningGroups=default(string), SettingsMetadata AllowPrivateSigningGroupsMetadata=default(SettingsMetadata), string AllowRecipientConnect=default(string), SettingsMetadata AllowRecipientConnectMetadata=default(SettingsMetadata), string AllowReminders=default(string), SettingsMetadata AllowRemindersMetadata=default(SettingsMetadata), string AllowRemoteNotary=default(string), SettingsMetadata AllowRemoteNotaryMetadata=default(SettingsMetadata), string AllowResourceFileBranding=default(string), SettingsMetadata AllowResourceFileBrandingMetadata=default(SettingsMetadata), string AllowSafeBioPharmaSignerCertificate=default(string), SettingsMetadata AllowSafeBioPharmaSignerCertificateMetadata=default(SettingsMetadata), string AllowSecurityAppliance=default(string), SettingsMetadata AllowSecurityApplianceMetadata=default(SettingsMetadata), string AllowSendToCertifiedDelivery=default(string), SettingsMetadata AllowSendToCertifiedDeliveryMetadata=default(SettingsMetadata), string AllowSendToIntermediary=default(string), SettingsMetadata AllowSendToIntermediaryMetadata=default(SettingsMetadata), string AllowServerTemplates=default(string), SettingsMetadata AllowServerTemplatesMetadata=default(SettingsMetadata), string AllowSetEmbeddedRecipientStartURL=default(string), SettingsMetadata AllowSetEmbeddedRecipientStartURLMetadata=default(SettingsMetadata), string AllowSharedTabs=default(string), SettingsMetadata AllowSharedTabsMetadata=default(SettingsMetadata), string AllowSignatureStamps=default(string), SettingsMetadata AllowSignatureStampsMetadata=default(SettingsMetadata), string AllowSignDocumentFromHomePage=default(string), SettingsMetadata AllowSignDocumentFromHomePageMetadata=default(SettingsMetadata), string AllowSignerReassign=default(string), SettingsMetadata AllowSignerReassignMetadata=default(SettingsMetadata), string AllowSignerReassignOverride=default(string), SettingsMetadata AllowSignerReassignOverrideMetadata=default(SettingsMetadata), string AllowSigningExtensions=default(string), SettingsMetadata AllowSigningExtensionsMetadata=default(SettingsMetadata), string AllowSigningGroups=default(string), SettingsMetadata AllowSigningGroupsMetadata=default(SettingsMetadata), string AllowSigningInsights=default(string), SettingsMetadata AllowSigningInsightsMetadata=default(SettingsMetadata), string AllowSigningRadioDeselect=default(string), SettingsMetadata AllowSigningRadioDeselectMetadata=default(SettingsMetadata), string AllowSignNow=default(string), string AllowSignNowMetadata=default(string), string AllowSMSDelivery=default(string), SettingsMetadata AllowSMSDeliveryMetadata=default(SettingsMetadata), string AllowSocialIdLogin=default(string), SettingsMetadata AllowSocialIdLoginMetadata=default(SettingsMetadata), string AllowSupplementalDocuments=default(string), SettingsMetadata AllowSupplementalDocumentsMetadata=default(SettingsMetadata), string AllowUsersToAccessDirectory=default(string), SettingsMetadata AllowUsersToAccessDirectoryMetadata=default(SettingsMetadata), string AllowValueInsights=default(string), SettingsMetadata AllowValueInsightsMetadata=default(SettingsMetadata), string AnchorPopulationScope=default(string), SettingsMetadata AnchorPopulationScopeMetadata=default(SettingsMetadata), string AnchorTagVersionedPlacementEnabled=default(string), SettingsMetadata AnchorTagVersionedPlacementMetadataEnabled=default(SettingsMetadata), string AttachCompletedEnvelope=default(string), SettingsMetadata AttachCompletedEnvelopeMetadata=default(SettingsMetadata), string AuthenticationCheck=default(string), SettingsMetadata AuthenticationCheckMetadata=default(SettingsMetadata), string AutoNavRule=default(string), SettingsMetadata AutoNavRuleMetadata=default(SettingsMetadata), string AutoProvisionSignerAccount=default(string), SettingsMetadata AutoProvisionSignerAccountMetadata=default(SettingsMetadata), string BccEmailArchive=default(string), SettingsMetadata BccEmailArchiveMetadata=default(SettingsMetadata), string BetaSwitchConfiguration=default(string), SettingsMetadata BetaSwitchConfigurationMetadata=default(SettingsMetadata), AddressInformation BillingAddress=default(AddressInformation), SettingsMetadata BillingAddressMetadata=default(SettingsMetadata), string BulkSend=default(string), string BulkSendMaxCopiesInBatch=default(string), string BulkSendMaxUnprocessedEnvelopesCount=default(string), SettingsMetadata BulkSendMetadata=default(SettingsMetadata), string CanSelfBrandSend=default(string), SettingsMetadata CanSelfBrandSendMetadata=default(SettingsMetadata), string CanSelfBrandSign=default(string), SettingsMetadata CanSelfBrandSignMetadata=default(SettingsMetadata), string CanUseSalesforceOAuth=default(string), SettingsMetadata CanUseSalesforceOAuthMetadata=default(SettingsMetadata), string CaptureVoiceRecording=default(string), SettingsMetadata CaptureVoiceRecordingMetadata=default(SettingsMetadata), string CfrUseWideImage=default(string), SettingsMetadata CfrUseWideImageMetadata=default(SettingsMetadata), string CheckForMultipleAdminsOnAccount=default(string), SettingsMetadata CheckForMultipleAdminsOnAccountMetadata=default(SettingsMetadata), string ChromeSignatureEnabled=default(string), SettingsMetadata ChromeSignatureEnabledMetadata=default(SettingsMetadata), string CommentEmailShowMessageText=default(string), SettingsMetadata CommentEmailShowMessageTextMetadata=default(SettingsMetadata), string CommentsAllowEnvelopeOverride=default(string), SettingsMetadata CommentsAllowEnvelopeOverrideMetadata=default(SettingsMetadata), string ConditionalFieldsEnabled=default(string), SettingsMetadata ConditionalFieldsEnabledMetadata=default(SettingsMetadata), string ConsumerDisclosureFrequency=default(string), SettingsMetadata ConsumerDisclosureFrequencyMetadata=default(SettingsMetadata), string ConvertPdfFields=default(string), SettingsMetadata ConvertPdfFieldsMetadata=default(SettingsMetadata), string DataPopulationScope=default(string), SettingsMetadata DataPopulationScopeMetadata=default(SettingsMetadata), string DisableAutoTemplateMatching=default(string), SettingsMetadata DisableAutoTemplateMatchingMetadata=default(SettingsMetadata), string DisableMobileApp=default(string), SettingsMetadata DisableMobileAppMetadata=default(SettingsMetadata), string DisableMobilePushNotifications=default(string), SettingsMetadata DisableMobilePushNotificationsMetadata=default(SettingsMetadata), string DisableMobileSending=default(string), SettingsMetadata DisableMobileSendingMetadata=default(SettingsMetadata), string DisableMultipleSessions=default(string), SettingsMetadata DisableMultipleSessionsMetadata=default(SettingsMetadata), SettingsMetadata DisablePurgeNotificationsForSenderMetadata=default(SettingsMetadata), string DisableSignerCertView=default(string), SettingsMetadata DisableSignerCertViewMetadata=default(SettingsMetadata), string DisableSignerHistoryView=default(string), SettingsMetadata DisableSignerHistoryViewMetadata=default(SettingsMetadata), string DisableStyleSignature=default(string), SettingsMetadata DisableStyleSignatureMetadata=default(SettingsMetadata), string DisableUploadSignature=default(string), SettingsMetadata DisableUploadSignatureMetadata=default(SettingsMetadata), string DisableUserSharing=default(string), SettingsMetadata DisableUserSharingMetadata=default(SettingsMetadata), string DisplayBetaSwitch=default(string), SettingsMetadata DisplayBetaSwitchMetadata=default(SettingsMetadata), string DocumentConversionRestrictions=default(string), SettingsMetadata DocumentConversionRestrictionsMetadata=default(SettingsMetadata), string DocumentRetention=default(string), SettingsMetadata DocumentRetentionMetadata=default(SettingsMetadata), string DocumentRetentionPurgeTabs=default(string), string DocumentVisibility=default(string), SettingsMetadata DocumentVisibilityMetadata=default(SettingsMetadata), string EmailTemplateVersion=default(string), SettingsMetadata EmailTemplateVersionMetadata=default(SettingsMetadata), string EnableAccessCodeGenerator=default(string), SettingsMetadata EnableAccessCodeGeneratorMetadata=default(SettingsMetadata), string EnableAdvancedPayments=default(string), SettingsMetadata EnableAdvancedPaymentsMetadata=default(SettingsMetadata), string EnableAdvancedPowerForms=default(string), SettingsMetadata EnableAdvancedPowerFormsMetadata=default(SettingsMetadata), string EnableAgreementActionsForCLM=default(string), SettingsMetadata EnableAgreementActionsForCLMMetadata=default(SettingsMetadata), string EnableAgreementActionsForESign=default(string), SettingsMetadata EnableAgreementActionsForESignMetadata=default(SettingsMetadata), string EnableAutoNav=default(string), SettingsMetadata EnableAutoNavMetadata=default(SettingsMetadata), string EnableCalculatedFields=default(string), SettingsMetadata EnableCalculatedFieldsMetadata=default(SettingsMetadata), string EnableClickwraps=default(string), SettingsMetadata EnableClickwrapsMetadata=default(SettingsMetadata), string EnableCommentsHistoryDownloadInSigning=default(string), SettingsMetadata EnableCommentsHistoryDownloadInSigningMetadata=default(SettingsMetadata), string EnableCustomerSatisfactionMetricTracking=default(string), SettingsMetadata EnableCustomerSatisfactionMetricTrackingMetadata=default(SettingsMetadata), string EnableDSPro=default(string), SettingsMetadata EnableDSProMetadata=default(SettingsMetadata), string EnableEnvelopeStampingByAccountAdmin=default(string), SettingsMetadata EnableEnvelopeStampingByAccountAdminMetadata=default(SettingsMetadata), string EnableEnvelopeStampingByDSAdmin=default(string), SettingsMetadata EnableEnvelopeStampingByDSAdminMetadata=default(SettingsMetadata), string EnableEsignCommunities=default(string), SettingsMetadata EnableEsignCommunitiesMetadata=default(SettingsMetadata), string EnableInBrowserEditor=default(string), SettingsMetadata EnableInBrowserEditorMetadata=default(SettingsMetadata), string EnablePaymentProcessing=default(string), SettingsMetadata EnablePaymentProcessingMetadata=default(SettingsMetadata), string EnablePowerForm=default(string), string EnablePowerFormDirect=default(string), SettingsMetadata EnablePowerFormDirectMetadata=default(SettingsMetadata), SettingsMetadata EnablePowerFormMetadata=default(SettingsMetadata), string EnableRecipientDomainValidation=default(string), SettingsMetadata EnableRecipientDomainValidationMetadata=default(SettingsMetadata), string EnableReportLinks=default(string), SettingsMetadata EnableReportLinksMetadata=default(SettingsMetadata), string EnableRequireSignOnPaper=default(string), SettingsMetadata EnableRequireSignOnPaperMetadata=default(SettingsMetadata), string EnableReservedDomain=default(string), SettingsMetadata EnableReservedDomainMetadata=default(SettingsMetadata), string EnableResponsiveSigning=default(string), SettingsMetadata EnableResponsiveSigningMetadata=default(SettingsMetadata), string EnableScheduledRelease=default(string), SettingsMetadata EnableScheduledReleaseMetadata=default(SettingsMetadata), string EnableSearch=default(string), SettingsMetadata EnableSearchMetadata=default(SettingsMetadata), string EnableSearchUI=default(string), SettingsMetadata EnableSearchUIMetadata=default(SettingsMetadata), string EnableSendingTagsFontSettings=default(string), SettingsMetadata EnableSendingTagsFontSettingsMetadata=default(SettingsMetadata), string EnableSendToAgent=default(string), SettingsMetadata EnableSendToAgentMetadata=default(SettingsMetadata), string EnableSendToIntermediary=default(string), SettingsMetadata EnableSendToIntermediaryMetadata=default(SettingsMetadata), string EnableSendToManage=default(string), SettingsMetadata EnableSendToManageMetadata=default(SettingsMetadata), string EnableSequentialSigningAPI=default(string), SettingsMetadata EnableSequentialSigningAPIMetadata=default(SettingsMetadata), string EnableSequentialSigningUI=default(string), SettingsMetadata EnableSequentialSigningUIMetadata=default(SettingsMetadata), string EnableSignerAttachments=default(string), SettingsMetadata EnableSignerAttachmentsMetadata=default(SettingsMetadata), string EnableSigningExtensionComments=default(string), SettingsMetadata EnableSigningExtensionCommentsMetadata=default(SettingsMetadata), string EnableSigningExtensionConversations=default(string), SettingsMetadata EnableSigningExtensionConversationsMetadata=default(SettingsMetadata), string EnableSigningOrderSettingsForAccount=default(string), SettingsMetadata EnableSigningOrderSettingsForAccountMetadata=default(SettingsMetadata), string EnableSignOnPaper=default(string), SettingsMetadata EnableSignOnPaperMetadata=default(SettingsMetadata), string EnableSignOnPaperOverride=default(string), SettingsMetadata EnableSignOnPaperOverrideMetadata=default(SettingsMetadata), string EnableSignWithNotary=default(string), SettingsMetadata EnableSignWithNotaryMetadata=default(SettingsMetadata), string EnableSmartContracts=default(string), SettingsMetadata EnableSmartContractsMetadata=default(SettingsMetadata), string EnableSMSAuthentication=default(string), SettingsMetadata EnableSMSAuthenticationMetadata=default(SettingsMetadata), string EnableSMSDeliveryAdditionalNotification=default(string), SettingsMetadata EnableSMSDeliveryAdditionalNotificationMetadata=default(SettingsMetadata), string EnableSocialIdLogin=default(string), SettingsMetadata EnableSocialIdLoginMetadata=default(SettingsMetadata), string EnableStrikeThrough=default(string), SettingsMetadata EnableStrikeThroughMetadata=default(SettingsMetadata), string EnableTransactionPoint=default(string), SettingsMetadata EnableTransactionPointMetadata=default(SettingsMetadata), string EnableVaulting=default(string), SettingsMetadata EnableVaultingMetadata=default(SettingsMetadata), string EnableWitnessing=default(string), SettingsMetadata EnableWitnessingMetadata=default(SettingsMetadata), string EnforceTemplateNameUniqueness=default(string), SettingsMetadata EnforceTemplateNameUniquenessMetadata=default(SettingsMetadata), string EnvelopeIntegrationAllowed=default(string), SettingsMetadata EnvelopeIntegrationAllowedMetadata=default(SettingsMetadata), string EnvelopeIntegrationEnabled=default(string), SettingsMetadata EnvelopeIntegrationEnabledMetadata=default(SettingsMetadata), string EnvelopeStampingDefaultValue=default(string), SettingsMetadata EnvelopeStampingDefaultValueMetadata=default(SettingsMetadata), string ExpressSend=default(string), string ExpressSendAllowTabs=default(string), SettingsMetadata ExpressSendAllowTabsMetadata=default(SettingsMetadata), SettingsMetadata ExpressSendMetadata=default(SettingsMetadata), ExternalDocumentSources ExternalDocumentSources=default(ExternalDocumentSources), string ExternalSignaturePadType=default(string), SettingsMetadata ExternalSignaturePadTypeMetadata=default(SettingsMetadata), string FaxOutEnabled=default(string), SettingsMetadata FaxOutEnabledMetadata=default(SettingsMetadata), string GuidedFormsHtmlAllowed=default(string), SettingsMetadata GuidedFormsHtmlAllowedMetadata=default(SettingsMetadata), string HideAccountAddressInCoC=default(string), SettingsMetadata HideAccountAddressInCoCMetadata=default(SettingsMetadata), string HidePricing=default(string), SettingsMetadata HidePricingMetadata=default(SettingsMetadata), List&lt; IdCheckConfiguration &gt; IdCheckConfigurations=default(List&lt; IdCheckConfiguration &gt;), string IdCheckExpire=default(string), string IdCheckExpireDays=default(string), SettingsMetadata IdCheckExpireDaysMetadata=default(SettingsMetadata), SettingsMetadata IdCheckExpireMetadata=default(SettingsMetadata), string IdCheckExpireMinutes=default(string), SettingsMetadata IdCheckExpireMinutesMetadata=default(SettingsMetadata), string IdCheckRequired=default(string), SettingsMetadata IdCheckRequiredMetadata=default(SettingsMetadata), List&lt; AccountIdentityVerificationWorkflow &gt; IdentityVerification=default(List&lt; AccountIdentityVerificationWorkflow &gt;), SettingsMetadata IdentityVerificationMetadata=default(SettingsMetadata), string IgnoreErrorIfAnchorTabNotFound=default(string), SettingsMetadata IgnoreErrorIfAnchorTabNotFoundMetadataEnabled=default(SettingsMetadata), string InPersonIDCheckQuestion=default(string), SettingsMetadata InPersonIDCheckQuestionMetadata=default(SettingsMetadata), string InPersonSigningEnabled=default(string), SettingsMetadata InPersonSigningEnabledMetadata=default(SettingsMetadata), string InSessionEnabled=default(string), SettingsMetadata InSessionEnabledMetadata=default(SettingsMetadata), string InSessionSuppressEmails=default(string), SettingsMetadata InSessionSuppressEmailsMetadata=default(SettingsMetadata), List&lt; LinkedExternalPrimaryAccount &gt; LinkedExternalPrimaryAccounts=default(List&lt; LinkedExternalPrimaryAccount &gt;), string MaximumSigningGroups=default(string), SettingsMetadata MaximumSigningGroupsMetadata=default(SettingsMetadata), string MaximumUsersPerSigningGroup=default(string), SettingsMetadata MaximumUsersPerSigningGroupMetadata=default(SettingsMetadata), string MaxNumberOfCustomStamps=default(string), string MobileSessionTimeout=default(string), SettingsMetadata MobileSessionTimeoutMetadata=default(SettingsMetadata), string NumberOfActiveCustomStamps=default(string), string OptInMobileSigningV02=default(string), SettingsMetadata OptInMobileSigningV02Metadata=default(SettingsMetadata), string OptOutAutoNavTextAndTabColorUpdates=default(string), SettingsMetadata OptOutAutoNavTextAndTabColorUpdatesMetadata=default(SettingsMetadata), string OptOutNewPlatformSeal=default(string), SettingsMetadata OptOutNewPlatformSealPlatformMetadata=default(SettingsMetadata), string PhoneAuthRecipientMayProvidePhoneNumber=default(string), SettingsMetadata PhoneAuthRecipientMayProvidePhoneNumberMetadata=default(SettingsMetadata), string PkiSignDownloadedPDFDocs=default(string), SettingsMetadata PkiSignDownloadedPDFDocsMetadata=default(SettingsMetadata), string RecipientsCanSignOffline=default(string), SettingsMetadata RecipientsCanSignOfflineMetadata=default(SettingsMetadata), string RecipientSigningAutoNavigationControl=default(string), SettingsMetadata RecipientSigningAutoNavigationControlMetadata=default(SettingsMetadata), string Require21CFRpt11Compliance=default(string), SettingsMetadata Require21CFRpt11ComplianceMetadata=default(SettingsMetadata), string RequireDeclineReason=default(string), SettingsMetadata RequireDeclineReasonMetadata=default(SettingsMetadata), string RequireExternalUserManagement=default(string), SettingsMetadata RequireExternalUserManagementMetadata=default(SettingsMetadata), string RequireSignerCertificateType=default(string), SettingsMetadata RequireSignerCertificateTypeMetadata=default(SettingsMetadata), string RsaVeridAccountName=default(string), string RsaVeridPassword=default(string), string RsaVeridRuleset=default(string), string RsaVeridUserId=default(string), string SelfSignedRecipientEmailDocument=default(string), SettingsMetadata SelfSignedRecipientEmailDocumentMetadata=default(SettingsMetadata), string SelfSignedRecipientEmailDocumentUserOverride=default(string), SettingsMetadata SelfSignedRecipientEmailDocumentUserOverrideMetadata=default(SettingsMetadata), string SenderCanSignInEachLocation=default(string), SettingsMetadata SenderCanSignInEachLocationMetadata=default(SettingsMetadata), string SenderMustAuthenticateSigning=default(string), SettingsMetadata SenderMustAuthenticateSigningMetadata=default(SettingsMetadata), string SendingTagsFontColor=default(string), SettingsMetadata SendingTagsFontColorMetadata=default(SettingsMetadata), string SendingTagsFontName=default(string), SettingsMetadata SendingTagsFontNameMetadata=default(SettingsMetadata), string SendingTagsFontSize=default(string), SettingsMetadata SendingTagsFontSizeMetadata=default(SettingsMetadata), string SendToCertifiedDeliveryEnabled=default(string), SettingsMetadata SendToCertifiedDeliveryEnabledMetadata=default(SettingsMetadata), string SessionTimeout=default(string), SettingsMetadata SessionTimeoutMetadata=default(SettingsMetadata), string SetRecipEmailLang=default(string), SettingsMetadata SetRecipEmailLangMetadata=default(SettingsMetadata), string SetRecipSignLang=default(string), SettingsMetadata SetRecipSignLangMetadata=default(SettingsMetadata), string SharedTemplateFolders=default(string), SettingsMetadata SharedTemplateFoldersMetadata=default(SettingsMetadata), string ShowCompleteDialogInEmbeddedSession=default(string), SettingsMetadata ShowCompleteDialogInEmbeddedSessionMetadata=default(SettingsMetadata), string ShowConditionalRoutingOnSend=default(string), SettingsMetadata ShowConditionalRoutingOnSendMetadata=default(SettingsMetadata), string ShowInitialConditionalFields=default(string), SettingsMetadata ShowInitialConditionalFieldsMetadata=default(SettingsMetadata), string ShowLocalizedWatermarks=default(string), SettingsMetadata ShowLocalizedWatermarksMetadata=default(SettingsMetadata), string ShowMaskedFieldsWhenDownloadingDocumentAsSender=default(string), SettingsMetadata ShowMaskedFieldsWhenDownloadingDocumentAsSenderMetadata=default(SettingsMetadata), string ShowTutorials=default(string), SettingsMetadata ShowTutorialsMetadata=default(SettingsMetadata), List&lt; string &gt; SignatureProviders=default(List&lt; string &gt;), SettingsMetadata SignatureProvidersMetadata=default(SettingsMetadata), string SignDateFormat=default(string), SettingsMetadata SignDateFormatMetadata=default(SettingsMetadata), string SignDateTimeAccountLanguageOverride=default(string), SettingsMetadata SignDateTimeAccountLanguageOverrideMetadata=default(SettingsMetadata), string SignDateTimeAccountTimezoneOverride=default(string), SettingsMetadata SignDateTimeAccountTimezoneOverrideMetadata=default(SettingsMetadata), string SignerAttachCertificateToEnvelopePDF=default(string), SettingsMetadata SignerAttachCertificateToEnvelopePDFMetadata=default(SettingsMetadata), string SignerAttachConcat=default(string), SettingsMetadata SignerAttachConcatMetadata=default(SettingsMetadata), string SignerCanCreateAccount=default(string), SettingsMetadata SignerCanCreateAccountMetadata=default(SettingsMetadata), string SignerCanSignOnMobile=default(string), SettingsMetadata SignerCanSignOnMobileMetadata=default(SettingsMetadata), string SignerInSessionUseEnvelopeCompleteEmail=default(string), SettingsMetadata SignerInSessionUseEnvelopeCompleteEmailMetadata=default(SettingsMetadata), string SignerLoginRequirements=default(string), SettingsMetadata SignerLoginRequirementsMetadata=default(SettingsMetadata), string SignerMustHaveAccount=default(string), SettingsMetadata SignerMustHaveAccountMetadata=default(SettingsMetadata), string SignerMustLoginToSign=default(string), SettingsMetadata SignerMustLoginToSignMetadata=default(SettingsMetadata), string SignerShowSecureFieldInitialValues=default(string), SettingsMetadata SignerShowSecureFieldInitialValuesMetadata=default(SettingsMetadata), string SigningSessionTimeout=default(string), SettingsMetadata SigningSessionTimeoutMetadata=default(SettingsMetadata), string SigningUiVersion=default(string), SettingsMetadata SigningUiVersionMetadata=default(SettingsMetadata), string SignTimeFormat=default(string), SettingsMetadata SignTimeFormatMetadata=default(SettingsMetadata), string SignTimeShowAmPm=default(string), SettingsMetadata SignTimeShowAmPmMetadata=default(SettingsMetadata), string SimplifiedSendingEnabled=default(string), SettingsMetadata SimplifiedSendingEnabledMetadata=default(SettingsMetadata), string SingleSignOnEnabled=default(string), SettingsMetadata SingleSignOnEnabledMetadata=default(SettingsMetadata), string SkipAuthCompletedEnvelopes=default(string), SettingsMetadata SkipAuthCompletedEnvelopesMetadata=default(SettingsMetadata), string SocialIdRecipAuth=default(string), SettingsMetadata SocialIdRecipAuthMetadata=default(SettingsMetadata), string SpecifyDocumentVisibility=default(string), SettingsMetadata SpecifyDocumentVisibilityMetadata=default(SettingsMetadata), string StartInAdvancedCorrect=default(string), SettingsMetadata StartInAdvancedCorrectMetadata=default(SettingsMetadata), string SupplementalDocumentsMustAccept=default(string), SettingsMetadata SupplementalDocumentsMustAcceptMetadata=default(SettingsMetadata), string SupplementalDocumentsMustRead=default(string), SettingsMetadata SupplementalDocumentsMustReadMetadata=default(SettingsMetadata), string SupplementalDocumentsMustView=default(string), SettingsMetadata SupplementalDocumentsMustViewMetadata=default(SettingsMetadata), string SuppressCertificateEnforcement=default(string), SettingsMetadata SuppressCertificateEnforcementMetadata=default(SettingsMetadata), TabAccountSettings TabAccountSettings=default(TabAccountSettings), string TimezoneOffsetAPI=default(string), SettingsMetadata TimezoneOffsetAPIMetadata=default(SettingsMetadata), string TimezoneOffsetUI=default(string), SettingsMetadata TimezoneOffsetUIMetadata=default(SettingsMetadata), string UniversalSignatureOptIn=default(string), string UseAccountLevelEmail=default(string), SettingsMetadata UseAccountLevelEmailMetadata=default(SettingsMetadata), string UseConsumerDisclosure=default(string), SettingsMetadata UseConsumerDisclosureMetadata=default(SettingsMetadata), string UseConsumerDisclosureWithinAccount=default(string), SettingsMetadata UseConsumerDisclosureWithinAccountMetadata=default(SettingsMetadata), string UseDerivedKeys=default(string), SettingsMetadata UseDerivedKeysMetadata=default(SettingsMetadata), string UseDocuSignExpressSignerCertificate=default(string), SettingsMetadata UseDocuSignExpressSignerCertificateMetadata=default(SettingsMetadata), string UseMultiAppGroupsData=default(string), SettingsMetadata UseMultiAppGroupsDataMetadata=default(SettingsMetadata), string UseNewBlobForPdf=default(string), SettingsMetadata UseNewBlobForPdfMetadata=default(SettingsMetadata), string UseSAFESignerCertificates=default(string), SettingsMetadata UseSAFESignerCertificatesMetadata=default(SettingsMetadata), string UsesAPI=default(string), SettingsMetadata UsesAPIMetadata=default(SettingsMetadata), string UseSignatureProviderPlatform=default(string), SettingsMetadata UseSignatureProviderPlatformMetadata=default(SettingsMetadata), string ValidationsAllowed=default(string), SettingsMetadata ValidationsAllowedMetadata=default(SettingsMetadata), string ValidationsBrand=default(string), SettingsMetadata ValidationsBrandMetadata=default(SettingsMetadata), string ValidationsCadence=default(string), SettingsMetadata ValidationsCadenceMetadata=default(SettingsMetadata), string ValidationsEnabled=default(string), SettingsMetadata ValidationsEnabledMetadata=default(SettingsMetadata), string ValidationsReport=default(string), SettingsMetadata ValidationsReportMetadata=default(SettingsMetadata), string WaterMarkEnabled=default(string), SettingsMetadata WaterMarkEnabledMetadata=default(SettingsMetadata), string WriteReminderToEnvelopeHistory=default(string), SettingsMetadata WriteReminderToEnvelopeHistoryMetadata=default(SettingsMetadata), string WurflMinAllowableScreenSize=default(string), SettingsMetadata WurflMinAllowableScreenSizeMetadata=default(SettingsMetadata))',
      ],
    ],
  ],
  [
    'accountsharedaccess',
    [
      'AccountSharedAccess',
      [
        '../class_docu_sign_1_1e_sign_1_1_model_1_1_account_shared_access.html#a3011946d73f5c1c22aec3b33ef9e6785',
        1,
        'DocuSign.eSign.Model.AccountSharedAccess.AccountSharedAccess()',
      ],
      [
        '../class_docu_sign_1_1e_sign_1_1_model_1_1_account_shared_access.html#a62ef2e78cf06e9934400d50796225871',
        1,
        'DocuSign.eSign.Model.AccountSharedAccess.AccountSharedAccess(string AccountId=default(string), string EndPosition=default(string), ErrorDetails ErrorDetails=default(ErrorDetails), string NextUri=default(string), string PreviousUri=default(string), string ResultSetSize=default(string), List&lt; MemberSharedItems &gt; SharedAccess=default(List&lt; MemberSharedItems &gt;), string StartPosition=default(string), string TotalSetSize=default(string))',
      ],
    ],
  ],
  [
    'accountsignature',
    [
      'AccountSignature',
      [
        '../class_docu_sign_1_1e_sign_1_1_model_1_1_account_signature.html#af3fcfb43dcc85d049cba4e71fbcbb75e',
        1,
        'DocuSign.eSign.Model.AccountSignature.AccountSignature()',
      ],
      [
        '../class_docu_sign_1_1e_sign_1_1_model_1_1_account_signature.html#a14ee20751784d452e80de05ef9374994',
        1,
        'DocuSign.eSign.Model.AccountSignature.AccountSignature(string AdoptedDateTime=default(string), string CreatedDateTime=default(string), string CustomField=default(string), DateStampProperties DateStampProperties=default(DateStampProperties), string DisallowUserResizeStamp=default(string), ErrorDetails ErrorDetails=default(ErrorDetails), string ExternalID=default(string), string ImageBase64=default(string), string ImageType=default(string), string Initials150ImageId=default(string), string InitialsImageUri=default(string), string IsDefault=default(string), string LastModifiedDateTime=default(string), string NrdsId=default(string), string NrdsLastName=default(string), string NrdsStatus=default(string), string PhoneticName=default(string), string Signature150ImageId=default(string), string SignatureFont=default(string), List&lt; SignatureGroup &gt; SignatureGroups=default(List&lt; SignatureGroup &gt;), string SignatureId=default(string), string SignatureImageUri=default(string), string SignatureInitials=default(string), string SignatureName=default(string), string SignatureRights=default(string), string SignatureType=default(string), List&lt; SignatureUser &gt; SignatureUsers=default(List&lt; SignatureUser &gt;), string StampFormat=default(string), string StampImageUri=default(string), string StampSizeMM=default(string), string StampType=default(string), string Status=default(string))',
      ],
    ],
  ],
  [
    'accountsignaturedefinition',
    [
      'AccountSignatureDefinition',
      [
        '../class_docu_sign_1_1e_sign_1_1_model_1_1_account_signature_definition.html#a7d71c5b34e241b923857435c95acf057',
        1,
        'DocuSign.eSign.Model.AccountSignatureDefinition.AccountSignatureDefinition()',
      ],
      [
        '../class_docu_sign_1_1e_sign_1_1_model_1_1_account_signature_definition.html#a0d157d67dad98b9302e152ae23a60331',
        1,
        'DocuSign.eSign.Model.AccountSignatureDefinition.AccountSignatureDefinition(DateStampProperties DateStampProperties=default(DateStampProperties), string DisallowUserResizeStamp=default(string), string ExternalID=default(string), string ImageType=default(string), string IsDefault=default(string), string NrdsId=default(string), string NrdsLastName=default(string), string PhoneticName=default(string), string SignatureFont=default(string), List&lt; SignatureGroupDef &gt; SignatureGroups=default(List&lt; SignatureGroupDef &gt;), string SignatureId=default(string), string SignatureInitials=default(string), string SignatureName=default(string), List&lt; SignatureUserDef &gt; SignatureUsers=default(List&lt; SignatureUserDef &gt;), string StampFormat=default(string), string StampSizeMM=default(string))',
      ],
    ],
  ],
  [
    'accountsignatureprovider',
    [
      'AccountSignatureProvider',
      [
        '../class_docu_sign_1_1e_sign_1_1_model_1_1_account_signature_provider.html#a95328d3f009ef973d3b27974af98eb80',
        1,
        'DocuSign.eSign.Model.AccountSignatureProvider.AccountSignatureProvider()',
      ],
      [
        '../class_docu_sign_1_1e_sign_1_1_model_1_1_account_signature_provider.html#a5495f521bbc821dc48e9fab1280824fa',
        1,
        'DocuSign.eSign.Model.AccountSignatureProvider.AccountSignatureProvider(string IsRequired=default(string), string Priority=default(string), string SignatureProviderDisplayName=default(string), string SignatureProviderId=default(string), string SignatureProviderName=default(string), List&lt; AccountSignatureProviderOption &gt; SignatureProviderOptionsMetadata=default(List&lt; AccountSignatureProviderOption &gt;), List&lt; SignatureProviderRequiredOption &gt; SignatureProviderRequiredOptions=default(List&lt; SignatureProviderRequiredOption &gt;))',
      ],
    ],
  ],
  [
    'accountsignatureprovideroption',
    [
      'AccountSignatureProviderOption',
      [
        '../class_docu_sign_1_1e_sign_1_1_model_1_1_account_signature_provider_option.html#a19af9164802ff8713d342026732f5a23',
        1,
        'DocuSign.eSign.Model.AccountSignatureProviderOption.AccountSignatureProviderOption()',
      ],
      [
        '../class_docu_sign_1_1e_sign_1_1_model_1_1_account_signature_provider_option.html#acf365302a7a7c768db4983f180ce09d5',
        1,
        'DocuSign.eSign.Model.AccountSignatureProviderOption.AccountSignatureProviderOption(string SignatureProviderOptionDisplayName=default(string), string SignatureProviderOptionId=default(string), string SignatureProviderOptionName=default(string))',
      ],
    ],
  ],
  [
    'accountsignatureproviders',
    [
      'AccountSignatureProviders',
      [
        '../class_docu_sign_1_1e_sign_1_1_model_1_1_account_signature_providers.html#a1e67bb0b1a91477b28613d84f04b9eec',
        1,
        'DocuSign.eSign.Model.AccountSignatureProviders.AccountSignatureProviders()',
      ],
      [
        '../class_docu_sign_1_1e_sign_1_1_model_1_1_account_signature_providers.html#ae90e44ce5cd2cab384139af7ca2e33c2',
        1,
        'DocuSign.eSign.Model.AccountSignatureProviders.AccountSignatureProviders(List&lt; AccountSignatureProvider &gt; SignatureProviders=default(List&lt; AccountSignatureProvider &gt;))',
      ],
    ],
  ],
  [
    'accountsignaturesinformation',
    [
      'AccountSignaturesInformation',
      [
        '../class_docu_sign_1_1e_sign_1_1_model_1_1_account_signatures_information.html#a4bf166409dca7661d1160d8b8582a64a',
        1,
        'DocuSign.eSign.Model.AccountSignaturesInformation.AccountSignaturesInformation()',
      ],
      [
        '../class_docu_sign_1_1e_sign_1_1_model_1_1_account_signatures_information.html#a033b6ff1ea6e0444b32886dba5e20449',
        1,
        'DocuSign.eSign.Model.AccountSignaturesInformation.AccountSignaturesInformation(List&lt; AccountSignature &gt; AccountSignatures=default(List&lt; AccountSignature &gt;))',
      ],
    ],
  ],
  [
    'accountuisettings',
    [
      'AccountUISettings',
      [
        '../class_docu_sign_1_1e_sign_1_1_model_1_1_account_u_i_settings.html#a4ecc2a19ecf0ec0ffa4765cf7a4e8a2d',
        1,
        'DocuSign.eSign.Model.AccountUISettings.AccountUISettings()',
      ],
      [
        '../class_docu_sign_1_1e_sign_1_1_model_1_1_account_u_i_settings.html#acf90729c730d8172bbb3253374d416b0',
        1,
        'DocuSign.eSign.Model.AccountUISettings.AccountUISettings(AdminMessage AdminMessage=default(AdminMessage), AskAnAdmin AskAnAdmin=default(AskAnAdmin), string EnableAdminMessage=default(string), SettingsMetadata EnableAdminMessageMetadata=default(SettingsMetadata), string EnableAdvancedPaymentsReactEdit=default(string), string EnableEasySignCanUseMultiTemplateApply=default(string), SettingsMetadata EnableEasySignCanUseMultiTemplateApplyMetadata=default(SettingsMetadata), string EnableEasySignTemplateUpload=default(string), SettingsMetadata EnableEasySignTemplateUploadMetadata=default(SettingsMetadata), string EnableEnvelopeCopyWithData=default(string), SettingsMetadata EnableEnvelopeCopyWithDataMetadata=default(SettingsMetadata), string EnableLegacyHomepageLink=default(string), SettingsMetadata EnableLegacyHomepageLinkMetadata=default(SettingsMetadata), string HasExternalLinkedAccounts=default(string), SettingsMetadata HasExternalLinkedAccountsMetadata=default(SettingsMetadata), string HideSendAnEnvelope=default(string), SettingsMetadata HideSendAnEnvelopeMetadata=default(SettingsMetadata), string HideUseATemplate=default(string), string HideUseATemplateInPrepare=default(string), SettingsMetadata HideUseATemplateInPrepareMetadata=default(SettingsMetadata), SettingsMetadata HideUseATemplateMetadata=default(SettingsMetadata), string OrderBasedRecipientIdGeneration=default(string), SettingsMetadata OrderBasedRecipientIdGenerationMetadata=default(SettingsMetadata), string RemoveEnvelopeForwarding=default(string), SettingsMetadata RemoveEnvelopeForwardingMetadata=default(SettingsMetadata), string ShouldRedactAccessCode=default(string), SettingsMetadata ShouldRedactAccessCodeMetadata=default(SettingsMetadata), string UploadNewImageToSignOrInitial=default(string), SettingsMetadata UploadNewImageToSignOrInitialMetadata=default(SettingsMetadata))',
      ],
    ],
  ],
  [
    'addaccount',
    [
      'AddAccount',
      [
        '../class_docu_sign_1_1e_sign_1_1_client_1_1_auth_1_1_o_auth_1_1_user_info.html#a0b3879cc04005a2f642a7362f6402a64',
        1,
        'DocuSign::eSign::Client::Auth::OAuth::UserInfo',
      ],
    ],
  ],
  [
    'addapikey',
    [
      'AddApiKey',
      [
        '../class_docu_sign_1_1e_sign_1_1_client_1_1_configuration.html#a2c8b823c33634280e43c8ce1bfe7324c',
        1,
        'DocuSign::eSign::Client::Configuration',
      ],
    ],
  ],
  [
    'addapikeyprefix',
    [
      'AddApiKeyPrefix',
      [
        '../class_docu_sign_1_1e_sign_1_1_client_1_1_configuration.html#a3472a4d66829a8d7cfd5cf3d4f500769',
        1,
        'DocuSign::eSign::Client::Configuration',
      ],
    ],
  ],
  [
    'adddefaultheader',
    [
      'AddDefaultHeader',
      [
        '../class_docu_sign_1_1e_sign_1_1_client_1_1_configuration.html#a1cb6868432a80c2db14eb6a7a63c735b',
        1,
        'DocuSign::eSign::Client::Configuration',
      ],
    ],
  ],
  [
    'addlinks',
    [
      'AddLinks',
      [
        '../class_docu_sign_1_1e_sign_1_1_client_1_1_auth_1_1_o_auth_1_1_user_info_1_1_organization.html#a71b650e0224c5d089925a6216cec8e12',
        1,
        'DocuSign::eSign::Client::Auth::OAuth::UserInfo::Organization',
      ],
    ],
  ],
  [
    'addon',
    [
      'AddOn',
      [
        '../class_docu_sign_1_1e_sign_1_1_model_1_1_add_on.html#ac303605d6a673422eccf1ee8048160d7',
        1,
        'DocuSign.eSign.Model.AddOn.AddOn()',
      ],
      [
        '../class_docu_sign_1_1e_sign_1_1_model_1_1_add_on.html#a0fd4120f8eada8dee6c4fff2b5a66a82',
        1,
        'DocuSign.eSign.Model.AddOn.AddOn(string Active=default(string), string AddOnId=default(string), string Id=default(string), string Name=default(string))',
      ],
    ],
  ],
  [
    'addressinformation',
    [
      'AddressInformation',
      [
        '../class_docu_sign_1_1e_sign_1_1_model_1_1_address_information.html#adff83d593834320b686f3ace419607c6',
        1,
        'DocuSign.eSign.Model.AddressInformation.AddressInformation()',
      ],
      [
        '../class_docu_sign_1_1e_sign_1_1_model_1_1_address_information.html#a35e9d71d45ec1876467f96dbbee39fe4',
        1,
        'DocuSign.eSign.Model.AddressInformation.AddressInformation(string Address1=default(string), string Address2=default(string), string City=default(string), string Country=default(string), string Fax=default(string), string Phone=default(string), string PostalCode=default(string), string StateOrProvince=default(string), string ZipPlus4=default(string))',
      ],
    ],
  ],
  [
    'addressinformationinput',
    [
      'AddressInformationInput',
      [
        '../class_docu_sign_1_1e_sign_1_1_model_1_1_address_information_input.html#ae84b046474879263bfce66fb48379539',
        1,
        'DocuSign.eSign.Model.AddressInformationInput.AddressInformationInput()',
      ],
      [
        '../class_docu_sign_1_1e_sign_1_1_model_1_1_address_information_input.html#a270f6bf8e9e0155a6aef2c9effe5f605',
        1,
        'DocuSign.eSign.Model.AddressInformationInput.AddressInformationInput(AddressInformation AddressInformation=default(AddressInformation), string DisplayLevelCode=default(string), string ReceiveInResponse=default(string))',
      ],
    ],
  ],
  [
    'addressinformationv2',
    [
      'AddressInformationV2',
      [
        '../class_docu_sign_1_1e_sign_1_1_model_1_1_address_information_v2.html#abe9e6fd2adb7c148bb8204ab992c71b5',
        1,
        'DocuSign.eSign.Model.AddressInformationV2.AddressInformationV2()',
      ],
      [
        '../class_docu_sign_1_1e_sign_1_1_model_1_1_address_information_v2.html#ae01efdccd90126fb061eb35c320c4133',
        1,
        'DocuSign.eSign.Model.AddressInformationV2.AddressInformationV2(string Address1=default(string), string Address2=default(string), string City=default(string), string Country=default(string), string Fax=default(string), string Phone=default(string), string PostalCode=default(string), string StateOrProvince=default(string))',
      ],
    ],
  ],
  [
    'adminmessage',
    [
      'AdminMessage',
      [
        '../class_docu_sign_1_1e_sign_1_1_model_1_1_admin_message.html#a3266e05182ad8e5b7a740d0fc8734938',
        1,
        'DocuSign.eSign.Model.AdminMessage.AdminMessage()',
      ],
      [
        '../class_docu_sign_1_1e_sign_1_1_model_1_1_admin_message.html#af4be12a81582cf66caa928dc7be04f97',
        1,
        'DocuSign.eSign.Model.AdminMessage.AdminMessage(string BaseMessage=default(string), string MoreInformation=default(string))',
      ],
    ],
  ],
  [
    'agent',
    [
      'Agent',
      [
        '../class_docu_sign_1_1e_sign_1_1_model_1_1_agent.html#aa554a7a0371f866fb8246a4863271ce9',
        1,
        'DocuSign.eSign.Model.Agent.Agent()',
      ],
      [
        '../class_docu_sign_1_1e_sign_1_1_model_1_1_agent.html#a71355c21eb71c860f2307eae634419f7',
        1,
        'DocuSign.eSign.Model.Agent.Agent(string AccessCode=default(string), PropertyMetadata AccessCodeMetadata=default(PropertyMetadata), string AddAccessCodeToEmail=default(string), List&lt; RecipientAdditionalNotification &gt; AdditionalNotifications=default(List&lt; RecipientAdditionalNotification &gt;), string AllowSystemOverrideForLockedRecipient=default(string), string ClientUserId=default(string), string CompletedCount=default(string), List&lt; string &gt; CustomFields=default(List&lt; string &gt;), string DeclinedDateTime=default(string), string DeclinedReason=default(string), string DeliveredDateTime=default(string), string DeliveryMethod=default(string), PropertyMetadata DeliveryMethodMetadata=default(PropertyMetadata), string DesignatorId=default(string), string DesignatorIdGuid=default(string), List&lt; DocumentVisibility &gt; DocumentVisibility=default(List&lt; DocumentVisibility &gt;), string Email=default(string), PropertyMetadata EmailMetadata=default(PropertyMetadata), RecipientEmailNotification EmailNotification=default(RecipientEmailNotification), string EmbeddedRecipientStartURL=default(string), ErrorDetails ErrorDetails=default(ErrorDetails), List&lt; string &gt; ExcludedDocuments=default(List&lt; string &gt;), string FaxNumber=default(string), PropertyMetadata FaxNumberMetadata=default(PropertyMetadata), string FirstName=default(string), PropertyMetadata FirstNameMetadata=default(PropertyMetadata), string FullName=default(string), PropertyMetadata FullNameMetadata=default(PropertyMetadata), string IdCheckConfigurationName=default(string), PropertyMetadata IdCheckConfigurationNameMetadata=default(PropertyMetadata), IdCheckInformationInput IdCheckInformationInput=default(IdCheckInformationInput), RecipientIdentityVerification IdentityVerification=default(RecipientIdentityVerification), string InheritEmailNotificationConfiguration=default(string), string LastName=default(string), PropertyMetadata LastNameMetadata=default(PropertyMetadata), string LockedRecipientPhoneAuthEditable=default(string), string LockedRecipientSmsEditable=default(string), string Name=default(string), PropertyMetadata NameMetadata=default(PropertyMetadata), string Note=default(string), PropertyMetadata NoteMetadata=default(PropertyMetadata), RecipientPhoneAuthentication PhoneAuthentication=default(RecipientPhoneAuthentication), List&lt; RecipientAttachment &gt; RecipientAttachments=default(List&lt; RecipientAttachment &gt;), AuthenticationStatus RecipientAuthenticationStatus=default(AuthenticationStatus), List&lt; FeatureAvailableMetadata &gt; RecipientFeatureMetadata=default(List&lt; FeatureAvailableMetadata &gt;), string RecipientId=default(string), string RecipientIdGuid=default(string), string RecipientType=default(string), PropertyMetadata RecipientTypeMetadata=default(PropertyMetadata), string RequireIdLookup=default(string), PropertyMetadata RequireIdLookupMetadata=default(PropertyMetadata), string RoleName=default(string), string RoutingOrder=default(string), PropertyMetadata RoutingOrderMetadata=default(PropertyMetadata), string SentDateTime=default(string), string SignedDateTime=default(string), string SigningGroupId=default(string), PropertyMetadata SigningGroupIdMetadata=default(PropertyMetadata), string SigningGroupName=default(string), List&lt; UserInfo &gt; SigningGroupUsers=default(List&lt; UserInfo &gt;), RecipientSMSAuthentication SmsAuthentication=default(RecipientSMSAuthentication), List&lt; SocialAuthentication &gt; SocialAuthentications=default(List&lt; SocialAuthentication &gt;), string Status=default(string), string StatusCode=default(string), string SuppressEmails=default(string), string TemplateLocked=default(string), string TemplateRequired=default(string), string TotalTabCount=default(string), string UserId=default(string))',
      ],
    ],
  ],
  [
    'apiclient',
    [
      'ApiClient',
      [
        '../class_docu_sign_1_1e_sign_1_1_client_1_1_api_client.html#a22206212f8ac49ce4102ef949cec2e0d',
        1,
        'DocuSign.eSign.Client.ApiClient.ApiClient()',
      ],
      [
        '../class_docu_sign_1_1e_sign_1_1_client_1_1_api_client.html#ae7c25e0df10f6fa80962af620ee09e4e',
        1,
        'DocuSign.eSign.Client.ApiClient.ApiClient(Configuration config)',
      ],
      [
        '../class_docu_sign_1_1e_sign_1_1_client_1_1_api_client.html#a6dad3b0988a109ba129797feeb4c93c7',
        1,
        'DocuSign.eSign.Client.ApiClient.ApiClient(String basePath=&quot;https://www.docusign.net/restapi&quot;, WebProxy proxy=null)',
      ],
      [
        '../class_docu_sign_1_1e_sign_1_1_client_1_1_api_client.html#a1835c72f8c2a33d8d28a57a66467089d',
        1,
        'DocuSign.eSign.Client.ApiClient.ApiClient(String basePath, String oAuthBasePath, WebProxy proxy=null)',
      ],
    ],
  ],
  [
    'apiexception',
    [
      'ApiException',
      [
        '../class_docu_sign_1_1e_sign_1_1_client_1_1_api_exception.html#a956067e15f75086249ac20d1808445c1',
        1,
        'DocuSign.eSign.Client.ApiException.ApiException()',
      ],
      [
        '../class_docu_sign_1_1e_sign_1_1_client_1_1_api_exception.html#a66561a93e1d04cfbab9033b70ce310a0',
        1,
        'DocuSign.eSign.Client.ApiException.ApiException(int errorCode, string message)',
      ],
      [
        '../class_docu_sign_1_1e_sign_1_1_client_1_1_api_exception.html#af37711b9f1784cca5535ced7fa942db9',
        1,
        'DocuSign.eSign.Client.ApiException.ApiException(int errorCode, string message, dynamic errorContent=null)',
      ],
    ],
  ],
  [
    'apirequestlog',
    [
      'ApiRequestLog',
      [
        '../class_docu_sign_1_1e_sign_1_1_model_1_1_api_request_log.html#ae0da7c2aaef36eacd317f827666bd1b6',
        1,
        'DocuSign.eSign.Model.ApiRequestLog.ApiRequestLog()',
      ],
      [
        '../class_docu_sign_1_1e_sign_1_1_model_1_1_api_request_log.html#a6f78bbd62a3caa1ec98c5b9ce9d62b15',
        1,
        'DocuSign.eSign.Model.ApiRequestLog.ApiRequestLog(string CreatedDateTime=default(string), string Description=default(string), string RequestLogId=default(string), string Status=default(string))',
      ],
    ],
  ],
  [
    'apirequestlogsresult',
    [
      'ApiRequestLogsResult',
      [
        '../class_docu_sign_1_1e_sign_1_1_model_1_1_api_request_logs_result.html#a923b6de83bbfb2e79c0b329c104bf33c',
        1,
        'DocuSign.eSign.Model.ApiRequestLogsResult.ApiRequestLogsResult()',
      ],
      [
        '../class_docu_sign_1_1e_sign_1_1_model_1_1_api_request_logs_result.html#aeb67b73f60356bb0782134a8fdf0dc85',
        1,
        'DocuSign.eSign.Model.ApiRequestLogsResult.ApiRequestLogsResult(List&lt; ApiRequestLog &gt; ApiRequestLogs=default(List&lt; ApiRequestLog &gt;))',
      ],
    ],
  ],
  [
    'apiresponse',
    [
      'ApiResponse',
      [
        '../class_docu_sign_1_1e_sign_1_1_client_1_1_api_response_3_01_t_01_4.html#a151e8c30b932a2704e0e318d3ce45978',
        1,
        'DocuSign::eSign::Client::ApiResponse&lt; T &gt;',
      ],
    ],
  ],
  [
    'applytemplate',
    [
      'ApplyTemplate',
      [
        '../interface_docu_sign_1_1e_sign_1_1_api_1_1_i_envelopes_api.html#aa31a85553570e02073ae8358ae530fe1',
        1,
        'DocuSign.eSign.Api.IEnvelopesApi.ApplyTemplate()',
      ],
      [
        '../class_docu_sign_1_1e_sign_1_1_api_1_1_envelopes_api.html#a86353bb47ae6e00f8e164d17c8caacd3',
        1,
        'DocuSign.eSign.Api.EnvelopesApi.ApplyTemplate()',
      ],
    ],
  ],
  [
    'applytemplateasync',
    [
      'ApplyTemplateAsync',
      [
        '../interface_docu_sign_1_1e_sign_1_1_api_1_1_i_envelopes_api.html#aec5b37660c1770fbf413289507ccf446',
        1,
        'DocuSign.eSign.Api.IEnvelopesApi.ApplyTemplateAsync()',
      ],
      [
        '../class_docu_sign_1_1e_sign_1_1_api_1_1_envelopes_api.html#a216a64429a221e3ef91e30d33761b702',
        1,
        'DocuSign.eSign.Api.EnvelopesApi.ApplyTemplateAsync()',
      ],
    ],
  ],
  [
    'applytemplateasyncwithhttpinfo',
    [
      'ApplyTemplateAsyncWithHttpInfo',
      [
        '../interface_docu_sign_1_1e_sign_1_1_api_1_1_i_envelopes_api.html#a8c1a2f418677e093a8bbb4207b855a75',
        1,
        'DocuSign.eSign.Api.IEnvelopesApi.ApplyTemplateAsyncWithHttpInfo()',
      ],
      [
        '../class_docu_sign_1_1e_sign_1_1_api_1_1_envelopes_api.html#ad5ae959fb604156b6daa2da40b1d9e7d',
        1,
        'DocuSign.eSign.Api.EnvelopesApi.ApplyTemplateAsyncWithHttpInfo()',
      ],
    ],
  ],
  [
    'applytemplatetodocument',
    [
      'ApplyTemplateToDocument',
      [
        '../interface_docu_sign_1_1e_sign_1_1_api_1_1_i_envelopes_api.html#ad3f0f94ca48ab695ba0f41c8c97c60db',
        1,
        'DocuSign.eSign.Api.IEnvelopesApi.ApplyTemplateToDocument()',
      ],
      [
        '../class_docu_sign_1_1e_sign_1_1_api_1_1_envelopes_api.html#ac559db0d177094d4f15f0a8aa8943933',
        1,
        'DocuSign.eSign.Api.EnvelopesApi.ApplyTemplateToDocument()',
      ],
    ],
  ],
  [
    'applytemplatetodocumentasync',
    [
      'ApplyTemplateToDocumentAsync',
      [
        '../interface_docu_sign_1_1e_sign_1_1_api_1_1_i_envelopes_api.html#a94e4737e642a20a961f4270f2c79adab',
        1,
        'DocuSign.eSign.Api.IEnvelopesApi.ApplyTemplateToDocumentAsync()',
      ],
      [
        '../class_docu_sign_1_1e_sign_1_1_api_1_1_envelopes_api.html#aa12b807c7c8a537b2e075a9cccefeaf0',
        1,
        'DocuSign.eSign.Api.EnvelopesApi.ApplyTemplateToDocumentAsync()',
      ],
    ],
  ],
  [
    'applytemplatetodocumentasyncwithhttpinfo',
    [
      'ApplyTemplateToDocumentAsyncWithHttpInfo',
      [
        '../interface_docu_sign_1_1e_sign_1_1_api_1_1_i_envelopes_api.html#ac5c12a8770b0a0c36f2425fecc808a94',
        1,
        'DocuSign.eSign.Api.IEnvelopesApi.ApplyTemplateToDocumentAsyncWithHttpInfo()',
      ],
      [
        '../class_docu_sign_1_1e_sign_1_1_api_1_1_envelopes_api.html#a4adec69cf6db49f830e38390a5b5d3cd',
        1,
        'DocuSign.eSign.Api.EnvelopesApi.ApplyTemplateToDocumentAsyncWithHttpInfo()',
      ],
    ],
  ],
  [
    'applytemplatetodocumentwithhttpinfo',
    [
      'ApplyTemplateToDocumentWithHttpInfo',
      [
        '../interface_docu_sign_1_1e_sign_1_1_api_1_1_i_envelopes_api.html#aa3ef8e1677403d82341fbdd1bdc9a3ef',
        1,
        'DocuSign.eSign.Api.IEnvelopesApi.ApplyTemplateToDocumentWithHttpInfo()',
      ],
      [
        '../class_docu_sign_1_1e_sign_1_1_api_1_1_envelopes_api.html#a65298d166f134c1ffb12f452cbe3dfdd',
        1,
        'DocuSign.eSign.Api.EnvelopesApi.ApplyTemplateToDocumentWithHttpInfo()',
      ],
    ],
  ],
  [
    'applytemplatewithhttpinfo',
    [
      'ApplyTemplateWithHttpInfo',
      [
        '../interface_docu_sign_1_1e_sign_1_1_api_1_1_i_envelopes_api.html#ad6c2ab87c8406104886a118a2e71d9d3',
        1,
        'DocuSign.eSign.Api.IEnvelopesApi.ApplyTemplateWithHttpInfo()',
      ],
      [
        '../class_docu_sign_1_1e_sign_1_1_api_1_1_envelopes_api.html#a28a3903428f00165f23a47863905283a',
        1,
        'DocuSign.eSign.Api.EnvelopesApi.ApplyTemplateWithHttpInfo()',
      ],
    ],
  ],
  [
    'approve',
    [
      'Approve',
      [
        '../class_docu_sign_1_1e_sign_1_1_model_1_1_approve.html#a2338a6ed4523bd68a1313619272160a7',
        1,
        'DocuSign.eSign.Model.Approve.Approve()',
      ],
      [
        '../class_docu_sign_1_1e_sign_1_1_model_1_1_approve.html#a561cfb74840237ba03260cec86bbe442',
        1,
        'DocuSign.eSign.Model.Approve.Approve(string AnchorAllowWhiteSpaceInCharacters=default(string), PropertyMetadata AnchorAllowWhiteSpaceInCharactersMetadata=default(PropertyMetadata), string AnchorCaseSensitive=default(string), PropertyMetadata AnchorCaseSensitiveMetadata=default(PropertyMetadata), string AnchorHorizontalAlignment=default(string), PropertyMetadata AnchorHorizontalAlignmentMetadata=default(PropertyMetadata), string AnchorIgnoreIfNotPresent=default(string), PropertyMetadata AnchorIgnoreIfNotPresentMetadata=default(PropertyMetadata), string AnchorMatchWholeWord=default(string), PropertyMetadata AnchorMatchWholeWordMetadata=default(PropertyMetadata), string AnchorString=default(string), PropertyMetadata AnchorStringMetadata=default(PropertyMetadata), string AnchorTabProcessorVersion=default(string), PropertyMetadata AnchorTabProcessorVersionMetadata=default(PropertyMetadata), string AnchorUnits=default(string), PropertyMetadata AnchorUnitsMetadata=default(PropertyMetadata), string AnchorXOffset=default(string), PropertyMetadata AnchorXOffsetMetadata=default(PropertyMetadata), string AnchorYOffset=default(string), PropertyMetadata AnchorYOffsetMetadata=default(PropertyMetadata), string Bold=default(string), PropertyMetadata BoldMetadata=default(PropertyMetadata), string ButtonText=default(string), PropertyMetadata ButtonTextMetadata=default(PropertyMetadata), string ConditionalParentLabel=default(string), PropertyMetadata ConditionalParentLabelMetadata=default(PropertyMetadata), string ConditionalParentValue=default(string), PropertyMetadata ConditionalParentValueMetadata=default(PropertyMetadata), string CustomTabId=default(string), PropertyMetadata CustomTabIdMetadata=default(PropertyMetadata), string DocumentId=default(string), PropertyMetadata DocumentIdMetadata=default(PropertyMetadata), ErrorDetails ErrorDetails=default(ErrorDetails), string Font=default(string), string FontColor=default(string), PropertyMetadata FontColorMetadata=default(PropertyMetadata), PropertyMetadata FontMetadata=default(PropertyMetadata), string FontSize=default(string), PropertyMetadata FontSizeMetadata=default(PropertyMetadata), string FormOrder=default(string), PropertyMetadata FormOrderMetadata=default(PropertyMetadata), string FormPageLabel=default(string), PropertyMetadata FormPageLabelMetadata=default(PropertyMetadata), string FormPageNumber=default(string), PropertyMetadata FormPageNumberMetadata=default(PropertyMetadata), string Height=default(string), PropertyMetadata HeightMetadata=default(PropertyMetadata), string Italic=default(string), PropertyMetadata ItalicMetadata=default(PropertyMetadata), LocalePolicyTab LocalePolicy=default(LocalePolicyTab), MergeField MergeField=default(MergeField), string MergeFieldXml=default(string), string PageNumber=default(string), PropertyMetadata PageNumberMetadata=default(PropertyMetadata), string RecipientId=default(string), string RecipientIdGuid=default(string), PropertyMetadata RecipientIdGuidMetadata=default(PropertyMetadata), PropertyMetadata RecipientIdMetadata=default(PropertyMetadata), SmartContractInformation SmartContractInformation=default(SmartContractInformation), string Source=default(string), string Status=default(string), PropertyMetadata StatusMetadata=default(PropertyMetadata), List&lt; string &gt; TabGroupLabels=default(List&lt; string &gt;), PropertyMetadata TabGroupLabelsMetadata=default(PropertyMetadata), string TabId=default(string), PropertyMetadata TabIdMetadata=default(PropertyMetadata), string TabLabel=default(string), PropertyMetadata TabLabelMetadata=default(PropertyMetadata), string TabOrder=default(string), PropertyMetadata TabOrderMetadata=default(PropertyMetadata), string TabType=default(string), PropertyMetadata TabTypeMetadata=default(PropertyMetadata), string TemplateLocked=default(string), PropertyMetadata TemplateLockedMetadata=default(PropertyMetadata), string TemplateRequired=default(string), PropertyMetadata TemplateRequiredMetadata=default(PropertyMetadata), string Tooltip=default(string), PropertyMetadata ToolTipMetadata=default(PropertyMetadata), string Underline=default(string), PropertyMetadata UnderlineMetadata=default(PropertyMetadata), string Width=default(string), PropertyMetadata WidthMetadata=default(PropertyMetadata), string XPosition=default(string), PropertyMetadata XPositionMetadata=default(PropertyMetadata), string YPosition=default(string), PropertyMetadata YPositionMetadata=default(PropertyMetadata))',
      ],
    ],
  ],
  [
    'appstoreproduct',
    [
      'AppStoreProduct',
      [
        '../class_docu_sign_1_1e_sign_1_1_model_1_1_app_store_product.html#ac2cd0589b5db27581bc7ee56574432b3',
        1,
        'DocuSign.eSign.Model.AppStoreProduct.AppStoreProduct()',
      ],
      [
        '../class_docu_sign_1_1e_sign_1_1_model_1_1_app_store_product.html#a834495e2790068b7806a4188b2a0f52c',
        1,
        'DocuSign.eSign.Model.AppStoreProduct.AppStoreProduct(string MarketPlace=default(string), string ProductId=default(string))',
      ],
    ],
  ],
  [
    'appstorereceipt',
    [
      'AppStoreReceipt',
      [
        '../class_docu_sign_1_1e_sign_1_1_model_1_1_app_store_receipt.html#a51c3679719b78dea3cf6c11dddf2e977',
        1,
        'DocuSign.eSign.Model.AppStoreReceipt.AppStoreReceipt()',
      ],
      [
        '../class_docu_sign_1_1e_sign_1_1_model_1_1_app_store_receipt.html#a0ec10619276fb1d44e7c254a65a31dd7',
        1,
        'DocuSign.eSign.Model.AppStoreReceipt.AppStoreReceipt(string ProductId=default(string), string ReceiptData=default(string))',
      ],
    ],
  ],
  [
    'askanadmin',
    [
      'AskAnAdmin',
      [
        '../class_docu_sign_1_1e_sign_1_1_model_1_1_ask_an_admin.html#a55ebc71769efb3654c2490d7e9a283ba',
        1,
        'DocuSign.eSign.Model.AskAnAdmin.AskAnAdmin()',
      ],
      [
        '../class_docu_sign_1_1e_sign_1_1_model_1_1_ask_an_admin.html#ab4aeebc27ae6ac59bbde09f6453a834b',
        1,
        'DocuSign.eSign.Model.AskAnAdmin.AskAnAdmin(string Email=default(string), string Message=default(string), string Name=default(string), string Phone=default(string))',
      ],
    ],
  ],
  [
    'attachment',
    [
      'Attachment',
      [
        '../class_docu_sign_1_1e_sign_1_1_model_1_1_attachment.html#a040c70dbced8ce63c4727b7f997a0db5',
        1,
        'DocuSign.eSign.Model.Attachment.Attachment()',
      ],
      [
        '../class_docu_sign_1_1e_sign_1_1_model_1_1_attachment.html#a5318cfc77c36c0ce8eb48475dc9c3cf5',
        1,
        'DocuSign.eSign.Model.Attachment.Attachment(string AccessControl=default(string), string AttachmentId=default(string), string AttachmentType=default(string), string Data=default(string), string Label=default(string), string Name=default(string), string RemoteUrl=default(string))',
      ],
    ],
  ],
  [
    'authenticationapi',
    [
      'AuthenticationApi',
      [
        '../class_docu_sign_1_1e_sign_1_1_api_1_1_authentication_api.html#a1a85773c378e96d78cd2419ed04dcb06',
        1,
        'DocuSign::eSign::Api::AuthenticationApi',
      ],
    ],
  ],
  [
    'authenticationmethod',
    [
      'AuthenticationMethod',
      [
        '../class_docu_sign_1_1e_sign_1_1_model_1_1_authentication_method.html#afc6c4674656060eaa5aee7ce312a4633',
        1,
        'DocuSign.eSign.Model.AuthenticationMethod.AuthenticationMethod()',
      ],
      [
        '../class_docu_sign_1_1e_sign_1_1_model_1_1_authentication_method.html#a43a13bc4f069ca864024d271b3924ea3',
        1,
        'DocuSign.eSign.Model.AuthenticationMethod.AuthenticationMethod(string AuthenticationType=default(string), string LastProvider=default(string), string LastTimestamp=default(string), string TotalCount=default(string))',
      ],
    ],
  ],
  [
    'authenticationstatus',
    [
      'AuthenticationStatus',
      [
        '../class_docu_sign_1_1e_sign_1_1_model_1_1_authentication_status.html#a84414a25e24017d79146772772b48cdb',
        1,
        'DocuSign.eSign.Model.AuthenticationStatus.AuthenticationStatus()',
      ],
      [
        '../class_docu_sign_1_1e_sign_1_1_model_1_1_authentication_status.html#a6fc9d746bcb4bc91508cad2ae9ebc68e',
        1,
        'DocuSign.eSign.Model.AuthenticationStatus.AuthenticationStatus(EventResult AccessCodeResult=default(EventResult), EventResult AgeVerifyResult=default(EventResult), EventResult AnySocialIDResult=default(EventResult), EventResult FacebookResult=default(EventResult), EventResult GoogleResult=default(EventResult), EventResult IdentityVerificationResult=default(EventResult), EventResult IdLookupResult=default(EventResult), EventResult IdQuestionsResult=default(EventResult), EventResult LinkedinResult=default(EventResult), EventResult LiveIDResult=default(EventResult), EventResult OfacResult=default(EventResult), EventResult OpenIDResult=default(EventResult), EventResult PhoneAuthResult=default(EventResult), EventResult SalesforceResult=default(EventResult), EventResult SignatureProviderResult=default(EventResult), EventResult SmsAuthResult=default(EventResult), EventResult STANPinResult=default(EventResult), EventResult TwitterResult=default(EventResult), EventResult YahooResult=default(EventResult))',
      ],
    ],
  ],
];
