var searchData = [
  [
    'base64encode',
    [
      'Base64Encode',
      [
        '../class_docu_sign_1_1e_sign_1_1_client_1_1_api_client.html#a6acf54cccb427b2c218e2ebb35f30456',
        1,
        'DocuSign::eSign::Client::ApiClient',
      ],
    ],
  ],
  [
    'bccemailaddress',
    [
      'BccEmailAddress',
      [
        '../class_docu_sign_1_1e_sign_1_1_model_1_1_bcc_email_address.html#a45c644b3daad9b6fada4eafc44fa1f3b',
        1,
        'DocuSign.eSign.Model.BccEmailAddress.BccEmailAddress()',
      ],
      [
        '../class_docu_sign_1_1e_sign_1_1_model_1_1_bcc_email_address.html#aad656123b36a701603e085058854b494',
        1,
        'DocuSign.eSign.Model.BccEmailAddress.BccEmailAddress(string BccEmailAddressId=default(string), string Email=default(string))',
      ],
    ],
  ],
  [
    'bccemailarchive',
    [
      'BccEmailArchive',
      [
        '../class_docu_sign_1_1e_sign_1_1_model_1_1_bcc_email_archive.html#af553fa5f559389f8ba57f1a533dc5e20',
        1,
        'DocuSign.eSign.Model.BccEmailArchive.BccEmailArchive()',
      ],
      [
        '../class_docu_sign_1_1e_sign_1_1_model_1_1_bcc_email_archive.html#a8adc74824fbf20b52a07c70189de9024',
        1,
        'DocuSign.eSign.Model.BccEmailArchive.BccEmailArchive(string AccountId=default(string), string BccEmailArchiveId=default(string), string Created=default(string), UserInfo CreatedBy=default(UserInfo), string Email=default(string), string EmailNotificationId=default(string), string Modified=default(string), UserInfo ModifiedBy=default(UserInfo), string Status=default(string), string Uri=default(string))',
      ],
    ],
  ],
  [
    'bccemailarchivehistory',
    [
      'BccEmailArchiveHistory',
      [
        '../class_docu_sign_1_1e_sign_1_1_model_1_1_bcc_email_archive_history.html#a08868fb539930928c82da079dd110d30',
        1,
        'DocuSign.eSign.Model.BccEmailArchiveHistory.BccEmailArchiveHistory()',
      ],
      [
        '../class_docu_sign_1_1e_sign_1_1_model_1_1_bcc_email_archive_history.html#aaaf2e245055ee3758ddbeb65e50fde7d',
        1,
        'DocuSign.eSign.Model.BccEmailArchiveHistory.BccEmailArchiveHistory(string AccountId=default(string), string Action=default(string), string Email=default(string), string Modified=default(string), UserInfo ModifiedBy=default(UserInfo), string Status=default(string))',
      ],
    ],
  ],
  [
    'bccemailarchivehistorylist',
    [
      'BccEmailArchiveHistoryList',
      [
        '../class_docu_sign_1_1e_sign_1_1_model_1_1_bcc_email_archive_history_list.html#ae956c6e8e598a0bdb4291cac8468e099',
        1,
        'DocuSign.eSign.Model.BccEmailArchiveHistoryList.BccEmailArchiveHistoryList()',
      ],
      [
        '../class_docu_sign_1_1e_sign_1_1_model_1_1_bcc_email_archive_history_list.html#a49b6af1c7d5ae9520790a3122993eefa',
        1,
        'DocuSign.eSign.Model.BccEmailArchiveHistoryList.BccEmailArchiveHistoryList(List&lt; BccEmailArchiveHistory &gt; BccEmailArchiveHistory=default(List&lt; BccEmailArchiveHistory &gt;), string EndPosition=default(string), string NextUri=default(string), string PreviousUri=default(string), string ResultSetSize=default(string), string StartPosition=default(string), string TotalSetSize=default(string))',
      ],
    ],
  ],
  [
    'bccemailarchivelist',
    [
      'BccEmailArchiveList',
      [
        '../class_docu_sign_1_1e_sign_1_1_model_1_1_bcc_email_archive_list.html#aca655b7120479d557063533c20ba9468',
        1,
        'DocuSign.eSign.Model.BccEmailArchiveList.BccEmailArchiveList()',
      ],
      [
        '../class_docu_sign_1_1e_sign_1_1_model_1_1_bcc_email_archive_list.html#ad47096cd77e4cfb0948780aea680f29b',
        1,
        'DocuSign.eSign.Model.BccEmailArchiveList.BccEmailArchiveList(List&lt; BccEmailArchive &gt; BccEmailArchives=default(List&lt; BccEmailArchive &gt;), string EndPosition=default(string), string NextUri=default(string), string PreviousUri=default(string), string ResultSetSize=default(string), string StartPosition=default(string), string TotalSetSize=default(string))',
      ],
    ],
  ],
  [
    'billingapi',
    [
      'BillingApi',
      [
        '../class_docu_sign_1_1e_sign_1_1_api_1_1_billing_api.html#a40bfb00ea52fa0735e3638b56662d882',
        1,
        'DocuSign::eSign::Api::BillingApi',
      ],
    ],
  ],
  [
    'billingcharge',
    [
      'BillingCharge',
      [
        '../class_docu_sign_1_1e_sign_1_1_model_1_1_billing_charge.html#adb1720660646266146b63804703745b8',
        1,
        'DocuSign.eSign.Model.BillingCharge.BillingCharge()',
      ],
      [
        '../class_docu_sign_1_1e_sign_1_1_model_1_1_billing_charge.html#a43f9b7209cb0940fec2d5a9b6be90b00',
        1,
        'DocuSign.eSign.Model.BillingCharge.BillingCharge(string AllowedQuantity=default(string), string Blocked=default(string), string ChargeName=default(string), string ChargeType=default(string), string ChargeUnitOfMeasure=default(string), List&lt; BillingDiscount &gt; Discounts=default(List&lt; BillingDiscount &gt;), string FirstEffectiveDate=default(string), string IncludedQuantity=default(string), string IncrementalQuantity=default(string), string LastEffectiveDate=default(string), List&lt; BillingPrice &gt; Prices=default(List&lt; BillingPrice &gt;), string UnitPrice=default(string), string UsedQuantity=default(string))',
      ],
    ],
  ],
  [
    'billingchargeresponse',
    [
      'BillingChargeResponse',
      [
        '../class_docu_sign_1_1e_sign_1_1_model_1_1_billing_charge_response.html#a4d44989c778173534b9d6ba064b5214b',
        1,
        'DocuSign.eSign.Model.BillingChargeResponse.BillingChargeResponse()',
      ],
      [
        '../class_docu_sign_1_1e_sign_1_1_model_1_1_billing_charge_response.html#a43797e8f1f2cde8c648706c15cf6a263',
        1,
        'DocuSign.eSign.Model.BillingChargeResponse.BillingChargeResponse(List&lt; BillingCharge &gt; BillingChargeItems=default(List&lt; BillingCharge &gt;))',
      ],
    ],
  ],
  [
    'billingdiscount',
    [
      'BillingDiscount',
      [
        '../class_docu_sign_1_1e_sign_1_1_model_1_1_billing_discount.html#a4b1a1e5c1ca6f03a7db7074060c626fe',
        1,
        'DocuSign.eSign.Model.BillingDiscount.BillingDiscount()',
      ],
      [
        '../class_docu_sign_1_1e_sign_1_1_model_1_1_billing_discount.html#aa6de7ab4452991bc56970b03419bbbbd',
        1,
        'DocuSign.eSign.Model.BillingDiscount.BillingDiscount(string BeginQuantity=default(string), string Discount=default(string), string EndQuantity=default(string))',
      ],
    ],
  ],
  [
    'billinginvoice',
    [
      'BillingInvoice',
      [
        '../class_docu_sign_1_1e_sign_1_1_model_1_1_billing_invoice.html#add9eba38cfc09b09ac5b40bce8b6168c',
        1,
        'DocuSign.eSign.Model.BillingInvoice.BillingInvoice()',
      ],
      [
        '../class_docu_sign_1_1e_sign_1_1_model_1_1_billing_invoice.html#a223ae0678073e6c401eb44566f8e36ff',
        1,
        'DocuSign.eSign.Model.BillingInvoice.BillingInvoice(string Amount=default(string), string Balance=default(string), string DueDate=default(string), string InvoiceId=default(string), List&lt; BillingInvoiceItem &gt; InvoiceItems=default(List&lt; BillingInvoiceItem &gt;), string InvoiceNumber=default(string), string InvoiceUri=default(string), string NonTaxableAmount=default(string), string PdfAvailable=default(string), string TaxableAmount=default(string))',
      ],
    ],
  ],
  [
    'billinginvoiceitem',
    [
      'BillingInvoiceItem',
      [
        '../class_docu_sign_1_1e_sign_1_1_model_1_1_billing_invoice_item.html#a61630a395baf1da89ecc301553827045',
        1,
        'DocuSign.eSign.Model.BillingInvoiceItem.BillingInvoiceItem()',
      ],
      [
        '../class_docu_sign_1_1e_sign_1_1_model_1_1_billing_invoice_item.html#a00977d8e7b934aa256ffb8f97fed6f0c',
        1,
        'DocuSign.eSign.Model.BillingInvoiceItem.BillingInvoiceItem(string ChargeAmount=default(string), string ChargeName=default(string), string InvoiceItemId=default(string), string Quantity=default(string), string UnitPrice=default(string))',
      ],
    ],
  ],
  [
    'billinginvoicesresponse',
    [
      'BillingInvoicesResponse',
      [
        '../class_docu_sign_1_1e_sign_1_1_model_1_1_billing_invoices_response.html#afed2d88fc8bed0d098c0e8376fc3e773',
        1,
        'DocuSign.eSign.Model.BillingInvoicesResponse.BillingInvoicesResponse()',
      ],
      [
        '../class_docu_sign_1_1e_sign_1_1_model_1_1_billing_invoices_response.html#a590daf39b0c213779dbb8cfff6b1ec0e',
        1,
        'DocuSign.eSign.Model.BillingInvoicesResponse.BillingInvoicesResponse(List&lt; BillingInvoice &gt; BillingInvoices=default(List&lt; BillingInvoice &gt;), string NextUri=default(string), string PreviousUri=default(string))',
      ],
    ],
  ],
  [
    'billinginvoicessummary',
    [
      'BillingInvoicesSummary',
      [
        '../class_docu_sign_1_1e_sign_1_1_model_1_1_billing_invoices_summary.html#a1eeaa42e8ec7a21263e3788723363f90',
        1,
        'DocuSign.eSign.Model.BillingInvoicesSummary.BillingInvoicesSummary()',
      ],
      [
        '../class_docu_sign_1_1e_sign_1_1_model_1_1_billing_invoices_summary.html#a4405e14be51a371cb6fdc70ace5c521c',
        1,
        'DocuSign.eSign.Model.BillingInvoicesSummary.BillingInvoicesSummary(List&lt; BillingInvoice &gt; BillingInvoices=default(List&lt; BillingInvoice &gt;), string PastDueBalance=default(string), string PaymentAllowed=default(string))',
      ],
    ],
  ],
  [
    'billingpayment',
    [
      'BillingPayment',
      [
        '../class_docu_sign_1_1e_sign_1_1_model_1_1_billing_payment.html#ad9c4f181c894bdd685f323d7e0d2eb14',
        1,
        'DocuSign.eSign.Model.BillingPayment.BillingPayment()',
      ],
      [
        '../class_docu_sign_1_1e_sign_1_1_model_1_1_billing_payment.html#ab76ef3f662c8810b1c822273a769191b',
        1,
        'DocuSign.eSign.Model.BillingPayment.BillingPayment(string Amount=default(string), string InvoiceId=default(string), string PaymentId=default(string))',
      ],
    ],
  ],
  [
    'billingpaymentitem',
    [
      'BillingPaymentItem',
      [
        '../class_docu_sign_1_1e_sign_1_1_model_1_1_billing_payment_item.html#a792ccc6405fc23143c2cb5edd53aa8ac',
        1,
        'DocuSign.eSign.Model.BillingPaymentItem.BillingPaymentItem()',
      ],
      [
        '../class_docu_sign_1_1e_sign_1_1_model_1_1_billing_payment_item.html#a35ffa9c52a5603fd54c9a52cf4fcc363',
        1,
        'DocuSign.eSign.Model.BillingPaymentItem.BillingPaymentItem(string Amount=default(string), string Description=default(string), string PaymentDate=default(string), string PaymentId=default(string), string PaymentNumber=default(string))',
      ],
    ],
  ],
  [
    'billingpaymentrequest',
    [
      'BillingPaymentRequest',
      [
        '../class_docu_sign_1_1e_sign_1_1_model_1_1_billing_payment_request.html#ad8d1ac9d6f98b62d7ee7dc05814b7187',
        1,
        'DocuSign.eSign.Model.BillingPaymentRequest.BillingPaymentRequest()',
      ],
      [
        '../class_docu_sign_1_1e_sign_1_1_model_1_1_billing_payment_request.html#aadcb8827360621262d3c13d37128aedc',
        1,
        'DocuSign.eSign.Model.BillingPaymentRequest.BillingPaymentRequest(string PaymentAmount=default(string))',
      ],
    ],
  ],
  [
    'billingpaymentresponse',
    [
      'BillingPaymentResponse',
      [
        '../class_docu_sign_1_1e_sign_1_1_model_1_1_billing_payment_response.html#aaecd7408f7fe00082da5e3838dd52ff6',
        1,
        'DocuSign.eSign.Model.BillingPaymentResponse.BillingPaymentResponse()',
      ],
      [
        '../class_docu_sign_1_1e_sign_1_1_model_1_1_billing_payment_response.html#a156d5444dcc5be7610d05544c896b667',
        1,
        'DocuSign.eSign.Model.BillingPaymentResponse.BillingPaymentResponse(List&lt; BillingPayment &gt; BillingPayments=default(List&lt; BillingPayment &gt;))',
      ],
    ],
  ],
  [
    'billingpaymentsresponse',
    [
      'BillingPaymentsResponse',
      [
        '../class_docu_sign_1_1e_sign_1_1_model_1_1_billing_payments_response.html#af6a31245ba734fb19a3956d26c115793',
        1,
        'DocuSign.eSign.Model.BillingPaymentsResponse.BillingPaymentsResponse()',
      ],
      [
        '../class_docu_sign_1_1e_sign_1_1_model_1_1_billing_payments_response.html#a9d9afb46848dddabadf3a3e7dcb93358',
        1,
        'DocuSign.eSign.Model.BillingPaymentsResponse.BillingPaymentsResponse(List&lt; BillingPaymentItem &gt; BillingPayments=default(List&lt; BillingPaymentItem &gt;), string NextUri=default(string), string PreviousUri=default(string))',
      ],
    ],
  ],
  [
    'billingplan',
    [
      'BillingPlan',
      [
        '../class_docu_sign_1_1e_sign_1_1_model_1_1_billing_plan.html#a4915978dac78cb4e29aa8ec04583e90e',
        1,
        'DocuSign.eSign.Model.BillingPlan.BillingPlan()',
      ],
      [
        '../class_docu_sign_1_1e_sign_1_1_model_1_1_billing_plan.html#ad0840210d6bca71331548d4e16b47136',
        1,
        'DocuSign.eSign.Model.BillingPlan.BillingPlan(List&lt; AppStoreProduct &gt; AppStoreProducts=default(List&lt; AppStoreProduct &gt;), List&lt; CurrencyPlanPrice &gt; CurrencyPlanPrices=default(List&lt; CurrencyPlanPrice &gt;), string EnableSupport=default(string), string IncludedSeats=default(string), string OtherDiscountPercent=default(string), string PaymentCycle=default(string), string PaymentMethod=default(string), string PerSeatPrice=default(string), string PlanClassification=default(string), List&lt; FeatureSet &gt; PlanFeatureSets=default(List&lt; FeatureSet &gt;), string PlanId=default(string), string PlanName=default(string), List&lt; SeatDiscount &gt; SeatDiscounts=default(List&lt; SeatDiscount &gt;), string SupportIncidentFee=default(string), string SupportPlanFee=default(string))',
      ],
    ],
  ],
  [
    'billingplaninformation',
    [
      'BillingPlanInformation',
      [
        '../class_docu_sign_1_1e_sign_1_1_model_1_1_billing_plan_information.html#aebe725ca483621bcea33a2954f1b3fa3',
        1,
        'DocuSign.eSign.Model.BillingPlanInformation.BillingPlanInformation()',
      ],
      [
        '../class_docu_sign_1_1e_sign_1_1_model_1_1_billing_plan_information.html#aac612b1da93000e523a11997e5dbff8a',
        1,
        'DocuSign.eSign.Model.BillingPlanInformation.BillingPlanInformation(AppStoreReceipt AppStoreReceipt=default(AppStoreReceipt), AccountAddress BillingAddress=default(AccountAddress), CreditCardInformation CreditCardInformation=default(CreditCardInformation), DirectDebitProcessorInformation DirectDebitProcessorInformation=default(DirectDebitProcessorInformation), string DowngradeReason=default(string), string EnableSupport=default(string), string IncludedSeats=default(string), string IncrementalSeats=default(string), string PaymentMethod=default(string), PaymentProcessorInformation PaymentProcessorInformation=default(PaymentProcessorInformation), PlanInformation PlanInformation=default(PlanInformation), ReferralInformation ReferralInformation=default(ReferralInformation), string RenewalStatus=default(string), string SaleDiscountAmount=default(string), string SaleDiscountFixedAmount=default(string), string SaleDiscountPercent=default(string), string SaleDiscountPeriods=default(string), string SaleDiscountSeatPriceOverride=default(string))',
      ],
    ],
  ],
  [
    'billingplanpreview',
    [
      'BillingPlanPreview',
      [
        '../class_docu_sign_1_1e_sign_1_1_model_1_1_billing_plan_preview.html#a577318688485eb4732e15ceba47863ff',
        1,
        'DocuSign.eSign.Model.BillingPlanPreview.BillingPlanPreview()',
      ],
      [
        '../class_docu_sign_1_1e_sign_1_1_model_1_1_billing_plan_preview.html#a55f9ddac41260542260f88d10c0bacf2',
        1,
        'DocuSign.eSign.Model.BillingPlanPreview.BillingPlanPreview(string CurrencyCode=default(string), BillingInvoice Invoice=default(BillingInvoice), string IsProrated=default(string), string SubtotalAmount=default(string), string TaxAmount=default(string), string TotalAmount=default(string))',
      ],
    ],
  ],
  [
    'billingplanresponse',
    [
      'BillingPlanResponse',
      [
        '../class_docu_sign_1_1e_sign_1_1_model_1_1_billing_plan_response.html#a4e738b32539c195ccd784a2628086d7b',
        1,
        'DocuSign.eSign.Model.BillingPlanResponse.BillingPlanResponse()',
      ],
      [
        '../class_docu_sign_1_1e_sign_1_1_model_1_1_billing_plan_response.html#a8ea135ca3f54650624e250839db91fcd',
        1,
        'DocuSign.eSign.Model.BillingPlanResponse.BillingPlanResponse(BillingPlan BillingPlan=default(BillingPlan), List&lt; BillingPlan &gt; SuccessorPlans=default(List&lt; BillingPlan &gt;))',
      ],
    ],
  ],
  [
    'billingplansresponse',
    [
      'BillingPlansResponse',
      [
        '../class_docu_sign_1_1e_sign_1_1_model_1_1_billing_plans_response.html#a93ecdd5087518128ef8042774bfb071e',
        1,
        'DocuSign.eSign.Model.BillingPlansResponse.BillingPlansResponse()',
      ],
      [
        '../class_docu_sign_1_1e_sign_1_1_model_1_1_billing_plans_response.html#a1da186a073e159b069c9a877cbfa3fa1',
        1,
        'DocuSign.eSign.Model.BillingPlansResponse.BillingPlansResponse(List&lt; BillingPlan &gt; BillingPlans=default(List&lt; BillingPlan &gt;))',
      ],
    ],
  ],
  [
    'billingplanupdateresponse',
    [
      'BillingPlanUpdateResponse',
      [
        '../class_docu_sign_1_1e_sign_1_1_model_1_1_billing_plan_update_response.html#ab3b1e30030c84d942875bb4fb18f331a',
        1,
        'DocuSign.eSign.Model.BillingPlanUpdateResponse.BillingPlanUpdateResponse()',
      ],
      [
        '../class_docu_sign_1_1e_sign_1_1_model_1_1_billing_plan_update_response.html#a738be3bed3d38ad0beb301befd3737d6',
        1,
        'DocuSign.eSign.Model.BillingPlanUpdateResponse.BillingPlanUpdateResponse(string AccountPaymentMethod=default(string), BillingPlanPreview BillingPlanPreview=default(BillingPlanPreview), string CurrencyCode=default(string), string IncludedSeats=default(string), string PaymentCycle=default(string), string PaymentMethod=default(string), string PlanId=default(string), string PlanName=default(string))',
      ],
    ],
  ],
  [
    'billingprice',
    [
      'BillingPrice',
      [
        '../class_docu_sign_1_1e_sign_1_1_model_1_1_billing_price.html#a67e33cf4338897854e7ad60b71aa215b',
        1,
        'DocuSign.eSign.Model.BillingPrice.BillingPrice()',
      ],
      [
        '../class_docu_sign_1_1e_sign_1_1_model_1_1_billing_price.html#a90ef4b59f1ab4b20500afe398b12ad16',
        1,
        'DocuSign.eSign.Model.BillingPrice.BillingPrice(string BeginQuantity=default(string), string EndQuantity=default(string), string UnitPrice=default(string))',
      ],
    ],
  ],
  [
    'brand',
    [
      'Brand',
      [
        '../class_docu_sign_1_1e_sign_1_1_model_1_1_brand.html#ae5dcd173063ec2f3791d1cdddefa87b6',
        1,
        'DocuSign.eSign.Model.Brand.Brand()',
      ],
      [
        '../class_docu_sign_1_1e_sign_1_1_model_1_1_brand.html#a3cad51c3a696605b293add3446af754c',
        1,
        'DocuSign.eSign.Model.Brand.Brand(string BrandCompany=default(string), string BrandId=default(string), List&lt; string &gt; BrandLanguages=default(List&lt; string &gt;), string BrandName=default(string), List&lt; NameValue &gt; Colors=default(List&lt; NameValue &gt;), string DefaultBrandLanguage=default(string), List&lt; BrandEmailContent &gt; EmailContent=default(List&lt; BrandEmailContent &gt;), ErrorDetails ErrorDetails=default(ErrorDetails), bool?IsOverridingCompanyName=default(bool?), bool?IsSendingDefault=default(bool?), bool?IsSigningDefault=default(bool?), List&lt; NameValue &gt; LandingPages=default(List&lt; NameValue &gt;), List&lt; BrandLink &gt; Links=default(List&lt; BrandLink &gt;), BrandLogos Logos=default(BrandLogos), BrandResourceUrls Resources=default(BrandResourceUrls))',
      ],
    ],
  ],
  [
    'brandemailcontent',
    [
      'BrandEmailContent',
      [
        '../class_docu_sign_1_1e_sign_1_1_model_1_1_brand_email_content.html#aa8145f1c0517599e0484985d3f979b58',
        1,
        'DocuSign.eSign.Model.BrandEmailContent.BrandEmailContent()',
      ],
      [
        '../class_docu_sign_1_1e_sign_1_1_model_1_1_brand_email_content.html#a2e01f63eaa8906485eefe604da62e22e',
        1,
        'DocuSign.eSign.Model.BrandEmailContent.BrandEmailContent(string Content=default(string), string EmailContentType=default(string), string EmailToLink=default(string), string LinkText=default(string))',
      ],
    ],
  ],
  [
    'brandlink',
    [
      'BrandLink',
      [
        '../class_docu_sign_1_1e_sign_1_1_model_1_1_brand_link.html#aa428c705c63c01dfa5766f4cc4a6b375',
        1,
        'DocuSign.eSign.Model.BrandLink.BrandLink()',
      ],
      [
        '../class_docu_sign_1_1e_sign_1_1_model_1_1_brand_link.html#a14f0bec8ad75846eea7cec58b4c7c533',
        1,
        'DocuSign.eSign.Model.BrandLink.BrandLink(string LinkText=default(string), string LinkType=default(string), string ShowLink=default(string), string UrlOrMailTo=default(string))',
      ],
    ],
  ],
  [
    'brandlogos',
    [
      'BrandLogos',
      [
        '../class_docu_sign_1_1e_sign_1_1_model_1_1_brand_logos.html#a3b0b914cdc77f32a92775a0e9183c403',
        1,
        'DocuSign.eSign.Model.BrandLogos.BrandLogos()',
      ],
      [
        '../class_docu_sign_1_1e_sign_1_1_model_1_1_brand_logos.html#a3123922ef98ff988497e035189587af6',
        1,
        'DocuSign.eSign.Model.BrandLogos.BrandLogos(string Email=default(string), string Primary=default(string), string Secondary=default(string))',
      ],
    ],
  ],
  [
    'brandrequest',
    [
      'BrandRequest',
      [
        '../class_docu_sign_1_1e_sign_1_1_model_1_1_brand_request.html#a69af51ac116cbcaf7a597d35bb6f142f',
        1,
        'DocuSign.eSign.Model.BrandRequest.BrandRequest()',
      ],
      [
        '../class_docu_sign_1_1e_sign_1_1_model_1_1_brand_request.html#a1fa551042dafeaebcdc6ddc0b1bf0d5f',
        1,
        'DocuSign.eSign.Model.BrandRequest.BrandRequest(string BrandId=default(string))',
      ],
    ],
  ],
  [
    'brandresources',
    [
      'BrandResources',
      [
        '../class_docu_sign_1_1e_sign_1_1_model_1_1_brand_resources.html#a47e0b7a2f949b3aece757fdbf94c544b',
        1,
        'DocuSign.eSign.Model.BrandResources.BrandResources()',
      ],
      [
        '../class_docu_sign_1_1e_sign_1_1_model_1_1_brand_resources.html#acad39cadea3273552e78985eca74a946',
        1,
        'DocuSign.eSign.Model.BrandResources.BrandResources(UserInfo CreatedByUserInfo=default(UserInfo), string CreatedDate=default(string), List&lt; string &gt; DataNotSavedNotInMaster=default(List&lt; string &gt;), UserInfo ModifiedByUserInfo=default(UserInfo), string ModifiedDate=default(string), List&lt; string &gt; ModifiedTemplates=default(List&lt; string &gt;), string ResourcesContentType=default(string), string ResourcesContentUri=default(string))',
      ],
    ],
  ],
  [
    'brandresourceslist',
    [
      'BrandResourcesList',
      [
        '../class_docu_sign_1_1e_sign_1_1_model_1_1_brand_resources_list.html#a12f8cff2f4235ce4b8e487929e282a01',
        1,
        'DocuSign.eSign.Model.BrandResourcesList.BrandResourcesList()',
      ],
      [
        '../class_docu_sign_1_1e_sign_1_1_model_1_1_brand_resources_list.html#a7ca5f4100c502c5ecc056dc52866ccc3',
        1,
        'DocuSign.eSign.Model.BrandResourcesList.BrandResourcesList(List&lt; BrandResources &gt; ResourcesContentTypes=default(List&lt; BrandResources &gt;))',
      ],
    ],
  ],
  [
    'brandresourceurls',
    [
      'BrandResourceUrls',
      [
        '../class_docu_sign_1_1e_sign_1_1_model_1_1_brand_resource_urls.html#a1dad0f934d03c603241ce4341b88632a',
        1,
        'DocuSign.eSign.Model.BrandResourceUrls.BrandResourceUrls()',
      ],
      [
        '../class_docu_sign_1_1e_sign_1_1_model_1_1_brand_resource_urls.html#a079d4b7583c1fbef550935ef54c70e83',
        1,
        'DocuSign.eSign.Model.BrandResourceUrls.BrandResourceUrls(string Email=default(string), string Sending=default(string), string Signing=default(string), string SigningCaptive=default(string))',
      ],
    ],
  ],
  [
    'brandsrequest',
    [
      'BrandsRequest',
      [
        '../class_docu_sign_1_1e_sign_1_1_model_1_1_brands_request.html#a8dc8d042692f5bad52817f88a1b2d71c',
        1,
        'DocuSign.eSign.Model.BrandsRequest.BrandsRequest()',
      ],
      [
        '../class_docu_sign_1_1e_sign_1_1_model_1_1_brands_request.html#a720787b2e81eb3043fa7e4a85153287d',
        1,
        'DocuSign.eSign.Model.BrandsRequest.BrandsRequest(List&lt; BrandRequest &gt; Brands=default(List&lt; BrandRequest &gt;))',
      ],
    ],
  ],
  [
    'brandsresponse',
    [
      'BrandsResponse',
      [
        '../class_docu_sign_1_1e_sign_1_1_model_1_1_brands_response.html#ab4b223106b3b60648bbf1f5c3fb17011',
        1,
        'DocuSign.eSign.Model.BrandsResponse.BrandsResponse()',
      ],
      [
        '../class_docu_sign_1_1e_sign_1_1_model_1_1_brands_response.html#ad21ed125ca0703609ea3b166b11b4073',
        1,
        'DocuSign.eSign.Model.BrandsResponse.BrandsResponse(List&lt; Brand &gt; Brands=default(List&lt; Brand &gt;), string RecipientBrandIdDefault=default(string), string SenderBrandIdDefault=default(string))',
      ],
    ],
  ],
  [
    'bulkenvelope',
    [
      'BulkEnvelope',
      [
        '../class_docu_sign_1_1e_sign_1_1_model_1_1_bulk_envelope.html#a167d200be78b6485f487f71ba07d8c75',
        1,
        'DocuSign.eSign.Model.BulkEnvelope.BulkEnvelope()',
      ],
      [
        '../class_docu_sign_1_1e_sign_1_1_model_1_1_bulk_envelope.html#aa5b8ff9ffcf162b5f8b5bbfb4807c6c0',
        1,
        'DocuSign.eSign.Model.BulkEnvelope.BulkEnvelope(string BulkRecipientRow=default(string), string BulkStatus=default(string), string Email=default(string), string EnvelopeId=default(string), string EnvelopeUri=default(string), ErrorDetails ErrorDetails=default(ErrorDetails), string Name=default(string), string SubmittedDateTime=default(string), string TransactionId=default(string))',
      ],
    ],
  ],
  [
    'bulkenvelopesapi',
    [
      'BulkEnvelopesApi',
      [
        '../class_docu_sign_1_1e_sign_1_1_api_1_1_bulk_envelopes_api.html#ab3765714ea6c35a3c9dc5f594b54409f',
        1,
        'DocuSign::eSign::Api::BulkEnvelopesApi',
      ],
    ],
  ],
  [
    'bulkenvelopesresponse',
    [
      'BulkEnvelopesResponse',
      [
        '../class_docu_sign_1_1e_sign_1_1_model_1_1_bulk_envelopes_response.html#a86d3cde9ce2c47e4181317ab75f5bf45',
        1,
        'DocuSign.eSign.Model.BulkEnvelopesResponse.BulkEnvelopesResponse()',
      ],
      [
        '../class_docu_sign_1_1e_sign_1_1_model_1_1_bulk_envelopes_response.html#addf2f7e18c7effae49414242c828be4e',
        1,
        'DocuSign.eSign.Model.BulkEnvelopesResponse.BulkEnvelopesResponse(List&lt; BulkEnvelopeStatus &gt; BulkEnvelopeStatuses=default(List&lt; BulkEnvelopeStatus &gt;), string EndPosition=default(string), string NextUri=default(string), string PreviousUri=default(string), string ResultSetSize=default(string), string StartPosition=default(string), string TotalSetSize=default(string))',
      ],
    ],
  ],
  [
    'bulkenvelopestatus',
    [
      'BulkEnvelopeStatus',
      [
        '../class_docu_sign_1_1e_sign_1_1_model_1_1_bulk_envelope_status.html#a3437659fdfddef688ed2027a95522d53',
        1,
        'DocuSign.eSign.Model.BulkEnvelopeStatus.BulkEnvelopeStatus()',
      ],
      [
        '../class_docu_sign_1_1e_sign_1_1_model_1_1_bulk_envelope_status.html#a39471f3a3658146de6c6cf94425b8f7e',
        1,
        'DocuSign.eSign.Model.BulkEnvelopeStatus.BulkEnvelopeStatus(string BatchId=default(string), string BatchSize=default(string), List&lt; BulkEnvelope &gt; BulkEnvelopes=default(List&lt; BulkEnvelope &gt;), string BulkEnvelopesBatchUri=default(string), string EndPosition=default(string), string Failed=default(string), string NextUri=default(string), string PreviousUri=default(string), string Queued=default(string), string ResultSetSize=default(string), string Sent=default(string), string StartPosition=default(string), string SubmittedDate=default(string), string TotalSetSize=default(string))',
      ],
    ],
  ],
  [
    'bulkrecipient',
    [
      'BulkRecipient',
      [
        '../class_docu_sign_1_1e_sign_1_1_model_1_1_bulk_recipient.html#a3a695ef72ece697ad2d493f9794aba74',
        1,
        'DocuSign.eSign.Model.BulkRecipient.BulkRecipient()',
      ],
      [
        '../class_docu_sign_1_1e_sign_1_1_model_1_1_bulk_recipient.html#a7b4aeb0c1c8b6705f4bdb55963af207a',
        1,
        'DocuSign.eSign.Model.BulkRecipient.BulkRecipient(string AccessCode=default(string), string Email=default(string), List&lt; ErrorDetails &gt; ErrorDetails=default(List&lt; ErrorDetails &gt;), string Identification=default(string), string Name=default(string), string Note=default(string), string PhoneNumber=default(string), List&lt; BulkRecipientSignatureProvider &gt; RecipientSignatureProviderInfo=default(List&lt; BulkRecipientSignatureProvider &gt;), string RowNumber=default(string), List&lt; BulkRecipientTabLabel &gt; TabLabels=default(List&lt; BulkRecipientTabLabel &gt;))',
      ],
    ],
  ],
  [
    'bulkrecipientsignatureprovider',
    [
      'BulkRecipientSignatureProvider',
      [
        '../class_docu_sign_1_1e_sign_1_1_model_1_1_bulk_recipient_signature_provider.html#a93e119642b478f6ea82783bdb576eb71',
        1,
        'DocuSign.eSign.Model.BulkRecipientSignatureProvider.BulkRecipientSignatureProvider()',
      ],
      [
        '../class_docu_sign_1_1e_sign_1_1_model_1_1_bulk_recipient_signature_provider.html#a26df6de31de0e74725718848cb7cfd76',
        1,
        'DocuSign.eSign.Model.BulkRecipientSignatureProvider.BulkRecipientSignatureProvider(string Name=default(string), string Value=default(string))',
      ],
    ],
  ],
  [
    'bulkrecipientsrequest',
    [
      'BulkRecipientsRequest',
      [
        '../class_docu_sign_1_1e_sign_1_1_model_1_1_bulk_recipients_request.html#a415a9f2bce55656378814eb6d6935e24',
        1,
        'DocuSign.eSign.Model.BulkRecipientsRequest.BulkRecipientsRequest()',
      ],
      [
        '../class_docu_sign_1_1e_sign_1_1_model_1_1_bulk_recipients_request.html#ac87d63c7d65a6e7acdb9a241290e6122',
        1,
        'DocuSign.eSign.Model.BulkRecipientsRequest.BulkRecipientsRequest(List&lt; BulkRecipient &gt; BulkRecipients=default(List&lt; BulkRecipient &gt;))',
      ],
    ],
  ],
  [
    'bulkrecipientsresponse',
    [
      'BulkRecipientsResponse',
      [
        '../class_docu_sign_1_1e_sign_1_1_model_1_1_bulk_recipients_response.html#ad797c3eca34e13612b8dd36b579d7cda',
        1,
        'DocuSign.eSign.Model.BulkRecipientsResponse.BulkRecipientsResponse()',
      ],
      [
        '../class_docu_sign_1_1e_sign_1_1_model_1_1_bulk_recipients_response.html#a743014f7933ec88b35735b5a2c35bd53',
        1,
        'DocuSign.eSign.Model.BulkRecipientsResponse.BulkRecipientsResponse(List&lt; BulkRecipient &gt; BulkRecipients=default(List&lt; BulkRecipient &gt;), string EndPosition=default(string), string NextUri=default(string), string PreviousUri=default(string), string ResultSetSize=default(string), string StartPosition=default(string), string TotalSetSize=default(string))',
      ],
    ],
  ],
  [
    'bulkrecipientssummaryresponse',
    [
      'BulkRecipientsSummaryResponse',
      [
        '../class_docu_sign_1_1e_sign_1_1_model_1_1_bulk_recipients_summary_response.html#a110b2b3b277879d2711b038c8f7f60bb',
        1,
        'DocuSign.eSign.Model.BulkRecipientsSummaryResponse.BulkRecipientsSummaryResponse()',
      ],
      [
        '../class_docu_sign_1_1e_sign_1_1_model_1_1_bulk_recipients_summary_response.html#ade4b560fee12382d21ea9d9334da0bd6',
        1,
        'DocuSign.eSign.Model.BulkRecipientsSummaryResponse.BulkRecipientsSummaryResponse(List&lt; BulkRecipient &gt; BulkRecipients=default(List&lt; BulkRecipient &gt;), string BulkRecipientsCount=default(string), string BulkRecipientsUri=default(string), List&lt; ErrorDetails &gt; ErrorDetails=default(List&lt; ErrorDetails &gt;))',
      ],
    ],
  ],
  [
    'bulkrecipientsupdateresponse',
    [
      'BulkRecipientsUpdateResponse',
      [
        '../class_docu_sign_1_1e_sign_1_1_model_1_1_bulk_recipients_update_response.html#aebeb25182779fe6ba9b86a6f52fec81f',
        1,
        'DocuSign.eSign.Model.BulkRecipientsUpdateResponse.BulkRecipientsUpdateResponse()',
      ],
      [
        '../class_docu_sign_1_1e_sign_1_1_model_1_1_bulk_recipients_update_response.html#a44ffcfcc6350b19a38662094fae3e718',
        1,
        'DocuSign.eSign.Model.BulkRecipientsUpdateResponse.BulkRecipientsUpdateResponse(Signer Signer=default(Signer))',
      ],
    ],
  ],
  [
    'bulkrecipienttablabel',
    [
      'BulkRecipientTabLabel',
      [
        '../class_docu_sign_1_1e_sign_1_1_model_1_1_bulk_recipient_tab_label.html#ae864f3ec09c58b343b0a9dfa38881504',
        1,
        'DocuSign.eSign.Model.BulkRecipientTabLabel.BulkRecipientTabLabel()',
      ],
      [
        '../class_docu_sign_1_1e_sign_1_1_model_1_1_bulk_recipient_tab_label.html#a497b017064bbbcf1f385e2874e142107',
        1,
        'DocuSign.eSign.Model.BulkRecipientTabLabel.BulkRecipientTabLabel(string Name=default(string), string Value=default(string))',
      ],
    ],
  ],
  [
    'bulksendbatchrequest',
    [
      'BulkSendBatchRequest',
      [
        '../class_docu_sign_1_1e_sign_1_1_model_1_1_bulk_send_batch_request.html#a547f982b4d0c88d39b41a5f4fdf8b34f',
        1,
        'DocuSign.eSign.Model.BulkSendBatchRequest.BulkSendBatchRequest()',
      ],
      [
        '../class_docu_sign_1_1e_sign_1_1_model_1_1_bulk_send_batch_request.html#af91c467b5960d2969363bf5518fbd02d',
        1,
        'DocuSign.eSign.Model.BulkSendBatchRequest.BulkSendBatchRequest(string BatchName=default(string))',
      ],
    ],
  ],
  [
    'bulksendbatchstatus',
    [
      'BulkSendBatchStatus',
      [
        '../class_docu_sign_1_1e_sign_1_1_model_1_1_bulk_send_batch_status.html#aac16cb0010b50bb41653a2634ae3ae4e',
        1,
        'DocuSign.eSign.Model.BulkSendBatchStatus.BulkSendBatchStatus()',
      ],
      [
        '../class_docu_sign_1_1e_sign_1_1_model_1_1_bulk_send_batch_status.html#a5bccda8416d7eade729dfef613110e29',
        1,
        'DocuSign.eSign.Model.BulkSendBatchStatus.BulkSendBatchStatus(string BatchId=default(string), string BatchName=default(string), string BatchSize=default(string), List&lt; BulkSendErrorStatus &gt; BulkErrors=default(List&lt; BulkSendErrorStatus &gt;), string EnvelopeIdOrTemplateId=default(string), string EnvelopesUri=default(string), string Failed=default(string), string MailingListId=default(string), string OwnerUserId=default(string), string Queued=default(string), string SenderUserId=default(string), string Sent=default(string), string SubmittedDate=default(string))',
      ],
    ],
  ],
  [
    'bulksendbatchsummaries',
    [
      'BulkSendBatchSummaries',
      [
        '../class_docu_sign_1_1e_sign_1_1_model_1_1_bulk_send_batch_summaries.html#a215008184d59925d322a518332ea61b1',
        1,
        'DocuSign.eSign.Model.BulkSendBatchSummaries.BulkSendBatchSummaries()',
      ],
      [
        '../class_docu_sign_1_1e_sign_1_1_model_1_1_bulk_send_batch_summaries.html#acabd78e28647c2494856624b2bed1da8',
        1,
        'DocuSign.eSign.Model.BulkSendBatchSummaries.BulkSendBatchSummaries(string BatchSizeLimit=default(string), List&lt; BulkSendBatchSummary &gt; BulkBatchSummaries=default(List&lt; BulkSendBatchSummary &gt;), string EndPosition=default(string), string NextUri=default(string), string PreviousUri=default(string), string QueueLimit=default(string), string ResultSetSize=default(string), string StartPosition=default(string), string TotalQueued=default(string), string TotalSetSize=default(string))',
      ],
    ],
  ],
  [
    'bulksendbatchsummary',
    [
      'BulkSendBatchSummary',
      [
        '../class_docu_sign_1_1e_sign_1_1_model_1_1_bulk_send_batch_summary.html#ae3909ec33551712b816c4ad8fee85858',
        1,
        'DocuSign.eSign.Model.BulkSendBatchSummary.BulkSendBatchSummary()',
      ],
      [
        '../class_docu_sign_1_1e_sign_1_1_model_1_1_bulk_send_batch_summary.html#a3ecbc2740f252cfdda7801734f7440f9',
        1,
        'DocuSign.eSign.Model.BulkSendBatchSummary.BulkSendBatchSummary(string BatchId=default(string), string BatchName=default(string), string BatchSize=default(string), string BatchUri=default(string), string Failed=default(string), string Queued=default(string), string Sent=default(string), string SubmittedDate=default(string))',
      ],
    ],
  ],
  [
    'bulksenderrorstatus',
    [
      'BulkSendErrorStatus',
      [
        '../class_docu_sign_1_1e_sign_1_1_model_1_1_bulk_send_error_status.html#a47cef8110c887faab2fa4f59533204d9',
        1,
        'DocuSign.eSign.Model.BulkSendErrorStatus.BulkSendErrorStatus()',
      ],
      [
        '../class_docu_sign_1_1e_sign_1_1_model_1_1_bulk_send_error_status.html#ae42fb869171607d65303ce6343542004',
        1,
        'DocuSign.eSign.Model.BulkSendErrorStatus.BulkSendErrorStatus(string Created=default(string), string ErrorMessage=default(string), List&lt; string &gt; RecipientEmails=default(List&lt; string &gt;))',
      ],
    ],
  ],
  [
    'bulksendingcopy',
    [
      'BulkSendingCopy',
      [
        '../class_docu_sign_1_1e_sign_1_1_model_1_1_bulk_sending_copy.html#af2e5d962d840f11fd15a84e30dd9a723',
        1,
        'DocuSign.eSign.Model.BulkSendingCopy.BulkSendingCopy()',
      ],
      [
        '../class_docu_sign_1_1e_sign_1_1_model_1_1_bulk_sending_copy.html#a0195b0b176be7f3d778dc130b4d55ab8',
        1,
        'DocuSign.eSign.Model.BulkSendingCopy.BulkSendingCopy(List&lt; BulkSendingCopyCustomField &gt; CustomFields=default(List&lt; BulkSendingCopyCustomField &gt;), string EmailBlurb=default(string), string EmailSubject=default(string), List&lt; BulkSendingCopyRecipient &gt; Recipients=default(List&lt; BulkSendingCopyRecipient &gt;))',
      ],
    ],
  ],
  [
    'bulksendingcopycustomfield',
    [
      'BulkSendingCopyCustomField',
      [
        '../class_docu_sign_1_1e_sign_1_1_model_1_1_bulk_sending_copy_custom_field.html#a4fd992b79a8675e8fae49ffb6c1e3694',
        1,
        'DocuSign.eSign.Model.BulkSendingCopyCustomField.BulkSendingCopyCustomField()',
      ],
      [
        '../class_docu_sign_1_1e_sign_1_1_model_1_1_bulk_sending_copy_custom_field.html#a887df58061e29f486ad98d6c7fa80032',
        1,
        'DocuSign.eSign.Model.BulkSendingCopyCustomField.BulkSendingCopyCustomField(string Name=default(string), string Value=default(string))',
      ],
    ],
  ],
  [
    'bulksendingcopyrecipient',
    [
      'BulkSendingCopyRecipient',
      [
        '../class_docu_sign_1_1e_sign_1_1_model_1_1_bulk_sending_copy_recipient.html#ac419db6566186d18797229604f143b91',
        1,
        'DocuSign.eSign.Model.BulkSendingCopyRecipient.BulkSendingCopyRecipient()',
      ],
      [
        '../class_docu_sign_1_1e_sign_1_1_model_1_1_bulk_sending_copy_recipient.html#aab257e5be27c3f1e39bc9e52f6062860',
        1,
        'DocuSign.eSign.Model.BulkSendingCopyRecipient.BulkSendingCopyRecipient(string AccessCode=default(string), string ClientUserId=default(string), List&lt; string &gt; CustomFields=default(List&lt; string &gt;), string DeliveryMethod=default(string), string Email=default(string), RecipientEmailNotification EmailNotification=default(RecipientEmailNotification), string EmbeddedRecipientStartURL=default(string), string FaxNumber=default(string), string HostEmail=default(string), string HostName=default(string), string IdCheckConfigurationName=default(string), IdCheckInformationInput IdCheckInformationInput=default(IdCheckInformationInput), string IdentificationMethod=default(string), string Name=default(string), string Note=default(string), RecipientPhoneAuthentication PhoneAuthentication=default(RecipientPhoneAuthentication), string RecipientId=default(string), List&lt; RecipientSignatureProvider &gt; RecipientSignatureProviders=default(List&lt; RecipientSignatureProvider &gt;), string RoleName=default(string), string SignerName=default(string), string SigningGroupId=default(string), RecipientSMSAuthentication SmsAuthentication=default(RecipientSMSAuthentication), List&lt; SocialAuthentication &gt; SocialAuthentications=default(List&lt; SocialAuthentication &gt;), List&lt; BulkSendingCopyTab &gt; Tabs=default(List&lt; BulkSendingCopyTab &gt;))',
      ],
    ],
  ],
  [
    'bulksendingcopytab',
    [
      'BulkSendingCopyTab',
      [
        '../class_docu_sign_1_1e_sign_1_1_model_1_1_bulk_sending_copy_tab.html#a026dd1c4f6fa5112fb036599e13295b2',
        1,
        'DocuSign.eSign.Model.BulkSendingCopyTab.BulkSendingCopyTab()',
      ],
      [
        '../class_docu_sign_1_1e_sign_1_1_model_1_1_bulk_sending_copy_tab.html#ab2067eeb18e4da209cd3b575881c700f',
        1,
        'DocuSign.eSign.Model.BulkSendingCopyTab.BulkSendingCopyTab(string InitialValue=default(string), string TabLabel=default(string))',
      ],
    ],
  ],
  [
    'bulksendinglist',
    [
      'BulkSendingList',
      [
        '../class_docu_sign_1_1e_sign_1_1_model_1_1_bulk_sending_list.html#acbe0f4d390d34b4bef6c7a73077062d9',
        1,
        'DocuSign.eSign.Model.BulkSendingList.BulkSendingList()',
      ],
      [
        '../class_docu_sign_1_1e_sign_1_1_model_1_1_bulk_sending_list.html#a95daa96c1994e3609117420ef2b9351a',
        1,
        'DocuSign.eSign.Model.BulkSendingList.BulkSendingList(List&lt; BulkSendingCopy &gt; BulkCopies=default(List&lt; BulkSendingCopy &gt;), string ListId=default(string), string Name=default(string))',
      ],
    ],
  ],
  [
    'bulksendinglistsummaries',
    [
      'BulkSendingListSummaries',
      [
        '../class_docu_sign_1_1e_sign_1_1_model_1_1_bulk_sending_list_summaries.html#ac01a354c4a178ef36025fdddb5253b1b',
        1,
        'DocuSign.eSign.Model.BulkSendingListSummaries.BulkSendingListSummaries()',
      ],
      [
        '../class_docu_sign_1_1e_sign_1_1_model_1_1_bulk_sending_list_summaries.html#afd517d8dcc773d3fcf9510b1b0e26050',
        1,
        'DocuSign.eSign.Model.BulkSendingListSummaries.BulkSendingListSummaries(List&lt; BulkSendingListSummary &gt; BulkListSummaries=default(List&lt; BulkSendingListSummary &gt;))',
      ],
    ],
  ],
  [
    'bulksendinglistsummary',
    [
      'BulkSendingListSummary',
      [
        '../class_docu_sign_1_1e_sign_1_1_model_1_1_bulk_sending_list_summary.html#ae00c551dd9299ef0c9d4800029980ed7',
        1,
        'DocuSign.eSign.Model.BulkSendingListSummary.BulkSendingListSummary()',
      ],
      [
        '../class_docu_sign_1_1e_sign_1_1_model_1_1_bulk_sending_list_summary.html#afe4a239c3d6b1a9271e917117e5429fc',
        1,
        'DocuSign.eSign.Model.BulkSendingListSummary.BulkSendingListSummary(string BulkSendListId=default(string), string CreatedByUser=default(string), string CreatedDate=default(string), string Name=default(string))',
      ],
    ],
  ],
  [
    'bulksendrequest',
    [
      'BulkSendRequest',
      [
        '../class_docu_sign_1_1e_sign_1_1_model_1_1_bulk_send_request.html#ae73598129ffbe9724fe37fbc50550b77',
        1,
        'DocuSign.eSign.Model.BulkSendRequest.BulkSendRequest()',
      ],
      [
        '../class_docu_sign_1_1e_sign_1_1_model_1_1_bulk_send_request.html#a0900933c61eef24d272de88ef11a0f05',
        1,
        'DocuSign.eSign.Model.BulkSendRequest.BulkSendRequest(string BatchName=default(string), string EnvelopeOrTemplateId=default(string))',
      ],
    ],
  ],
  [
    'bulksendresponse',
    [
      'BulkSendResponse',
      [
        '../class_docu_sign_1_1e_sign_1_1_model_1_1_bulk_send_response.html#a1078f41ed17975635b34400c63884884',
        1,
        'DocuSign.eSign.Model.BulkSendResponse.BulkSendResponse()',
      ],
      [
        '../class_docu_sign_1_1e_sign_1_1_model_1_1_bulk_send_response.html#a937ba454aaf7d80a49d892242d377e24',
        1,
        'DocuSign.eSign.Model.BulkSendResponse.BulkSendResponse(string BatchId=default(string), string BatchName=default(string), string BatchSize=default(string), string EnvelopeOrTemplateId=default(string), List&lt; string &gt; ErrorDetails=default(List&lt; string &gt;), List&lt; string &gt; Errors=default(List&lt; string &gt;), string QueueLimit=default(string), string TotalQueued=default(string))',
      ],
    ],
  ],
  [
    'bulksendtestresponse',
    [
      'BulkSendTestResponse',
      [
        '../class_docu_sign_1_1e_sign_1_1_model_1_1_bulk_send_test_response.html#aa276744ec5474062fdaf9911a7186332',
        1,
        'DocuSign.eSign.Model.BulkSendTestResponse.BulkSendTestResponse()',
      ],
      [
        '../class_docu_sign_1_1e_sign_1_1_model_1_1_bulk_send_test_response.html#a6a9b02a49d0427fb154848e1a285e3b7',
        1,
        'DocuSign.eSign.Model.BulkSendTestResponse.BulkSendTestResponse(bool?CanBeSent=default(bool?), List&lt; string &gt; ValidationErrorDetails=default(List&lt; string &gt;), List&lt; string &gt; ValidationErrors=default(List&lt; string &gt;))',
      ],
    ],
  ],
];
