var searchData = [
  [
    'samlassertionattribute',
    [
      'SamlAssertionAttribute',
      [
        '../class_docu_sign_1_1e_sign_1_1_model_1_1_saml_assertion_attribute.html#ad483b2b34d40fe75f2ad7a7a9b28554d',
        1,
        'DocuSign.eSign.Model.SamlAssertionAttribute.SamlAssertionAttribute()',
      ],
      [
        '../class_docu_sign_1_1e_sign_1_1_model_1_1_saml_assertion_attribute.html#a2e53c95693b1ce32288c7039971c3ff1',
        1,
        'DocuSign.eSign.Model.SamlAssertionAttribute.SamlAssertionAttribute(ErrorDetails ErrorDetails=default(ErrorDetails), string Name=default(string), string OriginalValue=default(string), string Value=default(string))',
      ],
    ],
  ],
  [
    'sanitizefilename',
    [
      'SanitizeFilename',
      [
        '../class_docu_sign_1_1e_sign_1_1_client_1_1_api_client.html#a1f86de95963a76f35b00b276b4de61ad',
        1,
        'DocuSign::eSign::Client::ApiClient',
      ],
    ],
  ],
  [
    'seal',
    [
      'Seal',
      [
        '../class_docu_sign_1_1e_sign_1_1_model_1_1_seal.html#a3107a6ccfd76522eae68196d6298ab44',
        1,
        'DocuSign.eSign.Model.Seal.Seal()',
      ],
      [
        '../class_docu_sign_1_1e_sign_1_1_model_1_1_seal.html#ae3683925edc5270897bba9d1f35896f4',
        1,
        'DocuSign.eSign.Model.Seal.Seal(Dictionary&lt; string, string &gt; Configuration=default(Dictionary&lt; string, string &gt;), string SealIdentifier=default(string))',
      ],
    ],
  ],
  [
    'sealidentifier',
    [
      'SealIdentifier',
      [
        '../class_docu_sign_1_1e_sign_1_1_model_1_1_seal_identifier.html#a59469dc94a8655a57ff8e74ee681ca5e',
        1,
        'DocuSign.eSign.Model.SealIdentifier.SealIdentifier()',
      ],
      [
        '../class_docu_sign_1_1e_sign_1_1_model_1_1_seal_identifier.html#a8ec2b63bf7f0bd0b5bf4533e625f0b8b',
        1,
        'DocuSign.eSign.Model.SealIdentifier.SealIdentifier(string SealDisplayName=default(string), string SealName=default(string))',
      ],
    ],
  ],
  [
    'sealsign',
    [
      'SealSign',
      [
        '../class_docu_sign_1_1e_sign_1_1_model_1_1_seal_sign.html#a63a949575c5fb86877b9102f78a8e98a',
        1,
        'DocuSign.eSign.Model.SealSign.SealSign()',
      ],
      [
        '../class_docu_sign_1_1e_sign_1_1_model_1_1_seal_sign.html#a2717949fdd2a1c5c86121d1a2f8c6dd4',
        1,
        'DocuSign.eSign.Model.SealSign.SealSign(string AccessCode=default(string), PropertyMetadata AccessCodeMetadata=default(PropertyMetadata), string AddAccessCodeToEmail=default(string), string AllowSystemOverrideForLockedRecipient=default(string), string ClientUserId=default(string), string CompletedCount=default(string), List&lt; string &gt; CustomFields=default(List&lt; string &gt;), string DeclinedDateTime=default(string), string DeclinedReason=default(string), string DeliveredDateTime=default(string), string DeliveryMethod=default(string), PropertyMetadata DeliveryMethodMetadata=default(PropertyMetadata), string DesignatorId=default(string), string DesignatorIdGuid=default(string), List&lt; DocumentVisibility &gt; DocumentVisibility=default(List&lt; DocumentVisibility &gt;), RecipientEmailNotification EmailNotification=default(RecipientEmailNotification), string EmbeddedRecipientStartURL=default(string), ErrorDetails ErrorDetails=default(ErrorDetails), string FaxNumber=default(string), PropertyMetadata FaxNumberMetadata=default(PropertyMetadata), string IdCheckConfigurationName=default(string), PropertyMetadata IdCheckConfigurationNameMetadata=default(PropertyMetadata), IdCheckInformationInput IdCheckInformationInput=default(IdCheckInformationInput), RecipientIdentityVerification IdentityVerification=default(RecipientIdentityVerification), string InheritEmailNotificationConfiguration=default(string), string LockedRecipientPhoneAuthEditable=default(string), string LockedRecipientSmsEditable=default(string), string Name=default(string), string Note=default(string), PropertyMetadata NoteMetadata=default(PropertyMetadata), RecipientPhoneAuthentication PhoneAuthentication=default(RecipientPhoneAuthentication), List&lt; RecipientAttachment &gt; RecipientAttachments=default(List&lt; RecipientAttachment &gt;), AuthenticationStatus RecipientAuthenticationStatus=default(AuthenticationStatus), List&lt; FeatureAvailableMetadata &gt; RecipientFeatureMetadata=default(List&lt; FeatureAvailableMetadata &gt;), string RecipientId=default(string), string RecipientIdGuid=default(string), List&lt; RecipientSignatureProvider &gt; RecipientSignatureProviders=default(List&lt; RecipientSignatureProvider &gt;), string RecipientType=default(string), PropertyMetadata RecipientTypeMetadata=default(PropertyMetadata), string RequireIdLookup=default(string), PropertyMetadata RequireIdLookupMetadata=default(PropertyMetadata), string RoleName=default(string), string RoutingOrder=default(string), PropertyMetadata RoutingOrderMetadata=default(PropertyMetadata), string SentDateTime=default(string), string SignedDateTime=default(string), RecipientSMSAuthentication SmsAuthentication=default(RecipientSMSAuthentication), List&lt; SocialAuthentication &gt; SocialAuthentications=default(List&lt; SocialAuthentication &gt;), string Status=default(string), string StatusCode=default(string), string SuppressEmails=default(string), Tabs Tabs=default(Tabs), string TemplateLocked=default(string), string TemplateRequired=default(string), string TotalTabCount=default(string), string UserId=default(string))',
      ],
    ],
  ],
  [
    'search',
    [
      'Search',
      [
        '../interface_docu_sign_1_1e_sign_1_1_api_1_1_i_folders_api.html#a700f26c7f37037f236777898ec5b22bb',
        1,
        'DocuSign.eSign.Api.IFoldersApi.Search()',
      ],
      [
        '../class_docu_sign_1_1e_sign_1_1_api_1_1_folders_api.html#acc753f2181a9e8d2c6d7bbf5fda664eb',
        1,
        'DocuSign.eSign.Api.FoldersApi.Search()',
      ],
    ],
  ],
  [
    'searchasync',
    [
      'SearchAsync',
      [
        '../interface_docu_sign_1_1e_sign_1_1_api_1_1_i_folders_api.html#a06f53d8f9381bfc5431cd4c6a460607c',
        1,
        'DocuSign.eSign.Api.IFoldersApi.SearchAsync()',
      ],
      [
        '../class_docu_sign_1_1e_sign_1_1_api_1_1_folders_api.html#ad11db15ad8fcbe92aa42c0484bd81577',
        1,
        'DocuSign.eSign.Api.FoldersApi.SearchAsync()',
      ],
    ],
  ],
  [
    'searchasyncwithhttpinfo',
    [
      'SearchAsyncWithHttpInfo',
      [
        '../interface_docu_sign_1_1e_sign_1_1_api_1_1_i_folders_api.html#a1d38807419d76afeaccb6047d61f7bd9',
        1,
        'DocuSign.eSign.Api.IFoldersApi.SearchAsyncWithHttpInfo()',
      ],
      [
        '../class_docu_sign_1_1e_sign_1_1_api_1_1_folders_api.html#ac5ad699bcfe9a0b3e84a9f5360376803',
        1,
        'DocuSign.eSign.Api.FoldersApi.SearchAsyncWithHttpInfo()',
      ],
    ],
  ],
  [
    'searchwithhttpinfo',
    [
      'SearchWithHttpInfo',
      [
        '../interface_docu_sign_1_1e_sign_1_1_api_1_1_i_folders_api.html#a95e34dcc2956b13631be11975fdc8191',
        1,
        'DocuSign.eSign.Api.IFoldersApi.SearchWithHttpInfo()',
      ],
      [
        '../class_docu_sign_1_1e_sign_1_1_api_1_1_folders_api.html#a57c5575eaef18ad1886c1e5dc26f9482',
        1,
        'DocuSign.eSign.Api.FoldersApi.SearchWithHttpInfo()',
      ],
    ],
  ],
  [
    'seatdiscount',
    [
      'SeatDiscount',
      [
        '../class_docu_sign_1_1e_sign_1_1_model_1_1_seat_discount.html#a7cc11f6323184d43de844a2affdeb837',
        1,
        'DocuSign.eSign.Model.SeatDiscount.SeatDiscount()',
      ],
      [
        '../class_docu_sign_1_1e_sign_1_1_model_1_1_seat_discount.html#a726f9984e9a6f977934120b7e9bec912',
        1,
        'DocuSign.eSign.Model.SeatDiscount.SeatDiscount(string BeginSeatCount=default(string), string DiscountPercent=default(string), string EndSeatCount=default(string))',
      ],
    ],
  ],
  [
    'selectheaderaccept',
    [
      'SelectHeaderAccept',
      [
        '../class_docu_sign_1_1e_sign_1_1_client_1_1_api_client.html#aecaec9f81064b381546f24082cb4d85e',
        1,
        'DocuSign::eSign::Client::ApiClient',
      ],
    ],
  ],
  [
    'selectheadercontenttype',
    [
      'SelectHeaderContentType',
      [
        '../class_docu_sign_1_1e_sign_1_1_client_1_1_api_client.html#aeb86cc525871fb01c97fc4b89ed19f03',
        1,
        'DocuSign::eSign::Client::ApiClient',
      ],
    ],
  ],
  [
    'sender',
    [
      'Sender',
      [
        '../class_docu_sign_1_1e_sign_1_1_model_1_1_sender.html#a5c646c0c2341e50e7ff74712ce08e40d',
        1,
        'DocuSign.eSign.Model.Sender.Sender()',
      ],
      [
        '../class_docu_sign_1_1e_sign_1_1_model_1_1_sender.html#a721754d5231fee1845d95e32a12335e7',
        1,
        'DocuSign.eSign.Model.Sender.Sender(string AccountIdGuid=default(string), string CompanyName=default(string))',
      ],
    ],
  ],
  [
    'senderemailnotifications',
    [
      'SenderEmailNotifications',
      [
        '../class_docu_sign_1_1e_sign_1_1_model_1_1_sender_email_notifications.html#a2b352c59db6f14dcb2c0a09d764a56ec',
        1,
        'DocuSign.eSign.Model.SenderEmailNotifications.SenderEmailNotifications()',
      ],
      [
        '../class_docu_sign_1_1e_sign_1_1_model_1_1_sender_email_notifications.html#a47f0f7cf40249d01cc556a1e2867a7e3',
        1,
        'DocuSign.eSign.Model.SenderEmailNotifications.SenderEmailNotifications(string ChangedSigner=default(string), string CommentsOnlyPrivateAndMention=default(string), string CommentsReceiveAll=default(string), string DeliveryFailed=default(string), string EnvelopeComplete=default(string), string OfflineSigningFailed=default(string), string PowerformResponsesLimitNotificationEmail=default(string), string PurgeDocuments=default(string), string RecipientViewed=default(string), string SenderEnvelopeDeclined=default(string), string WithdrawnConsent=default(string))',
      ],
    ],
  ],
  [
    'serialize',
    [
      'Serialize',
      [
        '../class_docu_sign_1_1e_sign_1_1_client_1_1_api_client.html#a620e8e153ddbf1a29139421715623c78',
        1,
        'DocuSign::eSign::Client::ApiClient',
      ],
    ],
  ],
  [
    'serializecsvtostring',
    [
      'SerializeCsvToString',
      [
        '../class_docu_sign_1_1e_sign_1_1_client_1_1_api_client.html#ac2ee7ae812fd4b9c6e33230b389fb824',
        1,
        'DocuSign::eSign::Client::ApiClient',
      ],
    ],
  ],
  [
    'serializecsvtostring_3c_20t_20_3e',
    [
      'SerializeCsvToString&lt; T &gt;',
      [
        '../class_docu_sign_1_1e_sign_1_1_client_1_1_api_client.html#a274edfa12a49df4d1e75dc183eb2a5fe',
        1,
        'DocuSign::eSign::Client::ApiClient',
      ],
    ],
  ],
  [
    'servertemplate',
    [
      'ServerTemplate',
      [
        '../class_docu_sign_1_1e_sign_1_1_model_1_1_server_template.html#afaf50d00af97ef8925284abb069484ea',
        1,
        'DocuSign.eSign.Model.ServerTemplate.ServerTemplate()',
      ],
      [
        '../class_docu_sign_1_1e_sign_1_1_model_1_1_server_template.html#a940797a2bd3ca056e4451399564eda96',
        1,
        'DocuSign.eSign.Model.ServerTemplate.ServerTemplate(string Sequence=default(string), string TemplateId=default(string))',
      ],
    ],
  ],
  [
    'serviceinformation',
    [
      'ServiceInformation',
      [
        '../class_docu_sign_1_1e_sign_1_1_model_1_1_service_information.html#a22ed8a711599995b543344d8e1bed3f5',
        1,
        'DocuSign.eSign.Model.ServiceInformation.ServiceInformation()',
      ],
      [
        '../class_docu_sign_1_1e_sign_1_1_model_1_1_service_information.html#acf1e9516c54da34742b02f18171c9085',
        1,
        'DocuSign.eSign.Model.ServiceInformation.ServiceInformation(string BuildBranch=default(string), string BuildBranchDeployedDateTime=default(string), string BuildSHA=default(string), string BuildVersion=default(string), List&lt; string &gt; LinkedSites=default(List&lt; string &gt;), List&lt; ServiceVersion &gt; ServiceVersions=default(List&lt; ServiceVersion &gt;))',
      ],
    ],
  ],
  [
    'serviceversion',
    [
      'ServiceVersion',
      [
        '../class_docu_sign_1_1e_sign_1_1_model_1_1_service_version.html#a46b13007c3097b9ffff4b42dbe84b627',
        1,
        'DocuSign.eSign.Model.ServiceVersion.ServiceVersion()',
      ],
      [
        '../class_docu_sign_1_1e_sign_1_1_model_1_1_service_version.html#a0e7547dc6537f0bc1948fa2ab6b77783',
        1,
        'DocuSign.eSign.Model.ServiceVersion.ServiceVersion(string Version=default(string), string VersionUrl=default(string))',
      ],
    ],
  ],
  [
    'setbasepath',
    [
      'SetBasePath',
      [
        '../class_docu_sign_1_1e_sign_1_1_client_1_1_api_client.html#abfc59b0c9364f2ea239310ca46f4be58',
        1,
        'DocuSign::eSign::Client::ApiClient',
      ],
    ],
  ],
  [
    'setoauthbasepath',
    [
      'SetOAuthBasePath',
      [
        '../class_docu_sign_1_1e_sign_1_1_client_1_1_api_client.html#ad5b9caf4647501735fe38d5640caf058',
        1,
        'DocuSign::eSign::Client::ApiClient',
      ],
    ],
  ],
  [
    'settingsmetadata',
    [
      'SettingsMetadata',
      [
        '../class_docu_sign_1_1e_sign_1_1_model_1_1_settings_metadata.html#aba3db845339b560b7e875fa0d5f90b6d',
        1,
        'DocuSign.eSign.Model.SettingsMetadata.SettingsMetadata()',
      ],
      [
        '../class_docu_sign_1_1e_sign_1_1_model_1_1_settings_metadata.html#a514650a50039ca964cbdc331ef92fa94',
        1,
        'DocuSign.eSign.Model.SettingsMetadata.SettingsMetadata(string Is21CFRPart11=default(string), List&lt; string &gt; Options=default(List&lt; string &gt;), string Rights=default(string), string UiHint=default(string), string UiOrder=default(string), string UiType=default(string))',
      ],
    ],
  ],
  [
    'shareditem',
    [
      'SharedItem',
      [
        '../class_docu_sign_1_1e_sign_1_1_model_1_1_shared_item.html#a3ca93649223ad996d47fa004ef5499bc',
        1,
        'DocuSign.eSign.Model.SharedItem.SharedItem()',
      ],
      [
        '../class_docu_sign_1_1e_sign_1_1_model_1_1_shared_item.html#a832974ac8f74f35cee8df4745d6bc9f0',
        1,
        'DocuSign.eSign.Model.SharedItem.SharedItem(ErrorDetails ErrorDetails=default(ErrorDetails), string Shared=default(string), UserInfo User=default(UserInfo))',
      ],
    ],
  ],
  [
    'signatureapi',
    [
      'SignatureApi',
      [
        '../class_docu_sign_1_1e_sign_1_1_api_1_1_signature_api.html#a99dadaf7dda9204b86a1f2822c90afcf',
        1,
        'DocuSign::eSign::Api::SignatureApi',
      ],
    ],
  ],
  [
    'signaturedatainfo',
    [
      'SignatureDataInfo',
      [
        '../class_docu_sign_1_1e_sign_1_1_model_1_1_signature_data_info.html#a89b3696e255a09d9ea85d8ab8f9cc85c',
        1,
        'DocuSign.eSign.Model.SignatureDataInfo.SignatureDataInfo()',
      ],
      [
        '../class_docu_sign_1_1e_sign_1_1_model_1_1_signature_data_info.html#a49a4bb8906e961c04cff636708253f5d',
        1,
        'DocuSign.eSign.Model.SignatureDataInfo.SignatureDataInfo(DocumentSecurityStore DocumentSecurityStore=default(DocumentSecurityStore), string SignatureData=default(string), string SignatureFieldName=default(string))',
      ],
    ],
  ],
  [
    'signaturegroup',
    [
      'SignatureGroup',
      [
        '../class_docu_sign_1_1e_sign_1_1_model_1_1_signature_group.html#a55c28f57e32205e0c33161d683f40136',
        1,
        'DocuSign.eSign.Model.SignatureGroup.SignatureGroup()',
      ],
      [
        '../class_docu_sign_1_1e_sign_1_1_model_1_1_signature_group.html#a27d1f85270c4687880268191ae626015',
        1,
        'DocuSign.eSign.Model.SignatureGroup.SignatureGroup(string GroupId=default(string), string GroupName=default(string), string Rights=default(string))',
      ],
    ],
  ],
  [
    'signaturegroupdef',
    [
      'SignatureGroupDef',
      [
        '../class_docu_sign_1_1e_sign_1_1_model_1_1_signature_group_def.html#a6876b05e373bd1a7ff50c361fd4b68dd',
        1,
        'DocuSign.eSign.Model.SignatureGroupDef.SignatureGroupDef()',
      ],
      [
        '../class_docu_sign_1_1e_sign_1_1_model_1_1_signature_group_def.html#a80a0e1744b51ff57739d48e4dc936c25',
        1,
        'DocuSign.eSign.Model.SignatureGroupDef.SignatureGroupDef(string GroupId=default(string), string Rights=default(string))',
      ],
    ],
  ],
  [
    'signatureproperties',
    [
      'SignatureProperties',
      [
        '../class_docu_sign_1_1e_sign_1_1_model_1_1_signature_properties.html#ac59fe0ea7a59b92d41fc7f5e70fcff9b',
        1,
        'DocuSign.eSign.Model.SignatureProperties.SignatureProperties()',
      ],
      [
        '../class_docu_sign_1_1e_sign_1_1_model_1_1_signature_properties.html#af6e37bf9611e02f830e7b9d53c95abd8',
        1,
        'DocuSign.eSign.Model.SignatureProperties.SignatureProperties(string Filter=default(string), string SubFilter=default(string))',
      ],
    ],
  ],
  [
    'signatureproviderrequiredoption',
    [
      'SignatureProviderRequiredOption',
      [
        '../class_docu_sign_1_1e_sign_1_1_model_1_1_signature_provider_required_option.html#aadc5d2dc59d2a33fff498068d08a74ac',
        1,
        'DocuSign.eSign.Model.SignatureProviderRequiredOption.SignatureProviderRequiredOption()',
      ],
      [
        '../class_docu_sign_1_1e_sign_1_1_model_1_1_signature_provider_required_option.html#a9da455417bfe3936921c975136c87bb9',
        1,
        'DocuSign.eSign.Model.SignatureProviderRequiredOption.SignatureProviderRequiredOption(List&lt; string &gt; RequiredSignatureProviderOptionIds=default(List&lt; string &gt;), string SignerType=default(string))',
      ],
    ],
  ],
  [
    'signaturetype',
    [
      'SignatureType',
      [
        '../class_docu_sign_1_1e_sign_1_1_model_1_1_signature_type.html#a00a7125f8a4d615a659008d8cbbcfd6d',
        1,
        'DocuSign.eSign.Model.SignatureType.SignatureType()',
      ],
      [
        '../class_docu_sign_1_1e_sign_1_1_model_1_1_signature_type.html#ad09f58f7342d78b2dd7fa84b4d6aed49',
        1,
        'DocuSign.eSign.Model.SignatureType.SignatureType(string IsDefault=default(string), string Type=default(string))',
      ],
    ],
  ],
  [
    'signatureuser',
    [
      'SignatureUser',
      [
        '../class_docu_sign_1_1e_sign_1_1_model_1_1_signature_user.html#a75413a75d43ab762431cb874b1868c48',
        1,
        'DocuSign.eSign.Model.SignatureUser.SignatureUser()',
      ],
      [
        '../class_docu_sign_1_1e_sign_1_1_model_1_1_signature_user.html#af7ecd9098e31e8159e1dc9b886bd238a',
        1,
        'DocuSign.eSign.Model.SignatureUser.SignatureUser(string IsDefault=default(string), string Rights=default(string), string UserId=default(string), string UserName=default(string))',
      ],
    ],
  ],
  [
    'signatureuserdef',
    [
      'SignatureUserDef',
      [
        '../class_docu_sign_1_1e_sign_1_1_model_1_1_signature_user_def.html#a33b98ac06b468204488e70b1bd2c8544',
        1,
        'DocuSign.eSign.Model.SignatureUserDef.SignatureUserDef()',
      ],
      [
        '../class_docu_sign_1_1e_sign_1_1_model_1_1_signature_user_def.html#a4b2d19326d87ed676a35c97bf57e571a',
        1,
        'DocuSign.eSign.Model.SignatureUserDef.SignatureUserDef(string IsDefault=default(string), string Rights=default(string), string UserId=default(string))',
      ],
    ],
  ],
  [
    'signer',
    [
      'Signer',
      [
        '../class_docu_sign_1_1e_sign_1_1_model_1_1_signer.html#a547c061c517d6c71122abd3c64c9f7ae',
        1,
        'DocuSign.eSign.Model.Signer.Signer()',
      ],
      [
        '../class_docu_sign_1_1e_sign_1_1_model_1_1_signer.html#aa9cba58cf3284cbc02638b228bd3f261',
        1,
        'DocuSign.eSign.Model.Signer.Signer(string AccessCode=default(string), PropertyMetadata AccessCodeMetadata=default(PropertyMetadata), string AddAccessCodeToEmail=default(string), List&lt; RecipientAdditionalNotification &gt; AdditionalNotifications=default(List&lt; RecipientAdditionalNotification &gt;), string AgentCanEditEmail=default(string), string AgentCanEditName=default(string), string AllowSystemOverrideForLockedRecipient=default(string), string AutoNavigation=default(string), string BulkRecipientsUri=default(string), string CanSignOffline=default(string), string ClientUserId=default(string), string CompletedCount=default(string), string CreationReason=default(string), List&lt; string &gt; CustomFields=default(List&lt; string &gt;), string DeclinedDateTime=default(string), string DeclinedReason=default(string), string DefaultRecipient=default(string), string DeliveredDateTime=default(string), string DeliveryMethod=default(string), PropertyMetadata DeliveryMethodMetadata=default(PropertyMetadata), string DesignatorId=default(string), string DesignatorIdGuid=default(string), List&lt; DocumentVisibility &gt; DocumentVisibility=default(List&lt; DocumentVisibility &gt;), string Email=default(string), PropertyMetadata EmailMetadata=default(PropertyMetadata), RecipientEmailNotification EmailNotification=default(RecipientEmailNotification), string EmbeddedRecipientStartURL=default(string), ErrorDetails ErrorDetails=default(ErrorDetails), List&lt; string &gt; ExcludedDocuments=default(List&lt; string &gt;), string FaxNumber=default(string), PropertyMetadata FaxNumberMetadata=default(PropertyMetadata), string FirstName=default(string), PropertyMetadata FirstNameMetadata=default(PropertyMetadata), string FullName=default(string), PropertyMetadata FullNameMetadata=default(PropertyMetadata), string IdCheckConfigurationName=default(string), PropertyMetadata IdCheckConfigurationNameMetadata=default(PropertyMetadata), IdCheckInformationInput IdCheckInformationInput=default(IdCheckInformationInput), RecipientIdentityVerification IdentityVerification=default(RecipientIdentityVerification), string InheritEmailNotificationConfiguration=default(string), string IsBulkRecipient=default(string), PropertyMetadata IsBulkRecipientMetadata=default(PropertyMetadata), string LastName=default(string), PropertyMetadata LastNameMetadata=default(PropertyMetadata), string LockedRecipientPhoneAuthEditable=default(string), string LockedRecipientSmsEditable=default(string), string Name=default(string), PropertyMetadata NameMetadata=default(PropertyMetadata), string NotaryId=default(string), string Note=default(string), PropertyMetadata NoteMetadata=default(PropertyMetadata), OfflineAttributes OfflineAttributes=default(OfflineAttributes), RecipientPhoneAuthentication PhoneAuthentication=default(RecipientPhoneAuthentication), RecipientProofFile ProofFile=default(RecipientProofFile), List&lt; RecipientAttachment &gt; RecipientAttachments=default(List&lt; RecipientAttachment &gt;), AuthenticationStatus RecipientAuthenticationStatus=default(AuthenticationStatus), List&lt; FeatureAvailableMetadata &gt; RecipientFeatureMetadata=default(List&lt; FeatureAvailableMetadata &gt;), string RecipientId=default(string), string RecipientIdGuid=default(string), List&lt; RecipientSignatureProvider &gt; RecipientSignatureProviders=default(List&lt; RecipientSignatureProvider &gt;), string RecipientSuppliesTabs=default(string), string RecipientType=default(string), PropertyMetadata RecipientTypeMetadata=default(PropertyMetadata), string RequireIdLookup=default(string), PropertyMetadata RequireIdLookupMetadata=default(PropertyMetadata), string RequireSignerCertificate=default(string), string RequireSignOnPaper=default(string), string RequireUploadSignature=default(string), string RoleName=default(string), string RoutingOrder=default(string), PropertyMetadata RoutingOrderMetadata=default(PropertyMetadata), string SentDateTime=default(string), RecipientSignatureInformation SignatureInfo=default(RecipientSignatureInformation), string SignedDateTime=default(string), string SignInEachLocation=default(string), PropertyMetadata SignInEachLocationMetadata=default(PropertyMetadata), string SigningGroupId=default(string), PropertyMetadata SigningGroupIdMetadata=default(PropertyMetadata), string SigningGroupName=default(string), List&lt; UserInfo &gt; SigningGroupUsers=default(List&lt; UserInfo &gt;), RecipientSMSAuthentication SmsAuthentication=default(RecipientSMSAuthentication), List&lt; SocialAuthentication &gt; SocialAuthentications=default(List&lt; SocialAuthentication &gt;), string Status=default(string), string StatusCode=default(string), string SuppressEmails=default(string), Tabs Tabs=default(Tabs), string TemplateLocked=default(string), string TemplateRequired=default(string), string TotalTabCount=default(string), string UserId=default(string))',
      ],
    ],
  ],
  [
    'signerattachment',
    [
      'SignerAttachment',
      [
        '../class_docu_sign_1_1e_sign_1_1_model_1_1_signer_attachment.html#a4a8b0771dcdb2b7cdd507ba31597ce5d',
        1,
        'DocuSign.eSign.Model.SignerAttachment.SignerAttachment()',
      ],
      [
        '../class_docu_sign_1_1e_sign_1_1_model_1_1_signer_attachment.html#ae4d6ea68ea478f221574d80d58db04c1',
        1,
        'DocuSign.eSign.Model.SignerAttachment.SignerAttachment(string AnchorAllowWhiteSpaceInCharacters=default(string), PropertyMetadata AnchorAllowWhiteSpaceInCharactersMetadata=default(PropertyMetadata), string AnchorCaseSensitive=default(string), PropertyMetadata AnchorCaseSensitiveMetadata=default(PropertyMetadata), string AnchorHorizontalAlignment=default(string), PropertyMetadata AnchorHorizontalAlignmentMetadata=default(PropertyMetadata), string AnchorIgnoreIfNotPresent=default(string), PropertyMetadata AnchorIgnoreIfNotPresentMetadata=default(PropertyMetadata), string AnchorMatchWholeWord=default(string), PropertyMetadata AnchorMatchWholeWordMetadata=default(PropertyMetadata), string AnchorString=default(string), PropertyMetadata AnchorStringMetadata=default(PropertyMetadata), string AnchorTabProcessorVersion=default(string), PropertyMetadata AnchorTabProcessorVersionMetadata=default(PropertyMetadata), string AnchorUnits=default(string), PropertyMetadata AnchorUnitsMetadata=default(PropertyMetadata), string AnchorXOffset=default(string), PropertyMetadata AnchorXOffsetMetadata=default(PropertyMetadata), string AnchorYOffset=default(string), PropertyMetadata AnchorYOffsetMetadata=default(PropertyMetadata), string ConditionalParentLabel=default(string), PropertyMetadata ConditionalParentLabelMetadata=default(PropertyMetadata), string ConditionalParentValue=default(string), PropertyMetadata ConditionalParentValueMetadata=default(PropertyMetadata), string CustomTabId=default(string), PropertyMetadata CustomTabIdMetadata=default(PropertyMetadata), string DocumentId=default(string), PropertyMetadata DocumentIdMetadata=default(PropertyMetadata), ErrorDetails ErrorDetails=default(ErrorDetails), string FormOrder=default(string), PropertyMetadata FormOrderMetadata=default(PropertyMetadata), string FormPageLabel=default(string), PropertyMetadata FormPageLabelMetadata=default(PropertyMetadata), string FormPageNumber=default(string), PropertyMetadata FormPageNumberMetadata=default(PropertyMetadata), string Height=default(string), PropertyMetadata HeightMetadata=default(PropertyMetadata), MergeField MergeField=default(MergeField), string MergeFieldXml=default(string), string Name=default(string), PropertyMetadata NameMetadata=default(PropertyMetadata), string Optional=default(string), PropertyMetadata OptionalMetadata=default(PropertyMetadata), string PageNumber=default(string), PropertyMetadata PageNumberMetadata=default(PropertyMetadata), string RecipientId=default(string), string RecipientIdGuid=default(string), PropertyMetadata RecipientIdGuidMetadata=default(PropertyMetadata), PropertyMetadata RecipientIdMetadata=default(PropertyMetadata), string ScaleValue=default(string), PropertyMetadata ScaleValueMetadata=default(PropertyMetadata), SmartContractInformation SmartContractInformation=default(SmartContractInformation), string Source=default(string), string Status=default(string), PropertyMetadata StatusMetadata=default(PropertyMetadata), List&lt; string &gt; TabGroupLabels=default(List&lt; string &gt;), PropertyMetadata TabGroupLabelsMetadata=default(PropertyMetadata), string TabId=default(string), PropertyMetadata TabIdMetadata=default(PropertyMetadata), string TabLabel=default(string), PropertyMetadata TabLabelMetadata=default(PropertyMetadata), string TabOrder=default(string), PropertyMetadata TabOrderMetadata=default(PropertyMetadata), string TabType=default(string), PropertyMetadata TabTypeMetadata=default(PropertyMetadata), string TemplateLocked=default(string), PropertyMetadata TemplateLockedMetadata=default(PropertyMetadata), string TemplateRequired=default(string), PropertyMetadata TemplateRequiredMetadata=default(PropertyMetadata), string Tooltip=default(string), PropertyMetadata ToolTipMetadata=default(PropertyMetadata), string Width=default(string), PropertyMetadata WidthMetadata=default(PropertyMetadata), string XPosition=default(string), PropertyMetadata XPositionMetadata=default(PropertyMetadata), string YPosition=default(string), PropertyMetadata YPositionMetadata=default(PropertyMetadata))',
      ],
    ],
  ],
  [
    'signeremailnotifications',
    [
      'SignerEmailNotifications',
      [
        '../class_docu_sign_1_1e_sign_1_1_model_1_1_signer_email_notifications.html#a448117a402e8c7cd98e3e1e5489bce5e',
        1,
        'DocuSign.eSign.Model.SignerEmailNotifications.SignerEmailNotifications()',
      ],
      [
        '../class_docu_sign_1_1e_sign_1_1_model_1_1_signer_email_notifications.html#a81ccddb93f39fa32af5a86ebe7c2970d',
        1,
        'DocuSign.eSign.Model.SignerEmailNotifications.SignerEmailNotifications(string AgentNotification=default(string), string CarbonCopyNotification=default(string), string CertifiedDeliveryNotification=default(string), string CommentsOnlyPrivateAndMention=default(string), string CommentsReceiveAll=default(string), string DocumentMarkupActivation=default(string), string EnvelopeActivation=default(string), string EnvelopeComplete=default(string), string EnvelopeCorrected=default(string), string EnvelopeDeclined=default(string), string EnvelopeVoided=default(string), string FaxReceived=default(string), string OfflineSigningFailed=default(string), string PurgeDocuments=default(string), string ReassignedSigner=default(string), string WhenSigningGroupMember=default(string))',
      ],
    ],
  ],
  [
    'signhashdocument',
    [
      'SignHashDocument',
      [
        '../class_docu_sign_1_1e_sign_1_1_model_1_1_sign_hash_document.html#a6da465f97f3fefcb9425f50901055bb6',
        1,
        'DocuSign.eSign.Model.SignHashDocument.SignHashDocument()',
      ],
      [
        '../class_docu_sign_1_1e_sign_1_1_model_1_1_sign_hash_document.html#a529d4ed4ea76071aafe5c5af96ce7aca',
        1,
        'DocuSign.eSign.Model.SignHashDocument.SignHashDocument(string Data=default(string), string DocumentId=default(string), string Format=default(string), string Name=default(string), long?RemainingSignatures=default(long?), List&lt; Revision &gt; Revisions=default(List&lt; Revision &gt;), SignatureProperties SignatureProperties=default(SignatureProperties), string SignatureType=default(string))',
      ],
    ],
  ],
  [
    'signhashsessioninfo',
    [
      'SignHashSessionInfo',
      [
        '../interface_docu_sign_1_1e_sign_1_1_api_1_1_i_signature_api.html#a2d280e816d5f16a4cac3332e0cfaf9c6',
        1,
        'DocuSign.eSign.Api.ISignatureApi.SignHashSessionInfo()',
      ],
      [
        '../class_docu_sign_1_1e_sign_1_1_api_1_1_signature_api.html#a66a90fed268e26f726107d4fdd57111c',
        1,
        'DocuSign.eSign.Api.SignatureApi.SignHashSessionInfo()',
      ],
      [
        '../interface_docu_sign_1_1e_sign_1_1_api_1_1_i_trust_service_providers_api.html#a9e346729803ef2c3f5190fba3862ea64',
        1,
        'DocuSign.eSign.Api.ITrustServiceProvidersApi.SignHashSessionInfo()',
      ],
      [
        '../class_docu_sign_1_1e_sign_1_1_api_1_1_trust_service_providers_api.html#a3bd49c3191ac30c74b124e8cdfac4b7e',
        1,
        'DocuSign.eSign.Api.TrustServiceProvidersApi.SignHashSessionInfo()',
      ],
    ],
  ],
  [
    'signhashsessioninfoasync',
    [
      'SignHashSessionInfoAsync',
      [
        '../interface_docu_sign_1_1e_sign_1_1_api_1_1_i_signature_api.html#abf092e5c833e65982f8bf2753da53f32',
        1,
        'DocuSign.eSign.Api.ISignatureApi.SignHashSessionInfoAsync()',
      ],
      [
        '../class_docu_sign_1_1e_sign_1_1_api_1_1_signature_api.html#a18762a594c3d9ae8c0dd8199d0c2a37e',
        1,
        'DocuSign.eSign.Api.SignatureApi.SignHashSessionInfoAsync()',
      ],
      [
        '../interface_docu_sign_1_1e_sign_1_1_api_1_1_i_trust_service_providers_api.html#aa1d53337a9825f5067f02213e02227f0',
        1,
        'DocuSign.eSign.Api.ITrustServiceProvidersApi.SignHashSessionInfoAsync()',
      ],
      [
        '../class_docu_sign_1_1e_sign_1_1_api_1_1_trust_service_providers_api.html#a58b2638c7060c2dfda6d44eeb73de995',
        1,
        'DocuSign.eSign.Api.TrustServiceProvidersApi.SignHashSessionInfoAsync()',
      ],
    ],
  ],
  [
    'signhashsessioninfoasyncwithhttpinfo',
    [
      'SignHashSessionInfoAsyncWithHttpInfo',
      [
        '../interface_docu_sign_1_1e_sign_1_1_api_1_1_i_signature_api.html#aff72aa11288de09617957711457a00a5',
        1,
        'DocuSign.eSign.Api.ISignatureApi.SignHashSessionInfoAsyncWithHttpInfo()',
      ],
      [
        '../class_docu_sign_1_1e_sign_1_1_api_1_1_signature_api.html#a711e01b49353146f625f865268322cb0',
        1,
        'DocuSign.eSign.Api.SignatureApi.SignHashSessionInfoAsyncWithHttpInfo()',
      ],
      [
        '../interface_docu_sign_1_1e_sign_1_1_api_1_1_i_trust_service_providers_api.html#a48d166b2ef9802255aeb07c6d21abb4a',
        1,
        'DocuSign.eSign.Api.ITrustServiceProvidersApi.SignHashSessionInfoAsyncWithHttpInfo()',
      ],
      [
        '../class_docu_sign_1_1e_sign_1_1_api_1_1_trust_service_providers_api.html#abc810ca189dc869c597fc122a34d0951',
        1,
        'DocuSign.eSign.Api.TrustServiceProvidersApi.SignHashSessionInfoAsyncWithHttpInfo()',
      ],
    ],
  ],
  [
    'signhashsessioninforesponse',
    [
      'SignHashSessionInfoResponse',
      [
        '../class_docu_sign_1_1e_sign_1_1_model_1_1_sign_hash_session_info_response.html#af5dbdd16cda3f3f6eeb7952d72e20846',
        1,
        'DocuSign.eSign.Model.SignHashSessionInfoResponse.SignHashSessionInfoResponse()',
      ],
      [
        '../class_docu_sign_1_1e_sign_1_1_model_1_1_sign_hash_session_info_response.html#a69d5248a1701d764ab2bcb7e091dd1e8',
        1,
        'DocuSign.eSign.Model.SignHashSessionInfoResponse.SignHashSessionInfoResponse(List&lt; SignHashDocument &gt; Documents=default(List&lt; SignHashDocument &gt;), string EnvelopeId=default(string), string Language=default(string), string RedirectionUrl=default(string), long?RemainingSignatureRequests=default(long?), Seal Seal=default(Seal), Sender Sender=default(Sender), User User=default(User))',
      ],
    ],
  ],
  [
    'signhashsessioninfowithhttpinfo',
    [
      'SignHashSessionInfoWithHttpInfo',
      [
        '../interface_docu_sign_1_1e_sign_1_1_api_1_1_i_signature_api.html#a18d79034d849e0bea68616d2900de29a',
        1,
        'DocuSign.eSign.Api.ISignatureApi.SignHashSessionInfoWithHttpInfo()',
      ],
      [
        '../class_docu_sign_1_1e_sign_1_1_api_1_1_signature_api.html#aea8c2c1c43768ca700820d3fbff47f35',
        1,
        'DocuSign.eSign.Api.SignatureApi.SignHashSessionInfoWithHttpInfo()',
      ],
      [
        '../interface_docu_sign_1_1e_sign_1_1_api_1_1_i_trust_service_providers_api.html#a50dace15eb574f1c027c7e15feea8448',
        1,
        'DocuSign.eSign.Api.ITrustServiceProvidersApi.SignHashSessionInfoWithHttpInfo()',
      ],
      [
        '../class_docu_sign_1_1e_sign_1_1_api_1_1_trust_service_providers_api.html#a0e903ef3e27f4c559552deed07447765',
        1,
        'DocuSign.eSign.Api.TrustServiceProvidersApi.SignHashSessionInfoWithHttpInfo()',
      ],
    ],
  ],
  [
    'signhere',
    [
      'SignHere',
      [
        '../class_docu_sign_1_1e_sign_1_1_model_1_1_sign_here.html#a4fcf4c9e07dce9bdadb15c16900aa609',
        1,
        'DocuSign.eSign.Model.SignHere.SignHere()',
      ],
      [
        '../class_docu_sign_1_1e_sign_1_1_model_1_1_sign_here.html#a88c35481b1281ed501b42f600b675316',
        1,
        'DocuSign.eSign.Model.SignHere.SignHere(string AnchorAllowWhiteSpaceInCharacters=default(string), PropertyMetadata AnchorAllowWhiteSpaceInCharactersMetadata=default(PropertyMetadata), string AnchorCaseSensitive=default(string), PropertyMetadata AnchorCaseSensitiveMetadata=default(PropertyMetadata), string AnchorHorizontalAlignment=default(string), PropertyMetadata AnchorHorizontalAlignmentMetadata=default(PropertyMetadata), string AnchorIgnoreIfNotPresent=default(string), PropertyMetadata AnchorIgnoreIfNotPresentMetadata=default(PropertyMetadata), string AnchorMatchWholeWord=default(string), PropertyMetadata AnchorMatchWholeWordMetadata=default(PropertyMetadata), string AnchorString=default(string), PropertyMetadata AnchorStringMetadata=default(PropertyMetadata), string AnchorTabProcessorVersion=default(string), PropertyMetadata AnchorTabProcessorVersionMetadata=default(PropertyMetadata), string AnchorUnits=default(string), PropertyMetadata AnchorUnitsMetadata=default(PropertyMetadata), string AnchorXOffset=default(string), PropertyMetadata AnchorXOffsetMetadata=default(PropertyMetadata), string AnchorYOffset=default(string), PropertyMetadata AnchorYOffsetMetadata=default(PropertyMetadata), string ConditionalParentLabel=default(string), PropertyMetadata ConditionalParentLabelMetadata=default(PropertyMetadata), string ConditionalParentValue=default(string), PropertyMetadata ConditionalParentValueMetadata=default(PropertyMetadata), string CustomTabId=default(string), PropertyMetadata CustomTabIdMetadata=default(PropertyMetadata), string DocumentId=default(string), PropertyMetadata DocumentIdMetadata=default(PropertyMetadata), ErrorDetails ErrorDetails=default(ErrorDetails), string FormOrder=default(string), PropertyMetadata FormOrderMetadata=default(PropertyMetadata), string FormPageLabel=default(string), PropertyMetadata FormPageLabelMetadata=default(PropertyMetadata), string FormPageNumber=default(string), PropertyMetadata FormPageNumberMetadata=default(PropertyMetadata), string Height=default(string), PropertyMetadata HeightMetadata=default(PropertyMetadata), string IsSealSignTab=default(string), MergeField MergeField=default(MergeField), string MergeFieldXml=default(string), string Name=default(string), PropertyMetadata NameMetadata=default(PropertyMetadata), string Optional=default(string), PropertyMetadata OptionalMetadata=default(PropertyMetadata), string PageNumber=default(string), PropertyMetadata PageNumberMetadata=default(PropertyMetadata), string RecipientId=default(string), string RecipientIdGuid=default(string), PropertyMetadata RecipientIdGuidMetadata=default(PropertyMetadata), PropertyMetadata RecipientIdMetadata=default(PropertyMetadata), string ScaleValue=default(string), PropertyMetadata ScaleValueMetadata=default(PropertyMetadata), SmartContractInformation SmartContractInformation=default(SmartContractInformation), string Source=default(string), Stamp Stamp=default(Stamp), string StampType=default(string), PropertyMetadata StampTypeMetadata=default(PropertyMetadata), string Status=default(string), PropertyMetadata StatusMetadata=default(PropertyMetadata), List&lt; string &gt; TabGroupLabels=default(List&lt; string &gt;), PropertyMetadata TabGroupLabelsMetadata=default(PropertyMetadata), string TabId=default(string), PropertyMetadata TabIdMetadata=default(PropertyMetadata), string TabLabel=default(string), PropertyMetadata TabLabelMetadata=default(PropertyMetadata), string TabOrder=default(string), PropertyMetadata TabOrderMetadata=default(PropertyMetadata), string TabType=default(string), PropertyMetadata TabTypeMetadata=default(PropertyMetadata), string TemplateLocked=default(string), PropertyMetadata TemplateLockedMetadata=default(PropertyMetadata), string TemplateRequired=default(string), PropertyMetadata TemplateRequiredMetadata=default(PropertyMetadata), string Tooltip=default(string), PropertyMetadata ToolTipMetadata=default(PropertyMetadata), string Width=default(string), PropertyMetadata WidthMetadata=default(PropertyMetadata), string XPosition=default(string), PropertyMetadata XPositionMetadata=default(PropertyMetadata), string YPosition=default(string), PropertyMetadata YPositionMetadata=default(PropertyMetadata))',
      ],
    ],
  ],
  [
    'signinggroup',
    [
      'SigningGroup',
      [
        '../class_docu_sign_1_1e_sign_1_1_model_1_1_signing_group.html#ac130193da634a4ccfb5040abb14de0b0',
        1,
        'DocuSign.eSign.Model.SigningGroup.SigningGroup()',
      ],
      [
        '../class_docu_sign_1_1e_sign_1_1_model_1_1_signing_group.html#a885baeb0d6e274198096e5799d55ec01',
        1,
        'DocuSign.eSign.Model.SigningGroup.SigningGroup(string Created=default(string), string CreatedBy=default(string), ErrorDetails ErrorDetails=default(ErrorDetails), string GroupEmail=default(string), string GroupName=default(string), string GroupType=default(string), string Modified=default(string), string ModifiedBy=default(string), string SigningGroupId=default(string), List&lt; SigningGroupUser &gt; Users=default(List&lt; SigningGroupUser &gt;))',
      ],
    ],
  ],
  [
    'signinggroupinformation',
    [
      'SigningGroupInformation',
      [
        '../class_docu_sign_1_1e_sign_1_1_model_1_1_signing_group_information.html#aa0440c4df2d454a49f7723135624949c',
        1,
        'DocuSign.eSign.Model.SigningGroupInformation.SigningGroupInformation()',
      ],
      [
        '../class_docu_sign_1_1e_sign_1_1_model_1_1_signing_group_information.html#aac6c31c424a81562d10dc3cf5ee8644e',
        1,
        'DocuSign.eSign.Model.SigningGroupInformation.SigningGroupInformation(List&lt; SigningGroup &gt; Groups=default(List&lt; SigningGroup &gt;))',
      ],
    ],
  ],
  [
    'signinggroupsapi',
    [
      'SigningGroupsApi',
      [
        '../class_docu_sign_1_1e_sign_1_1_api_1_1_signing_groups_api.html#a34c2f3c2f27d00a7939f7bc0286783ab',
        1,
        'DocuSign::eSign::Api::SigningGroupsApi',
      ],
    ],
  ],
  [
    'signinggroupuser',
    [
      'SigningGroupUser',
      [
        '../class_docu_sign_1_1e_sign_1_1_model_1_1_signing_group_user.html#ac700211ddadd84c47d91b11c5469e944',
        1,
        'DocuSign.eSign.Model.SigningGroupUser.SigningGroupUser()',
      ],
      [
        '../class_docu_sign_1_1e_sign_1_1_model_1_1_signing_group_user.html#a5406a3efbaac9fbdb2e2fbc3addd9295',
        1,
        'DocuSign.eSign.Model.SigningGroupUser.SigningGroupUser(string Email=default(string), ErrorDetails ErrorDetails=default(ErrorDetails), string UserName=default(string))',
      ],
    ],
  ],
  [
    'signinggroupusers',
    [
      'SigningGroupUsers',
      [
        '../class_docu_sign_1_1e_sign_1_1_model_1_1_signing_group_users.html#a02883cf5e7f5f26a60a3559cee861b29',
        1,
        'DocuSign.eSign.Model.SigningGroupUsers.SigningGroupUsers()',
      ],
      [
        '../class_docu_sign_1_1e_sign_1_1_model_1_1_signing_group_users.html#ab1f5c81c5888923bce42b05af35a3f0c',
        1,
        'DocuSign.eSign.Model.SigningGroupUsers.SigningGroupUsers(List&lt; SigningGroupUser &gt; Users=default(List&lt; SigningGroupUser &gt;))',
      ],
    ],
  ],
  [
    'signsessioninforequest',
    [
      'SignSessionInfoRequest',
      [
        '../class_docu_sign_1_1e_sign_1_1_model_1_1_sign_session_info_request.html#a7d101ffb71fa2551dc55a006414fe042',
        1,
        'DocuSign.eSign.Model.SignSessionInfoRequest.SignSessionInfoRequest()',
      ],
      [
        '../class_docu_sign_1_1e_sign_1_1_model_1_1_sign_session_info_request.html#a4ed61324280643081f0fc17e082eb4f1',
        1,
        'DocuSign.eSign.Model.SignSessionInfoRequest.SignSessionInfoRequest(string Certificate=default(string), string MaxSignatureLength=default(string), string ReturnFormat=default(string), string SigningLocation=default(string))',
      ],
    ],
  ],
  [
    'smartcontractinformation',
    [
      'SmartContractInformation',
      [
        '../class_docu_sign_1_1e_sign_1_1_model_1_1_smart_contract_information.html#aee6ccaebdb8a5b8bcecb685b331f6d45',
        1,
        'DocuSign.eSign.Model.SmartContractInformation.SmartContractInformation()',
      ],
      [
        '../class_docu_sign_1_1e_sign_1_1_model_1_1_smart_contract_information.html#a727a08456c148f564c21936ab3a48afd',
        1,
        'DocuSign.eSign.Model.SmartContractInformation.SmartContractInformation(string Code=default(string), string Uri=default(string))',
      ],
    ],
  ],
  [
    'smartsection',
    [
      'SmartSection',
      [
        '../class_docu_sign_1_1e_sign_1_1_model_1_1_smart_section.html#a49f68176b45eb5f5fd56ea5e04064ef7',
        1,
        'DocuSign.eSign.Model.SmartSection.SmartSection()',
      ],
      [
        '../class_docu_sign_1_1e_sign_1_1_model_1_1_smart_section.html#afa6f6635a2d8e81bfe665771eb373faf',
        1,
        'DocuSign.eSign.Model.SmartSection.SmartSection(string AnchorAllowWhiteSpaceInCharacters=default(string), PropertyMetadata AnchorAllowWhiteSpaceInCharactersMetadata=default(PropertyMetadata), string AnchorCaseSensitive=default(string), PropertyMetadata AnchorCaseSensitiveMetadata=default(PropertyMetadata), string AnchorHorizontalAlignment=default(string), PropertyMetadata AnchorHorizontalAlignmentMetadata=default(PropertyMetadata), string AnchorIgnoreIfNotPresent=default(string), PropertyMetadata AnchorIgnoreIfNotPresentMetadata=default(PropertyMetadata), string AnchorMatchWholeWord=default(string), PropertyMetadata AnchorMatchWholeWordMetadata=default(PropertyMetadata), string AnchorString=default(string), PropertyMetadata AnchorStringMetadata=default(PropertyMetadata), string AnchorTabProcessorVersion=default(string), PropertyMetadata AnchorTabProcessorVersionMetadata=default(PropertyMetadata), string AnchorUnits=default(string), PropertyMetadata AnchorUnitsMetadata=default(PropertyMetadata), string AnchorXOffset=default(string), PropertyMetadata AnchorXOffsetMetadata=default(PropertyMetadata), string AnchorYOffset=default(string), PropertyMetadata AnchorYOffsetMetadata=default(PropertyMetadata), bool?CaseSensitive=default(bool?), string ConditionalParentLabel=default(string), PropertyMetadata ConditionalParentLabelMetadata=default(PropertyMetadata), string ConditionalParentValue=default(string), PropertyMetadata ConditionalParentValueMetadata=default(PropertyMetadata), string CustomTabId=default(string), PropertyMetadata CustomTabIdMetadata=default(PropertyMetadata), SmartSectionDisplaySettings DisplaySettings=default(SmartSectionDisplaySettings), string DocumentId=default(string), PropertyMetadata DocumentIdMetadata=default(PropertyMetadata), string EndAnchor=default(string), SmartSectionAnchorPosition EndPosition=default(SmartSectionAnchorPosition), ErrorDetails ErrorDetails=default(ErrorDetails), string FormOrder=default(string), PropertyMetadata FormOrderMetadata=default(PropertyMetadata), string FormPageLabel=default(string), PropertyMetadata FormPageLabelMetadata=default(PropertyMetadata), string FormPageNumber=default(string), PropertyMetadata FormPageNumberMetadata=default(PropertyMetadata), string Height=default(string), PropertyMetadata HeightMetadata=default(PropertyMetadata), string Locked=default(string), PropertyMetadata LockedMetadata=default(PropertyMetadata), MergeField MergeField=default(MergeField), string MergeFieldXml=default(string), string OverlayType=default(string), PropertyMetadata OverlayTypeMetadata=default(PropertyMetadata), string PageNumber=default(string), PropertyMetadata PageNumberMetadata=default(PropertyMetadata), string RecipientId=default(string), string RecipientIdGuid=default(string), PropertyMetadata RecipientIdGuidMetadata=default(PropertyMetadata), PropertyMetadata RecipientIdMetadata=default(PropertyMetadata), bool?RemoveEndAnchor=default(bool?), bool?RemoveStartAnchor=default(bool?), string Shared=default(string), PropertyMetadata SharedMetadata=default(PropertyMetadata), SmartContractInformation SmartContractInformation=default(SmartContractInformation), string Source=default(string), string StartAnchor=default(string), SmartSectionAnchorPosition StartPosition=default(SmartSectionAnchorPosition), string Status=default(string), PropertyMetadata StatusMetadata=default(PropertyMetadata), List&lt; string &gt; TabGroupLabels=default(List&lt; string &gt;), PropertyMetadata TabGroupLabelsMetadata=default(PropertyMetadata), string TabId=default(string), PropertyMetadata TabIdMetadata=default(PropertyMetadata), string TabLabel=default(string), string TabOrder=default(string), PropertyMetadata TabOrderMetadata=default(PropertyMetadata), string TabType=default(string), PropertyMetadata TabTypeMetadata=default(PropertyMetadata), string TemplateLocked=default(string), PropertyMetadata TemplateLockedMetadata=default(PropertyMetadata), string TemplateRequired=default(string), PropertyMetadata TemplateRequiredMetadata=default(PropertyMetadata), string Tooltip=default(string), PropertyMetadata ToolTipMetadata=default(PropertyMetadata), string Width=default(string), PropertyMetadata WidthMetadata=default(PropertyMetadata), string XPosition=default(string), PropertyMetadata XPositionMetadata=default(PropertyMetadata), string YPosition=default(string), PropertyMetadata YPositionMetadata=default(PropertyMetadata))',
      ],
    ],
  ],
  [
    'smartsectionanchorposition',
    [
      'SmartSectionAnchorPosition',
      [
        '../class_docu_sign_1_1e_sign_1_1_model_1_1_smart_section_anchor_position.html#a7fdcba173682ae9f66bc969b7fce0cca',
        1,
        'DocuSign.eSign.Model.SmartSectionAnchorPosition.SmartSectionAnchorPosition()',
      ],
      [
        '../class_docu_sign_1_1e_sign_1_1_model_1_1_smart_section_anchor_position.html#a62f8400c5074e9dfc5736fc707e71729',
        1,
        'DocuSign.eSign.Model.SmartSectionAnchorPosition.SmartSectionAnchorPosition(int?PageNumber=default(int?), double?XPosition=default(double?), double?YPosition=default(double?))',
      ],
    ],
  ],
  [
    'smartsectioncollapsibledisplaysettings',
    [
      'SmartSectionCollapsibleDisplaySettings',
      [
        '../class_docu_sign_1_1e_sign_1_1_model_1_1_smart_section_collapsible_display_settings.html#af3b0935d0f5e388ecb8866824f41b309',
        1,
        'DocuSign.eSign.Model.SmartSectionCollapsibleDisplaySettings.SmartSectionCollapsibleDisplaySettings()',
      ],
      [
        '../class_docu_sign_1_1e_sign_1_1_model_1_1_smart_section_collapsible_display_settings.html#a72f29a4e7e54dc2df7d8961e4cd1995a',
        1,
        'DocuSign.eSign.Model.SmartSectionCollapsibleDisplaySettings.SmartSectionCollapsibleDisplaySettings(string ArrowClosed=default(string), string ArrowColor=default(string), string ArrowLocation=default(string), string ArrowOpen=default(string), string ArrowSize=default(string), string ArrowStyle=default(string), string ContainerStyle=default(string), string LabelStyle=default(string), bool?OnlyArrowIsClickable=default(bool?), string OuterLabelAndArrowStyle=default(string))',
      ],
    ],
  ],
  [
    'smartsectiondisplaysettings',
    [
      'SmartSectionDisplaySettings',
      [
        '../class_docu_sign_1_1e_sign_1_1_model_1_1_smart_section_display_settings.html#a7cd42e16960194ced6519004cade70a9',
        1,
        'DocuSign.eSign.Model.SmartSectionDisplaySettings.SmartSectionDisplaySettings()',
      ],
      [
        '../class_docu_sign_1_1e_sign_1_1_model_1_1_smart_section_display_settings.html#a021bdfcda6706517bb6a6b0c16d56d52',
        1,
        'DocuSign.eSign.Model.SmartSectionDisplaySettings.SmartSectionDisplaySettings(string CellStyle=default(string), SmartSectionCollapsibleDisplaySettings CollapsibleSettings=default(SmartSectionCollapsibleDisplaySettings), string Display=default(string), string DisplayLabel=default(string), int?DisplayOrder=default(int?), int?DisplayPageNumber=default(int?), bool?HideLabelWhenOpened=default(bool?), string InlineOuterStyle=default(string), string LabelWhenOpened=default(string), string PreLabel=default(string), bool?ScrollToTopWhenOpened=default(bool?), string TableStyle=default(string))',
      ],
    ],
  ],
  [
    'socialaccountinformation',
    [
      'SocialAccountInformation',
      [
        '../class_docu_sign_1_1e_sign_1_1_model_1_1_social_account_information.html#a50a38aa6eaf706549f0d8530c45281ea',
        1,
        'DocuSign.eSign.Model.SocialAccountInformation.SocialAccountInformation()',
      ],
      [
        '../class_docu_sign_1_1e_sign_1_1_model_1_1_social_account_information.html#ab7923c4e2fef11cefc9799bae33b3161',
        1,
        'DocuSign.eSign.Model.SocialAccountInformation.SocialAccountInformation(string Email=default(string), ErrorDetails ErrorDetails=default(ErrorDetails), string Provider=default(string), string SocialId=default(string), string UserName=default(string))',
      ],
    ],
  ],
  [
    'socialauthentication',
    [
      'SocialAuthentication',
      [
        '../class_docu_sign_1_1e_sign_1_1_model_1_1_social_authentication.html#a06a4f3f7bd93d3b068d92ccf82e68432',
        1,
        'DocuSign.eSign.Model.SocialAuthentication.SocialAuthentication()',
      ],
      [
        '../class_docu_sign_1_1e_sign_1_1_model_1_1_social_authentication.html#a2803918eed81fd7483d2dc4b07eb04e2',
        1,
        'DocuSign.eSign.Model.SocialAuthentication.SocialAuthentication(string Authentication=default(string))',
      ],
    ],
  ],
  [
    'ssn',
    [
      'Ssn',
      [
        '../class_docu_sign_1_1e_sign_1_1_model_1_1_ssn.html#a5b86a436ae9a0ffbd2b67bc481c25716',
        1,
        'DocuSign.eSign.Model.Ssn.Ssn()',
      ],
      [
        '../class_docu_sign_1_1e_sign_1_1_model_1_1_ssn.html#abed3a68c0e41b627fd02a2f6f54149af',
        1,
        'DocuSign.eSign.Model.Ssn.Ssn(string AnchorAllowWhiteSpaceInCharacters=default(string), PropertyMetadata AnchorAllowWhiteSpaceInCharactersMetadata=default(PropertyMetadata), string AnchorCaseSensitive=default(string), PropertyMetadata AnchorCaseSensitiveMetadata=default(PropertyMetadata), string AnchorHorizontalAlignment=default(string), PropertyMetadata AnchorHorizontalAlignmentMetadata=default(PropertyMetadata), string AnchorIgnoreIfNotPresent=default(string), PropertyMetadata AnchorIgnoreIfNotPresentMetadata=default(PropertyMetadata), string AnchorMatchWholeWord=default(string), PropertyMetadata AnchorMatchWholeWordMetadata=default(PropertyMetadata), string AnchorString=default(string), PropertyMetadata AnchorStringMetadata=default(PropertyMetadata), string AnchorTabProcessorVersion=default(string), PropertyMetadata AnchorTabProcessorVersionMetadata=default(PropertyMetadata), string AnchorUnits=default(string), PropertyMetadata AnchorUnitsMetadata=default(PropertyMetadata), string AnchorXOffset=default(string), PropertyMetadata AnchorXOffsetMetadata=default(PropertyMetadata), string AnchorYOffset=default(string), PropertyMetadata AnchorYOffsetMetadata=default(PropertyMetadata), string Bold=default(string), PropertyMetadata BoldMetadata=default(PropertyMetadata), string ConcealValueOnDocument=default(string), PropertyMetadata ConcealValueOnDocumentMetadata=default(PropertyMetadata), string ConditionalParentLabel=default(string), PropertyMetadata ConditionalParentLabelMetadata=default(PropertyMetadata), string ConditionalParentValue=default(string), PropertyMetadata ConditionalParentValueMetadata=default(PropertyMetadata), string CustomTabId=default(string), PropertyMetadata CustomTabIdMetadata=default(PropertyMetadata), string DisableAutoSize=default(string), PropertyMetadata DisableAutoSizeMetadata=default(PropertyMetadata), string DocumentId=default(string), PropertyMetadata DocumentIdMetadata=default(PropertyMetadata), ErrorDetails ErrorDetails=default(ErrorDetails), string Font=default(string), string FontColor=default(string), PropertyMetadata FontColorMetadata=default(PropertyMetadata), PropertyMetadata FontMetadata=default(PropertyMetadata), string FontSize=default(string), PropertyMetadata FontSizeMetadata=default(PropertyMetadata), string FormOrder=default(string), PropertyMetadata FormOrderMetadata=default(PropertyMetadata), string FormPageLabel=default(string), PropertyMetadata FormPageLabelMetadata=default(PropertyMetadata), string FormPageNumber=default(string), PropertyMetadata FormPageNumberMetadata=default(PropertyMetadata), string Height=default(string), PropertyMetadata HeightMetadata=default(PropertyMetadata), string Italic=default(string), PropertyMetadata ItalicMetadata=default(PropertyMetadata), LocalePolicyTab LocalePolicy=default(LocalePolicyTab), string Locked=default(string), PropertyMetadata LockedMetadata=default(PropertyMetadata), string MaxLength=default(string), PropertyMetadata MaxLengthMetadata=default(PropertyMetadata), MergeField MergeField=default(MergeField), string MergeFieldXml=default(string), string Name=default(string), PropertyMetadata NameMetadata=default(PropertyMetadata), string OriginalValue=default(string), PropertyMetadata OriginalValueMetadata=default(PropertyMetadata), string PageNumber=default(string), PropertyMetadata PageNumberMetadata=default(PropertyMetadata), string RecipientId=default(string), string RecipientIdGuid=default(string), PropertyMetadata RecipientIdGuidMetadata=default(PropertyMetadata), PropertyMetadata RecipientIdMetadata=default(PropertyMetadata), string RequireAll=default(string), PropertyMetadata RequireAllMetadata=default(PropertyMetadata), string Required=default(string), PropertyMetadata RequiredMetadata=default(PropertyMetadata), string RequireInitialOnSharedChange=default(string), PropertyMetadata RequireInitialOnSharedChangeMetadata=default(PropertyMetadata), string SenderRequired=default(string), PropertyMetadata SenderRequiredMetadata=default(PropertyMetadata), string Shared=default(string), PropertyMetadata SharedMetadata=default(PropertyMetadata), SmartContractInformation SmartContractInformation=default(SmartContractInformation), string Source=default(string), string Status=default(string), PropertyMetadata StatusMetadata=default(PropertyMetadata), List&lt; string &gt; TabGroupLabels=default(List&lt; string &gt;), PropertyMetadata TabGroupLabelsMetadata=default(PropertyMetadata), string TabId=default(string), PropertyMetadata TabIdMetadata=default(PropertyMetadata), string TabLabel=default(string), PropertyMetadata TabLabelMetadata=default(PropertyMetadata), string TabOrder=default(string), PropertyMetadata TabOrderMetadata=default(PropertyMetadata), string TabType=default(string), PropertyMetadata TabTypeMetadata=default(PropertyMetadata), string TemplateLocked=default(string), PropertyMetadata TemplateLockedMetadata=default(PropertyMetadata), string TemplateRequired=default(string), PropertyMetadata TemplateRequiredMetadata=default(PropertyMetadata), string Tooltip=default(string), PropertyMetadata ToolTipMetadata=default(PropertyMetadata), string Underline=default(string), PropertyMetadata UnderlineMetadata=default(PropertyMetadata), string ValidationMessage=default(string), PropertyMetadata ValidationMessageMetadata=default(PropertyMetadata), string ValidationPattern=default(string), PropertyMetadata ValidationPatternMetadata=default(PropertyMetadata), string Value=default(string), PropertyMetadata ValueMetadata=default(PropertyMetadata), string Width=default(string), PropertyMetadata WidthMetadata=default(PropertyMetadata), string XPosition=default(string), PropertyMetadata XPositionMetadata=default(PropertyMetadata), string YPosition=default(string), PropertyMetadata YPositionMetadata=default(PropertyMetadata))',
      ],
    ],
  ],
  [
    'ssn4informationinput',
    [
      'Ssn4InformationInput',
      [
        '../class_docu_sign_1_1e_sign_1_1_model_1_1_ssn4_information_input.html#af3872772801f9ae7cd4579d3be619e3a',
        1,
        'DocuSign.eSign.Model.Ssn4InformationInput.Ssn4InformationInput()',
      ],
      [
        '../class_docu_sign_1_1e_sign_1_1_model_1_1_ssn4_information_input.html#aa289825ba08a5172fb410ce31e8fd56a',
        1,
        'DocuSign.eSign.Model.Ssn4InformationInput.Ssn4InformationInput(string DisplayLevelCode=default(string), string ReceiveInResponse=default(string), string Ssn4=default(string))',
      ],
    ],
  ],
  [
    'ssn9informationinput',
    [
      'Ssn9InformationInput',
      [
        '../class_docu_sign_1_1e_sign_1_1_model_1_1_ssn9_information_input.html#a9ca33bca916fcc7172dbb48e85af3ffa',
        1,
        'DocuSign.eSign.Model.Ssn9InformationInput.Ssn9InformationInput()',
      ],
      [
        '../class_docu_sign_1_1e_sign_1_1_model_1_1_ssn9_information_input.html#ab64fb060f46e19727a96449be9d695e2',
        1,
        'DocuSign.eSign.Model.Ssn9InformationInput.Ssn9InformationInput(string DisplayLevelCode=default(string), string Ssn9=default(string))',
      ],
    ],
  ],
  [
    'stamp',
    [
      'Stamp',
      [
        '../class_docu_sign_1_1e_sign_1_1_model_1_1_stamp.html#a1525320bcdf82bfe2060549aea11159c',
        1,
        'DocuSign.eSign.Model.Stamp.Stamp()',
      ],
      [
        '../class_docu_sign_1_1e_sign_1_1_model_1_1_stamp.html#a0c1fa15df95ca1c00be016b373bc63a9',
        1,
        'DocuSign.eSign.Model.Stamp.Stamp(string AdoptedDateTime=default(string), string CreatedDateTime=default(string), string CustomField=default(string), DateStampProperties DateStampProperties=default(DateStampProperties), string DisallowUserResizeStamp=default(string), ErrorDetails ErrorDetails=default(ErrorDetails), string ExternalID=default(string), string ImageBase64=default(string), string ImageType=default(string), string LastModifiedDateTime=default(string), string PhoneticName=default(string), string SignatureName=default(string), string StampFormat=default(string), string StampImageUri=default(string), string StampSizeMM=default(string), string Status=default(string))',
      ],
    ],
  ],
  [
    'supportedlanguages',
    [
      'SupportedLanguages',
      [
        '../class_docu_sign_1_1e_sign_1_1_model_1_1_supported_languages.html#a0719f01909b90ff8bc38241dcfde11f2',
        1,
        'DocuSign.eSign.Model.SupportedLanguages.SupportedLanguages()',
      ],
      [
        '../class_docu_sign_1_1e_sign_1_1_model_1_1_supported_languages.html#ab54f283ff94f5b610929cc69e579fe6c',
        1,
        'DocuSign.eSign.Model.SupportedLanguages.SupportedLanguages(List&lt; NameValue &gt; Languages=default(List&lt; NameValue &gt;))',
      ],
    ],
  ],
  [
    'swaggerdateconverter',
    [
      'SwaggerDateConverter',
      [
        '../class_docu_sign_1_1e_sign_1_1_client_1_1_swagger_date_converter.html#a358ef45fb27c0832e718890d968e1239',
        1,
        'DocuSign::eSign::Client::SwaggerDateConverter',
      ],
    ],
  ],
];
