var searchData = [
  [
    'page',
    [
      'Page',
      [
        '../class_docu_sign_1_1e_sign_1_1_model_1_1_page.html#a700bb91fac4b15fa283d7ff250021c33',
        1,
        'DocuSign.eSign.Model.Page.Page()',
      ],
      [
        '../class_docu_sign_1_1e_sign_1_1_model_1_1_page.html#ab312eb196a8e695fcee7e68f2b76501b',
        1,
        'DocuSign.eSign.Model.Page.Page(string Dpi=default(string), ErrorDetails ErrorDetails=default(ErrorDetails), string Height=default(string), string ImageBytes=default(string), string MimeType=default(string), string PageId=default(string), string Sequence=default(string), string Width=default(string))',
      ],
    ],
  ],
  [
    'pageimages',
    [
      'PageImages',
      [
        '../class_docu_sign_1_1e_sign_1_1_model_1_1_page_images.html#a1a83b3403ecdee23c2840db852d8185f',
        1,
        'DocuSign.eSign.Model.PageImages.PageImages()',
      ],
      [
        '../class_docu_sign_1_1e_sign_1_1_model_1_1_page_images.html#a308b2eb132f465cdd94821d0eef699de',
        1,
        'DocuSign.eSign.Model.PageImages.PageImages(string EndPosition=default(string), string NextUri=default(string), List&lt; Page &gt; Pages=default(List&lt; Page &gt;), string PreviousUri=default(string), string ResultSetSize=default(string), string StartPosition=default(string), string TotalSetSize=default(string))',
      ],
    ],
  ],
  [
    'pagerequest',
    [
      'PageRequest',
      [
        '../class_docu_sign_1_1e_sign_1_1_model_1_1_page_request.html#a79495c6abef08bd84c3b2d4a24e79a86',
        1,
        'DocuSign.eSign.Model.PageRequest.PageRequest()',
      ],
      [
        '../class_docu_sign_1_1e_sign_1_1_model_1_1_page_request.html#a91d0724f1f9ae0620ba5a643cfb18991',
        1,
        'DocuSign.eSign.Model.PageRequest.PageRequest(string Password=default(string), string Rotate=default(string))',
      ],
    ],
  ],
  [
    'pagesize',
    [
      'PageSize',
      [
        '../class_docu_sign_1_1e_sign_1_1_model_1_1_page_size.html#ae9e35c623981d16fc3c9cbd2b2df671a',
        1,
        'DocuSign.eSign.Model.PageSize.PageSize()',
      ],
      [
        '../class_docu_sign_1_1e_sign_1_1_model_1_1_page_size.html#a9302286ea0e89aeaa646365fa70d3008',
        1,
        'DocuSign.eSign.Model.PageSize.PageSize(string PageHeight=default(string), string PageWidth=default(string))',
      ],
    ],
  ],
  [
    'parametertofile',
    [
      'ParameterToFile',
      [
        '../class_docu_sign_1_1e_sign_1_1_client_1_1_api_client.html#a2caefcdef436737acdcf618b6a4ab5fd',
        1,
        'DocuSign::eSign::Client::ApiClient',
      ],
    ],
  ],
  [
    'parametertostring',
    [
      'ParameterToString',
      [
        '../class_docu_sign_1_1e_sign_1_1_client_1_1_api_client.html#ade9f6ab08e3daa8bb9650c08b06cc654',
        1,
        'DocuSign::eSign::Client::ApiClient',
      ],
    ],
  ],
  [
    'pathextendedelement',
    [
      'PathExtendedElement',
      [
        '../class_docu_sign_1_1e_sign_1_1_model_1_1_path_extended_element.html#aca93b14b9395611e8cd0a0656b8269b3',
        1,
        'DocuSign.eSign.Model.PathExtendedElement.PathExtendedElement()',
      ],
      [
        '../class_docu_sign_1_1e_sign_1_1_model_1_1_path_extended_element.html#aeb8c84a601a1bd0773c0ea225c86bdd6',
        1,
        'DocuSign.eSign.Model.PathExtendedElement.PathExtendedElement(string Name=default(string), string Type=default(string), string TypeName=default(string))',
      ],
    ],
  ],
  [
    'paymentdetails',
    [
      'PaymentDetails',
      [
        '../class_docu_sign_1_1e_sign_1_1_model_1_1_payment_details.html#afb39bb94a95389cce8e4cbcd143ded8f',
        1,
        'DocuSign.eSign.Model.PaymentDetails.PaymentDetails()',
      ],
      [
        '../class_docu_sign_1_1e_sign_1_1_model_1_1_payment_details.html#a5ca947b82871ad7c58beebe10aa99432',
        1,
        'DocuSign.eSign.Model.PaymentDetails.PaymentDetails(List&lt; string &gt; AllowedPaymentMethods=default(List&lt; string &gt;), string ChargeId=default(string), string CurrencyCode=default(string), PropertyMetadata CurrencyCodeMetadata=default(PropertyMetadata), string CustomerId=default(string), string CustomMetadata=default(string), bool?CustomMetadataRequired=default(bool?), string GatewayAccountId=default(string), PropertyMetadata GatewayAccountIdMetadata=default(PropertyMetadata), string GatewayDisplayName=default(string), string GatewayName=default(string), List&lt; PaymentLineItem &gt; LineItems=default(List&lt; PaymentLineItem &gt;), string PaymentOption=default(string), string PaymentSourceId=default(string), PaymentSignerValues SignerValues=default(PaymentSignerValues), string Status=default(string), Money Total=default(Money))',
      ],
    ],
  ],
  [
    'paymentgatewayaccount',
    [
      'PaymentGatewayAccount',
      [
        '../class_docu_sign_1_1e_sign_1_1_model_1_1_payment_gateway_account.html#a01d954df81fffea3830b4491e1ba15ce',
        1,
        'DocuSign.eSign.Model.PaymentGatewayAccount.PaymentGatewayAccount()',
      ],
      [
        '../class_docu_sign_1_1e_sign_1_1_model_1_1_payment_gateway_account.html#a3b5f1a00290599a487a4a146ef309891',
        1,
        'DocuSign.eSign.Model.PaymentGatewayAccount.PaymentGatewayAccount(bool?AllowCustomMetadata=default(bool?), PaymentGatewayAccountSetting Config=default(PaymentGatewayAccountSetting), string DisplayName=default(string), string IsEnabled=default(string), string IsLegacy=default(string), string LastModified=default(string), string PaymentGateway=default(string), string PaymentGatewayAccountId=default(string), string PaymentGatewayDisplayName=default(string), PayPalLegacySettings PayPalLegacySettings=default(PayPalLegacySettings), List&lt; string &gt; SupportedCurrencies=default(List&lt; string &gt;), List&lt; string &gt; SupportedPaymentMethods=default(List&lt; string &gt;), List&lt; PaymentMethodWithOptions &gt; SupportedPaymentMethodsWithOptions=default(List&lt; PaymentMethodWithOptions &gt;), List&lt; string &gt; ZeroDecimalCurrencies=default(List&lt; string &gt;))',
      ],
    ],
  ],
  [
    'paymentgatewayaccountsetting',
    [
      'PaymentGatewayAccountSetting',
      [
        '../class_docu_sign_1_1e_sign_1_1_model_1_1_payment_gateway_account_setting.html#a623ae7d1a6c90f64e428028d424e0766',
        1,
        'DocuSign.eSign.Model.PaymentGatewayAccountSetting.PaymentGatewayAccountSetting()',
      ],
      [
        '../class_docu_sign_1_1e_sign_1_1_model_1_1_payment_gateway_account_setting.html#a315af7e9d981f07f79774e7d2e9f532e',
        1,
        'DocuSign.eSign.Model.PaymentGatewayAccountSetting.PaymentGatewayAccountSetting(string ApiFields=default(string), string AuthorizationCode=default(string), string CredentialStatus=default(string), string MerchantId=default(string))',
      ],
    ],
  ],
  [
    'paymentgatewayaccountsinfo',
    [
      'PaymentGatewayAccountsInfo',
      [
        '../class_docu_sign_1_1e_sign_1_1_model_1_1_payment_gateway_accounts_info.html#a2a4b51b8b9c35e9460a409dc9c05211b',
        1,
        'DocuSign.eSign.Model.PaymentGatewayAccountsInfo.PaymentGatewayAccountsInfo()',
      ],
      [
        '../class_docu_sign_1_1e_sign_1_1_model_1_1_payment_gateway_accounts_info.html#a1809b9bbc4413b57ea2a82692463a1f3',
        1,
        'DocuSign.eSign.Model.PaymentGatewayAccountsInfo.PaymentGatewayAccountsInfo(List&lt; PaymentGatewayAccount &gt; PaymentGatewayAccounts=default(List&lt; PaymentGatewayAccount &gt;))',
      ],
    ],
  ],
  [
    'paymentlineitem',
    [
      'PaymentLineItem',
      [
        '../class_docu_sign_1_1e_sign_1_1_model_1_1_payment_line_item.html#a88c2fbccbab785bc7be466ba7c6cad56',
        1,
        'DocuSign.eSign.Model.PaymentLineItem.PaymentLineItem()',
      ],
      [
        '../class_docu_sign_1_1e_sign_1_1_model_1_1_payment_line_item.html#a0fb392bf0ada7cd6ad379c678d957e68',
        1,
        'DocuSign.eSign.Model.PaymentLineItem.PaymentLineItem(string AmountReference=default(string), string Description=default(string), string ItemCode=default(string), string Name=default(string))',
      ],
    ],
  ],
  [
    'paymentmethodwithoptions',
    [
      'PaymentMethodWithOptions',
      [
        '../class_docu_sign_1_1e_sign_1_1_model_1_1_payment_method_with_options.html#a192c9dcfb7452ad26da96b58a2858249',
        1,
        'DocuSign.eSign.Model.PaymentMethodWithOptions.PaymentMethodWithOptions()',
      ],
      [
        '../class_docu_sign_1_1e_sign_1_1_model_1_1_payment_method_with_options.html#add0d43a3e2febc5ec14f982c9aba0284',
        1,
        'DocuSign.eSign.Model.PaymentMethodWithOptions.PaymentMethodWithOptions(List&lt; string &gt; SupportedOptions=default(List&lt; string &gt;), string Type=default(string))',
      ],
    ],
  ],
  [
    'paymentprocessorinformation',
    [
      'PaymentProcessorInformation',
      [
        '../class_docu_sign_1_1e_sign_1_1_model_1_1_payment_processor_information.html#a77693c726473698f57e00b5646f82a1e',
        1,
        'DocuSign.eSign.Model.PaymentProcessorInformation.PaymentProcessorInformation()',
      ],
      [
        '../class_docu_sign_1_1e_sign_1_1_model_1_1_payment_processor_information.html#a49d2d7d44207b81b660e4b87b26f7ab9',
        1,
        'DocuSign.eSign.Model.PaymentProcessorInformation.PaymentProcessorInformation(AddressInformation Address=default(AddressInformation), string BillingAgreementId=default(string), string Email=default(string))',
      ],
    ],
  ],
  [
    'paymentsignervalues',
    [
      'PaymentSignerValues',
      [
        '../class_docu_sign_1_1e_sign_1_1_model_1_1_payment_signer_values.html#aecc36b9933c85197506f20712dacbb6b',
        1,
        'DocuSign.eSign.Model.PaymentSignerValues.PaymentSignerValues()',
      ],
      [
        '../class_docu_sign_1_1e_sign_1_1_model_1_1_payment_signer_values.html#a3418663e565c13586f9df7435135aa80',
        1,
        'DocuSign.eSign.Model.PaymentSignerValues.PaymentSignerValues(string PaymentOption=default(string))',
      ],
    ],
  ],
  [
    'paypallegacysettings',
    [
      'PayPalLegacySettings',
      [
        '../class_docu_sign_1_1e_sign_1_1_model_1_1_pay_pal_legacy_settings.html#a032f612fa3334fabde4a003e7a8388b8',
        1,
        'DocuSign.eSign.Model.PayPalLegacySettings.PayPalLegacySettings()',
      ],
      [
        '../class_docu_sign_1_1e_sign_1_1_model_1_1_pay_pal_legacy_settings.html#a1c52803d33b708f63b61854c051fb546',
        1,
        'DocuSign.eSign.Model.PayPalLegacySettings.PayPalLegacySettings(string Currency=default(string), string Partner=default(string), string Password=default(string), string UserName=default(string), string Vendor=default(string))',
      ],
    ],
  ],
  [
    'permissionprofile',
    [
      'PermissionProfile',
      [
        '../class_docu_sign_1_1e_sign_1_1_model_1_1_permission_profile.html#af3fc153e3965cb43a109d5e052e31870',
        1,
        'DocuSign.eSign.Model.PermissionProfile.PermissionProfile()',
      ],
      [
        '../class_docu_sign_1_1e_sign_1_1_model_1_1_permission_profile.html#ade9cb8b09ebc9dd92589316dadb3282f',
        1,
        'DocuSign.eSign.Model.PermissionProfile.PermissionProfile(string ModifiedByUsername=default(string), string ModifiedDateTime=default(string), string PermissionProfileId=default(string), string PermissionProfileName=default(string), AccountRoleSettings Settings=default(AccountRoleSettings), string UserCount=default(string), List&lt; UserInformation &gt; Users=default(List&lt; UserInformation &gt;))',
      ],
    ],
  ],
  [
    'permissionprofileinformation',
    [
      'PermissionProfileInformation',
      [
        '../class_docu_sign_1_1e_sign_1_1_model_1_1_permission_profile_information.html#a743b06f81bf654c229d1ae028cf15ce6',
        1,
        'DocuSign.eSign.Model.PermissionProfileInformation.PermissionProfileInformation()',
      ],
      [
        '../class_docu_sign_1_1e_sign_1_1_model_1_1_permission_profile_information.html#a42c80216d5a076991f5803f54b950449',
        1,
        'DocuSign.eSign.Model.PermissionProfileInformation.PermissionProfileInformation(List&lt; PermissionProfile &gt; PermissionProfiles=default(List&lt; PermissionProfile &gt;))',
      ],
    ],
  ],
  [
    'phonenumber',
    [
      'PhoneNumber',
      [
        '../class_docu_sign_1_1e_sign_1_1_model_1_1_phone_number.html#a492050297c82d21af9a993296278e718',
        1,
        'DocuSign.eSign.Model.PhoneNumber.PhoneNumber()',
      ],
      [
        '../class_docu_sign_1_1e_sign_1_1_model_1_1_phone_number.html#a1844a9a2232a8b3b8f93a4c94048e489',
        1,
        'DocuSign.eSign.Model.PhoneNumber.PhoneNumber(string AnchorAllowWhiteSpaceInCharacters=default(string), PropertyMetadata AnchorAllowWhiteSpaceInCharactersMetadata=default(PropertyMetadata), string AnchorCaseSensitive=default(string), PropertyMetadata AnchorCaseSensitiveMetadata=default(PropertyMetadata), string AnchorHorizontalAlignment=default(string), PropertyMetadata AnchorHorizontalAlignmentMetadata=default(PropertyMetadata), string AnchorIgnoreIfNotPresent=default(string), PropertyMetadata AnchorIgnoreIfNotPresentMetadata=default(PropertyMetadata), string AnchorMatchWholeWord=default(string), PropertyMetadata AnchorMatchWholeWordMetadata=default(PropertyMetadata), string AnchorString=default(string), PropertyMetadata AnchorStringMetadata=default(PropertyMetadata), string AnchorTabProcessorVersion=default(string), PropertyMetadata AnchorTabProcessorVersionMetadata=default(PropertyMetadata), string AnchorUnits=default(string), PropertyMetadata AnchorUnitsMetadata=default(PropertyMetadata), string AnchorXOffset=default(string), PropertyMetadata AnchorXOffsetMetadata=default(PropertyMetadata), string AnchorYOffset=default(string), PropertyMetadata AnchorYOffsetMetadata=default(PropertyMetadata), string Bold=default(string), PropertyMetadata BoldMetadata=default(PropertyMetadata), string ConcealValueOnDocument=default(string), PropertyMetadata ConcealValueOnDocumentMetadata=default(PropertyMetadata), string ConditionalParentLabel=default(string), PropertyMetadata ConditionalParentLabelMetadata=default(PropertyMetadata), string ConditionalParentValue=default(string), PropertyMetadata ConditionalParentValueMetadata=default(PropertyMetadata), string CustomTabId=default(string), PropertyMetadata CustomTabIdMetadata=default(PropertyMetadata), string DisableAutoSize=default(string), PropertyMetadata DisableAutoSizeMetadata=default(PropertyMetadata), string DocumentId=default(string), PropertyMetadata DocumentIdMetadata=default(PropertyMetadata), ErrorDetails ErrorDetails=default(ErrorDetails), string Font=default(string), string FontColor=default(string), PropertyMetadata FontColorMetadata=default(PropertyMetadata), PropertyMetadata FontMetadata=default(PropertyMetadata), string FontSize=default(string), PropertyMetadata FontSizeMetadata=default(PropertyMetadata), string FormOrder=default(string), PropertyMetadata FormOrderMetadata=default(PropertyMetadata), string FormPageLabel=default(string), PropertyMetadata FormPageLabelMetadata=default(PropertyMetadata), string FormPageNumber=default(string), PropertyMetadata FormPageNumberMetadata=default(PropertyMetadata), string Height=default(string), PropertyMetadata HeightMetadata=default(PropertyMetadata), string Italic=default(string), PropertyMetadata ItalicMetadata=default(PropertyMetadata), LocalePolicyTab LocalePolicy=default(LocalePolicyTab), string Locked=default(string), PropertyMetadata LockedMetadata=default(PropertyMetadata), string MaxLength=default(string), PropertyMetadata MaxLengthMetadata=default(PropertyMetadata), MergeField MergeField=default(MergeField), string MergeFieldXml=default(string), string Name=default(string), PropertyMetadata NameMetadata=default(PropertyMetadata), string OriginalValue=default(string), PropertyMetadata OriginalValueMetadata=default(PropertyMetadata), string PageNumber=default(string), PropertyMetadata PageNumberMetadata=default(PropertyMetadata), string RecipientId=default(string), string RecipientIdGuid=default(string), PropertyMetadata RecipientIdGuidMetadata=default(PropertyMetadata), PropertyMetadata RecipientIdMetadata=default(PropertyMetadata), string Required=default(string), PropertyMetadata RequiredMetadata=default(PropertyMetadata), SmartContractInformation SmartContractInformation=default(SmartContractInformation), string Source=default(string), string Status=default(string), PropertyMetadata StatusMetadata=default(PropertyMetadata), List&lt; string &gt; TabGroupLabels=default(List&lt; string &gt;), PropertyMetadata TabGroupLabelsMetadata=default(PropertyMetadata), string TabId=default(string), PropertyMetadata TabIdMetadata=default(PropertyMetadata), string TabLabel=default(string), PropertyMetadata TabLabelMetadata=default(PropertyMetadata), string TabOrder=default(string), PropertyMetadata TabOrderMetadata=default(PropertyMetadata), string TabType=default(string), PropertyMetadata TabTypeMetadata=default(PropertyMetadata), string TemplateLocked=default(string), PropertyMetadata TemplateLockedMetadata=default(PropertyMetadata), string TemplateRequired=default(string), PropertyMetadata TemplateRequiredMetadata=default(PropertyMetadata), string Tooltip=default(string), PropertyMetadata ToolTipMetadata=default(PropertyMetadata), string Underline=default(string), PropertyMetadata UnderlineMetadata=default(PropertyMetadata), string Value=default(string), PropertyMetadata ValueMetadata=default(PropertyMetadata), string Width=default(string), PropertyMetadata WidthMetadata=default(PropertyMetadata), string XPosition=default(string), PropertyMetadata XPositionMetadata=default(PropertyMetadata), string YPosition=default(string), PropertyMetadata YPositionMetadata=default(PropertyMetadata))',
      ],
    ],
  ],
  [
    'planinformation',
    [
      'PlanInformation',
      [
        '../class_docu_sign_1_1e_sign_1_1_model_1_1_plan_information.html#a55a29cf970f45e9897dcbdba2d936e5d',
        1,
        'DocuSign.eSign.Model.PlanInformation.PlanInformation()',
      ],
      [
        '../class_docu_sign_1_1e_sign_1_1_model_1_1_plan_information.html#aa65a3845fcb9583195d753bd434fd4d1',
        1,
        'DocuSign.eSign.Model.PlanInformation.PlanInformation(List&lt; AddOn &gt; AddOns=default(List&lt; AddOn &gt;), string CurrencyCode=default(string), string FreeTrialDaysOverride=default(string), List&lt; FeatureSet &gt; PlanFeatureSets=default(List&lt; FeatureSet &gt;), string PlanId=default(string), List&lt; RecipientDomain &gt; RecipientDomains=default(List&lt; RecipientDomain &gt;))',
      ],
    ],
  ],
  [
    'polyline',
    [
      'PolyLine',
      [
        '../class_docu_sign_1_1e_sign_1_1_model_1_1_poly_line.html#a3c04f59a88ac16003b23f0f3d483839f',
        1,
        'DocuSign.eSign.Model.PolyLine.PolyLine()',
      ],
      [
        '../class_docu_sign_1_1e_sign_1_1_model_1_1_poly_line.html#a68e5b4afcfd9bce3e2fae177764a590c',
        1,
        'DocuSign.eSign.Model.PolyLine.PolyLine(string X1=default(string), string X2=default(string), string Y1=default(string), string Y2=default(string))',
      ],
    ],
  ],
  [
    'polylineoverlay',
    [
      'PolyLineOverlay',
      [
        '../class_docu_sign_1_1e_sign_1_1_model_1_1_poly_line_overlay.html#a3092ad30da5cd27e2ec4415b6a9f4fa1',
        1,
        'DocuSign.eSign.Model.PolyLineOverlay.PolyLineOverlay()',
      ],
      [
        '../class_docu_sign_1_1e_sign_1_1_model_1_1_poly_line_overlay.html#a734347659a95aa558982e5cda3a66052',
        1,
        'DocuSign.eSign.Model.PolyLineOverlay.PolyLineOverlay(string AnchorAllowWhiteSpaceInCharacters=default(string), PropertyMetadata AnchorAllowWhiteSpaceInCharactersMetadata=default(PropertyMetadata), string AnchorCaseSensitive=default(string), PropertyMetadata AnchorCaseSensitiveMetadata=default(PropertyMetadata), string AnchorHorizontalAlignment=default(string), PropertyMetadata AnchorHorizontalAlignmentMetadata=default(PropertyMetadata), string AnchorIgnoreIfNotPresent=default(string), PropertyMetadata AnchorIgnoreIfNotPresentMetadata=default(PropertyMetadata), string AnchorMatchWholeWord=default(string), PropertyMetadata AnchorMatchWholeWordMetadata=default(PropertyMetadata), string AnchorString=default(string), PropertyMetadata AnchorStringMetadata=default(PropertyMetadata), string AnchorTabProcessorVersion=default(string), PropertyMetadata AnchorTabProcessorVersionMetadata=default(PropertyMetadata), string AnchorUnits=default(string), PropertyMetadata AnchorUnitsMetadata=default(PropertyMetadata), string AnchorXOffset=default(string), PropertyMetadata AnchorXOffsetMetadata=default(PropertyMetadata), string AnchorYOffset=default(string), PropertyMetadata AnchorYOffsetMetadata=default(PropertyMetadata), string ConditionalParentLabel=default(string), PropertyMetadata ConditionalParentLabelMetadata=default(PropertyMetadata), string ConditionalParentValue=default(string), PropertyMetadata ConditionalParentValueMetadata=default(PropertyMetadata), string CustomTabId=default(string), PropertyMetadata CustomTabIdMetadata=default(PropertyMetadata), string DocumentId=default(string), PropertyMetadata DocumentIdMetadata=default(PropertyMetadata), ErrorDetails ErrorDetails=default(ErrorDetails), string FormOrder=default(string), PropertyMetadata FormOrderMetadata=default(PropertyMetadata), string FormPageLabel=default(string), PropertyMetadata FormPageLabelMetadata=default(PropertyMetadata), string FormPageNumber=default(string), PropertyMetadata FormPageNumberMetadata=default(PropertyMetadata), GraphicsContext GraphicsContext=default(GraphicsContext), string Height=default(string), PropertyMetadata HeightMetadata=default(PropertyMetadata), string Locked=default(string), PropertyMetadata LockedMetadata=default(PropertyMetadata), MergeField MergeField=default(MergeField), string MergeFieldXml=default(string), string OverlayType=default(string), PropertyMetadata OverlayTypeMetadata=default(PropertyMetadata), string PageNumber=default(string), PropertyMetadata PageNumberMetadata=default(PropertyMetadata), List&lt; PolyLine &gt; PolyLines=default(List&lt; PolyLine &gt;), string RecipientId=default(string), string RecipientIdGuid=default(string), PropertyMetadata RecipientIdGuidMetadata=default(PropertyMetadata), PropertyMetadata RecipientIdMetadata=default(PropertyMetadata), string Shared=default(string), PropertyMetadata SharedMetadata=default(PropertyMetadata), SmartContractInformation SmartContractInformation=default(SmartContractInformation), string Source=default(string), string Status=default(string), PropertyMetadata StatusMetadata=default(PropertyMetadata), List&lt; string &gt; TabGroupLabels=default(List&lt; string &gt;), PropertyMetadata TabGroupLabelsMetadata=default(PropertyMetadata), string TabId=default(string), PropertyMetadata TabIdMetadata=default(PropertyMetadata), string TabLabel=default(string), string TabOrder=default(string), PropertyMetadata TabOrderMetadata=default(PropertyMetadata), string TabType=default(string), PropertyMetadata TabTypeMetadata=default(PropertyMetadata), string TemplateLocked=default(string), PropertyMetadata TemplateLockedMetadata=default(PropertyMetadata), string TemplateRequired=default(string), PropertyMetadata TemplateRequiredMetadata=default(PropertyMetadata), string Tooltip=default(string), PropertyMetadata ToolTipMetadata=default(PropertyMetadata), string Width=default(string), PropertyMetadata WidthMetadata=default(PropertyMetadata), string XPosition=default(string), PropertyMetadata XPositionMetadata=default(PropertyMetadata), string YPosition=default(string), PropertyMetadata YPositionMetadata=default(PropertyMetadata))',
      ],
    ],
  ],
  [
    'postcontacts',
    [
      'PostContacts',
      [
        '../interface_docu_sign_1_1e_sign_1_1_api_1_1_i_users_api.html#a98aa5df0f64b579c03fc19c80fa958fa',
        1,
        'DocuSign.eSign.Api.IUsersApi.PostContacts()',
      ],
      [
        '../class_docu_sign_1_1e_sign_1_1_api_1_1_users_api.html#a2068b8ca9d34bd46e493d465eabdd877',
        1,
        'DocuSign.eSign.Api.UsersApi.PostContacts()',
      ],
    ],
  ],
  [
    'postcontactsasync',
    [
      'PostContactsAsync',
      [
        '../interface_docu_sign_1_1e_sign_1_1_api_1_1_i_users_api.html#a7484efbe190ab89ce7121ad15dc0ce90',
        1,
        'DocuSign.eSign.Api.IUsersApi.PostContactsAsync()',
      ],
      [
        '../class_docu_sign_1_1e_sign_1_1_api_1_1_users_api.html#a435415a408c0da125c48f5f7d68f9b86',
        1,
        'DocuSign.eSign.Api.UsersApi.PostContactsAsync()',
      ],
    ],
  ],
  [
    'postcontactsasyncwithhttpinfo',
    [
      'PostContactsAsyncWithHttpInfo',
      [
        '../interface_docu_sign_1_1e_sign_1_1_api_1_1_i_users_api.html#abfd0f265c530b32cd138117c499a7272',
        1,
        'DocuSign.eSign.Api.IUsersApi.PostContactsAsyncWithHttpInfo()',
      ],
      [
        '../class_docu_sign_1_1e_sign_1_1_api_1_1_users_api.html#a069830aa839048b88bfb64a59252afd9',
        1,
        'DocuSign.eSign.Api.UsersApi.PostContactsAsyncWithHttpInfo()',
      ],
    ],
  ],
  [
    'postcontactswithhttpinfo',
    [
      'PostContactsWithHttpInfo',
      [
        '../interface_docu_sign_1_1e_sign_1_1_api_1_1_i_users_api.html#af1a3f699c64ae1562108369c0caac542',
        1,
        'DocuSign.eSign.Api.IUsersApi.PostContactsWithHttpInfo()',
      ],
      [
        '../class_docu_sign_1_1e_sign_1_1_api_1_1_users_api.html#ac5e0d6d367fe4d51d71102bad5872d7e',
        1,
        'DocuSign.eSign.Api.UsersApi.PostContactsWithHttpInfo()',
      ],
    ],
  ],
  [
    'powerform',
    [
      'PowerForm',
      [
        '../class_docu_sign_1_1e_sign_1_1_model_1_1_power_form.html#aebd7a7ba257f6dba46a60fb92121effc',
        1,
        'DocuSign.eSign.Model.PowerForm.PowerForm()',
      ],
      [
        '../class_docu_sign_1_1e_sign_1_1_model_1_1_power_form.html#a0da132c4350c6fadd290a3f214183306',
        1,
        'DocuSign.eSign.Model.PowerForm.PowerForm(string CreatedBy=default(string), string CreatedDateTime=default(string), string EmailBody=default(string), string EmailSubject=default(string), List&lt; Envelope &gt; Envelopes=default(List&lt; Envelope &gt;), ErrorDetails ErrorDetails=default(ErrorDetails), string Instructions=default(string), string IsActive=default(string), string LastUsed=default(string), string LimitUseInterval=default(string), string LimitUseIntervalEnabled=default(string), string LimitUseIntervalUnits=default(string), string MaxUseEnabled=default(string), string Name=default(string), string PowerFormId=default(string), string PowerFormUrl=default(string), List&lt; PowerFormRecipient &gt; Recipients=default(List&lt; PowerFormRecipient &gt;), string SenderName=default(string), string SenderUserId=default(string), string SigningMode=default(string), string TemplateId=default(string), string TemplateName=default(string), string TimesUsed=default(string), string Uri=default(string), string UsesRemaining=default(string))',
      ],
    ],
  ],
  [
    'powerformformdataenvelope',
    [
      'PowerFormFormDataEnvelope',
      [
        '../class_docu_sign_1_1e_sign_1_1_model_1_1_power_form_form_data_envelope.html#a053bb7c22224fe468c1dacfa62f477a5',
        1,
        'DocuSign.eSign.Model.PowerFormFormDataEnvelope.PowerFormFormDataEnvelope()',
      ],
      [
        '../class_docu_sign_1_1e_sign_1_1_model_1_1_power_form_form_data_envelope.html#a72ec850ad4afd4c7094730ae2bd0bce3',
        1,
        'DocuSign.eSign.Model.PowerFormFormDataEnvelope.PowerFormFormDataEnvelope(string EnvelopeId=default(string), List&lt; PowerFormFormDataRecipient &gt; Recipients=default(List&lt; PowerFormFormDataRecipient &gt;))',
      ],
    ],
  ],
  [
    'powerformformdatarecipient',
    [
      'PowerFormFormDataRecipient',
      [
        '../class_docu_sign_1_1e_sign_1_1_model_1_1_power_form_form_data_recipient.html#a2d5d55de5e60fc35a14d47975203b7ad',
        1,
        'DocuSign.eSign.Model.PowerFormFormDataRecipient.PowerFormFormDataRecipient()',
      ],
      [
        '../class_docu_sign_1_1e_sign_1_1_model_1_1_power_form_form_data_recipient.html#ab025e8caedcef8d7aa158c3d4341a9bc',
        1,
        'DocuSign.eSign.Model.PowerFormFormDataRecipient.PowerFormFormDataRecipient(string Email=default(string), List&lt; NameValue &gt; FormData=default(List&lt; NameValue &gt;), string Name=default(string), string RecipientId=default(string))',
      ],
    ],
  ],
  [
    'powerformrecipient',
    [
      'PowerFormRecipient',
      [
        '../class_docu_sign_1_1e_sign_1_1_model_1_1_power_form_recipient.html#a435732866c249fda42207460c378fc1e',
        1,
        'DocuSign.eSign.Model.PowerFormRecipient.PowerFormRecipient()',
      ],
      [
        '../class_docu_sign_1_1e_sign_1_1_model_1_1_power_form_recipient.html#a7aee00c1c86c990721b795a0b354d7d0',
        1,
        'DocuSign.eSign.Model.PowerFormRecipient.PowerFormRecipient(string AccessCode=default(string), string AccessCodeLocked=default(string), string AccessCodeRequired=default(string), string Email=default(string), string EmailLocked=default(string), string IdCheckConfigurationName=default(string), string IdCheckRequired=default(string), string Name=default(string), string RecipientType=default(string), string RoleName=default(string), string RoutingOrder=default(string), string TemplateRequiresIdLookup=default(string), string UserNameLocked=default(string))',
      ],
    ],
  ],
  [
    'powerformsapi',
    [
      'PowerFormsApi',
      [
        '../class_docu_sign_1_1e_sign_1_1_api_1_1_power_forms_api.html#a7b5f29c36f46ab9cc3e053c72f167371',
        1,
        'DocuSign::eSign::Api::PowerFormsApi',
      ],
    ],
  ],
  [
    'powerformsendersresponse',
    [
      'PowerFormSendersResponse',
      [
        '../class_docu_sign_1_1e_sign_1_1_model_1_1_power_form_senders_response.html#a045bf2775cb9b803cf5d0a028c8bb9ad',
        1,
        'DocuSign.eSign.Model.PowerFormSendersResponse.PowerFormSendersResponse()',
      ],
      [
        '../class_docu_sign_1_1e_sign_1_1_model_1_1_power_form_senders_response.html#ae38bceddfb36ee06ccf6bb7d8acf370c',
        1,
        'DocuSign.eSign.Model.PowerFormSendersResponse.PowerFormSendersResponse(int?EndPosition=default(int?), string NextUri=default(string), List&lt; UserInfo &gt; PowerFormSenders=default(List&lt; UserInfo &gt;), string PreviousUri=default(string), int?ResultSetSize=default(int?), int?StartPosition=default(int?), int?TotalSetSize=default(int?))',
      ],
    ],
  ],
  [
    'powerformsformdataresponse',
    [
      'PowerFormsFormDataResponse',
      [
        '../class_docu_sign_1_1e_sign_1_1_model_1_1_power_forms_form_data_response.html#af0c6fd71b1ffa45514dc4dcd12adea9f',
        1,
        'DocuSign.eSign.Model.PowerFormsFormDataResponse.PowerFormsFormDataResponse()',
      ],
      [
        '../class_docu_sign_1_1e_sign_1_1_model_1_1_power_forms_form_data_response.html#afaf17142856a4ca52675870e86bf982d',
        1,
        'DocuSign.eSign.Model.PowerFormsFormDataResponse.PowerFormsFormDataResponse(List&lt; PowerFormFormDataEnvelope &gt; Envelopes=default(List&lt; PowerFormFormDataEnvelope &gt;))',
      ],
    ],
  ],
  [
    'powerformsrequest',
    [
      'PowerFormsRequest',
      [
        '../class_docu_sign_1_1e_sign_1_1_model_1_1_power_forms_request.html#a41461153fffbf8c3a101e699a63b139b',
        1,
        'DocuSign.eSign.Model.PowerFormsRequest.PowerFormsRequest()',
      ],
      [
        '../class_docu_sign_1_1e_sign_1_1_model_1_1_power_forms_request.html#aa141a823c1abf612356ce94b0df6f7c3',
        1,
        'DocuSign.eSign.Model.PowerFormsRequest.PowerFormsRequest(List&lt; PowerForm &gt; PowerForms=default(List&lt; PowerForm &gt;))',
      ],
    ],
  ],
  [
    'powerformsresponse',
    [
      'PowerFormsResponse',
      [
        '../class_docu_sign_1_1e_sign_1_1_model_1_1_power_forms_response.html#a627a3b0dcf1835fbd98bce9ce8d700d4',
        1,
        'DocuSign.eSign.Model.PowerFormsResponse.PowerFormsResponse()',
      ],
      [
        '../class_docu_sign_1_1e_sign_1_1_model_1_1_power_forms_response.html#ab1d094fccf21c3c9cadcd0c4bc2b2856',
        1,
        'DocuSign.eSign.Model.PowerFormsResponse.PowerFormsResponse(int?EndPosition=default(int?), string NextUri=default(string), List&lt; PowerForm &gt; PowerForms=default(List&lt; PowerForm &gt;), string PreviousUri=default(string), int?ResultSetSize=default(int?), int?StartPosition=default(int?), int?TotalSetSize=default(int?))',
      ],
    ],
  ],
  [
    'prefilltabs',
    [
      'PrefillTabs',
      [
        '../class_docu_sign_1_1e_sign_1_1_model_1_1_prefill_tabs.html#ae6439475d986e3d7b3fe74a9ff1b6d71',
        1,
        'DocuSign.eSign.Model.PrefillTabs.PrefillTabs()',
      ],
      [
        '../class_docu_sign_1_1e_sign_1_1_model_1_1_prefill_tabs.html#a9c8380a4e89e76cae795f91ee166a717',
        1,
        'DocuSign.eSign.Model.PrefillTabs.PrefillTabs(List&lt; Checkbox &gt; CheckboxTabs=default(List&lt; Checkbox &gt;), List&lt; RadioGroup &gt; RadioGroupTabs=default(List&lt; RadioGroup &gt;), List&lt; TabGroup &gt; TabGroups=default(List&lt; TabGroup &gt;), List&lt; Text &gt; TextTabs=default(List&lt; Text &gt;))',
      ],
    ],
  ],
  [
    'proofserviceresourcetoken',
    [
      'ProofServiceResourceToken',
      [
        '../class_docu_sign_1_1e_sign_1_1_model_1_1_proof_service_resource_token.html#a17b2b078ba996a78505426ac4d783d07',
        1,
        'DocuSign.eSign.Model.ProofServiceResourceToken.ProofServiceResourceToken()',
      ],
      [
        '../class_docu_sign_1_1e_sign_1_1_model_1_1_proof_service_resource_token.html#ace131237b1bb487911eeeed245714a29',
        1,
        'DocuSign.eSign.Model.ProofServiceResourceToken.ProofServiceResourceToken(string ProofBaseURI=default(string), string ResourceToken=default(string))',
      ],
    ],
  ],
  [
    'proofserviceviewlink',
    [
      'ProofServiceViewLink',
      [
        '../class_docu_sign_1_1e_sign_1_1_model_1_1_proof_service_view_link.html#a75ec9d946579f22befd8fe3e79baf9ad',
        1,
        'DocuSign.eSign.Model.ProofServiceViewLink.ProofServiceViewLink()',
      ],
      [
        '../class_docu_sign_1_1e_sign_1_1_model_1_1_proof_service_view_link.html#a35b7d10eea6d58d1b825c85d04647e6b',
        1,
        'DocuSign.eSign.Model.ProofServiceViewLink.ProofServiceViewLink(string ViewLink=default(string))',
      ],
    ],
  ],
  [
    'propertymetadata',
    [
      'PropertyMetadata',
      [
        '../class_docu_sign_1_1e_sign_1_1_model_1_1_property_metadata.html#a21743c463f34a8d31b3f29cfff913194',
        1,
        'DocuSign.eSign.Model.PropertyMetadata.PropertyMetadata()',
      ],
      [
        '../class_docu_sign_1_1e_sign_1_1_model_1_1_property_metadata.html#a2de42476a323c1b9d47b04e44c78950f',
        1,
        'DocuSign.eSign.Model.PropertyMetadata.PropertyMetadata(List&lt; string &gt; Options=default(List&lt; string &gt;), string Rights=default(string))',
      ],
    ],
  ],
  [
    'province',
    [
      'Province',
      [
        '../class_docu_sign_1_1e_sign_1_1_model_1_1_province.html#aff306ee747f2f0c1851f66e634b90608',
        1,
        'DocuSign.eSign.Model.Province.Province()',
      ],
      [
        '../class_docu_sign_1_1e_sign_1_1_model_1_1_province.html#a5cc38937970a554f2f33347107ebeaa7',
        1,
        'DocuSign.eSign.Model.Province.Province(string IsoCode=default(string), string Name=default(string))',
      ],
    ],
  ],
  [
    'provisioninginformation',
    [
      'ProvisioningInformation',
      [
        '../class_docu_sign_1_1e_sign_1_1_model_1_1_provisioning_information.html#ae5c5572713640bc2c63a487c02f33aa8',
        1,
        'DocuSign.eSign.Model.ProvisioningInformation.ProvisioningInformation()',
      ],
      [
        '../class_docu_sign_1_1e_sign_1_1_model_1_1_provisioning_information.html#a46db1587a38e07a21e85669bacfd77fe',
        1,
        'DocuSign.eSign.Model.ProvisioningInformation.ProvisioningInformation(string DefaultConnectionId=default(string), string DefaultPlanId=default(string), string DistributorCode=default(string), string DistributorPassword=default(string), string PasswordRuleText=default(string), string PlanPromotionText=default(string), string PurchaseOrderOrPromAllowed=default(string))',
      ],
    ],
  ],
  [
    'purchasedenvelopesinformation',
    [
      'PurchasedEnvelopesInformation',
      [
        '../class_docu_sign_1_1e_sign_1_1_model_1_1_purchased_envelopes_information.html#a0fb6fbac2b0840a1c32d7d77359efaf5',
        1,
        'DocuSign.eSign.Model.PurchasedEnvelopesInformation.PurchasedEnvelopesInformation()',
      ],
      [
        '../class_docu_sign_1_1e_sign_1_1_model_1_1_purchased_envelopes_information.html#af2ecef73483f773dfd43ab99e8f60857',
        1,
        'DocuSign.eSign.Model.PurchasedEnvelopesInformation.PurchasedEnvelopesInformation(string Amount=default(string), string AppName=default(string), string CurrencyCode=default(string), string Platform=default(string), string ProductId=default(string), string Quantity=default(string), string ReceiptData=default(string), string StoreName=default(string), string TransactionId=default(string))',
      ],
    ],
  ],
  [
    'purchaseenvelopes',
    [
      'PurchaseEnvelopes',
      [
        '../interface_docu_sign_1_1e_sign_1_1_api_1_1_i_billing_api.html#a16e9588c4ea483f811cb6e660cb6247f',
        1,
        'DocuSign.eSign.Api.IBillingApi.PurchaseEnvelopes()',
      ],
      [
        '../class_docu_sign_1_1e_sign_1_1_api_1_1_billing_api.html#ac0ad41d294b0bcad0924808384c22a78',
        1,
        'DocuSign.eSign.Api.BillingApi.PurchaseEnvelopes()',
      ],
    ],
  ],
  [
    'purchaseenvelopesasync',
    [
      'PurchaseEnvelopesAsync',
      [
        '../interface_docu_sign_1_1e_sign_1_1_api_1_1_i_billing_api.html#af6bb9ca2b5e5a4e975ade330185eebad',
        1,
        'DocuSign.eSign.Api.IBillingApi.PurchaseEnvelopesAsync()',
      ],
      [
        '../class_docu_sign_1_1e_sign_1_1_api_1_1_billing_api.html#a613d0667f2bed3aabdf28afd5a52a1ab',
        1,
        'DocuSign.eSign.Api.BillingApi.PurchaseEnvelopesAsync()',
      ],
    ],
  ],
  [
    'purchaseenvelopesasyncwithhttpinfo',
    [
      'PurchaseEnvelopesAsyncWithHttpInfo',
      [
        '../interface_docu_sign_1_1e_sign_1_1_api_1_1_i_billing_api.html#ab9d41fad7916598a3c5151ade381a086',
        1,
        'DocuSign.eSign.Api.IBillingApi.PurchaseEnvelopesAsyncWithHttpInfo()',
      ],
      [
        '../class_docu_sign_1_1e_sign_1_1_api_1_1_billing_api.html#ad83e07290551142ffb80551fbaf2945a',
        1,
        'DocuSign.eSign.Api.BillingApi.PurchaseEnvelopesAsyncWithHttpInfo()',
      ],
    ],
  ],
  [
    'purchaseenvelopeswithhttpinfo',
    [
      'PurchaseEnvelopesWithHttpInfo',
      [
        '../interface_docu_sign_1_1e_sign_1_1_api_1_1_i_billing_api.html#aa62c515ae6784e06f30eca5cdd7c1a05',
        1,
        'DocuSign.eSign.Api.IBillingApi.PurchaseEnvelopesWithHttpInfo()',
      ],
      [
        '../class_docu_sign_1_1e_sign_1_1_api_1_1_billing_api.html#ab2db6fa5bf2cc882352cce9ea899da99',
        1,
        'DocuSign.eSign.Api.BillingApi.PurchaseEnvelopesWithHttpInfo()',
      ],
    ],
  ],
  [
    'putattachment',
    [
      'PutAttachment',
      [
        '../interface_docu_sign_1_1e_sign_1_1_api_1_1_i_envelopes_api.html#a0e188a0af063aae6c60e132aad5a9eb8',
        1,
        'DocuSign.eSign.Api.IEnvelopesApi.PutAttachment()',
      ],
      [
        '../class_docu_sign_1_1e_sign_1_1_api_1_1_envelopes_api.html#ac0d5b99bc588235cf8c6b68e25ad1d14',
        1,
        'DocuSign.eSign.Api.EnvelopesApi.PutAttachment()',
      ],
    ],
  ],
  [
    'putattachmentasync',
    [
      'PutAttachmentAsync',
      [
        '../interface_docu_sign_1_1e_sign_1_1_api_1_1_i_envelopes_api.html#ae3e6a08229c9027bc0d38d7c4e716a53',
        1,
        'DocuSign.eSign.Api.IEnvelopesApi.PutAttachmentAsync()',
      ],
      [
        '../class_docu_sign_1_1e_sign_1_1_api_1_1_envelopes_api.html#a053b4d8d34950b3c389e7ee61947a179',
        1,
        'DocuSign.eSign.Api.EnvelopesApi.PutAttachmentAsync()',
      ],
    ],
  ],
  [
    'putattachmentasyncwithhttpinfo',
    [
      'PutAttachmentAsyncWithHttpInfo',
      [
        '../interface_docu_sign_1_1e_sign_1_1_api_1_1_i_envelopes_api.html#a053c5c772be59a0124d5c452a1a3e8a7',
        1,
        'DocuSign.eSign.Api.IEnvelopesApi.PutAttachmentAsyncWithHttpInfo()',
      ],
      [
        '../class_docu_sign_1_1e_sign_1_1_api_1_1_envelopes_api.html#a99e906bdaa82ae3e62b744fa220aa6cd',
        1,
        'DocuSign.eSign.Api.EnvelopesApi.PutAttachmentAsyncWithHttpInfo()',
      ],
    ],
  ],
  [
    'putattachments',
    [
      'PutAttachments',
      [
        '../interface_docu_sign_1_1e_sign_1_1_api_1_1_i_envelopes_api.html#ad4d3ebbfbe71b263fe05d1c84dc33b42',
        1,
        'DocuSign.eSign.Api.IEnvelopesApi.PutAttachments()',
      ],
      [
        '../class_docu_sign_1_1e_sign_1_1_api_1_1_envelopes_api.html#a3fea9a2913364d1d35e27a5c2f02cd50',
        1,
        'DocuSign.eSign.Api.EnvelopesApi.PutAttachments()',
      ],
    ],
  ],
  [
    'putattachmentsasync',
    [
      'PutAttachmentsAsync',
      [
        '../interface_docu_sign_1_1e_sign_1_1_api_1_1_i_envelopes_api.html#abc7b3f8f93039dfa4a49ad20f11d281b',
        1,
        'DocuSign.eSign.Api.IEnvelopesApi.PutAttachmentsAsync()',
      ],
      [
        '../class_docu_sign_1_1e_sign_1_1_api_1_1_envelopes_api.html#a17fa3b5c0971380e3e42de35fbc2d8fc',
        1,
        'DocuSign.eSign.Api.EnvelopesApi.PutAttachmentsAsync()',
      ],
    ],
  ],
  [
    'putattachmentsasyncwithhttpinfo',
    [
      'PutAttachmentsAsyncWithHttpInfo',
      [
        '../interface_docu_sign_1_1e_sign_1_1_api_1_1_i_envelopes_api.html#a51f5d40e6d90491b352838b1f86c842d',
        1,
        'DocuSign.eSign.Api.IEnvelopesApi.PutAttachmentsAsyncWithHttpInfo()',
      ],
      [
        '../class_docu_sign_1_1e_sign_1_1_api_1_1_envelopes_api.html#adb5f4c8b78c13e35041d04f3bc83598b',
        1,
        'DocuSign.eSign.Api.EnvelopesApi.PutAttachmentsAsyncWithHttpInfo()',
      ],
    ],
  ],
  [
    'putattachmentswithhttpinfo',
    [
      'PutAttachmentsWithHttpInfo',
      [
        '../interface_docu_sign_1_1e_sign_1_1_api_1_1_i_envelopes_api.html#aefbbab741cf50f197c50aedbefef7d40',
        1,
        'DocuSign.eSign.Api.IEnvelopesApi.PutAttachmentsWithHttpInfo()',
      ],
      [
        '../class_docu_sign_1_1e_sign_1_1_api_1_1_envelopes_api.html#a43022018377e914043c39a4472d61f40',
        1,
        'DocuSign.eSign.Api.EnvelopesApi.PutAttachmentsWithHttpInfo()',
      ],
    ],
  ],
  [
    'putattachmentwithhttpinfo',
    [
      'PutAttachmentWithHttpInfo',
      [
        '../interface_docu_sign_1_1e_sign_1_1_api_1_1_i_envelopes_api.html#ac9acbd76260344a21748e12d44aee320',
        1,
        'DocuSign.eSign.Api.IEnvelopesApi.PutAttachmentWithHttpInfo()',
      ],
      [
        '../class_docu_sign_1_1e_sign_1_1_api_1_1_envelopes_api.html#a3c99537aeb6ebbb97a1c62f1f358bcdf',
        1,
        'DocuSign.eSign.Api.EnvelopesApi.PutAttachmentWithHttpInfo()',
      ],
    ],
  ],
  [
    'putcontacts',
    [
      'PutContacts',
      [
        '../interface_docu_sign_1_1e_sign_1_1_api_1_1_i_users_api.html#a7f98c934d92f360048c3b0f09dd13fc6',
        1,
        'DocuSign.eSign.Api.IUsersApi.PutContacts()',
      ],
      [
        '../class_docu_sign_1_1e_sign_1_1_api_1_1_users_api.html#aea55175a209a18af0399fbfefd27c03d',
        1,
        'DocuSign.eSign.Api.UsersApi.PutContacts()',
      ],
    ],
  ],
  [
    'putcontactsasync',
    [
      'PutContactsAsync',
      [
        '../interface_docu_sign_1_1e_sign_1_1_api_1_1_i_users_api.html#a56e5f6936e048517dcec2026a479102e',
        1,
        'DocuSign.eSign.Api.IUsersApi.PutContactsAsync()',
      ],
      [
        '../class_docu_sign_1_1e_sign_1_1_api_1_1_users_api.html#a17df712db40b904f573c24c95170d8e7',
        1,
        'DocuSign.eSign.Api.UsersApi.PutContactsAsync()',
      ],
    ],
  ],
  [
    'putcontactsasyncwithhttpinfo',
    [
      'PutContactsAsyncWithHttpInfo',
      [
        '../interface_docu_sign_1_1e_sign_1_1_api_1_1_i_users_api.html#a719dc599261c5a6857146270ee0dba44',
        1,
        'DocuSign.eSign.Api.IUsersApi.PutContactsAsyncWithHttpInfo()',
      ],
      [
        '../class_docu_sign_1_1e_sign_1_1_api_1_1_users_api.html#a513e09018580b443e2b71edca84720fc',
        1,
        'DocuSign.eSign.Api.UsersApi.PutContactsAsyncWithHttpInfo()',
      ],
    ],
  ],
  [
    'putcontactswithhttpinfo',
    [
      'PutContactsWithHttpInfo',
      [
        '../interface_docu_sign_1_1e_sign_1_1_api_1_1_i_users_api.html#af05703f5c5e480e6b1157db93a314b69',
        1,
        'DocuSign.eSign.Api.IUsersApi.PutContactsWithHttpInfo()',
      ],
      [
        '../class_docu_sign_1_1e_sign_1_1_api_1_1_users_api.html#a3c198fff93339d41a6b8a76c1a07e279',
        1,
        'DocuSign.eSign.Api.UsersApi.PutContactsWithHttpInfo()',
      ],
    ],
  ],
];
