var searchData = [
  [
    'idcheckconfiguration',
    [
      'IdCheckConfiguration',
      [
        '../class_docu_sign_1_1e_sign_1_1_model_1_1_id_check_configuration.html#a61ca6d2efd98e4ecf3a908a23fc3a0e3',
        1,
        'DocuSign.eSign.Model.IdCheckConfiguration.IdCheckConfiguration()',
      ],
      [
        '../class_docu_sign_1_1e_sign_1_1_model_1_1_id_check_configuration.html#affdbbf57b5492494f4f5d186cad71bff',
        1,
        'DocuSign.eSign.Model.IdCheckConfiguration.IdCheckConfiguration(List&lt; IdCheckSecurityStep &gt; AuthSteps=default(List&lt; IdCheckSecurityStep &gt;), string IsDefault=default(string), string Name=default(string))',
      ],
    ],
  ],
  [
    'idcheckinformationinput',
    [
      'IdCheckInformationInput',
      [
        '../class_docu_sign_1_1e_sign_1_1_model_1_1_id_check_information_input.html#aaf08a306d82b34455c1714fb356ba59f',
        1,
        'DocuSign.eSign.Model.IdCheckInformationInput.IdCheckInformationInput()',
      ],
      [
        '../class_docu_sign_1_1e_sign_1_1_model_1_1_id_check_information_input.html#a19eeda59b9b10200bc2757d76e17c6d3',
        1,
        'DocuSign.eSign.Model.IdCheckInformationInput.IdCheckInformationInput(AddressInformationInput AddressInformationInput=default(AddressInformationInput), DobInformationInput DobInformationInput=default(DobInformationInput), Ssn4InformationInput Ssn4InformationInput=default(Ssn4InformationInput), Ssn9InformationInput Ssn9InformationInput=default(Ssn9InformationInput))',
      ],
    ],
  ],
  [
    'idchecksecuritystep',
    [
      'IdCheckSecurityStep',
      [
        '../class_docu_sign_1_1e_sign_1_1_model_1_1_id_check_security_step.html#a0e8c5e28d25b18eade2853920100f3ec',
        1,
        'DocuSign.eSign.Model.IdCheckSecurityStep.IdCheckSecurityStep()',
      ],
      [
        '../class_docu_sign_1_1e_sign_1_1_model_1_1_id_check_security_step.html#a7c73b680b9442922ab2b052d266a46f1',
        1,
        'DocuSign.eSign.Model.IdCheckSecurityStep.IdCheckSecurityStep(string AuthType=default(string))',
      ],
    ],
  ],
  [
    'initialhere',
    [
      'InitialHere',
      [
        '../class_docu_sign_1_1e_sign_1_1_model_1_1_initial_here.html#a122454da018fd767c9197a27f896065f',
        1,
        'DocuSign.eSign.Model.InitialHere.InitialHere()',
      ],
      [
        '../class_docu_sign_1_1e_sign_1_1_model_1_1_initial_here.html#a33448578f29e2cf2f4366d8d1af93298',
        1,
        'DocuSign.eSign.Model.InitialHere.InitialHere(string AnchorAllowWhiteSpaceInCharacters=default(string), PropertyMetadata AnchorAllowWhiteSpaceInCharactersMetadata=default(PropertyMetadata), string AnchorCaseSensitive=default(string), PropertyMetadata AnchorCaseSensitiveMetadata=default(PropertyMetadata), string AnchorHorizontalAlignment=default(string), PropertyMetadata AnchorHorizontalAlignmentMetadata=default(PropertyMetadata), string AnchorIgnoreIfNotPresent=default(string), PropertyMetadata AnchorIgnoreIfNotPresentMetadata=default(PropertyMetadata), string AnchorMatchWholeWord=default(string), PropertyMetadata AnchorMatchWholeWordMetadata=default(PropertyMetadata), string AnchorString=default(string), PropertyMetadata AnchorStringMetadata=default(PropertyMetadata), string AnchorTabProcessorVersion=default(string), PropertyMetadata AnchorTabProcessorVersionMetadata=default(PropertyMetadata), string AnchorUnits=default(string), PropertyMetadata AnchorUnitsMetadata=default(PropertyMetadata), string AnchorXOffset=default(string), PropertyMetadata AnchorXOffsetMetadata=default(PropertyMetadata), string AnchorYOffset=default(string), PropertyMetadata AnchorYOffsetMetadata=default(PropertyMetadata), string ConditionalParentLabel=default(string), PropertyMetadata ConditionalParentLabelMetadata=default(PropertyMetadata), string ConditionalParentValue=default(string), PropertyMetadata ConditionalParentValueMetadata=default(PropertyMetadata), string CustomTabId=default(string), PropertyMetadata CustomTabIdMetadata=default(PropertyMetadata), string DocumentId=default(string), PropertyMetadata DocumentIdMetadata=default(PropertyMetadata), ErrorDetails ErrorDetails=default(ErrorDetails), string FormOrder=default(string), PropertyMetadata FormOrderMetadata=default(PropertyMetadata), string FormPageLabel=default(string), PropertyMetadata FormPageLabelMetadata=default(PropertyMetadata), string FormPageNumber=default(string), PropertyMetadata FormPageNumberMetadata=default(PropertyMetadata), string Height=default(string), PropertyMetadata HeightMetadata=default(PropertyMetadata), MergeField MergeField=default(MergeField), string MergeFieldXml=default(string), string Name=default(string), PropertyMetadata NameMetadata=default(PropertyMetadata), string Optional=default(string), PropertyMetadata OptionalMetadata=default(PropertyMetadata), string PageNumber=default(string), PropertyMetadata PageNumberMetadata=default(PropertyMetadata), string RecipientId=default(string), string RecipientIdGuid=default(string), PropertyMetadata RecipientIdGuidMetadata=default(PropertyMetadata), PropertyMetadata RecipientIdMetadata=default(PropertyMetadata), string ScaleValue=default(string), PropertyMetadata ScaleValueMetadata=default(PropertyMetadata), SmartContractInformation SmartContractInformation=default(SmartContractInformation), string Source=default(string), string Status=default(string), PropertyMetadata StatusMetadata=default(PropertyMetadata), List&lt; string &gt; TabGroupLabels=default(List&lt; string &gt;), PropertyMetadata TabGroupLabelsMetadata=default(PropertyMetadata), string TabId=default(string), PropertyMetadata TabIdMetadata=default(PropertyMetadata), string TabLabel=default(string), PropertyMetadata TabLabelMetadata=default(PropertyMetadata), string TabOrder=default(string), PropertyMetadata TabOrderMetadata=default(PropertyMetadata), string TabType=default(string), PropertyMetadata TabTypeMetadata=default(PropertyMetadata), string TemplateLocked=default(string), PropertyMetadata TemplateLockedMetadata=default(PropertyMetadata), string TemplateRequired=default(string), PropertyMetadata TemplateRequiredMetadata=default(PropertyMetadata), string Tooltip=default(string), PropertyMetadata ToolTipMetadata=default(PropertyMetadata), string Width=default(string), PropertyMetadata WidthMetadata=default(PropertyMetadata), string XPosition=default(string), PropertyMetadata XPositionMetadata=default(PropertyMetadata), string YPosition=default(string), PropertyMetadata YPositionMetadata=default(PropertyMetadata))',
      ],
    ],
  ],
  [
    'inlinetemplate',
    [
      'InlineTemplate',
      [
        '../class_docu_sign_1_1e_sign_1_1_model_1_1_inline_template.html#adb03f1c794127aa233a2ac471e22ccaa',
        1,
        'DocuSign.eSign.Model.InlineTemplate.InlineTemplate()',
      ],
      [
        '../class_docu_sign_1_1e_sign_1_1_model_1_1_inline_template.html#a0ea7a88557f2dd3952596ed18770e8e8',
        1,
        'DocuSign.eSign.Model.InlineTemplate.InlineTemplate(CustomFields CustomFields=default(CustomFields), List&lt; Document &gt; Documents=default(List&lt; Document &gt;), Envelope Envelope=default(Envelope), Recipients Recipients=default(Recipients), string Sequence=default(string))',
      ],
    ],
  ],
  [
    'inpersonsigner',
    [
      'InPersonSigner',
      [
        '../class_docu_sign_1_1e_sign_1_1_model_1_1_in_person_signer.html#a459589cada846214fb16a07ed576e0bf',
        1,
        'DocuSign.eSign.Model.InPersonSigner.InPersonSigner()',
      ],
      [
        '../class_docu_sign_1_1e_sign_1_1_model_1_1_in_person_signer.html#ac3131b1fff5b4b92b8813fe1f53548fd',
        1,
        'DocuSign.eSign.Model.InPersonSigner.InPersonSigner(string AccessCode=default(string), PropertyMetadata AccessCodeMetadata=default(PropertyMetadata), string AddAccessCodeToEmail=default(string), string AllowSystemOverrideForLockedRecipient=default(string), string AutoNavigation=default(string), string CanSignOffline=default(string), string ClientUserId=default(string), string CompletedCount=default(string), string CreationReason=default(string), List&lt; string &gt; CustomFields=default(List&lt; string &gt;), string DeclinedDateTime=default(string), string DeclinedReason=default(string), string DefaultRecipient=default(string), string DeliveredDateTime=default(string), string DeliveryMethod=default(string), PropertyMetadata DeliveryMethodMetadata=default(PropertyMetadata), string DesignatorId=default(string), string DesignatorIdGuid=default(string), List&lt; DocumentVisibility &gt; DocumentVisibility=default(List&lt; DocumentVisibility &gt;), string Email=default(string), PropertyMetadata EmailMetadata=default(PropertyMetadata), RecipientEmailNotification EmailNotification=default(RecipientEmailNotification), string EmbeddedRecipientStartURL=default(string), ErrorDetails ErrorDetails=default(ErrorDetails), List&lt; string &gt; ExcludedDocuments=default(List&lt; string &gt;), string FaxNumber=default(string), PropertyMetadata FaxNumberMetadata=default(PropertyMetadata), string HostEmail=default(string), PropertyMetadata HostEmailMetadata=default(PropertyMetadata), string HostName=default(string), PropertyMetadata HostNameMetadata=default(PropertyMetadata), string IdCheckConfigurationName=default(string), PropertyMetadata IdCheckConfigurationNameMetadata=default(PropertyMetadata), IdCheckInformationInput IdCheckInformationInput=default(IdCheckInformationInput), RecipientIdentityVerification IdentityVerification=default(RecipientIdentityVerification), string InheritEmailNotificationConfiguration=default(string), string InPersonSigningType=default(string), PropertyMetadata InPersonSigningTypeMetadata=default(PropertyMetadata), string LockedRecipientPhoneAuthEditable=default(string), string LockedRecipientSmsEditable=default(string), string Name=default(string), PropertyMetadata NameMetadata=default(PropertyMetadata), NotaryHost NotaryHost=default(NotaryHost), string NotaryId=default(string), string Note=default(string), PropertyMetadata NoteMetadata=default(PropertyMetadata), OfflineAttributes OfflineAttributes=default(OfflineAttributes), RecipientPhoneAuthentication PhoneAuthentication=default(RecipientPhoneAuthentication), List&lt; RecipientAttachment &gt; RecipientAttachments=default(List&lt; RecipientAttachment &gt;), AuthenticationStatus RecipientAuthenticationStatus=default(AuthenticationStatus), List&lt; FeatureAvailableMetadata &gt; RecipientFeatureMetadata=default(List&lt; FeatureAvailableMetadata &gt;), string RecipientId=default(string), string RecipientIdGuid=default(string), List&lt; RecipientSignatureProvider &gt; RecipientSignatureProviders=default(List&lt; RecipientSignatureProvider &gt;), string RecipientSuppliesTabs=default(string), string RecipientType=default(string), PropertyMetadata RecipientTypeMetadata=default(PropertyMetadata), string RequireIdLookup=default(string), PropertyMetadata RequireIdLookupMetadata=default(PropertyMetadata), string RequireSignerCertificate=default(string), string RequireSignOnPaper=default(string), string RequireUploadSignature=default(string), string RoleName=default(string), string RoutingOrder=default(string), PropertyMetadata RoutingOrderMetadata=default(PropertyMetadata), string SentDateTime=default(string), RecipientSignatureInformation SignatureInfo=default(RecipientSignatureInformation), string SignedDateTime=default(string), string SignerEmail=default(string), PropertyMetadata SignerEmailMetadata=default(PropertyMetadata), string SignerFirstName=default(string), PropertyMetadata SignerFirstNameMetadata=default(PropertyMetadata), string SignerLastName=default(string), PropertyMetadata SignerLastNameMetadata=default(PropertyMetadata), string SignerName=default(string), PropertyMetadata SignerNameMetadata=default(PropertyMetadata), string SignInEachLocation=default(string), PropertyMetadata SignInEachLocationMetadata=default(PropertyMetadata), string SigningGroupId=default(string), PropertyMetadata SigningGroupIdMetadata=default(PropertyMetadata), string SigningGroupName=default(string), List&lt; UserInfo &gt; SigningGroupUsers=default(List&lt; UserInfo &gt;), RecipientSMSAuthentication SmsAuthentication=default(RecipientSMSAuthentication), List&lt; SocialAuthentication &gt; SocialAuthentications=default(List&lt; SocialAuthentication &gt;), string Status=default(string), string StatusCode=default(string), string SuppressEmails=default(string), Tabs Tabs=default(Tabs), string TemplateLocked=default(string), string TemplateRequired=default(string), string TotalTabCount=default(string), string UserId=default(string))',
      ],
    ],
  ],
  [
    'integrateduserinfolist',
    [
      'IntegratedUserInfoList',
      [
        '../class_docu_sign_1_1e_sign_1_1_model_1_1_integrated_user_info_list.html#acc55b3790df4c54e6fd41d5a548456a8',
        1,
        'DocuSign.eSign.Model.IntegratedUserInfoList.IntegratedUserInfoList()',
      ],
      [
        '../class_docu_sign_1_1e_sign_1_1_model_1_1_integrated_user_info_list.html#a4f5f19ecfc2182efa7bdb801e034e7bd',
        1,
        'DocuSign.eSign.Model.IntegratedUserInfoList.IntegratedUserInfoList(string AllUsersSelected=default(string), string EndPosition=default(string), string NextUri=default(string), string PreviousUri=default(string), string ResultSetSize=default(string), string StartPosition=default(string), string TotalSetSize=default(string), List&lt; UserInfo &gt; Users=default(List&lt; UserInfo &gt;))',
      ],
    ],
  ],
  [
    'interceptrequest',
    [
      'InterceptRequest',
      [
        '../class_docu_sign_1_1e_sign_1_1_client_1_1_api_client.html#a1fcd8ae4a7dbdfd9c829a057ebbed5a6',
        1,
        'DocuSign::eSign::Client::ApiClient',
      ],
    ],
  ],
  [
    'interceptresponse',
    [
      'InterceptResponse',
      [
        '../class_docu_sign_1_1e_sign_1_1_client_1_1_api_client.html#ab1edb8b60dce695981d29f97a1531796',
        1,
        'DocuSign::eSign::Client::ApiClient',
      ],
    ],
  ],
  [
    'intermediary',
    [
      'Intermediary',
      [
        '../class_docu_sign_1_1e_sign_1_1_model_1_1_intermediary.html#ab3dbf68d27639fbddf16fde2f9d2edfd',
        1,
        'DocuSign.eSign.Model.Intermediary.Intermediary()',
      ],
      [
        '../class_docu_sign_1_1e_sign_1_1_model_1_1_intermediary.html#a2d473e3c25a84a582bb5449df6c3f068',
        1,
        'DocuSign.eSign.Model.Intermediary.Intermediary(string AccessCode=default(string), PropertyMetadata AccessCodeMetadata=default(PropertyMetadata), string AddAccessCodeToEmail=default(string), List&lt; RecipientAdditionalNotification &gt; AdditionalNotifications=default(List&lt; RecipientAdditionalNotification &gt;), string AllowSystemOverrideForLockedRecipient=default(string), string ClientUserId=default(string), string CompletedCount=default(string), List&lt; string &gt; CustomFields=default(List&lt; string &gt;), string DeclinedDateTime=default(string), string DeclinedReason=default(string), string DeliveredDateTime=default(string), string DeliveryMethod=default(string), PropertyMetadata DeliveryMethodMetadata=default(PropertyMetadata), string DesignatorId=default(string), string DesignatorIdGuid=default(string), List&lt; DocumentVisibility &gt; DocumentVisibility=default(List&lt; DocumentVisibility &gt;), string Email=default(string), PropertyMetadata EmailMetadata=default(PropertyMetadata), RecipientEmailNotification EmailNotification=default(RecipientEmailNotification), string EmbeddedRecipientStartURL=default(string), ErrorDetails ErrorDetails=default(ErrorDetails), List&lt; string &gt; ExcludedDocuments=default(List&lt; string &gt;), string FaxNumber=default(string), PropertyMetadata FaxNumberMetadata=default(PropertyMetadata), string FirstName=default(string), PropertyMetadata FirstNameMetadata=default(PropertyMetadata), string FullName=default(string), PropertyMetadata FullNameMetadata=default(PropertyMetadata), string IdCheckConfigurationName=default(string), PropertyMetadata IdCheckConfigurationNameMetadata=default(PropertyMetadata), IdCheckInformationInput IdCheckInformationInput=default(IdCheckInformationInput), RecipientIdentityVerification IdentityVerification=default(RecipientIdentityVerification), string InheritEmailNotificationConfiguration=default(string), string LastName=default(string), PropertyMetadata LastNameMetadata=default(PropertyMetadata), string LockedRecipientPhoneAuthEditable=default(string), string LockedRecipientSmsEditable=default(string), string Name=default(string), PropertyMetadata NameMetadata=default(PropertyMetadata), string Note=default(string), PropertyMetadata NoteMetadata=default(PropertyMetadata), RecipientPhoneAuthentication PhoneAuthentication=default(RecipientPhoneAuthentication), List&lt; RecipientAttachment &gt; RecipientAttachments=default(List&lt; RecipientAttachment &gt;), AuthenticationStatus RecipientAuthenticationStatus=default(AuthenticationStatus), List&lt; FeatureAvailableMetadata &gt; RecipientFeatureMetadata=default(List&lt; FeatureAvailableMetadata &gt;), string RecipientId=default(string), string RecipientIdGuid=default(string), string RecipientType=default(string), PropertyMetadata RecipientTypeMetadata=default(PropertyMetadata), string RequireIdLookup=default(string), PropertyMetadata RequireIdLookupMetadata=default(PropertyMetadata), string RoleName=default(string), string RoutingOrder=default(string), PropertyMetadata RoutingOrderMetadata=default(PropertyMetadata), string SentDateTime=default(string), string SignedDateTime=default(string), string SigningGroupId=default(string), PropertyMetadata SigningGroupIdMetadata=default(PropertyMetadata), string SigningGroupName=default(string), List&lt; UserInfo &gt; SigningGroupUsers=default(List&lt; UserInfo &gt;), RecipientSMSAuthentication SmsAuthentication=default(RecipientSMSAuthentication), List&lt; SocialAuthentication &gt; SocialAuthentications=default(List&lt; SocialAuthentication &gt;), string Status=default(string), string StatusCode=default(string), string SuppressEmails=default(string), string TemplateLocked=default(string), string TemplateRequired=default(string), string TotalTabCount=default(string), string UserId=default(string))',
      ],
    ],
  ],
];
