var searchData = [
  [
    'favoritetemplatescontentitem',
    [
      'FavoriteTemplatesContentItem',
      [
        '../class_docu_sign_1_1e_sign_1_1_model_1_1_favorite_templates_content_item.html#ac6011151b2f3f461d225e219d644e508',
        1,
        'DocuSign.eSign.Model.FavoriteTemplatesContentItem.FavoriteTemplatesContentItem()',
      ],
      [
        '../class_docu_sign_1_1e_sign_1_1_model_1_1_favorite_templates_content_item.html#ac3dc3a0f937e81cdd3b580417519f3ef',
        1,
        'DocuSign.eSign.Model.FavoriteTemplatesContentItem.FavoriteTemplatesContentItem(ErrorDetails ErrorDetails=default(ErrorDetails), string FavoritedDate=default(string), string TemplateId=default(string))',
      ],
    ],
  ],
  [
    'favoritetemplatesinfo',
    [
      'FavoriteTemplatesInfo',
      [
        '../class_docu_sign_1_1e_sign_1_1_model_1_1_favorite_templates_info.html#a2afd2aef8e19ad5565806bc8694901a8',
        1,
        'DocuSign.eSign.Model.FavoriteTemplatesInfo.FavoriteTemplatesInfo()',
      ],
      [
        '../class_docu_sign_1_1e_sign_1_1_model_1_1_favorite_templates_info.html#a7f94db3045e9fa905a8b9bbf9ebb759e',
        1,
        'DocuSign.eSign.Model.FavoriteTemplatesInfo.FavoriteTemplatesInfo(ErrorDetails ErrorDetails=default(ErrorDetails), List&lt; FavoriteTemplatesContentItem &gt; FavoriteTemplates=default(List&lt; FavoriteTemplatesContentItem &gt;), int?TemplatesUpdatedCount=default(int?))',
      ],
    ],
  ],
  [
    'featureavailablemetadata',
    [
      'FeatureAvailableMetadata',
      [
        '../class_docu_sign_1_1e_sign_1_1_model_1_1_feature_available_metadata.html#a99b45db989b9b458f6a18e430a455f3d',
        1,
        'DocuSign.eSign.Model.FeatureAvailableMetadata.FeatureAvailableMetadata()',
      ],
      [
        '../class_docu_sign_1_1e_sign_1_1_model_1_1_feature_available_metadata.html#af7dcca9ee569333f4157c12b3d8187c7',
        1,
        'DocuSign.eSign.Model.FeatureAvailableMetadata.FeatureAvailableMetadata(string Availabilty=default(string), string FeatureName=default(string))',
      ],
    ],
  ],
  [
    'featureset',
    [
      'FeatureSet',
      [
        '../class_docu_sign_1_1e_sign_1_1_model_1_1_feature_set.html#a28b6c14beb8e5990db469779d1fafa50',
        1,
        'DocuSign.eSign.Model.FeatureSet.FeatureSet()',
      ],
      [
        '../class_docu_sign_1_1e_sign_1_1_model_1_1_feature_set.html#adf75dff67848102ce40d679f2a470bc9',
        1,
        'DocuSign.eSign.Model.FeatureSet.FeatureSet(List&lt; CurrencyFeatureSetPrice &gt; CurrencyFeatureSetPrices=default(List&lt; CurrencyFeatureSetPrice &gt;), string EnvelopeFee=default(string), string FeatureSetId=default(string), string FixedFee=default(string), string Is21CFRPart11=default(string), string IsActive=default(string), string IsEnabled=default(string), string Name=default(string), string SeatFee=default(string))',
      ],
    ],
  ],
  [
    'filetype',
    [
      'FileType',
      [
        '../class_docu_sign_1_1e_sign_1_1_model_1_1_file_type.html#ae304ef41050491f0fd952ba49fb20cab',
        1,
        'DocuSign.eSign.Model.FileType.FileType()',
      ],
      [
        '../class_docu_sign_1_1e_sign_1_1_model_1_1_file_type.html#a9765edd80830a6529298da79632bbd9a',
        1,
        'DocuSign.eSign.Model.FileType.FileType(string FileExtension=default(string), string MimeType=default(string))',
      ],
    ],
  ],
  [
    'filetypelist',
    [
      'FileTypeList',
      [
        '../class_docu_sign_1_1e_sign_1_1_model_1_1_file_type_list.html#ad224f3ddfebb6cc13d16fd68970bc9f0',
        1,
        'DocuSign.eSign.Model.FileTypeList.FileTypeList()',
      ],
      [
        '../class_docu_sign_1_1e_sign_1_1_model_1_1_file_type_list.html#a20a346881a36614d39f194fd7455f8ba',
        1,
        'DocuSign.eSign.Model.FileTypeList.FileTypeList(List&lt; FileType &gt; FileTypes=default(List&lt; FileType &gt;))',
      ],
    ],
  ],
  [
    'filter',
    [
      'Filter',
      [
        '../class_docu_sign_1_1e_sign_1_1_model_1_1_filter.html#a8ac0df63db26fe104ef497ccb3216dec',
        1,
        'DocuSign.eSign.Model.Filter.Filter()',
      ],
      [
        '../class_docu_sign_1_1e_sign_1_1_model_1_1_filter.html#a83967e8fe9c6c552a8f8884d5f85badf',
        1,
        'DocuSign.eSign.Model.Filter.Filter(string ActionRequired=default(string), string Expires=default(string), string FolderIds=default(string), string FromDateTime=default(string), string IsTemplate=default(string), string Order=default(string), string OrderBy=default(string), string SearchTarget=default(string), string SearchText=default(string), string Status=default(string), string ToDateTime=default(string))',
      ],
    ],
  ],
  [
    'firstname',
    [
      'FirstName',
      [
        '../class_docu_sign_1_1e_sign_1_1_model_1_1_first_name.html#a65c255971c3e842ca874bac7d23b2804',
        1,
        'DocuSign.eSign.Model.FirstName.FirstName()',
      ],
      [
        '../class_docu_sign_1_1e_sign_1_1_model_1_1_first_name.html#a1ba31caf60186631ea0d3c9317eb4fc9',
        1,
        'DocuSign.eSign.Model.FirstName.FirstName(string AnchorAllowWhiteSpaceInCharacters=default(string), PropertyMetadata AnchorAllowWhiteSpaceInCharactersMetadata=default(PropertyMetadata), string AnchorCaseSensitive=default(string), PropertyMetadata AnchorCaseSensitiveMetadata=default(PropertyMetadata), string AnchorHorizontalAlignment=default(string), PropertyMetadata AnchorHorizontalAlignmentMetadata=default(PropertyMetadata), string AnchorIgnoreIfNotPresent=default(string), PropertyMetadata AnchorIgnoreIfNotPresentMetadata=default(PropertyMetadata), string AnchorMatchWholeWord=default(string), PropertyMetadata AnchorMatchWholeWordMetadata=default(PropertyMetadata), string AnchorString=default(string), PropertyMetadata AnchorStringMetadata=default(PropertyMetadata), string AnchorTabProcessorVersion=default(string), PropertyMetadata AnchorTabProcessorVersionMetadata=default(PropertyMetadata), string AnchorUnits=default(string), PropertyMetadata AnchorUnitsMetadata=default(PropertyMetadata), string AnchorXOffset=default(string), PropertyMetadata AnchorXOffsetMetadata=default(PropertyMetadata), string AnchorYOffset=default(string), PropertyMetadata AnchorYOffsetMetadata=default(PropertyMetadata), string Bold=default(string), PropertyMetadata BoldMetadata=default(PropertyMetadata), string ConditionalParentLabel=default(string), PropertyMetadata ConditionalParentLabelMetadata=default(PropertyMetadata), string ConditionalParentValue=default(string), PropertyMetadata ConditionalParentValueMetadata=default(PropertyMetadata), string CustomTabId=default(string), PropertyMetadata CustomTabIdMetadata=default(PropertyMetadata), string DocumentId=default(string), PropertyMetadata DocumentIdMetadata=default(PropertyMetadata), ErrorDetails ErrorDetails=default(ErrorDetails), string Font=default(string), string FontColor=default(string), PropertyMetadata FontColorMetadata=default(PropertyMetadata), PropertyMetadata FontMetadata=default(PropertyMetadata), string FontSize=default(string), PropertyMetadata FontSizeMetadata=default(PropertyMetadata), string FormOrder=default(string), PropertyMetadata FormOrderMetadata=default(PropertyMetadata), string FormPageLabel=default(string), PropertyMetadata FormPageLabelMetadata=default(PropertyMetadata), string FormPageNumber=default(string), PropertyMetadata FormPageNumberMetadata=default(PropertyMetadata), string Height=default(string), PropertyMetadata HeightMetadata=default(PropertyMetadata), string Italic=default(string), PropertyMetadata ItalicMetadata=default(PropertyMetadata), LocalePolicyTab LocalePolicy=default(LocalePolicyTab), MergeField MergeField=default(MergeField), string MergeFieldXml=default(string), string Name=default(string), PropertyMetadata NameMetadata=default(PropertyMetadata), string PageNumber=default(string), PropertyMetadata PageNumberMetadata=default(PropertyMetadata), string RecipientId=default(string), string RecipientIdGuid=default(string), PropertyMetadata RecipientIdGuidMetadata=default(PropertyMetadata), PropertyMetadata RecipientIdMetadata=default(PropertyMetadata), SmartContractInformation SmartContractInformation=default(SmartContractInformation), string Source=default(string), string Status=default(string), PropertyMetadata StatusMetadata=default(PropertyMetadata), List&lt; string &gt; TabGroupLabels=default(List&lt; string &gt;), PropertyMetadata TabGroupLabelsMetadata=default(PropertyMetadata), string TabId=default(string), PropertyMetadata TabIdMetadata=default(PropertyMetadata), string TabLabel=default(string), PropertyMetadata TabLabelMetadata=default(PropertyMetadata), string TabOrder=default(string), PropertyMetadata TabOrderMetadata=default(PropertyMetadata), string TabType=default(string), PropertyMetadata TabTypeMetadata=default(PropertyMetadata), string TemplateLocked=default(string), PropertyMetadata TemplateLockedMetadata=default(PropertyMetadata), string TemplateRequired=default(string), PropertyMetadata TemplateRequiredMetadata=default(PropertyMetadata), string Tooltip=default(string), PropertyMetadata ToolTipMetadata=default(PropertyMetadata), string Underline=default(string), PropertyMetadata UnderlineMetadata=default(PropertyMetadata), string Value=default(string), PropertyMetadata ValueMetadata=default(PropertyMetadata), string Width=default(string), PropertyMetadata WidthMetadata=default(PropertyMetadata), string XPosition=default(string), PropertyMetadata XPositionMetadata=default(PropertyMetadata), string YPosition=default(string), PropertyMetadata YPositionMetadata=default(PropertyMetadata))',
      ],
    ],
  ],
  [
    'folder',
    [
      'Folder',
      [
        '../class_docu_sign_1_1e_sign_1_1_model_1_1_folder.html#aee30b27f7b6c4ee57c05ad84e75165f0',
        1,
        'DocuSign.eSign.Model.Folder.Folder()',
      ],
      [
        '../class_docu_sign_1_1e_sign_1_1_model_1_1_folder.html#a88725c13dc82be91b18f40b93ae86a62',
        1,
        'DocuSign.eSign.Model.Folder.Folder(ErrorDetails ErrorDetails=default(ErrorDetails), Filter Filter=default(Filter), string FolderId=default(string), List&lt; FolderItemV2 &gt; FolderItems=default(List&lt; FolderItemV2 &gt;), List&lt; Folder &gt; Folders=default(List&lt; Folder &gt;), string HasAccess=default(string), string HasSubFolders=default(string), string ItemCount=default(string), string Name=default(string), UserInfo Owner=default(UserInfo), string ParentFolderId=default(string), string ParentFolderUri=default(string), string SubFolderCount=default(string), string Type=default(string), string Uri=default(string))',
      ],
    ],
  ],
  [
    'folderitem',
    [
      'FolderItem',
      [
        '../class_docu_sign_1_1e_sign_1_1_model_1_1_folder_item.html#ae219d35a9d23595c2201ce26fc701711',
        1,
        'DocuSign.eSign.Model.FolderItem.FolderItem()',
      ],
      [
        '../class_docu_sign_1_1e_sign_1_1_model_1_1_folder_item.html#ace151cc78d83e0c82e7348dc27dcd6b9',
        1,
        'DocuSign.eSign.Model.FolderItem.FolderItem(string CompletedDateTime=default(string), string CreatedDateTime=default(string), List&lt; CustomFieldV2 &gt; CustomFields=default(List&lt; CustomFieldV2 &gt;), string Description=default(string), string EnvelopeId=default(string), string EnvelopeUri=default(string), string Is21CFRPart11=default(string), string IsSignatureProviderEnvelope=default(string), string LastModified=default(string), string Name=default(string), string OwnerName=default(string), int?PageCount=default(int?), string Password=default(string), string SenderEmail=default(string), string SenderName=default(string), string SentDateTime=default(string), string Shared=default(string), string Status=default(string), string Subject=default(string), string TemplateId=default(string), string Uri=default(string))',
      ],
    ],
  ],
  [
    'folderitemresponse',
    [
      'FolderItemResponse',
      [
        '../class_docu_sign_1_1e_sign_1_1_model_1_1_folder_item_response.html#aeeec560891befb514633f9def6e21d24',
        1,
        'DocuSign.eSign.Model.FolderItemResponse.FolderItemResponse()',
      ],
      [
        '../class_docu_sign_1_1e_sign_1_1_model_1_1_folder_item_response.html#a7ad899384bee16d9885e75c0d9358544',
        1,
        'DocuSign.eSign.Model.FolderItemResponse.FolderItemResponse(string EndPosition=default(string), List&lt; FolderItemV2 &gt; FolderItems=default(List&lt; FolderItemV2 &gt;), string NextUri=default(string), string PreviousUri=default(string), string ResultSetSize=default(string), string StartPosition=default(string), string TotalRows=default(string))',
      ],
    ],
  ],
  [
    'folderitemsresponse',
    [
      'FolderItemsResponse',
      [
        '../class_docu_sign_1_1e_sign_1_1_model_1_1_folder_items_response.html#ab4a2fd7a2b35d4561734d47aa7213298',
        1,
        'DocuSign.eSign.Model.FolderItemsResponse.FolderItemsResponse()',
      ],
      [
        '../class_docu_sign_1_1e_sign_1_1_model_1_1_folder_items_response.html#a802283fa27d13caf0bf4d8d10462687c',
        1,
        'DocuSign.eSign.Model.FolderItemsResponse.FolderItemsResponse(string EndPosition=default(string), List&lt; EnvelopeSummary &gt; Envelopes=default(List&lt; EnvelopeSummary &gt;), List&lt; Folder &gt; Folders=default(List&lt; Folder &gt;), string NextUri=default(string), string PreviousUri=default(string), string ResultSetSize=default(string), string StartPosition=default(string), string TotalSetSize=default(string))',
      ],
    ],
  ],
  [
    'folderitemv2',
    [
      'FolderItemV2',
      [
        '../class_docu_sign_1_1e_sign_1_1_model_1_1_folder_item_v2.html#a5cde809473930a0a668141150da8667a',
        1,
        'DocuSign.eSign.Model.FolderItemV2.FolderItemV2()',
      ],
      [
        '../class_docu_sign_1_1e_sign_1_1_model_1_1_folder_item_v2.html#a87548f6c5cba57e1990305113d98a76a',
        1,
        'DocuSign.eSign.Model.FolderItemV2.FolderItemV2(string CompletedDateTime=default(string), string CreatedDateTime=default(string), string EnvelopeId=default(string), string EnvelopeUri=default(string), string ExpireDateTime=default(string), string FolderId=default(string), string FolderUri=default(string), string Is21CFRPart11=default(string), string OwnerName=default(string), Recipients Recipients=default(Recipients), string RecipientsUri=default(string), string SenderCompany=default(string), string SenderEmail=default(string), string SenderName=default(string), string SenderUserId=default(string), string SentDateTime=default(string), string Status=default(string), string Subject=default(string), string TemplateId=default(string), string TemplateUri=default(string))',
      ],
    ],
  ],
  [
    'foldersapi',
    [
      'FoldersApi',
      [
        '../class_docu_sign_1_1e_sign_1_1_api_1_1_folders_api.html#a763f6727c63d3b49eaa1db1bf7cc5f92',
        1,
        'DocuSign::eSign::Api::FoldersApi',
      ],
    ],
  ],
  [
    'foldershareditem',
    [
      'FolderSharedItem',
      [
        '../class_docu_sign_1_1e_sign_1_1_model_1_1_folder_shared_item.html#a9b2cbc42e8dac127285a46288c662b3c',
        1,
        'DocuSign.eSign.Model.FolderSharedItem.FolderSharedItem()',
      ],
      [
        '../class_docu_sign_1_1e_sign_1_1_model_1_1_folder_shared_item.html#ad49a45917592780ea86cc3318589a09e',
        1,
        'DocuSign.eSign.Model.FolderSharedItem.FolderSharedItem(ErrorDetails ErrorDetails=default(ErrorDetails), string FolderId=default(string), string Name=default(string), UserInfo Owner=default(UserInfo), string ParentFolderId=default(string), string ParentFolderUri=default(string), string Shared=default(string), List&lt; MemberGroupSharedItem &gt; SharedGroups=default(List&lt; MemberGroupSharedItem &gt;), List&lt; UserSharedItem &gt; SharedUsers=default(List&lt; UserSharedItem &gt;), string Uri=default(string), UserInfo User=default(UserInfo))',
      ],
    ],
  ],
  [
    'foldersrequest',
    [
      'FoldersRequest',
      [
        '../class_docu_sign_1_1e_sign_1_1_model_1_1_folders_request.html#a31b3ea9ed823e2a39cf23a8642124778',
        1,
        'DocuSign.eSign.Model.FoldersRequest.FoldersRequest()',
      ],
      [
        '../class_docu_sign_1_1e_sign_1_1_model_1_1_folders_request.html#a6f443565e82ec3bd7d766dca5be824da',
        1,
        'DocuSign.eSign.Model.FoldersRequest.FoldersRequest(List&lt; string &gt; EnvelopeIds=default(List&lt; string &gt;), List&lt; Folder &gt; Folders=default(List&lt; Folder &gt;), string FromFolderId=default(string))',
      ],
    ],
  ],
  [
    'foldersresponse',
    [
      'FoldersResponse',
      [
        '../class_docu_sign_1_1e_sign_1_1_model_1_1_folders_response.html#a533a2f48cea69c54e6cbdb5ebf0e244f',
        1,
        'DocuSign.eSign.Model.FoldersResponse.FoldersResponse()',
      ],
      [
        '../class_docu_sign_1_1e_sign_1_1_model_1_1_folders_response.html#a503e4db714e4ae520901495757156989',
        1,
        'DocuSign.eSign.Model.FoldersResponse.FoldersResponse(string EndPosition=default(string), List&lt; EnvelopeSummary &gt; Envelopes=default(List&lt; EnvelopeSummary &gt;), List&lt; Folder &gt; Folders=default(List&lt; Folder &gt;), string NextUri=default(string), string PreviousUri=default(string), string ResultSetSize=default(string), string StartPosition=default(string), string TotalSetSize=default(string))',
      ],
    ],
  ],
  [
    'forgottenpasswordinformation',
    [
      'ForgottenPasswordInformation',
      [
        '../class_docu_sign_1_1e_sign_1_1_model_1_1_forgotten_password_information.html#a9266de2373e721128ed59bb181864820',
        1,
        'DocuSign.eSign.Model.ForgottenPasswordInformation.ForgottenPasswordInformation()',
      ],
      [
        '../class_docu_sign_1_1e_sign_1_1_model_1_1_forgotten_password_information.html#af875a5011704ac7c5ca97f044a388fbc',
        1,
        'DocuSign.eSign.Model.ForgottenPasswordInformation.ForgottenPasswordInformation(string ForgottenPasswordAnswer1=default(string), string ForgottenPasswordAnswer2=default(string), string ForgottenPasswordAnswer3=default(string), string ForgottenPasswordAnswer4=default(string), string ForgottenPasswordQuestion1=default(string), string ForgottenPasswordQuestion2=default(string), string ForgottenPasswordQuestion3=default(string), string ForgottenPasswordQuestion4=default(string))',
      ],
    ],
  ],
  [
    'formdataitem',
    [
      'FormDataItem',
      [
        '../class_docu_sign_1_1e_sign_1_1_model_1_1_form_data_item.html#abbb051ee24ee038674fd8efa01a8b7d8',
        1,
        'DocuSign.eSign.Model.FormDataItem.FormDataItem()',
      ],
      [
        '../class_docu_sign_1_1e_sign_1_1_model_1_1_form_data_item.html#aff6ad74342410aae666ea47a125ed0ae',
        1,
        'DocuSign.eSign.Model.FormDataItem.FormDataItem(ErrorDetails ErrorDetails=default(ErrorDetails), string ListSelectedValue=default(string), string Name=default(string), string OriginalValue=default(string), string Value=default(string))',
      ],
    ],
  ],
  [
    'formulatab',
    [
      'FormulaTab',
      [
        '../class_docu_sign_1_1e_sign_1_1_model_1_1_formula_tab.html#a885e3a912daeeab265633d1dc0a37ff4',
        1,
        'DocuSign.eSign.Model.FormulaTab.FormulaTab()',
      ],
      [
        '../class_docu_sign_1_1e_sign_1_1_model_1_1_formula_tab.html#af09f8495bffef3a60c6e657fe7c08843',
        1,
        'DocuSign.eSign.Model.FormulaTab.FormulaTab(string AnchorAllowWhiteSpaceInCharacters=default(string), PropertyMetadata AnchorAllowWhiteSpaceInCharactersMetadata=default(PropertyMetadata), string AnchorCaseSensitive=default(string), PropertyMetadata AnchorCaseSensitiveMetadata=default(PropertyMetadata), string AnchorHorizontalAlignment=default(string), PropertyMetadata AnchorHorizontalAlignmentMetadata=default(PropertyMetadata), string AnchorIgnoreIfNotPresent=default(string), PropertyMetadata AnchorIgnoreIfNotPresentMetadata=default(PropertyMetadata), string AnchorMatchWholeWord=default(string), PropertyMetadata AnchorMatchWholeWordMetadata=default(PropertyMetadata), string AnchorString=default(string), PropertyMetadata AnchorStringMetadata=default(PropertyMetadata), string AnchorTabProcessorVersion=default(string), PropertyMetadata AnchorTabProcessorVersionMetadata=default(PropertyMetadata), string AnchorUnits=default(string), PropertyMetadata AnchorUnitsMetadata=default(PropertyMetadata), string AnchorXOffset=default(string), PropertyMetadata AnchorXOffsetMetadata=default(PropertyMetadata), string AnchorYOffset=default(string), PropertyMetadata AnchorYOffsetMetadata=default(PropertyMetadata), string Bold=default(string), PropertyMetadata BoldMetadata=default(PropertyMetadata), string ConcealValueOnDocument=default(string), PropertyMetadata ConcealValueOnDocumentMetadata=default(PropertyMetadata), string ConditionalParentLabel=default(string), PropertyMetadata ConditionalParentLabelMetadata=default(PropertyMetadata), string ConditionalParentValue=default(string), PropertyMetadata ConditionalParentValueMetadata=default(PropertyMetadata), string CustomTabId=default(string), PropertyMetadata CustomTabIdMetadata=default(PropertyMetadata), string DisableAutoSize=default(string), PropertyMetadata DisableAutoSizeMetadata=default(PropertyMetadata), string DocumentId=default(string), PropertyMetadata DocumentIdMetadata=default(PropertyMetadata), ErrorDetails ErrorDetails=default(ErrorDetails), string Font=default(string), string FontColor=default(string), PropertyMetadata FontColorMetadata=default(PropertyMetadata), PropertyMetadata FontMetadata=default(PropertyMetadata), string FontSize=default(string), PropertyMetadata FontSizeMetadata=default(PropertyMetadata), string FormOrder=default(string), PropertyMetadata FormOrderMetadata=default(PropertyMetadata), string FormPageLabel=default(string), PropertyMetadata FormPageLabelMetadata=default(PropertyMetadata), string FormPageNumber=default(string), PropertyMetadata FormPageNumberMetadata=default(PropertyMetadata), string Formula=default(string), PropertyMetadata FormulaMetadata=default(PropertyMetadata), string Height=default(string), PropertyMetadata HeightMetadata=default(PropertyMetadata), string Hidden=default(string), PropertyMetadata HiddenMetadata=default(PropertyMetadata), string IsPaymentAmount=default(string), PropertyMetadata IsPaymentAmountMetadata=default(PropertyMetadata), string Italic=default(string), PropertyMetadata ItalicMetadata=default(PropertyMetadata), LocalePolicyTab LocalePolicy=default(LocalePolicyTab), string Locked=default(string), PropertyMetadata LockedMetadata=default(PropertyMetadata), string MaxLength=default(string), PropertyMetadata MaxLengthMetadata=default(PropertyMetadata), MergeField MergeField=default(MergeField), string MergeFieldXml=default(string), string Name=default(string), PropertyMetadata NameMetadata=default(PropertyMetadata), string OriginalValue=default(string), PropertyMetadata OriginalValueMetadata=default(PropertyMetadata), string PageNumber=default(string), PropertyMetadata PageNumberMetadata=default(PropertyMetadata), PaymentDetails PaymentDetails=default(PaymentDetails), string RecipientId=default(string), string RecipientIdGuid=default(string), PropertyMetadata RecipientIdGuidMetadata=default(PropertyMetadata), PropertyMetadata RecipientIdMetadata=default(PropertyMetadata), string RequireAll=default(string), PropertyMetadata RequireAllMetadata=default(PropertyMetadata), string Required=default(string), PropertyMetadata RequiredMetadata=default(PropertyMetadata), string RequireInitialOnSharedChange=default(string), PropertyMetadata RequireInitialOnSharedChangeMetadata=default(PropertyMetadata), string RoundDecimalPlaces=default(string), PropertyMetadata RoundDecimalPlacesMetadata=default(PropertyMetadata), string SenderRequired=default(string), PropertyMetadata SenderRequiredMetadata=default(PropertyMetadata), string Shared=default(string), PropertyMetadata SharedMetadata=default(PropertyMetadata), SmartContractInformation SmartContractInformation=default(SmartContractInformation), string Source=default(string), string Status=default(string), PropertyMetadata StatusMetadata=default(PropertyMetadata), List&lt; string &gt; TabGroupLabels=default(List&lt; string &gt;), PropertyMetadata TabGroupLabelsMetadata=default(PropertyMetadata), string TabId=default(string), PropertyMetadata TabIdMetadata=default(PropertyMetadata), string TabLabel=default(string), PropertyMetadata TabLabelMetadata=default(PropertyMetadata), string TabOrder=default(string), PropertyMetadata TabOrderMetadata=default(PropertyMetadata), string TabType=default(string), PropertyMetadata TabTypeMetadata=default(PropertyMetadata), string TemplateLocked=default(string), PropertyMetadata TemplateLockedMetadata=default(PropertyMetadata), string TemplateRequired=default(string), PropertyMetadata TemplateRequiredMetadata=default(PropertyMetadata), string Tooltip=default(string), PropertyMetadata ToolTipMetadata=default(PropertyMetadata), string Underline=default(string), PropertyMetadata UnderlineMetadata=default(PropertyMetadata), string ValidationMessage=default(string), PropertyMetadata ValidationMessageMetadata=default(PropertyMetadata), string ValidationPattern=default(string), PropertyMetadata ValidationPatternMetadata=default(PropertyMetadata), string Value=default(string), PropertyMetadata ValueMetadata=default(PropertyMetadata), string Width=default(string), PropertyMetadata WidthMetadata=default(PropertyMetadata), string XPosition=default(string), PropertyMetadata XPositionMetadata=default(PropertyMetadata), string YPosition=default(string), PropertyMetadata YPositionMetadata=default(PropertyMetadata))',
      ],
    ],
  ],
  [
    'fullname',
    [
      'FullName',
      [
        '../class_docu_sign_1_1e_sign_1_1_model_1_1_full_name.html#ab132ff26d42f2026d31393cebddf7bb4',
        1,
        'DocuSign.eSign.Model.FullName.FullName()',
      ],
      [
        '../class_docu_sign_1_1e_sign_1_1_model_1_1_full_name.html#aff958a34146055123637bc7702ffda43',
        1,
        'DocuSign.eSign.Model.FullName.FullName(string AnchorAllowWhiteSpaceInCharacters=default(string), PropertyMetadata AnchorAllowWhiteSpaceInCharactersMetadata=default(PropertyMetadata), string AnchorCaseSensitive=default(string), PropertyMetadata AnchorCaseSensitiveMetadata=default(PropertyMetadata), string AnchorHorizontalAlignment=default(string), PropertyMetadata AnchorHorizontalAlignmentMetadata=default(PropertyMetadata), string AnchorIgnoreIfNotPresent=default(string), PropertyMetadata AnchorIgnoreIfNotPresentMetadata=default(PropertyMetadata), string AnchorMatchWholeWord=default(string), PropertyMetadata AnchorMatchWholeWordMetadata=default(PropertyMetadata), string AnchorString=default(string), PropertyMetadata AnchorStringMetadata=default(PropertyMetadata), string AnchorTabProcessorVersion=default(string), PropertyMetadata AnchorTabProcessorVersionMetadata=default(PropertyMetadata), string AnchorUnits=default(string), PropertyMetadata AnchorUnitsMetadata=default(PropertyMetadata), string AnchorXOffset=default(string), PropertyMetadata AnchorXOffsetMetadata=default(PropertyMetadata), string AnchorYOffset=default(string), PropertyMetadata AnchorYOffsetMetadata=default(PropertyMetadata), string Bold=default(string), PropertyMetadata BoldMetadata=default(PropertyMetadata), string ConditionalParentLabel=default(string), PropertyMetadata ConditionalParentLabelMetadata=default(PropertyMetadata), string ConditionalParentValue=default(string), PropertyMetadata ConditionalParentValueMetadata=default(PropertyMetadata), string CustomTabId=default(string), PropertyMetadata CustomTabIdMetadata=default(PropertyMetadata), string DocumentId=default(string), PropertyMetadata DocumentIdMetadata=default(PropertyMetadata), ErrorDetails ErrorDetails=default(ErrorDetails), string Font=default(string), string FontColor=default(string), PropertyMetadata FontColorMetadata=default(PropertyMetadata), PropertyMetadata FontMetadata=default(PropertyMetadata), string FontSize=default(string), PropertyMetadata FontSizeMetadata=default(PropertyMetadata), string FormOrder=default(string), PropertyMetadata FormOrderMetadata=default(PropertyMetadata), string FormPageLabel=default(string), PropertyMetadata FormPageLabelMetadata=default(PropertyMetadata), string FormPageNumber=default(string), PropertyMetadata FormPageNumberMetadata=default(PropertyMetadata), string Height=default(string), PropertyMetadata HeightMetadata=default(PropertyMetadata), string Italic=default(string), PropertyMetadata ItalicMetadata=default(PropertyMetadata), LocalePolicyTab LocalePolicy=default(LocalePolicyTab), MergeField MergeField=default(MergeField), string MergeFieldXml=default(string), string Name=default(string), PropertyMetadata NameMetadata=default(PropertyMetadata), string PageNumber=default(string), PropertyMetadata PageNumberMetadata=default(PropertyMetadata), string RecipientId=default(string), string RecipientIdGuid=default(string), PropertyMetadata RecipientIdGuidMetadata=default(PropertyMetadata), PropertyMetadata RecipientIdMetadata=default(PropertyMetadata), SmartContractInformation SmartContractInformation=default(SmartContractInformation), string Source=default(string), string Status=default(string), PropertyMetadata StatusMetadata=default(PropertyMetadata), List&lt; string &gt; TabGroupLabels=default(List&lt; string &gt;), PropertyMetadata TabGroupLabelsMetadata=default(PropertyMetadata), string TabId=default(string), PropertyMetadata TabIdMetadata=default(PropertyMetadata), string TabLabel=default(string), PropertyMetadata TabLabelMetadata=default(PropertyMetadata), string TabOrder=default(string), PropertyMetadata TabOrderMetadata=default(PropertyMetadata), string TabType=default(string), PropertyMetadata TabTypeMetadata=default(PropertyMetadata), string TemplateLocked=default(string), PropertyMetadata TemplateLockedMetadata=default(PropertyMetadata), string TemplateRequired=default(string), PropertyMetadata TemplateRequiredMetadata=default(PropertyMetadata), string Tooltip=default(string), PropertyMetadata ToolTipMetadata=default(PropertyMetadata), string Underline=default(string), PropertyMetadata UnderlineMetadata=default(PropertyMetadata), string Value=default(string), PropertyMetadata ValueMetadata=default(PropertyMetadata), string Width=default(string), PropertyMetadata WidthMetadata=default(PropertyMetadata), string XPosition=default(string), PropertyMetadata XPositionMetadata=default(PropertyMetadata), string YPosition=default(string), PropertyMetadata YPositionMetadata=default(PropertyMetadata))',
      ],
    ],
  ],
];
