var searchData = [
  [
    'namevalue',
    [
      'NameValue',
      [
        '../class_docu_sign_1_1e_sign_1_1_model_1_1_name_value.html#a07cd67dbd4844a37b6b9cc1f9e6afde9',
        1,
        'DocuSign.eSign.Model.NameValue.NameValue()',
      ],
      [
        '../class_docu_sign_1_1e_sign_1_1_model_1_1_name_value.html#afafb8b46b23c7930225b47efb87df414',
        1,
        'DocuSign.eSign.Model.NameValue.NameValue(ErrorDetails ErrorDetails=default(ErrorDetails), string Name=default(string), string OriginalValue=default(string), string Value=default(string))',
      ],
    ],
  ],
  [
    'newaccountdefinition',
    [
      'NewAccountDefinition',
      [
        '../class_docu_sign_1_1e_sign_1_1_model_1_1_new_account_definition.html#a0210db9dc3a8130d0b41f5deeced83d1',
        1,
        'DocuSign.eSign.Model.NewAccountDefinition.NewAccountDefinition()',
      ],
      [
        '../class_docu_sign_1_1e_sign_1_1_model_1_1_new_account_definition.html#abb34fb4a204475cdd3a5e03c254bfc94',
        1,
        'DocuSign.eSign.Model.NewAccountDefinition.NewAccountDefinition(string AccountName=default(string), AccountSettingsInformation AccountSettings=default(AccountSettingsInformation), AccountAddress AddressInformation=default(AccountAddress), CreditCardInformation CreditCardInformation=default(CreditCardInformation), DirectDebitProcessorInformation DirectDebitProcessorInformation=default(DirectDebitProcessorInformation), string DistributorCode=default(string), string DistributorPassword=default(string), string EnvelopePartitionId=default(string), UserInformation InitialUser=default(UserInformation), string PaymentMethod=default(string), PaymentProcessorInformation PaymentProcessorInformation=default(PaymentProcessorInformation), PlanInformation PlanInformation=default(PlanInformation), ReferralInformation ReferralInformation=default(ReferralInformation), SocialAccountInformation SocialAccountInformation=default(SocialAccountInformation))',
      ],
    ],
  ],
  [
    'newaccountsummary',
    [
      'NewAccountSummary',
      [
        '../class_docu_sign_1_1e_sign_1_1_model_1_1_new_account_summary.html#a28ea9bdc65b914c71cf5c10ea7f7336c',
        1,
        'DocuSign.eSign.Model.NewAccountSummary.NewAccountSummary()',
      ],
      [
        '../class_docu_sign_1_1e_sign_1_1_model_1_1_new_account_summary.html#a57d6d32bda77ac2beeea2b371c023c31',
        1,
        'DocuSign.eSign.Model.NewAccountSummary.NewAccountSummary(string AccountId=default(string), string AccountIdGuid=default(string), string AccountName=default(string), string ApiPassword=default(string), string BaseUrl=default(string), BillingPlanPreview BillingPlanPreview=default(BillingPlanPreview), string UserId=default(string))',
      ],
    ],
  ],
  [
    'newuser',
    [
      'NewUser',
      [
        '../class_docu_sign_1_1e_sign_1_1_model_1_1_new_user.html#a71327cfbd26d34ffcb4781357b25f183',
        1,
        'DocuSign.eSign.Model.NewUser.NewUser()',
      ],
      [
        '../class_docu_sign_1_1e_sign_1_1_model_1_1_new_user.html#ac7979c488eaba151dd28f69c63c337fa',
        1,
        'DocuSign.eSign.Model.NewUser.NewUser(string ApiPassword=default(string), string CreatedDateTime=default(string), string Email=default(string), ErrorDetails ErrorDetails=default(ErrorDetails), string MembershipId=default(string), string PermissionProfileId=default(string), string PermissionProfileName=default(string), string Uri=default(string), string UserId=default(string), string UserName=default(string), string UserStatus=default(string))',
      ],
    ],
  ],
  [
    'newusersdefinition',
    [
      'NewUsersDefinition',
      [
        '../class_docu_sign_1_1e_sign_1_1_model_1_1_new_users_definition.html#a4917502b773d768287fa1b00c3068608',
        1,
        'DocuSign.eSign.Model.NewUsersDefinition.NewUsersDefinition()',
      ],
      [
        '../class_docu_sign_1_1e_sign_1_1_model_1_1_new_users_definition.html#a21b3335e9dfbae685a18e278c1285bf5',
        1,
        'DocuSign.eSign.Model.NewUsersDefinition.NewUsersDefinition(List&lt; UserInformation &gt; NewUsers=default(List&lt; UserInformation &gt;))',
      ],
    ],
  ],
  [
    'newuserssummary',
    [
      'NewUsersSummary',
      [
        '../class_docu_sign_1_1e_sign_1_1_model_1_1_new_users_summary.html#a83957353d08630f17a317ce31392b21e',
        1,
        'DocuSign.eSign.Model.NewUsersSummary.NewUsersSummary()',
      ],
      [
        '../class_docu_sign_1_1e_sign_1_1_model_1_1_new_users_summary.html#a8aff7d3549f8a947812dd4e652ba397d',
        1,
        'DocuSign.eSign.Model.NewUsersSummary.NewUsersSummary(List&lt; NewUser &gt; NewUsers=default(List&lt; NewUser &gt;))',
      ],
    ],
  ],
  [
    'notarize',
    [
      'Notarize',
      [
        '../class_docu_sign_1_1e_sign_1_1_model_1_1_notarize.html#aac97e7b5bd6d59d5cb8786b4b8f28e99',
        1,
        'DocuSign.eSign.Model.Notarize.Notarize()',
      ],
      [
        '../class_docu_sign_1_1e_sign_1_1_model_1_1_notarize.html#af88546b244362ba93d85b1904c432a73',
        1,
        'DocuSign.eSign.Model.Notarize.Notarize(string AnchorAllowWhiteSpaceInCharacters=default(string), PropertyMetadata AnchorAllowWhiteSpaceInCharactersMetadata=default(PropertyMetadata), string AnchorCaseSensitive=default(string), PropertyMetadata AnchorCaseSensitiveMetadata=default(PropertyMetadata), string AnchorHorizontalAlignment=default(string), PropertyMetadata AnchorHorizontalAlignmentMetadata=default(PropertyMetadata), string AnchorIgnoreIfNotPresent=default(string), PropertyMetadata AnchorIgnoreIfNotPresentMetadata=default(PropertyMetadata), string AnchorMatchWholeWord=default(string), PropertyMetadata AnchorMatchWholeWordMetadata=default(PropertyMetadata), string AnchorString=default(string), PropertyMetadata AnchorStringMetadata=default(PropertyMetadata), string AnchorTabProcessorVersion=default(string), PropertyMetadata AnchorTabProcessorVersionMetadata=default(PropertyMetadata), string AnchorUnits=default(string), PropertyMetadata AnchorUnitsMetadata=default(PropertyMetadata), string AnchorXOffset=default(string), PropertyMetadata AnchorXOffsetMetadata=default(PropertyMetadata), string AnchorYOffset=default(string), PropertyMetadata AnchorYOffsetMetadata=default(PropertyMetadata), string ConditionalParentLabel=default(string), PropertyMetadata ConditionalParentLabelMetadata=default(PropertyMetadata), string ConditionalParentValue=default(string), PropertyMetadata ConditionalParentValueMetadata=default(PropertyMetadata), string CustomTabId=default(string), PropertyMetadata CustomTabIdMetadata=default(PropertyMetadata), string DocumentId=default(string), PropertyMetadata DocumentIdMetadata=default(PropertyMetadata), ErrorDetails ErrorDetails=default(ErrorDetails), string FormOrder=default(string), PropertyMetadata FormOrderMetadata=default(PropertyMetadata), string FormPageLabel=default(string), PropertyMetadata FormPageLabelMetadata=default(PropertyMetadata), string FormPageNumber=default(string), PropertyMetadata FormPageNumberMetadata=default(PropertyMetadata), string Height=default(string), PropertyMetadata HeightMetadata=default(PropertyMetadata), string Locked=default(string), PropertyMetadata LockedMetadata=default(PropertyMetadata), MergeField MergeField=default(MergeField), string MergeFieldXml=default(string), string PageNumber=default(string), PropertyMetadata PageNumberMetadata=default(PropertyMetadata), string RecipientId=default(string), string RecipientIdGuid=default(string), PropertyMetadata RecipientIdGuidMetadata=default(PropertyMetadata), PropertyMetadata RecipientIdMetadata=default(PropertyMetadata), string Required=default(string), PropertyMetadata RequiredMetadata=default(PropertyMetadata), SmartContractInformation SmartContractInformation=default(SmartContractInformation), string Source=default(string), string Status=default(string), PropertyMetadata StatusMetadata=default(PropertyMetadata), List&lt; string &gt; TabGroupLabels=default(List&lt; string &gt;), PropertyMetadata TabGroupLabelsMetadata=default(PropertyMetadata), string TabId=default(string), PropertyMetadata TabIdMetadata=default(PropertyMetadata), string TabOrder=default(string), PropertyMetadata TabOrderMetadata=default(PropertyMetadata), string TabType=default(string), PropertyMetadata TabTypeMetadata=default(PropertyMetadata), string TemplateLocked=default(string), PropertyMetadata TemplateLockedMetadata=default(PropertyMetadata), string TemplateRequired=default(string), PropertyMetadata TemplateRequiredMetadata=default(PropertyMetadata), string Tooltip=default(string), PropertyMetadata ToolTipMetadata=default(PropertyMetadata), string Width=default(string), PropertyMetadata WidthMetadata=default(PropertyMetadata), string XPosition=default(string), PropertyMetadata XPositionMetadata=default(PropertyMetadata), string YPosition=default(string), PropertyMetadata YPositionMetadata=default(PropertyMetadata))',
      ],
    ],
  ],
  [
    'notary',
    [
      'Notary',
      [
        '../class_docu_sign_1_1e_sign_1_1_model_1_1_notary.html#a0e0f40af9c9df0ff11c65c6c4edce269',
        1,
        'DocuSign.eSign.Model.Notary.Notary()',
      ],
      [
        '../class_docu_sign_1_1e_sign_1_1_model_1_1_notary.html#ac1ce369d34a8a2fa38758d7eec87d8f3',
        1,
        'DocuSign.eSign.Model.Notary.Notary(string CreatedDate=default(string), string Enabled=default(string), string Searchable=default(string), UserInformation UserInfo=default(UserInformation))',
      ],
    ],
  ],
  [
    'notaryapi',
    [
      'NotaryApi',
      [
        '../class_docu_sign_1_1e_sign_1_1_api_1_1_notary_api.html#ac6c0b08cd7ac0a9ec7f29014d19b0a72',
        1,
        'DocuSign::eSign::Api::NotaryApi',
      ],
    ],
  ],
  [
    'notarycertificate',
    [
      'NotaryCertificate',
      [
        '../class_docu_sign_1_1e_sign_1_1_model_1_1_notary_certificate.html#a3b8271fb575ea4d8e034a657037d4d58',
        1,
        'DocuSign.eSign.Model.NotaryCertificate.NotaryCertificate()',
      ],
      [
        '../class_docu_sign_1_1e_sign_1_1_model_1_1_notary_certificate.html#ab867452b7e4cf336ce71789bcc894981',
        1,
        'DocuSign.eSign.Model.NotaryCertificate.NotaryCertificate(string AnchorAllowWhiteSpaceInCharacters=default(string), PropertyMetadata AnchorAllowWhiteSpaceInCharactersMetadata=default(PropertyMetadata), string AnchorCaseSensitive=default(string), PropertyMetadata AnchorCaseSensitiveMetadata=default(PropertyMetadata), string AnchorHorizontalAlignment=default(string), PropertyMetadata AnchorHorizontalAlignmentMetadata=default(PropertyMetadata), string AnchorIgnoreIfNotPresent=default(string), PropertyMetadata AnchorIgnoreIfNotPresentMetadata=default(PropertyMetadata), string AnchorMatchWholeWord=default(string), PropertyMetadata AnchorMatchWholeWordMetadata=default(PropertyMetadata), string AnchorString=default(string), PropertyMetadata AnchorStringMetadata=default(PropertyMetadata), string AnchorTabProcessorVersion=default(string), PropertyMetadata AnchorTabProcessorVersionMetadata=default(PropertyMetadata), string AnchorUnits=default(string), PropertyMetadata AnchorUnitsMetadata=default(PropertyMetadata), string AnchorXOffset=default(string), PropertyMetadata AnchorXOffsetMetadata=default(PropertyMetadata), string AnchorYOffset=default(string), PropertyMetadata AnchorYOffsetMetadata=default(PropertyMetadata), string ConditionalParentLabel=default(string), PropertyMetadata ConditionalParentLabelMetadata=default(PropertyMetadata), string ConditionalParentValue=default(string), PropertyMetadata ConditionalParentValueMetadata=default(PropertyMetadata), string CustomTabId=default(string), PropertyMetadata CustomTabIdMetadata=default(PropertyMetadata), string DocumentId=default(string), PropertyMetadata DocumentIdMetadata=default(PropertyMetadata), ErrorDetails ErrorDetails=default(ErrorDetails), string FormOrder=default(string), PropertyMetadata FormOrderMetadata=default(PropertyMetadata), string FormPageLabel=default(string), PropertyMetadata FormPageLabelMetadata=default(PropertyMetadata), string FormPageNumber=default(string), PropertyMetadata FormPageNumberMetadata=default(PropertyMetadata), string Height=default(string), PropertyMetadata HeightMetadata=default(PropertyMetadata), string Locked=default(string), PropertyMetadata LockedMetadata=default(PropertyMetadata), MergeField MergeField=default(MergeField), string MergeFieldXml=default(string), string PageNumber=default(string), PropertyMetadata PageNumberMetadata=default(PropertyMetadata), string RecipientId=default(string), string RecipientIdGuid=default(string), PropertyMetadata RecipientIdGuidMetadata=default(PropertyMetadata), PropertyMetadata RecipientIdMetadata=default(PropertyMetadata), string Required=default(string), PropertyMetadata RequiredMetadata=default(PropertyMetadata), SmartContractInformation SmartContractInformation=default(SmartContractInformation), string Status=default(string), PropertyMetadata StatusMetadata=default(PropertyMetadata), List&lt; string &gt; TabGroupLabels=default(List&lt; string &gt;), PropertyMetadata TabGroupLabelsMetadata=default(PropertyMetadata), string TabId=default(string), PropertyMetadata TabIdMetadata=default(PropertyMetadata), PropertyMetadata TabLabelMetadata=default(PropertyMetadata), string TabOrder=default(string), PropertyMetadata TabOrderMetadata=default(PropertyMetadata), string TabType=default(string), PropertyMetadata TabTypeMetadata=default(PropertyMetadata), string TemplateLocked=default(string), PropertyMetadata TemplateLockedMetadata=default(PropertyMetadata), string TemplateRequired=default(string), PropertyMetadata TemplateRequiredMetadata=default(PropertyMetadata), string Tooltip=default(string), PropertyMetadata ToolTipMetadata=default(PropertyMetadata), string Width=default(string), PropertyMetadata WidthMetadata=default(PropertyMetadata), string XPosition=default(string), PropertyMetadata XPositionMetadata=default(PropertyMetadata), string YPosition=default(string), PropertyMetadata YPositionMetadata=default(PropertyMetadata))',
      ],
    ],
  ],
  [
    'notaryhost',
    [
      'NotaryHost',
      [
        '../class_docu_sign_1_1e_sign_1_1_model_1_1_notary_host.html#abaf8b353cf92c95aae94b65d9f13ce34',
        1,
        'DocuSign.eSign.Model.NotaryHost.NotaryHost()',
      ],
      [
        '../class_docu_sign_1_1e_sign_1_1_model_1_1_notary_host.html#af476b03dd7197bbbb5238917886ad12c',
        1,
        'DocuSign.eSign.Model.NotaryHost.NotaryHost(string AccessCode=default(string), PropertyMetadata AccessCodeMetadata=default(PropertyMetadata), string AddAccessCodeToEmail=default(string), string AllowSystemOverrideForLockedRecipient=default(string), string ClientUserId=default(string), string CompletedCount=default(string), List&lt; string &gt; CustomFields=default(List&lt; string &gt;), string DeclinedDateTime=default(string), string DeclinedReason=default(string), string DeliveredDateTime=default(string), string DeliveryMethod=default(string), PropertyMetadata DeliveryMethodMetadata=default(PropertyMetadata), string DesignatorId=default(string), string DesignatorIdGuid=default(string), List&lt; DocumentVisibility &gt; DocumentVisibility=default(List&lt; DocumentVisibility &gt;), string Email=default(string), PropertyMetadata EmailMetadata=default(PropertyMetadata), RecipientEmailNotification EmailNotification=default(RecipientEmailNotification), string EmbeddedRecipientStartURL=default(string), ErrorDetails ErrorDetails=default(ErrorDetails), string FaxNumber=default(string), PropertyMetadata FaxNumberMetadata=default(PropertyMetadata), string HostRecipientId=default(string), string IdCheckConfigurationName=default(string), PropertyMetadata IdCheckConfigurationNameMetadata=default(PropertyMetadata), IdCheckInformationInput IdCheckInformationInput=default(IdCheckInformationInput), RecipientIdentityVerification IdentityVerification=default(RecipientIdentityVerification), string InheritEmailNotificationConfiguration=default(string), string LockedRecipientPhoneAuthEditable=default(string), string LockedRecipientSmsEditable=default(string), string Name=default(string), PropertyMetadata NameMetadata=default(PropertyMetadata), string Note=default(string), PropertyMetadata NoteMetadata=default(PropertyMetadata), RecipientPhoneAuthentication PhoneAuthentication=default(RecipientPhoneAuthentication), List&lt; RecipientAttachment &gt; RecipientAttachments=default(List&lt; RecipientAttachment &gt;), AuthenticationStatus RecipientAuthenticationStatus=default(AuthenticationStatus), List&lt; FeatureAvailableMetadata &gt; RecipientFeatureMetadata=default(List&lt; FeatureAvailableMetadata &gt;), string RecipientId=default(string), string RecipientIdGuid=default(string), string RecipientType=default(string), PropertyMetadata RecipientTypeMetadata=default(PropertyMetadata), string RequireIdLookup=default(string), PropertyMetadata RequireIdLookupMetadata=default(PropertyMetadata), string RoleName=default(string), string RoutingOrder=default(string), PropertyMetadata RoutingOrderMetadata=default(PropertyMetadata), string SentDateTime=default(string), string SignedDateTime=default(string), string SigningGroupId=default(string), PropertyMetadata SigningGroupIdMetadata=default(PropertyMetadata), string SigningGroupName=default(string), List&lt; UserInfo &gt; SigningGroupUsers=default(List&lt; UserInfo &gt;), RecipientSMSAuthentication SmsAuthentication=default(RecipientSMSAuthentication), List&lt; SocialAuthentication &gt; SocialAuthentications=default(List&lt; SocialAuthentication &gt;), string Status=default(string), string StatusCode=default(string), string SuppressEmails=default(string), Tabs Tabs=default(Tabs), string TemplateLocked=default(string), string TemplateRequired=default(string), string TotalTabCount=default(string), string UserId=default(string))',
      ],
    ],
  ],
  [
    'notaryjournal',
    [
      'NotaryJournal',
      [
        '../class_docu_sign_1_1e_sign_1_1_model_1_1_notary_journal.html#a95ab4f39e5a034ee7c4fa6fadb2ad681',
        1,
        'DocuSign.eSign.Model.NotaryJournal.NotaryJournal()',
      ],
      [
        '../class_docu_sign_1_1e_sign_1_1_model_1_1_notary_journal.html#ae84db1db12794d3bcf90e0754ac420c0',
        1,
        'DocuSign.eSign.Model.NotaryJournal.NotaryJournal(string CreatedDate=default(string), string DocumentName=default(string), Jurisdiction Jurisdiction=default(Jurisdiction), string NotaryJournalId=default(string), NotaryJournalMetaData NotaryJournalMetaData=default(NotaryJournalMetaData), string SignerName=default(string))',
      ],
    ],
  ],
  [
    'notaryjournalcrediblewitness',
    [
      'NotaryJournalCredibleWitness',
      [
        '../class_docu_sign_1_1e_sign_1_1_model_1_1_notary_journal_credible_witness.html#a321bb5689493990eb6a3a00174b3b81c',
        1,
        'DocuSign.eSign.Model.NotaryJournalCredibleWitness.NotaryJournalCredibleWitness()',
      ],
      [
        '../class_docu_sign_1_1e_sign_1_1_model_1_1_notary_journal_credible_witness.html#a3caff09e150de78c0f54a8c75fe1e335',
        1,
        'DocuSign.eSign.Model.NotaryJournalCredibleWitness.NotaryJournalCredibleWitness(string Address=default(string), string Name=default(string), string SignatureImage=default(string))',
      ],
    ],
  ],
  [
    'notaryjournallist',
    [
      'NotaryJournalList',
      [
        '../class_docu_sign_1_1e_sign_1_1_model_1_1_notary_journal_list.html#a39c35363f1a37585b9019fed3a2020e5',
        1,
        'DocuSign.eSign.Model.NotaryJournalList.NotaryJournalList()',
      ],
      [
        '../class_docu_sign_1_1e_sign_1_1_model_1_1_notary_journal_list.html#a77c6d0749f218f1427cc7a8d72de4cd0',
        1,
        'DocuSign.eSign.Model.NotaryJournalList.NotaryJournalList(string EndPosition=default(string), string NextUri=default(string), List&lt; NotaryJournal &gt; NotaryJournals=default(List&lt; NotaryJournal &gt;), string PreviousUri=default(string), string ResultSetSize=default(string), string StartPosition=default(string), string TotalSetSize=default(string))',
      ],
    ],
  ],
  [
    'notaryjournalmetadata',
    [
      'NotaryJournalMetaData',
      [
        '../class_docu_sign_1_1e_sign_1_1_model_1_1_notary_journal_meta_data.html#ad1c988e6bce6992185a1498981813c15',
        1,
        'DocuSign.eSign.Model.NotaryJournalMetaData.NotaryJournalMetaData()',
      ],
      [
        '../class_docu_sign_1_1e_sign_1_1_model_1_1_notary_journal_meta_data.html#a90fcb25e6c2833b1f92bcbdbbf1f0b66',
        1,
        'DocuSign.eSign.Model.NotaryJournalMetaData.NotaryJournalMetaData(string Comment=default(string), List&lt; NotaryJournalCredibleWitness &gt; CredibleWitnesses=default(List&lt; NotaryJournalCredibleWitness &gt;), string SignatureImage=default(string), string SignerIdType=default(string))',
      ],
    ],
  ],
  [
    'notaryjurisdiction',
    [
      'NotaryJurisdiction',
      [
        '../class_docu_sign_1_1e_sign_1_1_model_1_1_notary_jurisdiction.html#a023c9acff06af548504f2240e6d24179',
        1,
        'DocuSign.eSign.Model.NotaryJurisdiction.NotaryJurisdiction()',
      ],
      [
        '../class_docu_sign_1_1e_sign_1_1_model_1_1_notary_jurisdiction.html#a1cf561abfec2ffbfc3c17000c4373cff',
        1,
        'DocuSign.eSign.Model.NotaryJurisdiction.NotaryJurisdiction(string CommissionExpiration=default(string), string CommissionId=default(string), string County=default(string), ErrorDetails ErrorDetails=default(ErrorDetails), Jurisdiction Jurisdiction=default(Jurisdiction), string RegisteredName=default(string), string SealType=default(string))',
      ],
    ],
  ],
  [
    'notaryjurisdictionlist',
    [
      'NotaryJurisdictionList',
      [
        '../class_docu_sign_1_1e_sign_1_1_model_1_1_notary_jurisdiction_list.html#abb2d8196f728cf5e1f78f31260920794',
        1,
        'DocuSign.eSign.Model.NotaryJurisdictionList.NotaryJurisdictionList()',
      ],
      [
        '../class_docu_sign_1_1e_sign_1_1_model_1_1_notary_jurisdiction_list.html#ab983828b7d0d2f93063de649fd77d716',
        1,
        'DocuSign.eSign.Model.NotaryJurisdictionList.NotaryJurisdictionList(string EndPosition=default(string), string NextUri=default(string), List&lt; NotaryJurisdiction &gt; NotaryJurisdictions=default(List&lt; NotaryJurisdiction &gt;), string PreviousUri=default(string), string ResultSetSize=default(string), string StartPosition=default(string), string TotalSetSize=default(string))',
      ],
    ],
  ],
  [
    'notaryrecipient',
    [
      'NotaryRecipient',
      [
        '../class_docu_sign_1_1e_sign_1_1_model_1_1_notary_recipient.html#a20a86a2d150d35a635b0be26eeb59824',
        1,
        'DocuSign.eSign.Model.NotaryRecipient.NotaryRecipient()',
      ],
      [
        '../class_docu_sign_1_1e_sign_1_1_model_1_1_notary_recipient.html#ab977275afb83914b1b31ce48d49691ac',
        1,
        'DocuSign.eSign.Model.NotaryRecipient.NotaryRecipient(string AccessCode=default(string), PropertyMetadata AccessCodeMetadata=default(PropertyMetadata), string AddAccessCodeToEmail=default(string), List&lt; RecipientAdditionalNotification &gt; AdditionalNotifications=default(List&lt; RecipientAdditionalNotification &gt;), string AgentCanEditEmail=default(string), string AgentCanEditName=default(string), string AllowSystemOverrideForLockedRecipient=default(string), string AutoNavigation=default(string), string BulkRecipientsUri=default(string), string CanSignOffline=default(string), string ClientUserId=default(string), string CompletedCount=default(string), string CreationReason=default(string), List&lt; string &gt; CustomFields=default(List&lt; string &gt;), string DeclinedDateTime=default(string), string DeclinedReason=default(string), string DefaultRecipient=default(string), string DeliveredDateTime=default(string), string DeliveryMethod=default(string), PropertyMetadata DeliveryMethodMetadata=default(PropertyMetadata), string DesignatorId=default(string), string DesignatorIdGuid=default(string), List&lt; DocumentVisibility &gt; DocumentVisibility=default(List&lt; DocumentVisibility &gt;), string Email=default(string), PropertyMetadata EmailMetadata=default(PropertyMetadata), RecipientEmailNotification EmailNotification=default(RecipientEmailNotification), string EmbeddedRecipientStartURL=default(string), ErrorDetails ErrorDetails=default(ErrorDetails), List&lt; string &gt; ExcludedDocuments=default(List&lt; string &gt;), string FaxNumber=default(string), PropertyMetadata FaxNumberMetadata=default(PropertyMetadata), string FirstName=default(string), PropertyMetadata FirstNameMetadata=default(PropertyMetadata), string FullName=default(string), PropertyMetadata FullNameMetadata=default(PropertyMetadata), string IdCheckConfigurationName=default(string), PropertyMetadata IdCheckConfigurationNameMetadata=default(PropertyMetadata), IdCheckInformationInput IdCheckInformationInput=default(IdCheckInformationInput), RecipientIdentityVerification IdentityVerification=default(RecipientIdentityVerification), string InheritEmailNotificationConfiguration=default(string), string IsBulkRecipient=default(string), PropertyMetadata IsBulkRecipientMetadata=default(PropertyMetadata), string LastName=default(string), PropertyMetadata LastNameMetadata=default(PropertyMetadata), string LiveOakStartURL=default(string), string LockedRecipientPhoneAuthEditable=default(string), string LockedRecipientSmsEditable=default(string), string Name=default(string), PropertyMetadata NameMetadata=default(PropertyMetadata), string NotaryId=default(string), List&lt; string &gt; NotarySigners=default(List&lt; string &gt;), string NotaryType=default(string), string Note=default(string), PropertyMetadata NoteMetadata=default(PropertyMetadata), OfflineAttributes OfflineAttributes=default(OfflineAttributes), RecipientPhoneAuthentication PhoneAuthentication=default(RecipientPhoneAuthentication), RecipientProofFile ProofFile=default(RecipientProofFile), List&lt; RecipientAttachment &gt; RecipientAttachments=default(List&lt; RecipientAttachment &gt;), AuthenticationStatus RecipientAuthenticationStatus=default(AuthenticationStatus), List&lt; FeatureAvailableMetadata &gt; RecipientFeatureMetadata=default(List&lt; FeatureAvailableMetadata &gt;), string RecipientId=default(string), string RecipientIdGuid=default(string), List&lt; RecipientSignatureProvider &gt; RecipientSignatureProviders=default(List&lt; RecipientSignatureProvider &gt;), string RecipientSuppliesTabs=default(string), string RecipientType=default(string), PropertyMetadata RecipientTypeMetadata=default(PropertyMetadata), string RequireIdLookup=default(string), PropertyMetadata RequireIdLookupMetadata=default(PropertyMetadata), string RequireSignerCertificate=default(string), string RequireSignOnPaper=default(string), string RequireUploadSignature=default(string), string RoleName=default(string), string RoutingOrder=default(string), PropertyMetadata RoutingOrderMetadata=default(PropertyMetadata), string SentDateTime=default(string), RecipientSignatureInformation SignatureInfo=default(RecipientSignatureInformation), string SignedDateTime=default(string), string SignInEachLocation=default(string), PropertyMetadata SignInEachLocationMetadata=default(PropertyMetadata), string SigningGroupId=default(string), PropertyMetadata SigningGroupIdMetadata=default(PropertyMetadata), string SigningGroupName=default(string), List&lt; UserInfo &gt; SigningGroupUsers=default(List&lt; UserInfo &gt;), RecipientSMSAuthentication SmsAuthentication=default(RecipientSMSAuthentication), List&lt; SocialAuthentication &gt; SocialAuthentications=default(List&lt; SocialAuthentication &gt;), string Status=default(string), string StatusCode=default(string), string SuppressEmails=default(string), Tabs Tabs=default(Tabs), string TemplateLocked=default(string), string TemplateRequired=default(string), string TotalTabCount=default(string), string UserId=default(string))',
      ],
    ],
  ],
  [
    'notaryresult',
    [
      'NotaryResult',
      [
        '../class_docu_sign_1_1e_sign_1_1_model_1_1_notary_result.html#acc6f34505e2fa0519aa4670d8d33fbcd',
        1,
        'DocuSign.eSign.Model.NotaryResult.NotaryResult()',
      ],
      [
        '../class_docu_sign_1_1e_sign_1_1_model_1_1_notary_result.html#a8afb795d751aca4d10c88e7beac52c80',
        1,
        'DocuSign.eSign.Model.NotaryResult.NotaryResult(List&lt; Jurisdiction &gt; Jurisdictions=default(List&lt; Jurisdiction &gt;), Notary Notary=default(Notary))',
      ],
    ],
  ],
  [
    'notaryseal',
    [
      'NotarySeal',
      [
        '../class_docu_sign_1_1e_sign_1_1_model_1_1_notary_seal.html#a49b08184058d0831014afe23f1685271',
        1,
        'DocuSign.eSign.Model.NotarySeal.NotarySeal()',
      ],
      [
        '../class_docu_sign_1_1e_sign_1_1_model_1_1_notary_seal.html#acb099c55fe57f71e3c33fa784e95f376',
        1,
        'DocuSign.eSign.Model.NotarySeal.NotarySeal(string AnchorAllowWhiteSpaceInCharacters=default(string), PropertyMetadata AnchorAllowWhiteSpaceInCharactersMetadata=default(PropertyMetadata), string AnchorCaseSensitive=default(string), PropertyMetadata AnchorCaseSensitiveMetadata=default(PropertyMetadata), string AnchorHorizontalAlignment=default(string), PropertyMetadata AnchorHorizontalAlignmentMetadata=default(PropertyMetadata), string AnchorIgnoreIfNotPresent=default(string), PropertyMetadata AnchorIgnoreIfNotPresentMetadata=default(PropertyMetadata), string AnchorMatchWholeWord=default(string), PropertyMetadata AnchorMatchWholeWordMetadata=default(PropertyMetadata), string AnchorString=default(string), PropertyMetadata AnchorStringMetadata=default(PropertyMetadata), string AnchorTabProcessorVersion=default(string), PropertyMetadata AnchorTabProcessorVersionMetadata=default(PropertyMetadata), string AnchorUnits=default(string), PropertyMetadata AnchorUnitsMetadata=default(PropertyMetadata), string AnchorXOffset=default(string), PropertyMetadata AnchorXOffsetMetadata=default(PropertyMetadata), string AnchorYOffset=default(string), PropertyMetadata AnchorYOffsetMetadata=default(PropertyMetadata), string ConditionalParentLabel=default(string), PropertyMetadata ConditionalParentLabelMetadata=default(PropertyMetadata), string ConditionalParentValue=default(string), PropertyMetadata ConditionalParentValueMetadata=default(PropertyMetadata), string CustomTabId=default(string), PropertyMetadata CustomTabIdMetadata=default(PropertyMetadata), string DocumentId=default(string), PropertyMetadata DocumentIdMetadata=default(PropertyMetadata), ErrorDetails ErrorDetails=default(ErrorDetails), string FormOrder=default(string), PropertyMetadata FormOrderMetadata=default(PropertyMetadata), string FormPageLabel=default(string), PropertyMetadata FormPageLabelMetadata=default(PropertyMetadata), string FormPageNumber=default(string), PropertyMetadata FormPageNumberMetadata=default(PropertyMetadata), string Height=default(string), PropertyMetadata HeightMetadata=default(PropertyMetadata), MergeField MergeField=default(MergeField), string MergeFieldXml=default(string), string Name=default(string), PropertyMetadata NameMetadata=default(PropertyMetadata), string PageNumber=default(string), PropertyMetadata PageNumberMetadata=default(PropertyMetadata), string RecipientId=default(string), string RecipientIdGuid=default(string), PropertyMetadata RecipientIdGuidMetadata=default(PropertyMetadata), PropertyMetadata RecipientIdMetadata=default(PropertyMetadata), string ScaleValue=default(string), PropertyMetadata ScaleValueMetadata=default(PropertyMetadata), SmartContractInformation SmartContractInformation=default(SmartContractInformation), string Source=default(string), string Status=default(string), PropertyMetadata StatusMetadata=default(PropertyMetadata), List&lt; string &gt; TabGroupLabels=default(List&lt; string &gt;), PropertyMetadata TabGroupLabelsMetadata=default(PropertyMetadata), string TabId=default(string), PropertyMetadata TabIdMetadata=default(PropertyMetadata), string TabLabel=default(string), PropertyMetadata TabLabelMetadata=default(PropertyMetadata), string TabOrder=default(string), PropertyMetadata TabOrderMetadata=default(PropertyMetadata), string TabType=default(string), PropertyMetadata TabTypeMetadata=default(PropertyMetadata), string TemplateLocked=default(string), PropertyMetadata TemplateLockedMetadata=default(PropertyMetadata), string TemplateRequired=default(string), PropertyMetadata TemplateRequiredMetadata=default(PropertyMetadata), string Tooltip=default(string), PropertyMetadata ToolTipMetadata=default(PropertyMetadata), string Width=default(string), PropertyMetadata WidthMetadata=default(PropertyMetadata), string XPosition=default(string), PropertyMetadata XPositionMetadata=default(PropertyMetadata), string YPosition=default(string), PropertyMetadata YPositionMetadata=default(PropertyMetadata))',
      ],
    ],
  ],
  [
    'note',
    [
      'Note',
      [
        '../class_docu_sign_1_1e_sign_1_1_model_1_1_note.html#ae0dc6a52e3cb12641bc7ab2b054611ec',
        1,
        'DocuSign.eSign.Model.Note.Note()',
      ],
      [
        '../class_docu_sign_1_1e_sign_1_1_model_1_1_note.html#ac7b0863af831ba1ed846220dc5d0aa31',
        1,
        'DocuSign.eSign.Model.Note.Note(string AnchorAllowWhiteSpaceInCharacters=default(string), PropertyMetadata AnchorAllowWhiteSpaceInCharactersMetadata=default(PropertyMetadata), string AnchorCaseSensitive=default(string), PropertyMetadata AnchorCaseSensitiveMetadata=default(PropertyMetadata), string AnchorHorizontalAlignment=default(string), PropertyMetadata AnchorHorizontalAlignmentMetadata=default(PropertyMetadata), string AnchorIgnoreIfNotPresent=default(string), PropertyMetadata AnchorIgnoreIfNotPresentMetadata=default(PropertyMetadata), string AnchorMatchWholeWord=default(string), PropertyMetadata AnchorMatchWholeWordMetadata=default(PropertyMetadata), string AnchorString=default(string), PropertyMetadata AnchorStringMetadata=default(PropertyMetadata), string AnchorTabProcessorVersion=default(string), PropertyMetadata AnchorTabProcessorVersionMetadata=default(PropertyMetadata), string AnchorUnits=default(string), PropertyMetadata AnchorUnitsMetadata=default(PropertyMetadata), string AnchorXOffset=default(string), PropertyMetadata AnchorXOffsetMetadata=default(PropertyMetadata), string AnchorYOffset=default(string), PropertyMetadata AnchorYOffsetMetadata=default(PropertyMetadata), string Bold=default(string), PropertyMetadata BoldMetadata=default(PropertyMetadata), string ConditionalParentLabel=default(string), PropertyMetadata ConditionalParentLabelMetadata=default(PropertyMetadata), string ConditionalParentValue=default(string), PropertyMetadata ConditionalParentValueMetadata=default(PropertyMetadata), string CustomTabId=default(string), PropertyMetadata CustomTabIdMetadata=default(PropertyMetadata), string DocumentId=default(string), PropertyMetadata DocumentIdMetadata=default(PropertyMetadata), ErrorDetails ErrorDetails=default(ErrorDetails), string Font=default(string), string FontColor=default(string), PropertyMetadata FontColorMetadata=default(PropertyMetadata), PropertyMetadata FontMetadata=default(PropertyMetadata), string FontSize=default(string), PropertyMetadata FontSizeMetadata=default(PropertyMetadata), string FormOrder=default(string), PropertyMetadata FormOrderMetadata=default(PropertyMetadata), string FormPageLabel=default(string), PropertyMetadata FormPageLabelMetadata=default(PropertyMetadata), string FormPageNumber=default(string), PropertyMetadata FormPageNumberMetadata=default(PropertyMetadata), string Height=default(string), PropertyMetadata HeightMetadata=default(PropertyMetadata), string Italic=default(string), PropertyMetadata ItalicMetadata=default(PropertyMetadata), LocalePolicyTab LocalePolicy=default(LocalePolicyTab), MergeField MergeField=default(MergeField), string MergeFieldXml=default(string), string Name=default(string), PropertyMetadata NameMetadata=default(PropertyMetadata), string PageNumber=default(string), PropertyMetadata PageNumberMetadata=default(PropertyMetadata), string RecipientId=default(string), string RecipientIdGuid=default(string), PropertyMetadata RecipientIdGuidMetadata=default(PropertyMetadata), PropertyMetadata RecipientIdMetadata=default(PropertyMetadata), string Shared=default(string), PropertyMetadata SharedMetadata=default(PropertyMetadata), SmartContractInformation SmartContractInformation=default(SmartContractInformation), string Source=default(string), string Status=default(string), PropertyMetadata StatusMetadata=default(PropertyMetadata), List&lt; string &gt; TabGroupLabels=default(List&lt; string &gt;), PropertyMetadata TabGroupLabelsMetadata=default(PropertyMetadata), string TabId=default(string), PropertyMetadata TabIdMetadata=default(PropertyMetadata), string TabLabel=default(string), PropertyMetadata TabLabelMetadata=default(PropertyMetadata), string TabOrder=default(string), PropertyMetadata TabOrderMetadata=default(PropertyMetadata), string TabType=default(string), PropertyMetadata TabTypeMetadata=default(PropertyMetadata), string TemplateLocked=default(string), PropertyMetadata TemplateLockedMetadata=default(PropertyMetadata), string TemplateRequired=default(string), PropertyMetadata TemplateRequiredMetadata=default(PropertyMetadata), string Tooltip=default(string), PropertyMetadata ToolTipMetadata=default(PropertyMetadata), string Underline=default(string), PropertyMetadata UnderlineMetadata=default(PropertyMetadata), string Value=default(string), PropertyMetadata ValueMetadata=default(PropertyMetadata), string Width=default(string), PropertyMetadata WidthMetadata=default(PropertyMetadata), string XPosition=default(string), PropertyMetadata XPositionMetadata=default(PropertyMetadata), string YPosition=default(string), PropertyMetadata YPositionMetadata=default(PropertyMetadata))',
      ],
    ],
  ],
  [
    'notification',
    [
      'Notification',
      [
        '../class_docu_sign_1_1e_sign_1_1_model_1_1_notification.html#a1420b4eefd73ecf8a58e9dd11d7cbca1',
        1,
        'DocuSign.eSign.Model.Notification.Notification()',
      ],
      [
        '../class_docu_sign_1_1e_sign_1_1_model_1_1_notification.html#a7d04a2fb69141ae7622b86e23f321e16',
        1,
        'DocuSign.eSign.Model.Notification.Notification(Expirations Expirations=default(Expirations), Reminders Reminders=default(Reminders), string UseAccountDefaults=default(string))',
      ],
    ],
  ],
  [
    'notificationdefaults',
    [
      'NotificationDefaults',
      [
        '../class_docu_sign_1_1e_sign_1_1_model_1_1_notification_defaults.html#ae2360c6090c484511e095eeb68e54e4a',
        1,
        'DocuSign.eSign.Model.NotificationDefaults.NotificationDefaults()',
      ],
      [
        '../class_docu_sign_1_1e_sign_1_1_model_1_1_notification_defaults.html#afb13f28ac91b78ad21916247b22ea6a9',
        1,
        'DocuSign.eSign.Model.NotificationDefaults.NotificationDefaults(NotificationDefaultSettings ApiEmailNotifications=default(NotificationDefaultSettings), NotificationDefaultSettings EmailNotifications=default(NotificationDefaultSettings))',
      ],
    ],
  ],
  [
    'notificationdefaultsettings',
    [
      'NotificationDefaultSettings',
      [
        '../class_docu_sign_1_1e_sign_1_1_model_1_1_notification_default_settings.html#ab39c305ad7034f8e55161cd34bf8ee2e',
        1,
        'DocuSign.eSign.Model.NotificationDefaultSettings.NotificationDefaultSettings()',
      ],
      [
        '../class_docu_sign_1_1e_sign_1_1_model_1_1_notification_default_settings.html#aac45f35257f46aca29d88837141de8f8',
        1,
        'DocuSign.eSign.Model.NotificationDefaultSettings.NotificationDefaultSettings(SenderEmailNotifications SenderEmailNotifications=default(SenderEmailNotifications), SignerEmailNotifications SignerEmailNotifications=default(SignerEmailNotifications))',
      ],
    ],
  ],
  [
    'number',
    [
      'Number',
      [
        '../class_docu_sign_1_1e_sign_1_1_model_1_1_number.html#ada75c3a5395847f36379255678c5ce36',
        1,
        'DocuSign.eSign.Model.Number.Number()',
      ],
      [
        '../class_docu_sign_1_1e_sign_1_1_model_1_1_number.html#a90514183322774fe227297c9b5baa697',
        1,
        'DocuSign.eSign.Model.Number.Number(string AnchorAllowWhiteSpaceInCharacters=default(string), PropertyMetadata AnchorAllowWhiteSpaceInCharactersMetadata=default(PropertyMetadata), string AnchorCaseSensitive=default(string), PropertyMetadata AnchorCaseSensitiveMetadata=default(PropertyMetadata), string AnchorHorizontalAlignment=default(string), PropertyMetadata AnchorHorizontalAlignmentMetadata=default(PropertyMetadata), string AnchorIgnoreIfNotPresent=default(string), PropertyMetadata AnchorIgnoreIfNotPresentMetadata=default(PropertyMetadata), string AnchorMatchWholeWord=default(string), PropertyMetadata AnchorMatchWholeWordMetadata=default(PropertyMetadata), string AnchorString=default(string), PropertyMetadata AnchorStringMetadata=default(PropertyMetadata), string AnchorTabProcessorVersion=default(string), PropertyMetadata AnchorTabProcessorVersionMetadata=default(PropertyMetadata), string AnchorUnits=default(string), PropertyMetadata AnchorUnitsMetadata=default(PropertyMetadata), string AnchorXOffset=default(string), PropertyMetadata AnchorXOffsetMetadata=default(PropertyMetadata), string AnchorYOffset=default(string), PropertyMetadata AnchorYOffsetMetadata=default(PropertyMetadata), string Bold=default(string), PropertyMetadata BoldMetadata=default(PropertyMetadata), string ConcealValueOnDocument=default(string), PropertyMetadata ConcealValueOnDocumentMetadata=default(PropertyMetadata), string ConditionalParentLabel=default(string), PropertyMetadata ConditionalParentLabelMetadata=default(PropertyMetadata), string ConditionalParentValue=default(string), PropertyMetadata ConditionalParentValueMetadata=default(PropertyMetadata), string CustomTabId=default(string), PropertyMetadata CustomTabIdMetadata=default(PropertyMetadata), string DisableAutoSize=default(string), PropertyMetadata DisableAutoSizeMetadata=default(PropertyMetadata), string DocumentId=default(string), PropertyMetadata DocumentIdMetadata=default(PropertyMetadata), ErrorDetails ErrorDetails=default(ErrorDetails), string Font=default(string), string FontColor=default(string), PropertyMetadata FontColorMetadata=default(PropertyMetadata), PropertyMetadata FontMetadata=default(PropertyMetadata), string FontSize=default(string), PropertyMetadata FontSizeMetadata=default(PropertyMetadata), string FormOrder=default(string), PropertyMetadata FormOrderMetadata=default(PropertyMetadata), string FormPageLabel=default(string), PropertyMetadata FormPageLabelMetadata=default(PropertyMetadata), string FormPageNumber=default(string), PropertyMetadata FormPageNumberMetadata=default(PropertyMetadata), string Formula=default(string), PropertyMetadata FormulaMetadata=default(PropertyMetadata), string Height=default(string), PropertyMetadata HeightMetadata=default(PropertyMetadata), string IsPaymentAmount=default(string), PropertyMetadata IsPaymentAmountMetadata=default(PropertyMetadata), string Italic=default(string), PropertyMetadata ItalicMetadata=default(PropertyMetadata), LocalePolicyTab LocalePolicy=default(LocalePolicyTab), string Locked=default(string), PropertyMetadata LockedMetadata=default(PropertyMetadata), string MaxLength=default(string), PropertyMetadata MaxLengthMetadata=default(PropertyMetadata), MergeField MergeField=default(MergeField), string MergeFieldXml=default(string), string Name=default(string), PropertyMetadata NameMetadata=default(PropertyMetadata), string OriginalValue=default(string), PropertyMetadata OriginalValueMetadata=default(PropertyMetadata), string PageNumber=default(string), PropertyMetadata PageNumberMetadata=default(PropertyMetadata), string RecipientId=default(string), string RecipientIdGuid=default(string), PropertyMetadata RecipientIdGuidMetadata=default(PropertyMetadata), PropertyMetadata RecipientIdMetadata=default(PropertyMetadata), string RequireAll=default(string), PropertyMetadata RequireAllMetadata=default(PropertyMetadata), string Required=default(string), PropertyMetadata RequiredMetadata=default(PropertyMetadata), string RequireInitialOnSharedChange=default(string), PropertyMetadata RequireInitialOnSharedChangeMetadata=default(PropertyMetadata), string SenderRequired=default(string), PropertyMetadata SenderRequiredMetadata=default(PropertyMetadata), string Shared=default(string), PropertyMetadata SharedMetadata=default(PropertyMetadata), SmartContractInformation SmartContractInformation=default(SmartContractInformation), string Source=default(string), string Status=default(string), PropertyMetadata StatusMetadata=default(PropertyMetadata), List&lt; string &gt; TabGroupLabels=default(List&lt; string &gt;), PropertyMetadata TabGroupLabelsMetadata=default(PropertyMetadata), string TabId=default(string), PropertyMetadata TabIdMetadata=default(PropertyMetadata), string TabLabel=default(string), PropertyMetadata TabLabelMetadata=default(PropertyMetadata), string TabOrder=default(string), PropertyMetadata TabOrderMetadata=default(PropertyMetadata), string TabType=default(string), PropertyMetadata TabTypeMetadata=default(PropertyMetadata), string TemplateLocked=default(string), PropertyMetadata TemplateLockedMetadata=default(PropertyMetadata), string TemplateRequired=default(string), PropertyMetadata TemplateRequiredMetadata=default(PropertyMetadata), string Tooltip=default(string), PropertyMetadata ToolTipMetadata=default(PropertyMetadata), string Underline=default(string), PropertyMetadata UnderlineMetadata=default(PropertyMetadata), string ValidationMessage=default(string), PropertyMetadata ValidationMessageMetadata=default(PropertyMetadata), string ValidationPattern=default(string), PropertyMetadata ValidationPatternMetadata=default(PropertyMetadata), string Value=default(string), PropertyMetadata ValueMetadata=default(PropertyMetadata), string Width=default(string), PropertyMetadata WidthMetadata=default(PropertyMetadata), string XPosition=default(string), PropertyMetadata XPositionMetadata=default(PropertyMetadata), string YPosition=default(string), PropertyMetadata YPositionMetadata=default(PropertyMetadata))',
      ],
    ],
  ],
];
