var searchData = [
  [
    'watermark',
    [
      'Watermark',
      [
        '../class_docu_sign_1_1e_sign_1_1_model_1_1_watermark.html#a7f8921a40ccd13c32027288272c325ef',
        1,
        'DocuSign.eSign.Model.Watermark.Watermark()',
      ],
      [
        '../class_docu_sign_1_1e_sign_1_1_model_1_1_watermark.html#a0b81d67253725ef8c16579199702edf6',
        1,
        'DocuSign.eSign.Model.Watermark.Watermark(string DisplayAngle=default(string), string Enabled=default(string), string Font=default(string), string FontColor=default(string), string FontSize=default(string), string Id=default(string), string ImageBase64=default(string), string Transparency=default(string), string WatermarkText=default(string))',
      ],
    ],
  ],
  [
    'witness',
    [
      'Witness',
      [
        '../class_docu_sign_1_1e_sign_1_1_model_1_1_witness.html#a8141274662fd7bd26b061b310c23e43a',
        1,
        'DocuSign.eSign.Model.Witness.Witness()',
      ],
      [
        '../class_docu_sign_1_1e_sign_1_1_model_1_1_witness.html#ac35f41cbae171daef9f501a5bf6a5043',
        1,
        'DocuSign.eSign.Model.Witness.Witness(string AccessCode=default(string), PropertyMetadata AccessCodeMetadata=default(PropertyMetadata), string AddAccessCodeToEmail=default(string), List&lt; RecipientAdditionalNotification &gt; AdditionalNotifications=default(List&lt; RecipientAdditionalNotification &gt;), string AgentCanEditEmail=default(string), string AgentCanEditName=default(string), string AllowSystemOverrideForLockedRecipient=default(string), string AutoNavigation=default(string), string BulkRecipientsUri=default(string), string CanSignOffline=default(string), string ClientUserId=default(string), string CompletedCount=default(string), string CreationReason=default(string), List&lt; string &gt; CustomFields=default(List&lt; string &gt;), string DeclinedDateTime=default(string), string DeclinedReason=default(string), string DefaultRecipient=default(string), string DeliveredDateTime=default(string), string DeliveryMethod=default(string), PropertyMetadata DeliveryMethodMetadata=default(PropertyMetadata), string DesignatorId=default(string), string DesignatorIdGuid=default(string), List&lt; DocumentVisibility &gt; DocumentVisibility=default(List&lt; DocumentVisibility &gt;), string Email=default(string), PropertyMetadata EmailMetadata=default(PropertyMetadata), RecipientEmailNotification EmailNotification=default(RecipientEmailNotification), string EmbeddedRecipientStartURL=default(string), ErrorDetails ErrorDetails=default(ErrorDetails), List&lt; string &gt; ExcludedDocuments=default(List&lt; string &gt;), string FaxNumber=default(string), PropertyMetadata FaxNumberMetadata=default(PropertyMetadata), string FirstName=default(string), PropertyMetadata FirstNameMetadata=default(PropertyMetadata), string FullName=default(string), PropertyMetadata FullNameMetadata=default(PropertyMetadata), string IdCheckConfigurationName=default(string), PropertyMetadata IdCheckConfigurationNameMetadata=default(PropertyMetadata), IdCheckInformationInput IdCheckInformationInput=default(IdCheckInformationInput), RecipientIdentityVerification IdentityVerification=default(RecipientIdentityVerification), string InheritEmailNotificationConfiguration=default(string), string IsBulkRecipient=default(string), PropertyMetadata IsBulkRecipientMetadata=default(PropertyMetadata), string LastName=default(string), PropertyMetadata LastNameMetadata=default(PropertyMetadata), string LockedRecipientPhoneAuthEditable=default(string), string LockedRecipientSmsEditable=default(string), string Name=default(string), PropertyMetadata NameMetadata=default(PropertyMetadata), string NotaryId=default(string), string Note=default(string), PropertyMetadata NoteMetadata=default(PropertyMetadata), OfflineAttributes OfflineAttributes=default(OfflineAttributes), RecipientPhoneAuthentication PhoneAuthentication=default(RecipientPhoneAuthentication), RecipientProofFile ProofFile=default(RecipientProofFile), List&lt; RecipientAttachment &gt; RecipientAttachments=default(List&lt; RecipientAttachment &gt;), AuthenticationStatus RecipientAuthenticationStatus=default(AuthenticationStatus), List&lt; FeatureAvailableMetadata &gt; RecipientFeatureMetadata=default(List&lt; FeatureAvailableMetadata &gt;), string RecipientId=default(string), string RecipientIdGuid=default(string), List&lt; RecipientSignatureProvider &gt; RecipientSignatureProviders=default(List&lt; RecipientSignatureProvider &gt;), string RecipientSuppliesTabs=default(string), string RecipientType=default(string), PropertyMetadata RecipientTypeMetadata=default(PropertyMetadata), string RequireIdLookup=default(string), PropertyMetadata RequireIdLookupMetadata=default(PropertyMetadata), string RequireSignerCertificate=default(string), string RequireSignOnPaper=default(string), string RequireUploadSignature=default(string), string RoleName=default(string), string RoutingOrder=default(string), PropertyMetadata RoutingOrderMetadata=default(PropertyMetadata), string SentDateTime=default(string), RecipientSignatureInformation SignatureInfo=default(RecipientSignatureInformation), string SignedDateTime=default(string), string SignInEachLocation=default(string), PropertyMetadata SignInEachLocationMetadata=default(PropertyMetadata), string SigningGroupId=default(string), PropertyMetadata SigningGroupIdMetadata=default(PropertyMetadata), string SigningGroupName=default(string), List&lt; UserInfo &gt; SigningGroupUsers=default(List&lt; UserInfo &gt;), RecipientSMSAuthentication SmsAuthentication=default(RecipientSMSAuthentication), List&lt; SocialAuthentication &gt; SocialAuthentications=default(List&lt; SocialAuthentication &gt;), string Status=default(string), string StatusCode=default(string), string SuppressEmails=default(string), Tabs Tabs=default(Tabs), string TemplateLocked=default(string), string TemplateRequired=default(string), string TotalTabCount=default(string), string UserId=default(string), string WitnessFor=default(string), string WitnessForGuid=default(string))',
      ],
    ],
  ],
  [
    'workflow',
    [
      'Workflow',
      [
        '../class_docu_sign_1_1e_sign_1_1_model_1_1_workflow.html#a373b09ec9757448ee463d4c956f7c888',
        1,
        'DocuSign.eSign.Model.Workflow.Workflow()',
      ],
      [
        '../class_docu_sign_1_1e_sign_1_1_model_1_1_workflow.html#af84eeec7627c7ab1d09766da2e6ff04f',
        1,
        'DocuSign.eSign.Model.Workflow.Workflow(string CurrentWorkflowStepId=default(string), string WorkflowStatus=default(string), List&lt; WorkflowStep &gt; WorkflowSteps=default(List&lt; WorkflowStep &gt;))',
      ],
    ],
  ],
  [
    'workflowstep',
    [
      'WorkflowStep',
      [
        '../class_docu_sign_1_1e_sign_1_1_model_1_1_workflow_step.html#a55413ae5a97092eb790cde1d68bff892',
        1,
        'DocuSign.eSign.Model.WorkflowStep.WorkflowStep()',
      ],
      [
        '../class_docu_sign_1_1e_sign_1_1_model_1_1_workflow_step.html#aa0b41ff61b8e0b4c108ab5d6a33bc351',
        1,
        'DocuSign.eSign.Model.WorkflowStep.WorkflowStep(string Action=default(string), string CompletedDate=default(string), string ItemId=default(string), RecipientRouting RecipientRouting=default(RecipientRouting), string Status=default(string), string TriggeredDate=default(string), string TriggerOnItem=default(string), string WorkflowStepId=default(string))',
      ],
    ],
  ],
  [
    'workspace',
    [
      'Workspace',
      [
        '../class_docu_sign_1_1e_sign_1_1_model_1_1_workspace.html#ad511271a3ebf00775e00b4223b194b13',
        1,
        'DocuSign.eSign.Model.Workspace.Workspace()',
      ],
      [
        '../class_docu_sign_1_1e_sign_1_1_model_1_1_workspace.html#a21851d704b80c7694ea5e750b2b5a9a4',
        1,
        'DocuSign.eSign.Model.Workspace.Workspace(string BillableAccountId=default(string), WorkspaceUser CallerInformation=default(WorkspaceUser), string Created=default(string), WorkspaceUser CreatedByInformation=default(WorkspaceUser), string LastModified=default(string), WorkspaceUser LastModifiedByInformation=default(WorkspaceUser), WorkspaceSettings Settings=default(WorkspaceSettings), string Status=default(string), string WorkspaceBaseUrl=default(string), string WorkspaceDescription=default(string), string WorkspaceId=default(string), string WorkspaceName=default(string), string WorkspaceUri=default(string))',
      ],
    ],
  ],
  [
    'workspacefoldercontents',
    [
      'WorkspaceFolderContents',
      [
        '../class_docu_sign_1_1e_sign_1_1_model_1_1_workspace_folder_contents.html#abc2049470553c3ccae7978e6b49f2d05',
        1,
        'DocuSign.eSign.Model.WorkspaceFolderContents.WorkspaceFolderContents()',
      ],
      [
        '../class_docu_sign_1_1e_sign_1_1_model_1_1_workspace_folder_contents.html#adbc05e7f3483c3d5e2bc75990794bb9e',
        1,
        'DocuSign.eSign.Model.WorkspaceFolderContents.WorkspaceFolderContents(string EndPosition=default(string), WorkspaceItem Folder=default(WorkspaceItem), List&lt; WorkspaceItem &gt; Items=default(List&lt; WorkspaceItem &gt;), List&lt; WorkspaceItem &gt; ParentFolders=default(List&lt; WorkspaceItem &gt;), string ResultSetSize=default(string), string StartPosition=default(string), string TotalSetSize=default(string), string WorkspaceId=default(string))',
      ],
    ],
  ],
  [
    'workspaceitem',
    [
      'WorkspaceItem',
      [
        '../class_docu_sign_1_1e_sign_1_1_model_1_1_workspace_item.html#af193daf6bb1abae7e9fcbe8a6f515013',
        1,
        'DocuSign.eSign.Model.WorkspaceItem.WorkspaceItem()',
      ],
      [
        '../class_docu_sign_1_1e_sign_1_1_model_1_1_workspace_item.html#a376e7817278701ac723144f40a84436e',
        1,
        'DocuSign.eSign.Model.WorkspaceItem.WorkspaceItem(WorkspaceUserAuthorization CallerAuthorization=default(WorkspaceUserAuthorization), string ContentType=default(string), string Created=default(string), string CreatedById=default(string), WorkspaceUser CreatedByInformation=default(WorkspaceUser), string Extension=default(string), string FileSize=default(string), string FileUri=default(string), string Id=default(string), string IsPublic=default(string), string LastModified=default(string), string LastModifiedById=default(string), WorkspaceUser LastModifiedByInformation=default(WorkspaceUser), string Name=default(string), string PageCount=default(string), string ParentFolderId=default(string), string ParentFolderUri=default(string), string Sha256=default(string), string ThumbHeight=default(string), Page Thumbnail=default(Page), string ThumbWidth=default(string), string Type=default(string), string Uri=default(string), WorkspaceUserAuthorization UserAuthorization=default(WorkspaceUserAuthorization))',
      ],
    ],
  ],
  [
    'workspaceitemlist',
    [
      'WorkspaceItemList',
      [
        '../class_docu_sign_1_1e_sign_1_1_model_1_1_workspace_item_list.html#a359eff6def74dc0c94a860667437718f',
        1,
        'DocuSign.eSign.Model.WorkspaceItemList.WorkspaceItemList()',
      ],
      [
        '../class_docu_sign_1_1e_sign_1_1_model_1_1_workspace_item_list.html#a19d3b97ea2496627ab071595cc7913ca',
        1,
        'DocuSign.eSign.Model.WorkspaceItemList.WorkspaceItemList(List&lt; WorkspaceItem &gt; Items=default(List&lt; WorkspaceItem &gt;))',
      ],
    ],
  ],
  [
    'workspacelist',
    [
      'WorkspaceList',
      [
        '../class_docu_sign_1_1e_sign_1_1_model_1_1_workspace_list.html#ad5ebeba6dbcf2318ac9f802fae7d6277',
        1,
        'DocuSign.eSign.Model.WorkspaceList.WorkspaceList()',
      ],
      [
        '../class_docu_sign_1_1e_sign_1_1_model_1_1_workspace_list.html#ad3949b9d425c942075e2d0080582b9af',
        1,
        'DocuSign.eSign.Model.WorkspaceList.WorkspaceList(string EndPosition=default(string), string ResultSetSize=default(string), string StartPosition=default(string), string TotalSetSize=default(string), List&lt; Workspace &gt; Workspaces=default(List&lt; Workspace &gt;))',
      ],
    ],
  ],
  [
    'workspacesapi',
    [
      'WorkspacesApi',
      [
        '../class_docu_sign_1_1e_sign_1_1_api_1_1_workspaces_api.html#a2621e6d70c67c3c915a5da506854c29f',
        1,
        'DocuSign::eSign::Api::WorkspacesApi',
      ],
    ],
  ],
  [
    'workspacesettings',
    [
      'WorkspaceSettings',
      [
        '../class_docu_sign_1_1e_sign_1_1_model_1_1_workspace_settings.html#a6ec396c87323635d96a5e899a09d19bc',
        1,
        'DocuSign.eSign.Model.WorkspaceSettings.WorkspaceSettings()',
      ],
      [
        '../class_docu_sign_1_1e_sign_1_1_model_1_1_workspace_settings.html#a2751b8c36a523be751e2e01f3359508b',
        1,
        'DocuSign.eSign.Model.WorkspaceSettings.WorkspaceSettings(string CommentsAllowed=default(string))',
      ],
    ],
  ],
  [
    'workspaceuser',
    [
      'WorkspaceUser',
      [
        '../class_docu_sign_1_1e_sign_1_1_model_1_1_workspace_user.html#a9226fcec9b05025bfa558f6fe131fdd8',
        1,
        'DocuSign.eSign.Model.WorkspaceUser.WorkspaceUser()',
      ],
      [
        '../class_docu_sign_1_1e_sign_1_1_model_1_1_workspace_user.html#a2b6326bf2d63e49b25c85873e0eb3cb6',
        1,
        'DocuSign.eSign.Model.WorkspaceUser.WorkspaceUser(string AccountId=default(string), string AccountName=default(string), string ActiveSince=default(string), string Created=default(string), string CreatedById=default(string), string Email=default(string), ErrorDetails ErrorDetails=default(ErrorDetails), string InvitationEmailBlurb=default(string), string InvitationEmailSubject=default(string), string LastModified=default(string), string LastModifiedById=default(string), string Status=default(string), string Type=default(string), string UserId=default(string), string UserName=default(string), string WorkspaceId=default(string), string WorkspaceUserBaseUrl=default(string), string WorkspaceUserId=default(string), string WorkspaceUserUri=default(string))',
      ],
    ],
  ],
  [
    'workspaceuserauthorization',
    [
      'WorkspaceUserAuthorization',
      [
        '../class_docu_sign_1_1e_sign_1_1_model_1_1_workspace_user_authorization.html#afd8655b276f83d38d283bae578252068',
        1,
        'DocuSign.eSign.Model.WorkspaceUserAuthorization.WorkspaceUserAuthorization()',
      ],
      [
        '../class_docu_sign_1_1e_sign_1_1_model_1_1_workspace_user_authorization.html#a1b3c885e541d5c74bebe9eeee0eb0995',
        1,
        'DocuSign.eSign.Model.WorkspaceUserAuthorization.WorkspaceUserAuthorization(string CanDelete=default(string), string CanMove=default(string), string CanTransact=default(string), string CanView=default(string), string Created=default(string), string CreatedById=default(string), ErrorDetails ErrorDetails=default(ErrorDetails), string Modified=default(string), string ModifiedById=default(string), string WorkspaceUserId=default(string), WorkspaceUser WorkspaceUserInformation=default(WorkspaceUser))',
      ],
    ],
  ],
];
